unpackaged/main/default/objects/Account/fields/Account_Owner_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Owner_Type__c</fullName>
    <description>What business unit: The Account types belong to.</description>
    <label>Account Owner Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BDR</fullName>
                <default>true</default>
                <label>BDR</label>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>Ops</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Email_Domain__c.field-meta.xml
<CustomField>
    <fullName>Email_Domain__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Use this one for Xom Integrations.</inlineHelpText>
    <label>Email Domain</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/Generic_Account__c.field-meta.xml
<CustomField>
    <fullName>Generic_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Generic Account</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Last_Year_Account_Spend__c.field-meta.xml
<CustomField>
    <fullName>Last_Year_Account_Spend__c</fullName>
    <label>Last Year Account Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Lifetime_Spend__c.field-meta.xml
<CustomField>
    <fullName>Lifetime_Spend__c</fullName>
    <label>Lifetime Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Number_Contacts__c.field-meta.xml
<CustomField>
    <fullName>Number_Contacts__c</fullName>
    <label># of Contacts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Number_Orders__c.field-meta.xml
<CustomField>
    <fullName>Number_Orders__c</fullName>
    <label>Lifetime No. of Orders</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Sup_Last_Year_Account_Spend__c.field-meta.xml
<CustomField>
    <fullName>Sup_Last_Year_Account_Spend__c</fullName>
    <label>Last Year Account Spend Supplies</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Sup_Lifetime_Spend__c.field-meta.xml
<CustomField>
    <fullName>Sup_Lifetime_Spend__c</fullName>
    <label>Lifetime Spend Supplies</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Sup_This_Year_Account_Spend__c.field-meta.xml
<CustomField>
    <fullName>Sup_This_Year_Account_Spend__c</fullName>
    <label>Supplies This Year Account Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Sup_Year_Before_Last_Account_Spend__c.field-meta.xml
<CustomField>
    <fullName>Sup_Year_Before_Last_Account_Spend__c</fullName>
    <label>Year Before Last Account Spend Supplies</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/This_Year_Account_Spend__c.field-meta.xml
<CustomField>
    <fullName>This_Year_Account_Spend__c</fullName>
    <label>This Year Account Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Year_Before_Last_Account_Spend__c.field-meta.xml
<CustomField>
    <fullName>Year_Before_Last_Account_Spend__c</fullName>
    <label>Year Before Last Account Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/YTDSpend__c.field-meta.xml
<CustomField>
    <fullName>YTDSpend__c</fullName>
    <description>Calculated amount of how much the account has Ordered this Year.</description>
    <inlineHelpText>Sum of Won Opportunities associated to the account.</inlineHelpText>
    <label>YTDSpend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Account_Owner_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Owner_Type__c</fullName>
    <formula>TEXT(Account.Account_Owner_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Owner Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Number_Orders__c.field-meta.xml
<CustomField>
    <fullName>Number_Orders__c</fullName>
    <label># of Orders</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Generic_Account__c.field-meta.xml
<CustomField>
    <fullName>Generic_Account__c</fullName>
    <formula>IF(Account.Generic_Account__c = TRUE,"True","False")</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Generic Account</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Loss_Reason__c.field-meta.xml
<CustomField>
    <fullName>Loss_Reason__c</fullName>
    <label>Loss Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No Response</fullName>
            </value>
            <value>
                <fullName>No Bid</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Lead Time</fullName>
            </value>
            <value>
                <fullName>Service Concerns</fullName>
            </value>
            <value>
                <fullName>Project Canceled</fullName>
            </value>
            <value>
                <fullName>Purchasing from Different Opportunity</fullName>
            </value>
            <value>
                <fullName>On-Demand Competition</fullName>
            </value>
            <value>
                <fullName>Local Competition</fullName>
            </value>
            <value>
                <fullName>Budgetary</fullName>
            </value>
            <value>
                <fullName>Late quote</fullName>
            </value>
            <value>
                <fullName>Customer Made In-House</fullName>
            </value>
            <value>
                <fullName>Ordered Online</fullName>
                <label>Ordered Online - Supply Record Only</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/Manufacturing_Services.recordType-meta.xml
<RecordType>
    <fullName>Manufacturing_Services</fullName>
    <active>true</active>
    <businessProcess>Xometry Sales Process</businessProcess>
    <description>Core Services: Instant Quote, Marketplace, etc.</description>
    <label>Manufacturing Services</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/recordTypes/Supplies.recordType-meta.xml
<RecordType>
    <fullName>Supplies</fullName>
    <active>true</active>
    <businessProcess>Supplies Sales Process</businessProcess>
    <description>Supplies Record Type</description>
    <label>Supplies</label>
</RecordType>

unpackaged/main/default/objects/Order_Erp__c/Order_Erp__c.object-meta.xml
<CustomObject>
    <description>This object cotains the orders from Xometry ERP. An order is created in Salesforce when the Order date is populated. 

Technical Note: Quote and Orders are the same object in the source system but seperated in Salesforce as Orders represent the end of the opportunity process.</description>
    <label>Order ERP</label>
    <nameField>
        <displayFormat>Order-{000000}</displayFormat>
        <label>Order Erp Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders ERP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order_Erp__c/fields/Order_Canceled_Flag__c.field-meta.xml
<CustomField>
    <fullName>Order_Canceled_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>A flag that shows that an order has been canceled.</description>
    <label>Order Canceled Flag</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/recordTypes/Manufacturing_Services.recordType-meta.xml
<RecordType>
    <fullName>Manufacturing_Services</fullName>
    <active>true</active>
    <description>Core Services: Instant Quote, Marketplace, etc.</description>
    <label>Manufacturing Services</label>
</RecordType>

unpackaged/main/default/objects/Supplies_Quote__c/Supplies_Quote__c.object-meta.xml
<CustomObject>
    <description>This stores the P21 Quotes as records in Salesforce before transformation.</description>
    <label>Supplies Quote</label>
    <nameField>
        <label>Supplies Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplies Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Supplies_Quote__c/fields/P21_ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>P21_ERP_ID__c</fullName>
    <description>The unique Order ID which can be a Quote from P21 Order Entry.</description>
    <externalId>true</externalId>
    <label>P21 ERP ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/monthlyAcctAggReCalcTest.cls
@isTest
private class monthlyAcctAggReCalcTest {
    @isTest
    static void batchAcctAggUpdateMainTest() {
        User objUser = [
            SELECT Id
            FROM User
            WHERE
                Id IN (SELECT AssigneeId FROM PermissionSetAssignment WHERE PermissionSet.Label = 'Ignore All VR')
                AND IsActive = TRUE
            LIMIT 1
        ];

        System.runAs(objUser) {
            List<Account> testAccountList = TestDataFactory.createTestAccountNonGenerics(2, 'AM', 1);
            Account testAccount = testAccountList[0];
            ID dummyOwnerID = testAccount.ownerID;
            ID testAccountID = testAccount.ID;
            List<Order_ERP__C> newOrdersList = new List<Order_ERP__C>();
            Contact myretContact = [
                SELECT ID, FirstName, LastName, Email
                FROM Contact
                WHERE AccountID = :testAccountID
                ORDER BY Name
            ];
            ID myretContactID = myretContact.ID;
            List<Order_ERP__C> insertOrdersList = new List<Order_ERP__C>();
            Date thisYear = Date.today();
            Date lastYear = Date.today().addYears(-1);
            Date yearBeforeLast = Date.today().addYears(-2);
            Datetime thisYearDatetime = Datetime.now();
            Datetime lastYearDatetime = Datetime.now().addYears(-1);
            Datetime yearBeforeLastDatetime = Datetime.now().addYears(-2);
            // this year
            Order_ERP__C ord = TestDataFactory.createOrderERPFromAccContact(
                false,
                'Q00-0000-0000',
                'BBBBB-34567',
                '56564-55667',
                testAccount,
                myretContact,
                thisYear,
                thisYearDatetime
            );
            insertOrdersList.add(ord);

            Order_ERP__C ord1 = TestDataFactory.createOrderERPFromAccContact(
                false,
                'Q00-0000-0001',
                'BBBBB-34568',
                '56564-55668',
                testAccount,
                myretContact,
                thisYear,
                thisYearDatetime
            );
            insertOrdersList.add(ord1);

            Order_ERP__C ord2 = TestDataFactory.createOrderERPFromAccContact(
                false,
                'Q00-0000-0002',
                'BBBBB-34569',
                '56564-55669',
                testAccount,
                myretContact,
                thisYear,
                thisYearDatetime
            );
            insertOrdersList.add(ord2);

            // Last year
            Order_ERP__C ord3 = TestDataFactory.createOrderERPFromAccContact(
                false,
                'Q00-0000-0003',
                'BBBBB-34570',
                '56564-55670',
                testAccount,
                myretContact,
                lastYear,
                lastYearDatetime
            );
            insertOrdersList.add(ord3);

            Order_ERP__C ord4 = TestDataFactory.createOrderERPFromAccContact(
                false,
                'Q00-0000-0004',
                'BBBBB-34571',
                '56564-55671',
                testAccount,
                myretContact,
                lastYear,
                lastYearDatetime
            );
            insertOrdersList.add(ord4);

            Order_ERP__C ord5 = TestDataFactory.createOrderERPFromAccContact(
                false,
                'Q00-0000-0005',
                'BBBBB-34572',
                '56564-55672',
                testAccount,
                myretContact,
                lastYear,
                lastYearDatetime
            );
            insertOrdersList.add(ord5);

            // Year before Last
            Order_ERP__C ord6 = TestDataFactory.createOrderERPFromAccContact(
                false,
                'Q00-0000-0006',
                'BBBBB-34573',
                '56564-55673',
                testAccount,
                myretContact,
                yearBeforeLast,
                yearBeforeLastDatetime
            );
            insertOrdersList.add(ord6);

            Order_ERP__C ord7 = TestDataFactory.createOrderERPFromAccContact(
                false,
                'Q00-0000-0007',
                'BBBBB-34574',
                '56564-55674',
                testAccount,
                myretContact,
                yearBeforeLast,
                yearBeforeLastDatetime
            );
            insertOrdersList.add(ord7);

            Order_ERP__C ord8 = TestDataFactory.createOrderERPFromAccContact(
                false,
                'Q00-0000-0008',
                'BBBBB-34575',
                '56564-55675',
                testAccount,
                myretContact,
                yearBeforeLast,
                yearBeforeLastDatetime
            );
            insertOrdersList.add(ord8);
            insert insertOrdersList;

            ord2.Order_Canceled_Flag__c = true;

            // Account resAcct = [SELECT ID, YTDSpend__c FROM Account WHERE ID = :testAccountID];
            // System.debug('The initial YTDSpend__C is: ' + resAcct.YTDSpend__c);

            List<Opportunity> myOpps = new List<Opportunity>();
            List<Opportunity> lstOpp = new List<Opportunity>();

            for (Opportunity opp : [
                SELECT Id, Stagename, Amount, AccountId, CloseDate, RecordTypeId
                FROM Opportunity
                WHERE AccountID = :testAccountID
            ]) {
                if (opp.AccountID == testAccountID) {
                    myOpps.add(opp);
                }
            }

            ID oppManufacturingServRTypeID = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName()
                .get('Manufacturing_Services')
                .getRecordTypeID();

            Opportunity myOpp = myOpps[0];
            myOpp.RecordTypeId = oppManufacturingServRTypeID;
            myOpp.Stagename = 'Closed Lost';
            myOpp.Loss_Reason__c = 'Order Cancelled';

            lstOpp.add(myOpp);

            update lstOpp;
            System.debug('**CM** lstOpp ' + lstOpp);
        }
        Account noOrderTestAccount = new Account();
        ID accountCustomerRecordTypeID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
            .get('Customer')
            .getRecordTypeID();
        noOrderTestAccount.name = 'EmptyShell';
        noOrderTestAccount.ownerID = [SELECT OwnerId FROM Account LIMIT 1].OwnerId;
        noOrderTestAccount.recordTypeID = accountCustomerRecordTypeID;
        noOrderTestAccount.Generic_Account__c = false;
        noOrderTestAccount.Account_Owner_Type__c = 'AM';
        noOrderTestAccount.Email_Domain__c = 'noOrderTest.com';

        Test.startTest();
        insert noOrderTestAccount;
        monthlyAcctAggReCalc batch = new monthlyAcctAggReCalc();
        Database.executeBatch(batch);
        Test.stopTest();
        List<Account> accounts = [
            SELECT
                ID,
                Name,
                YTDSpend__c,
                Lifetime_Spend__c,
                Number_Orders__c,
                Number_Contacts__c,
                This_Year_Account_Spend__c,
                Last_Year_Account_Spend__c,
                Year_Before_Last_Account_Spend__c
            FROM Account
        ];
        Account resAcct = accounts[0];
        System.assertequals(10000, resAcct.YTDSpend__c, 'YTDSpend__c is not correct');
        System.assertequals(40000, resAcct.Lifetime_Spend__c, 'Lifetime_Spend__c is not correct');
        System.assertequals(8, resAcct.Number_Orders__c, 'Number_Orders__c is not correct');
        System.assertequals(1, resAcct.Number_Contacts__c, 'Number_Contacts__c is not correct');
        System.assertequals(10000, resAcct.This_Year_Account_Spend__c, 'This_Year_Account_Spend__c is not correct');
        System.assertequals(15000, resAcct.Last_Year_Account_Spend__c, 'Last_Year_Account_Spend__c is not correct');
        System.assertequals(
            15000,
            resAcct.Year_Before_Last_Account_Spend__c,
            'Year_Before_Last_Account_Spend__c is not correct'
        );
        for (account a : accounts) {
            if (a.Name == 'EmptyShell') {
                System.assertequals(0, a.YTDSpend__C, 'FYTD for empty account was not 0!');
            }
        }
    }

    @isTest
    static void batchAcctAggUpdateMainTest_Supplies() {
        User objUser = [
            SELECT Id
            FROM User
            WHERE
                Id IN (SELECT AssigneeId FROM PermissionSetAssignment WHERE PermissionSet.Label = 'Ignore All VR')
                AND IsActive = TRUE
            LIMIT 1
        ];
        System.runAs(objUser) {
            List<Account> testAccountList = TestDataFactory.createTestAccountNonGenerics(2, 'AM', 1);
            Account testAccount = testAccountList[0];
            ID dummyOwnerID = testAccount.ownerID;
            ID testAccountID = testAccount.ID;
            Contact myretContact = [
                SELECT ID, FirstName, LastName, Email
                FROM Contact
                WHERE AccountID = :testAccountID
                ORDER BY Name
            ];
            ID myretContactID = myretContact.ID;
            List<Order_ERP__C> insertOrdersList = new List<Order_ERP__C>();
            Date thisYear = Date.today();
            Date lastYear = Date.today().addYears(-1);
            Date yearBeforeLast = Date.today().addYears(-2);
            Datetime thisYearDatetime = Datetime.now();
            Datetime lastYearDatetime = Datetime.now().addYears(-1);
            Datetime yearBeforeLastDatetime = Datetime.now().addYears(-2);
            // this year

            // Account resAcct = [SELECT ID, YTDSpend__c FROM Account WHERE ID = :testAccountID];
            // System.debug('The initial YTDSpend__C is: ' + resAcct.YTDSpend__c);

            ID oppSupplierRTypeID = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName()
                .get('Supplies')
                .getRecordTypeID();

            List<Supplies_Quote__C> lstSuppliesQuote = new List<Supplies_Quote__C>();
            Supplies_Quote__C sQuoteTest = TestDataFactory.createSuppliesQuote(
                false,
                myretContact.Email,
                testAccount.Email_Domain__c,
                myretContact.FirstName,
                myretContact.LastName,
                thisYear,
                thisYearDateTime
            );
            Supplies_Quote__C sQuoteTest2 = TestDataFactory.createSuppliesQuote(
                false,
                myretContact.Email,
                testAccount.Email_Domain__c,
                myretContact.FirstName,
                myretContact.LastName,
                thisYear,
                thisYearDateTime
            );
            sQuoteTest2.P21_ERP_ID__c = 'OE23478';
            Supplies_Quote__C sQuoteTest3 = TestDataFactory.createSuppliesQuote(
                false,
                myretContact.Email,
                testAccount.Email_Domain__c,
                myretContact.FirstName,
                myretContact.LastName,
                lastYear,
                lastYearDateTime
            );
            sQuoteTest3.P21_ERP_ID__c = 'OE23479';
            Supplies_Quote__C sQuoteTest4 = TestDataFactory.createSuppliesQuote(
                false,
                myretContact.Email,
                testAccount.Email_Domain__c,
                myretContact.FirstName,
                myretContact.LastName,
                lastYear,
                lastYearDateTime
            );
            sQuoteTest4.P21_ERP_ID__c = 'OE23480';
            Supplies_Quote__C sQuoteTest5 = TestDataFactory.createSuppliesQuote(
                false,
                myretContact.Email,
                testAccount.Email_Domain__c,
                myretContact.FirstName,
                myretContact.LastName,
                yearBeforeLast,
                yearBeforeLastDateTime
            );
            sQuoteTest5.P21_ERP_ID__c = 'OE23481';
            Supplies_Quote__C sQuoteTest6 = TestDataFactory.createSuppliesQuote(
                false,
                myretContact.Email,
                testAccount.Email_Domain__c,
                myretContact.FirstName,
                myretContact.LastName,
                yearBeforeLast,
                yearBeforeLastDateTime
            );
            sQuoteTest6.P21_ERP_ID__c = 'OE23482';

            lstSuppliesQuote.add(sQuoteTest);
            lstSuppliesQuote.add(sQuoteTest2);
            lstSuppliesQuote.add(sQuoteTest3);
            lstSuppliesQuote.add(sQuoteTest4);
            lstSuppliesQuote.add(sQuoteTest5);
            lstSuppliesQuote.add(sQuoteTest6);
            insert lstSuppliesQuote;

            List<Opportunity> myOpps = new List<Opportunity>();
            List<Opportunity> lstOpp = new List<Opportunity>();

            for (Opportunity opp : [
                SELECT Id, Stagename, Amount, AccountId, CloseDate, RecordTypeId
                FROM Opportunity
                WHERE RecordTypeId = :oppSupplierRTypeID OR AccountID = :testAccountID
            ]) {
                if (opp.RecordTypeId == oppSupplierRTypeID) {
                    lstOpp.add(opp);
                }

                if (opp.AccountID == testAccountID) {
                    myOpps.add(opp);
                }
            }

            lstOpp[0].StageName = 'Closed Won';
            lstOpp[0].CloseDate = System.today();
            lstOpp[1].StageName = 'Closed Lost';
            lstOpp[1].CloseDate = System.today();
            lstOpp[2].StageName = 'Closed Won';
            lstOpp[2].CloseDate = System.today().addYears(-1);
            lstOpp[3].StageName = 'Closed Lost';
            lstOpp[3].CloseDate = System.today().addYears(-1);
            lstOpp[4].StageName = 'Closed Won';
            lstOpp[4].CloseDate = System.today().addYears(-2);
            lstOpp[5].StageName = 'Closed Won';
            lstOpp[5].CloseDate = System.today().addYears(-2);

            update lstOpp;
            System.debug('**CM** lstOpp ' + lstOpp);
        }

        Test.startTest();
        monthlyAcctAggReCalc batch = new monthlyAcctAggReCalc();
        Database.executeBatch(batch);
        Test.stopTest();
        List<Account> accounts = [
            SELECT
                ID,
                Sup_Lifetime_Spend__c,
                Sup_This_Year_Account_Spend__c,
                Sup_Last_Year_Account_Spend__c,
                Sup_Year_Before_Last_Account_Spend__c
            FROM Account
        ];
        Account resAcct = accounts[0];
        System.assertequals(2000, resAcct.Sup_Lifetime_Spend__c, 'Sup_Lifetime_Spend__c is not correct');
        System.assertequals(
            500,
            resAcct.Sup_This_Year_Account_Spend__c,
            'Sup_This_Year_Account_Spend__c is not correct'
        );
        System.assertequals(
            500,
            resAcct.Sup_Last_Year_Account_Spend__c,
            'Sup_Last_Year_Account_Spend__c is not correct'
        );
        System.assertequals(
            1000,
            resAcct.Sup_Year_Before_Last_Account_Spend__c,
            'Sup_Year_Before_Last_Account_Spend__c is not correct'
        );
    }
}