unpackaged/main/default/objects/Account/fields/Account_Owner_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Owner_Type__c</fullName>
    <description>What business unit: The Account types belong to.</description>
    <label>Account Owner Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BDR</fullName>
                <default>true</default>
                <label>BDR</label>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>Ops</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account_Team__c/Account_Team__c.object-meta.xml
<CustomObject>
    <label>Account Team</label>
    <nameField>
        <displayFormat>AT-{000000000}</displayFormat>
        <label>Account Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Account_Team__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Account_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Account_Owner_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Owner_Type__c</fullName>
    <formula>TEXT(Account.Account_Owner_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Owner Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <formula>IF ( AND (  Account_Owner_Type__c = 'BDR', Account.BDR_Retention_Countdown_Calculation__c &lt; 91, Account.BDR_Retention_Countdown_Calculation__c &gt; 0),'NEW', IF ( AND (  Account_Owner_Type__c = 'BDR', Account.BDR_Retention_Countdown_Calculation__c &lt;= 0), 'RETENTION', IF ( AND (  Account_Owner_Type__c = 'AM',  AM_Retention_Countdown_Calculation__c  &lt; 366,  AM_Retention_Countdown_Calculation__c  &gt; 0),'NEW', IF ( AND (  Account_Owner_Type__c = 'AM',  AM_Retention_Countdown_Calculation__c  &lt;= 0), 'RETENTION',''))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Retention_Exemption__c.field-meta.xml
<CustomField>
    <fullName>Retention_Exemption__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Retention Exemption</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Quick Reference to the Primary Contact on an Opportunity</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities(PC)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/Manufacturing_Services.recordType-meta.xml
<RecordType>
    <fullName>Manufacturing_Services</fullName>
    <active>true</active>
    <businessProcess>Xometry Sales Process</businessProcess>
    <description>Core Services: Instant Quote, Marketplace, etc.</description>
    <label>Manufacturing Services</label>
</RecordType>

unpackaged/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Container for Opportunities that are part of the same project</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project__c/fields/Hold_Project_to_Prior_Owner__c.field-meta.xml
<CustomField>
    <fullName>Hold_Project_to_Prior_Owner__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hold Project to Prior Owner</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <inlineHelpText>A short description of this Project</inlineHelpText>
    <label>Project</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Initial Engagement</fullName>
            </value>
            <value>
                <fullName>Negotiation / Revision</fullName>
            </value>
            <value>
                <fullName>Pending Payment</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/csamContactFlip.cls
global class csamContactFlip implements Database.Batchable<sObject> {
    //CSAM stands for Enterprise Account Manager
    global Integer recordsProcessed = 0;
    static final ID oppManufacturingServRTypeID = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName()
        .get('Manufacturing_Services')
        .getRecordTypeID();
    static final String AUDIT_DEV_NOTE = 'Contact Owner Updates for CSAM';
    static final String AUDIT_DEV_NAME = 'csamContactFlip.execute';
    global Database.QueryLocator start(Database.BatchableContext bc) {
        //This query is designed to update Contacts both when a CSAM no longer is on an account team or when they have been added
        return Database.getQueryLocator(
            'Select ID, AccountID, Name, OwnerID, Account.OwnerID, Account.ParentID from Contact where Account.account_owner_type__c = \'AM\'  and Customer_Type__c= \'RETENTION\' and Retention_Exemption__c = false order by AccountID'
        );
    }
    global void execute(Database.BatchableContext bc, List<Contact> scope) {
        integer updateTracker = 0;
        Set<ID> contactIDSet = new Set<ID>();
        Set<ID> accountIDSet = new Set<ID>();
        Set<ID> parentAccountIDSet = new Set<ID>();
        Set<ID> accountAndParentAcctIDSet = new Set<ID>();
        Map<ID, ID> contactToAccountIDMap = new Map<ID, ID>();
        for (Contact c : scope) {
            contactIDSet.add(c.ID);
            accountIDSet.add(c.AccountID);
            if (c.Account.ParentID != null) {
                parentAccountIDSet.add(c.Account.ParentID);
                accountAndParentAcctIDSet.add(c.Account.ParentID);
                contactToAccountIDMap.put(c.ID, c.Account.ParentID);
            } else {
                contactToAccountIDMap.put(c.ID, c.AccountID);
                accountAndParentAcctIDSet.add(c.AccountID);
            }
        }

        Map<ID, Account_Team__C> accountTeamCSAMMap = accountTeamHandler.createAccountTeamCSAMMap(
            accountAndParentAcctIDSet
        );

        List<Contact> updateContactList = new List<Contact>();
        //For the Contact check if the CSAMmember exists and there is a matching owner
        //If no CSAM exists then make sure the contact matches the account owner
        for (Contact c : scope) {
            contact contactToUpdate = new Contact();
            contactToUpdate.ID = c.ID;
            //When an Account has a parent always use the parent AccountID so use the Map from above
            if (contactToAccountIDMap.containsKey(c.ID)) {
                ID lAccountID = contactToAccountIDMap.get(c.ID);

                if (accountTeamCSAMMap.containsKey(lAccountID)) {
                    Account_Team__C atm = accountTeamCSAMMap.get(lAccountID);
                    if (c.OwnerID != atm.Team_Member__c) {
                        contactToUpdate.OwnerID = atm.Team_Member__c;
                        updateContactList.add(contactToUpdate);
                    }
                } else if (c.OwnerID != c.Account.OwnerID) {
                    contactToUpdate.OwnerID = c.Account.OwnerID;
                    updateContactList.add(contactToUpdate);
                }
            }
        }

        if (!updateContactList.isEmpty()) {
            recordsProcessed += updateContactList.size();
            updateTracker += DatabaseUtilities.saveToDatabaseTracking(
                updateContactList,
                AUDIT_DEV_NAME,
                AUDIT_DEV_NOTE
            );
        }

        //Update the Opportunity Owner to be the contacts Owner
        //Get All Opportunities that are Open and Update accordingly
        List<Opportunity> opportunityFetchList = [
            SELECT ID, OWNERID, PRIMARY_CONTACT__C, PRIMARY_CONTACT__R.OWNERID
            FROM Opportunity
            WHERE
                StageName NOT IN ('Closed Won', 'Closed Lost')
                AND PRIMARY_CONTACT__C IN :contactIDSet
                AND RecordTypeId = :oppManufacturingServRTypeID
        ];
        List<Opportunity> opportunityToUpdateList = new List<Opportunity>();
        for (Opportunity opp : opportunityFetchList) {
            if (opp.OWNERID != opp.PRIMARY_CONTACT__R.OWNERID) {
                Opportunity updateOpp = new Opportunity();
                updateOpp.ID = opp.ID;
                updateOpp.OWNERID = opp.PRIMARY_CONTACT__R.OWNERID;
                opportunityToUpdateList.add(updateOpp);
            }
        }

        if (opportunityToUpdateList.size() > 0) {
            recordsProcessed += opportunityToUpdateList.size();
            updateTracker += DatabaseUtilities.saveToDatabaseTracking(
                opportunityToUpdateList,
                AUDIT_DEV_NAME,
                AUDIT_DEV_NOTE
            );
        }

        //Update the Project Owner to be the contacts Owner
        //Get Projects and Update Accordingly
        List<Project__c> projectList = new List<Project__c>(
            [
                SELECT Id, OwnerId, Primary_Contact__c, Primary_Contact__r.OwnerId
                FROM Project__c
                WHERE
                    Primary_Contact__c IN :contactIDSet
                    AND Stage__c NOT IN ('Closed Won', 'Closed Lost')
                    AND Hold_Project_to_Prior_Owner__c = FALSE
            ]
        );
        List<Project__c> projectsToUpdateList = new List<Project__c>();
        for (Project__c thisProject : projectList) {
            if (thisProject.OwnerId != thisProject.Primary_Contact__r.OwnerId) {
                //Project__c updateOpp = new Project__c();
                //updateOpp.Id = opp.Id;
                thisProject.OwnerId = thisProject.Primary_Contact__r.OwnerId;
                projectsToUpdateList.add(thisProject);
            }
        }
        if (projectsToUpdateList.size() > 0) {
            recordsProcessed += projectsToUpdateList.size();
            updateTracker += DatabaseUtilities.saveToDatabaseTracking(
                projectsToUpdateList,
                AUDIT_DEV_NAME,
                AUDIT_DEV_NOTE
            );
        }

        System.debug('Current Records Processed' + recordsProcessed);
        System.debug('The update tracker records for this batch are ' + updatetracker);
    }

    global void finish(Database.BatchableContext bc) {
        //execute any post-processing operations
        //this is uesful for testing with Database.Stateful turning off for production to improve performance
        //System.debug(recordsProcessed + ' records processed. Shazam!');
        System.debug('Finished CSAM processing Shazam!');
    }
}