unpackaged/main/default/objects/Account/fields/Batch_Reassign__c.field-meta.xml
<CustomField>
    <fullName>Batch_Reassign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Batch Reassign</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Batch</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Date_of_First_Quote__c.field-meta.xml
<CustomField>
    <fullName>Date_of_First_Quote__c</fullName>
    <label>Date of First Quote</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/House_Retainer__c.field-meta.xml
<CustomField>
    <fullName>House_Retainer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>House Retainer</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Success_Team__c.field-meta.xml
<CustomField>
    <fullName>Success_Team__c</fullName>
    <formula>IF(ISBLANK(ParentId),
 (House_Retainer__c || Generic_Account__c) &amp;&amp;
 (ISBLANK(GNO_PartnerId__c) || !ISBLANK(Date_of_First_Quote__c))
,
 (Parent.House_Retainer__c || Parent.Generic_Account__c) &amp;&amp;
 (ISBLANK(Parent.GNO_PartnerId__c) || !ISBLANK(Parent.Date_of_First_Quote__c))
)</formula>
    <label>Success Team</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Primary_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>The Primary Email of the Contact.</description>
    <externalId>true</externalId>
    <inlineHelpText>Adjust the email above to change the value. The Primary Email Address is a unique email in the system.</inlineHelpText>
    <label>Primary Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Success_Team__c.field-meta.xml
<CustomField>
    <fullName>Success_Team__c</fullName>
    <formula>Account.Success_Team__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Success Team</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Container for Opportunities that are part of the same project</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <inlineHelpText>A short description of this Project</inlineHelpText>
    <label>Project</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/AccountSuccessTeamReassignBatch_Test.cls
@isTest
private class AccountSuccessTeamReassignBatch_Test {
    static User objUser = [SELECT Id FROM User WHERE Name = 'Success Team'];

    @TestSetup
    private static void setup() {
        Map<String, Account> accountHierarchyMap = TestDataFactory.createTestAccountHierarchy();

        accountHierarchyMap.get('Dragon Keepers').House_Retainer__c = TRUE;
        accountHierarchyMap.get('Dragon Keepers').Date_of_First_Quote__c = System.Today().addDays(-3);
        update accountHierarchyMap.get('Dragon Keepers');
    }

    @isTest
    private static void PendingPayment() {

        List<Account> lstAcc = [SELECT Id, ParentId, Success_Team__c, Owner.Name FROM Account];

        Project__c project1 = TestDataFactory.createProject(
            true,
            null,
            lstAcc[0].Id,
            null,
            'PreInserted Project',
            'Pending Payment'
        );

        Test.startTest();
            Database.executeBatch(new AccountSuccessTeamReassignBatch());
        Test.stopTest();

        List<Account> lstAcc2 = [SELECT Id, ParentId, Success_Team__c, Owner.Name, Batch_Reassign__c FROM Account WHERE ParentId = null AND Success_Team__c = TRUE AND Owner.Name != 'Success Team'];
        System.assertEquals(lstAcc2[0].Batch_Reassign__c, null, 'The Batch_Reassign__c field was populated');
    }

    @isTest
    private static void closedProjects() {
        List<Account> lstAcc = [SELECT Id, ParentId, Success_Team__c, Owner.Name FROM Account];

        Project__c project1 = TestDataFactory.createProject(
            true,
            null,
            lstAcc[0].Id,
            null,
            'PreInserted Project',
            'Closed won'
        );

        Test.startTest();
            Database.executeBatch(new AccountSuccessTeamReassignBatch());
        Test.stopTest();

        List<Account> lstAcc2 = [SELECT Id, ParentId, Success_Team__c, Owner.Name, Batch_Reassign__c FROM Account WHERE ParentId = null AND Success_Team__c = TRUE AND Owner.Name != 'Success Team'];
        System.assertEquals(lstAcc2[0].Batch_Reassign__c, objUser.Id, 'The Batch_Reassign__c field was not populated');
    }

    @isTest
    private static void open_LastActivityLessThanLast7Days() {
        List<Account> lstAcc = [SELECT Id, ParentId, Success_Team__c, Owner.Name FROM Account];

        Contact objContact = new Contact();
        objContact.FirstName = 'TestMan';
        objContact.LastName = 'LastNamington';
        objContact.Primary_Email__c = 'TestMan@domain.com';
        insert objContact;

        Datetime dtLastDate = Datetime.now().addDays(-15);
        Test.setCreatedDate(objContact.Id, dtLastDate);

        Project__c project1 = TestDataFactory.createProject(
            true,
            objContact.Id,
            lstAcc[0].Id,
            null,
            'PreInserted Project',
            'Open'
        );

        Test.startTest();
            Database.executeBatch(new AccountSuccessTeamReassignBatch());
        Test.stopTest();

        List<Account> lstAcc2 = [SELECT Id, ParentId, Success_Team__c, Owner.Name, Batch_Reassign__c FROM Account WHERE ParentId = null AND Success_Team__c = TRUE AND Owner.Name != 'Success Team'];
        System.assertEquals(lstAcc2[0].Batch_Reassign__c, null, 'The Batch_Reassign__c field was populated');
    }

    @isTest
    private static void open_CreatedDateLessThanLast7Days() {
        List<Account> lstAcc = [SELECT Id, ParentId, Success_Team__c, Owner.Name FROM Account];
        
        Project__c project1 = TestDataFactory.createProject(
            true,
            null,
            lstAcc[0].Id,
            null,
            'PreInserted Project',
            'Open'
        );

        Datetime dtLastDate = Datetime.now().addDays(-15);
        Test.setCreatedDate(project1.Id, dtLastDate);

        Test.startTest();
            Database.executeBatch(new AccountSuccessTeamReassignBatch());
        Test.stopTest();

        List<Account> lstAcc2 = [SELECT Id, ParentId, Success_Team__c, Owner.Name, Batch_Reassign__c FROM Account WHERE ParentId = null AND Success_Team__c = TRUE AND Owner.Name != 'Success Team'];
        System.assertEquals(lstAcc2[0].Batch_Reassign__c, objUser.Id, 'The Batch_Reassign__c field was not populated');
    }

    @isTest
    private static void open_LastActivityGreaterThanLast7Days () {
        List<Account> lstAcc = [SELECT Id, ParentId, Success_Team__c, Owner.Name FROM Account];

        Contact objContact = new Contact();
        objContact.FirstName = 'TestMan';
        objContact.LastName = 'LastNamington';
        objContact.Primary_Email__c = 'TestMan@domain.com';
        insert objContact;

        Project__c project1 = TestDataFactory.createProject(
            true,
            objContact.Id,
            lstAcc[0].Id,
            null,
            'PreInserted Project',
            'Open'
        );

        Test.startTest();
            Database.executeBatch(new AccountSuccessTeamReassignBatch());
        Test.stopTest();

        List<Account> lstAcc2 = [SELECT Id, ParentId, Success_Team__c, Owner.Name, Batch_Reassign__c FROM Account WHERE ParentId = null AND Success_Team__c = TRUE AND Owner.Name != 'Success Team'];
        System.assertEquals(lstAcc2[0].Batch_Reassign__c, null, 'The Batch_Reassign__c field was populated');
    }

    @isTest
    private static void open_CreatedDateGreaterThanLast7Days() {
        List<Account> lstAcc = [SELECT Id, ParentId, Success_Team__c, Owner.Name FROM Account];
        

        Project__c project1 = TestDataFactory.createProject(
            true,
            null,
            lstAcc[0].Id,
            null,
            'PreInserted Project',
            'Open'
        );

        Test.startTest();
            Database.executeBatch(new AccountSuccessTeamReassignBatch());
        Test.stopTest();

        List<Account> lstAcc2 = [SELECT Id, ParentId, Success_Team__c, Owner.Name, Batch_Reassign__c FROM Account WHERE ParentId = null AND Success_Team__c = TRUE AND Owner.Name != 'Success Team'];
        System.assertEquals(lstAcc2[0].Batch_Reassign__c, null, 'The Batch_Reassign__c field was populated');
    }
}