unpackaged/main/default/objects/Account/fields/Batch_Reassign__c.field-meta.xml
<CustomField>
    <fullName>Batch_Reassign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Batch Reassign</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Batch</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Success_Team__c.field-meta.xml
<CustomField>
    <fullName>Success_Team__c</fullName>
    <formula>IF(ISBLANK(ParentId),
 (House_Retainer__c || Generic_Account__c) &amp;&amp;
 (ISBLANK(GNO_PartnerId__c) || !ISBLANK(Date_of_First_Quote__c))
,
 (Parent.House_Retainer__c || Parent.Generic_Account__c) &amp;&amp;
 (ISBLANK(Parent.GNO_PartnerId__c) || !ISBLANK(Parent.Date_of_First_Quote__c))
)</formula>
    <label>Success Team</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Container for Opportunities that are part of the same project</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project__c/fields/Primary_Contact_Last_Activity_Date_AM__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_Last_Activity_Date_AM__c</fullName>
    <formula>Primary_Contact__r.Last_Activity_Date_AM__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Contact Last Activity Date AM</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Primary_Contact_Next_Activity_Date_AM__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_Next_Activity_Date_AM__c</fullName>
    <formula>Primary_Contact__r.Next_Activity_Date_AM__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Contact Next Activity Date AM</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <inlineHelpText>A short description of this Project</inlineHelpText>
    <label>Project</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Initial Engagement</fullName>
            </value>
            <value>
                <fullName>Negotiation / Revision</fullName>
            </value>
            <value>
                <fullName>Pending Payment</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Top_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Top_Account_Id__c</fullName>
    <formula>IF(!ISBLANK(AccountId__r.ParentId),CASESAFEID(AccountId__r.ParentId),CASESAFEID(AccountId__c))</formula>
    <label>Top Account Id</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/AccountSuccessTeamReassignBatch.cls
global class AccountSuccessTeamReassignBatch implements Database.Batchable<sObject> {

    global User objSuccessTeamUser = [SELECT Id FROM User WHERE Name = 'Success Team'];

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            [
                SELECT Id
                FROM Account
                WHERE 
                    ParentId = null AND 
                    Success_Team__c = TRUE AND 
                    OwnerId !=: objSuccessTeamUser.Id
            ]
        );
    }

    global void execute(Database.BatchableContext bc, List<Account> accountList) {
        Map<String, Account> mapAccountReassing = new Map<String,Account>(accountList);
        Set<String> setAccountId = mapAccountReassing.keySet();
        Date dtSevenDaysAgo = System.today().addDays(-7);

        List<Project__c> lstProjects = [SELECT Top_Account_Id__c 
                                        FROM Project__c 
                                        WHERE   
                                            Top_Account_Id__c IN: setAccountId AND        
                                            (
                                                Stage__c IN ('Pending Payment') OR
                                                (
                                                    (NOT Stage__c IN ('Closed Won', 'Closed Lost', 'Pending Payment')) AND 
                                                    (
                                                        Primary_Contact_Last_Activity_Date_AM__c >=: dtSevenDaysAgo OR
                                                        Primary_Contact_Next_Activity_Date_AM__c >=: System.Today() OR
                                                        CreatedDate >=: dtSevenDaysAgo
                                                    )
                                                )
                                            )                                                   
                                        ];
        
        for(Project__c objProject : lstProjects)
        {
            mapAccountReassing.remove(objProject.Top_Account_Id__c);
        }
        
        for(Account objAccount : mapAccountReassing.values())
        {
            System.debug('objAccount.Id ::: '+objAccount.Id);
            objAccount.Batch_Reassign__c = objSuccessTeamUser.Id;
        }

        DatabaseUtilities.saveToDatabase(mapAccountReassing.values(), 'AccountSuccessTeamReassignBatch.execute', 'Reassign accounts to Success Team User');
    }

    global void finish(Database.BatchableContext bc) {
    }
}