unpackaged/main/default/objects/Account/fields/Batch_Reassign__c.field-meta.xml
<CustomField>
    <fullName>Batch_Reassign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Batch Reassign</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Batch</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Admin_Ref_Variable__mdt/Admin_Ref_Variable__mdt.object-meta.xml
<CustomObject>
    <description>This custom metadata is used to allow admins to adjust variables that are used in Apex flows</description>
    <label>Admin Ref Variable</label>
    <pluralLabel>Admin Ref Variables</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Admin_Ref_Variable__mdt/fields/Text_Ref_Var__c.field-meta.xml
<CustomField>
    <fullName>Text_Ref_Var__c</fullName>
    <description>If the variable to be referenced by apex or elsewhere is a text variable</description>
    <label>Text Ref Var</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Primary_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>The Primary Email of the Contact.</description>
    <externalId>true</externalId>
    <inlineHelpText>Adjust the email above to change the value. The Primary Email Address is a unique email in the system.</inlineHelpText>
    <label>Primary Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Quick Reference to the Primary Contact on an Opportunity</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities(PC)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Container for Opportunities that are part of the same project</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <inlineHelpText>A short description of this Project</inlineHelpText>
    <label>Project</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Initial Engagement</fullName>
            </value>
            <value>
                <fullName>Negotiation / Revision</fullName>
            </value>
            <value>
                <fullName>Pending Payment</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/AccountReassignBatchTest.cls
@isTest
private class AccountReassignBatchTest {
    @isTest(seeAllData=false)
    private static void accountReassignBatchTest() {
        Id currentUserId = UserInfo.getUserId();
        Account a = TestDataFactory.createTestAccountNonGenerics(5, 'AM', 1)[0];
        Id oldOwnerId = a.OwnerId;
        a.Batch_Reassign__c = currentUserId;
        update a;

        System.assertNotEquals(oldOwnerId, currentUserId);

        Test.startTest();
        AccountReassignBatch batch = new AccountReassignBatch();
        Database.executeBatch(batch);

        Test.stopTest();

        System.assertEquals(
            currentUserId,
            [SELECT OwnerId FROM Account WHERE Id = :a.Id]
            .OwnerId,
            'Account should be reassigned.'
        );
    }

    @isTest(seeAllData=false)
    private static void accountIgnoreReassignBatchTest() {
        Account a = TestDataFactory.createTestAccountNonGenerics(5, 'AM', 1)[0];
        User currentUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        User oldOwner = new User(Id = a.OwnerId);

        a.Batch_Reassign__c = oldOwner.Id;
        a.OwnerId = currentUser.Id;
        update a;

        System.assertNotEquals(oldOwner.Id, a.OwnerId);

        System.runAs(currentUser) {
            oldOwner.isActive = false;
            update oldOwner;
        }

        Test.startTest();
        AccountReassignBatch batch = new AccountReassignBatch();
        Database.executeBatch(batch);
        Test.stopTest();

        System.assertEquals(currentUser.Id, [SELECT OwnerId FROM Account WHERE Id = :a.Id].OwnerId);
        System.assertEquals(
            oldOwner.Id,
            [SELECT Batch_Reassign__c FROM Account WHERE Id = :a.Id]
            .Batch_Reassign__c,
            'Reassign should be skiped on inactive users'
        );
    }

    @isTest(seeAllData=false)
    private static void accountReassignCLProjectBatchTest() {
        Id adminRefPoolId;
        for (Admin_Ref_Variable__mdt adminRefVarValues : [
            SELECT Text_Ref_Var__c
            FROM Admin_Ref_Variable__mdt
            WHERE DeveloperName = 'ProjectCloseAuto'
        ]) {
            adminRefPoolId = adminRefVarValues.Text_Ref_Var__c.split(';')[0];
        }

        Account testAccount = TestDataFactory.createTestAccountNonGenerics(5, 'AM', 1)[0];
        testAccount.Batch_Reassign__c = adminRefPoolId;
        update testAccount;

        Contact testContact = new Contact(
            AccountId = testAccount.Id,
            Primary_Email__c = 'test@test123.com',
            FirstName = 'Test',
            LastName = 'Contact'
        );
        insert testContact;

        Project__c testProject = new Project__c(
            AccountId__c = testAccount.Id,
            Name = 'Test Project',
            Stage__c = 'New',
            Primary_Contact__c = testContact.Id
        );
        insert testProject;

        Test.startTest();
        AccountReassignBatch batch = new AccountReassignBatch();
        Database.executeBatch(batch);
        Test.stopTest();

        System.assertEquals(
            adminRefPoolId,
            [SELECT OwnerId FROM Account WHERE Id = :testAccount.Id]
            .OwnerId,
            'Account should be reassigned.'
        );
        System.assertEquals(
            'Closed Lost',
            [SELECT Stage__c FROM Project__c WHERE Id = :testProject.Id]
            .Stage__c,
            'Project should be closed.'
        );
    }

    @isTest(seeAllData=false)
    private static void accountReassignCWProjectBatchTest() {
        Id adminRefPoolId;
        for (Admin_Ref_Variable__mdt adminRefVarValues : [
            SELECT Text_Ref_Var__c
            FROM Admin_Ref_Variable__mdt
            WHERE DeveloperName = 'ProjectCloseAuto'
        ]) {
            adminRefPoolId = adminRefVarValues.Text_Ref_Var__c.split(';')[0];
        }

        Account testAccount = TestDataFactory.createTestAccountNonGenerics(5, 'AM', 1)[0];
        testAccount.Batch_Reassign__c = adminRefPoolId;
        update testAccount;

        Contact testContact = new Contact(
            AccountId = testAccount.Id,
            Primary_Email__c = 'test@test123.com',
            FirstName = 'Test',
            LastName = 'Contact'
        );
        insert testContact;

        Project__c testProject = new Project__c(
            AccountId__c = testAccount.Id,
            Name = 'Test Project',
            Stage__c = 'New',
            Primary_Contact__c = testContact.Id
        );
        insert testProject;

        Opportunity testOpp = new Opportunity(
            Name = 'Test',
            Project__c = testProject.Id,
            StageName = 'Closed Won',
            CloseDate = Date.today()
        );
        insert testOpp;

        Test.startTest();
        AccountReassignBatch batch = new AccountReassignBatch();
        Database.executeBatch(batch);
        Test.stopTest();

        System.assertEquals(
            adminRefPoolId,
            [SELECT OwnerId FROM Account WHERE Id = :testAccount.Id]
            .OwnerId,
            'Account should be reassigned.'
        );
        System.assertEquals(
            'Closed Won',
            [SELECT Stage__c FROM Project__c WHERE Id = :testProject.Id]
            .Stage__c,
            'Project should be closed.'
        );
    }
}