unpackaged/main/default/objects/Account/fields/Batch_Reassign__c.field-meta.xml
<CustomField>
    <fullName>Batch_Reassign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Batch Reassign</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Batch</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Admin_Ref_Variable__mdt/Admin_Ref_Variable__mdt.object-meta.xml
<CustomObject>
    <description>This custom metadata is used to allow admins to adjust variables that are used in Apex flows</description>
    <label>Admin Ref Variable</label>
    <pluralLabel>Admin Ref Variables</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Admin_Ref_Variable__mdt/fields/Text_Ref_Var__c.field-meta.xml
<CustomField>
    <fullName>Text_Ref_Var__c</fullName>
    <description>If the variable to be referenced by apex or elsewhere is a text variable</description>
    <label>Text Ref Var</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Container for Opportunities that are part of the same project</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Closed_Lost_Reason__c.field-meta.xml
<CustomField>
    <fullName>Closed_Lost_Reason__c</fullName>
    <inlineHelpText>Some Closed Lost details require additional information. For example: if selecting Competition please enter the competitor's name or 'Unknown'.</inlineHelpText>
    <label>Closed Lost Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <inlineHelpText>A short description of this Project</inlineHelpText>
    <label>Project</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Initial Engagement</fullName>
            </value>
            <value>
                <fullName>Negotiation / Revision</fullName>
            </value>
            <value>
                <fullName>Pending Payment</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Sub_Stage__c.field-meta.xml
<CustomField>
    <fullName>Sub_Stage__c</fullName>
    <label>Sub Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Stage__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Sub_Stage</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Sub_Stage.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>No Response</fullName>
    </customValue>
    <customValue>
        <fullName>No Bid</fullName>
    </customValue>
    <customValue>
        <fullName>Price</fullName>
    </customValue>
    <customValue>
        <fullName>Lead Time</fullName>
    </customValue>
    <customValue>
        <fullName>Service Concerns</fullName>
    </customValue>
    <customValue>
        <fullName>Project Canceled</fullName>
    </customValue>
    <customValue>
        <fullName>Purchasing from Different Opportunity</fullName>
    </customValue>
    <customValue>
        <fullName>On-Demand Competition</fullName>
    </customValue>
    <customValue>
        <fullName>Local Competition</fullName>
    </customValue>
    <customValue>
        <fullName>Budgetary</fullName>
    </customValue>
    <customValue>
        <fullName>Late Quote</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Made In-House</fullName>
    </customValue>
    <customValue>
        <fullName>Auto-Closed</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Project on Hold</fullName>
    </customValue>
    <customValue>
        <fullName>Purchase Order</fullName>
    </customValue>
    <customValue>
        <fullName>Credit Card</fullName>
    </customValue>
    <masterLabel>Sub Stage</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/AccountReassignBatch.cls
/**
 * @description simple batch to reduce flow cpu work
 * scan for accounts flagged with Batch_Reassign__c and update the owner with the value
 */

global class AccountReassignBatch implements Database.Batchable<sObject>, Database.Stateful {
    static final String BATCH_METHOD_NAME = 'AccountReassignBatch.execute';
    Set<Id> queueAndactiveUserIds = new Set<Id>();
    Set<Id> adminRefPoolIds = new Set<Id>();

    public AccountReassignBatch() {
        for (Group g : [SELECT Id, Type, Name FROM Group WHERE Type = 'Queue']) {
            queueAndactiveUserIds.add(g.Id);
        }

        for (User u : [SELECT Id FROM User WHERE IsActive = TRUE]) {
            queueAndactiveUserIds.add(u.Id);
        }

        for (Admin_Ref_Variable__mdt adminRefVarValues : [
            SELECT Text_Ref_Var__c
            FROM Admin_Ref_Variable__mdt
            WHERE DeveloperName = 'ProjectCloseAuto'
        ]) {
            adminRefPoolIds.addAll((List<Id>) adminRefVarValues.Text_Ref_Var__c.split(';'));
        }
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            [SELECT Id, Batch_Reassign__c FROM Account WHERE Batch_Reassign__c IN :queueAndactiveUserIds]
        );
    }

    global void execute(Database.BatchableContext bc, List<Account> accList) {
        List<Account> accountsToReassign = new List<Account>();
        List<Id> accountsToClose = new List<Id>();
        for (Account acc : accList) {
            if (adminRefPoolIds.contains(acc.Batch_Reassign__c)) {
                accountsToClose.add(acc.Id);
            }
            acc.OwnerId = acc.Batch_Reassign__c;
            acc.Batch_Reassign__c = null;
            accountsToReassign.add(acc);
        }

        Map<Id, Project__c> projectsToCloseMap = new Map<Id, Project__c>();
        for (Project__c project : [
            SELECT Id
            FROM Project__c
            WHERE AccountId__c IN :accountsToClose AND Stage__c NOT IN ('Closed Lost', 'Closed Won')
        ]) {

            projectsToCloseMap.put(project.Id, project);

        }

        //Get a list of cw opps that are in Closed Projects
        Set<Id> projectsWithCwOppsSet = new Set<Id>();
        for (Opportunity opp : [
            SELECT ID, StageName, Project__c
            FROM Opportunity
            WHERE StageName = 'Closed Won' AND Project__c IN :projectsToCloseMap.keySet()
        ]) {

            projectsWithCwOppsSet.add(opp.Project__c);

        }

        for( Project__c project : projectsToCloseMap.values() ){

            if( !projectsWithCwOppsSet.contains(project.Id) ){
                project.Stage__c = 'Closed Lost';
                project.Sub_Stage__c = 'Auto-Closed';
                project.Closed_Lost_Reason__c = 'Auto-closed due to reassignment back to the Pool User';
            }else{
                project.Stage__c = 'Closed Won';
            }

        }

        DatabaseUtilities.saveToDatabase(projectsToCloseMap.values(), BATCH_METHOD_NAME, 'Project Close Batch update');

        DatabaseUtilities.saveToDatabase(accountsToReassign, BATCH_METHOD_NAME, 'Account Reassign Batch update');
    }

    global void finish(Database.BatchableContext bc) {
    }
}