unpackaged/main/default/objects/Account/fields/Date_of_First_Order__c.field-meta.xml
<CustomField>
    <fullName>Date_of_First_Order__c</fullName>
    <description>This field is the date of First Order on Account. Used to populate a countdown timer for  BDRs and as a reference.</description>
    <label>Date of First Order</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Number_Orderers__c.field-meta.xml
<CustomField>
    <fullName>Number_Orderers__c</fullName>
    <label># of Buyers</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/Order_Erp__c.object-meta.xml
<CustomObject>
    <description>This object cotains the orders from Xometry ERP. An order is created in Salesforce when the Order date is populated. 

Technical Note: Quote and Orders are the same object in the source system but seperated in Salesforce as Orders represent the end of the opportunity process.</description>
    <label>Order ERP</label>
    <nameField>
        <displayFormat>Order-{000000}</displayFormat>
        <label>Order Erp Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders ERP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order_Erp__c/fields/AccountID__c.field-meta.xml
<CustomField>
    <fullName>AccountID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Account that the order is placed for.</description>
    <label>AccountID</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Orders_Erp</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/ContactID__c.field-meta.xml
<CustomField>
    <fullName>ContactID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ContactID</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Orders_Erp</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/Order_ERP_CreatedDate__c.field-meta.xml
<CustomField>
    <fullName>Order_ERP_CreatedDate__c</fullName>
    <description>Date that an order was placed.</description>
    <label>Order Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/updateAccountOrderERPInfoBatch.cls
/*
Batch class that summarizes in the account record what is the first Order_ERP, the last Order_ERP and the number of different contacts related to the Order_ERP records of the account
*/
global class updateAccountOrderERPInfoBatch implements Database.Batchable<sObject>, Database.Stateful {
    // instance member to retain state across transactions
    global Integer UCQDrecordsProcessed = 0;
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT ID from Account'
        );
    }
    global void execute(Database.BatchableContext bc, List<Account> scope) {
        Map<ID, Account> lAccountIDMap = new Map<ID, Account>(scope);
        SET<ID> lAccountIDSET = lAccountIDMap.keySet();
        
        // Fetch the Orders ERP Dates
        AggregateResult[] orderAggRes = [
            SELECT
                AccountID__C AccountID,
                Max(Order_ERP_CreatedDate__c) Last_Order_Date,
                Min(Order_ERP_CreatedDate__c) First_Order_Date,
                COUNT_DISTINCT(ContactID__c) Num_of_Orderers
            FROM Order_ERP__C
            WHERE AccountID__C IN :lAccountIDSET
            GROUP BY AccountID__C
        ];
        for (AggregateResult laggRes : orderAggRes) {
            ID lID = ID.valueOf(String.valueOf(laggRes.get('AccountID')));
            Date lLastOrderDate = Date.valueOf(String.valueOf(laggRes.get('Last_Order_Date')));
            Date lFirstOrderDate = Date.valueOf(String.valueOf(laggRes.get('First_Order_Date')));
            Integer lNum_of_Orderers = Integer.valueOf(String.valueOf(laggRes.get('Num_of_Orderers')));
            if (lAccountIDMap.containsKey(lID)) {
                account lAccount = lAccountIDMap.get(lID);
                lAccount.Date_of_First_Order__c = lFirstOrderDate;
                lAccount.Date_of_Last_Order__c = lLastOrderDate;
                lAccount.Number_Orderers__c = lNum_of_Orderers;
                lAccountIDMap.put(lAccount.ID, lAccount);
            }
        }
        
        //Update the Accounts
        System.debug('About to start the Account Updates');
        List<Account> accountUpdateList = new List<Account>();
        accountUpdateList = lAccountIDMap.values();
        System.debug('Account to Update List is');
        System.debug(accountUpdateList);
        Integer updateTracker = DatabaseUtilities.saveToDatabaseTracking(
            accountUpdateList,
            'updateAccountOrderERPInfoBatch.execute',
            'Account Updates in Execution updateAccountOrderERPInfoBatch'
        );
        UCQDrecordsProcessed = UCQDrecordsProcessed + accountUpdateList.size();

        System.debug('Account Records Processed ' + UCQDrecordsProcessed);
        System.debug('The update tracker records for this batch are ' + updateTracker);
    }

    global void finish(Database.BatchableContext bc) {
        System.debug(UCQDrecordsProcessed + ' records processed. Shazam!');
    }
}