unpackaged/main/default/objects/Account/fields/Date_of_First_Order__c.field-meta.xml
<CustomField>
    <fullName>Date_of_First_Order__c</fullName>
    <description>This field is the date of First Order on Account. Used to populate a countdown timer for  BDRs and as a reference.</description>
    <label>Date of First Order</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Date_of_First_Quote__c.field-meta.xml
<CustomField>
    <fullName>Date_of_First_Quote__c</fullName>
    <label>Date of First Quote</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Number_Orderers__c.field-meta.xml
<CustomField>
    <fullName>Number_Orderers__c</fullName>
    <label># of Buyers</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Number_Quoters__c.field-meta.xml
<CustomField>
    <fullName>Number_Quoters__c</fullName>
    <label># of Quoters</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Sup_DateOfLastOrder__c.field-meta.xml
<CustomField>
    <fullName>Sup_DateOfLastOrder__c</fullName>
    <label>Supplies Date of Last Order</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Sup_NumberOfOrderers__c.field-meta.xml
<CustomField>
    <fullName>Sup_NumberOfOrderers__c</fullName>
    <label>Supplies Number of Orderers</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Sup_NumberQuoters__c.field-meta.xml
<CustomField>
    <fullName>Sup_NumberQuoters__c</fullName>
    <label>Supplies Number of Quoters</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/Order_Erp__c.object-meta.xml
<CustomObject>
    <description>This object cotains the orders from Xometry ERP. An order is created in Salesforce when the Order date is populated. 

Technical Note: Quote and Orders are the same object in the source system but seperated in Salesforce as Orders represent the end of the opportunity process.</description>
    <label>Order ERP</label>
    <nameField>
        <displayFormat>Order-{000000}</displayFormat>
        <label>Order Erp Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders ERP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order_Erp__c/fields/AccountID__c.field-meta.xml
<CustomField>
    <fullName>AccountID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Account that the order is placed for.</description>
    <label>AccountID</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Orders_Erp</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/ContactID__c.field-meta.xml
<CustomField>
    <fullName>ContactID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ContactID</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Orders_Erp</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/Order_ERP_CreatedDate__c.field-meta.xml
<CustomField>
    <fullName>Order_ERP_CreatedDate__c</fullName>
    <description>Date that an order was placed.</description>
    <label>Order Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/Quote_ERP__c.object-meta.xml
<CustomObject>
    <description>A quote that is sent over from ERP</description>
    <label>Quote ERP</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote_ERP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes ERP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Quote_ERP__c/fields/AccountID__c.field-meta.xml
<CustomField>
    <fullName>AccountID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Account that the quote belongs to</description>
    <label>AccountID</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Quotes_ERP</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/ContactID__c.field-meta.xml
<CustomField>
    <fullName>ContactID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Contact</description>
    <label>ContactID</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Quotes_ERP</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Quote_ERP_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Quote_ERP_Created_Date__c</fullName>
    <description>The date the quote was created in the ERP system</description>
    <label>Quote Created Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Order__c/Supplies_Order__c.object-meta.xml
<CustomObject>
    <label>Supplies Order</label>
    <nameField>
        <label>Supplies Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplies Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Supplies_Order__c/fields/AccountID__c.field-meta.xml
<CustomField>
    <fullName>AccountID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AccountID</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supplies Orders</relationshipLabel>
    <relationshipName>Supplies_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Order__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ContactId</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Supplies Orders</relationshipLabel>
    <relationshipName>Supplies_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Quote__c/Supplies_Quote__c.object-meta.xml
<CustomObject>
    <description>This stores the P21 Quotes as records in Salesforce before transformation.</description>
    <label>Supplies Quote</label>
    <nameField>
        <label>Supplies Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplies Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Supplies_Quote__c/fields/AccountID__c.field-meta.xml
<CustomField>
    <fullName>AccountID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AccountID</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supplies Quotes</relationshipLabel>
    <relationshipName>Supplies_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Quote__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ContactId</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Supplies Quotes</relationshipLabel>
    <relationshipName>Supplies_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Quote__c/fields/Quote_P21_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Quote_P21_Created_Date__c</fullName>
    <label>Quote Created Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/updateAccountQuoteDates.cls
global class updateAccountQuoteDates implements Database.Batchable<sObject>, Database.Stateful {
    // instance member to retain state across transactions
    global Integer UCQDrecordsProcessed = 0;
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT ID, Name,Number_Quoters__c, Number_Orderers__c, Date_of_First_Order__c, Date_of_First_Quote__c, Date_of_Last_Order__c, Date_of_Last_Quote__c, Sup_DateOfFirstQuote__c, Sup_DateOfLastQuote__c, Sup_NumberQuoters__c, Sup_DateOfFirstOrder__c, Sup_DateOfLastOrder__c, Sup_NumberOfOrderers__c from Account'
        );
    }
    global void execute(Database.BatchableContext bc, List<Account> scope) {
        SET<ID> lAccountIDSET = new Set<ID>();
        Map<ID, Account> lAccountIDMap = new Map<ID, Account>();
        for (Account a : scope) {
            lAccountIDSET.add(a.ID);
            lAccountIDMap.put(a.ID, a);
        }
        // Fetch the Quote Dates
        AggregateResult[] quoteAggRes = [
            SELECT
                AccountID__C AccountID,
                Max(Quote_ERP_Created_Date__C) Last_Quote_Date,
                Min(Quote_ERP_Created_Date__C) First_Quote_Date,
                COUNT_DISTINCT(ContactID__c) Num_of_Quoters
            FROM Quote_ERP__C
            WHERE AccountID__C IN :lAccountIDSET
            GROUP BY AccountID__C
        ];
        for (AggregateResult laggRes : quoteAggRes) {
            ID lID = ID.valueOf(String.valueOf(laggRes.get('AccountID')));
            Date lLastQuoteDate = Date.valueOf(String.valueOf(laggRes.get('Last_Quote_Date')));
            Date lFirstQuoteDate = Date.valueOf(String.valueOf(laggRes.get('First_Quote_Date')));
            Integer lNum_of_Quoters = Integer.valueOf(String.valueOf(laggRes.get('Num_of_Quoters')));
            if (lAccountIDMap.containsKey(lID)) {
                Account lAccount = lAccountIDMap.get(lID);
                lAccount.Date_of_First_Quote__c = lFirstQuoteDate;
                lAccount.Date_of_Last_Quote__c = lLastQuoteDate;
                lAccount.Number_Quoters__c = lNum_of_Quoters;
                lAccountIDMap.put(lAccount.ID, lAccount);
            }
        }
        // Fetch the Orders Data
        AggregateResult[] orderAggRes = [
            SELECT
                AccountID__C AccountID,
                Max(Order_ERP_CreatedDate__c) Last_Order_Date,
                Min(Order_ERP_CreatedDate__c) First_Order_Date,
                COUNT_DISTINCT(ContactID__c) Num_of_Orderers
            FROM Order_ERP__C
            WHERE AccountID__C IN :lAccountIDSET
            GROUP BY AccountID__C
        ];
        for (AggregateResult laggRes : orderAggRes) {
            ID lID = ID.valueOf(String.valueOf(laggRes.get('AccountID')));
            Date lLastOrderDate = Date.valueOf(String.valueOf(laggRes.get('Last_Order_Date')));
            Date lFirstOrderDate = Date.valueOf(String.valueOf(laggRes.get('First_Order_Date')));
            Integer lNum_of_Orderers = Integer.valueOf(String.valueOf(laggRes.get('Num_of_Orderers')));
            if (lAccountIDMap.containsKey(lID)) {
                account lAccount = lAccountIDMap.get(lID);
                lAccount.Date_of_First_Order__c = lFirstOrderDate;
                lAccount.Date_of_Last_Order__c = lLastOrderDate;
                lAccount.Number_Orderers__c = lNum_of_Orderers;
                lAccountIDMap.put(lAccount.ID, lAccount);
            }
        }

        // Fetch the Supplies Quote Dates
        AggregateResult[] suppliesQuoteAggRes = [
            SELECT
                AccountID__C AccountID,
                Max(Quote_P21_Created_Date__c) Sup_LastQuoteDate,
                Min(Quote_P21_Created_Date__c) Sup_FirstQuoteDate,
                COUNT_DISTINCT(ContactID__c) Sup_NumOfQuoters
            FROM Supplies_Quote__C
            WHERE AccountID__C IN :lAccountIDSET
            GROUP BY AccountID__C
        ];
        for (AggregateResult laggRes : suppliesQuoteAggRes) {
            ID lID = ID.valueOf(String.valueOf(laggRes.get('AccountID')));
            Date lSupLastQuoteDate = Date.valueOf(String.valueOf(laggRes.get('Sup_LastQuoteDate')));
            Date lSupFirstQuoteDate = Date.valueOf(String.valueOf(laggRes.get('Sup_FirstQuoteDate')));
            Integer lSupNumOfQuoters = Integer.valueOf(String.valueOf(laggRes.get('Sup_NumOfQuoters')));
            if (lAccountIDMap.containsKey(lID)) {
                Account lAccount = lAccountIDMap.get(lID);
                lAccount.Sup_DateOfFirstQuote__c = lSupFirstQuoteDate;
                lAccount.Sup_DateOfLastQuote__c = lSupLastQuoteDate;
                lAccount.Sup_NumberQuoters__c = lSupNumOfQuoters;
                lAccountIDMap.put(lAccount.ID, lAccount);
            }
        }
        // Fetch the Supplies Order Dates
        AggregateResult[] suppliesOrderAggRes = [
            SELECT
                AccountID__C AccountID,
                Max(Order_Date__c) Sup_LastOrderDate,
                Min(Order_Date__c) Sup_FirstOrderDate,
                COUNT_DISTINCT(ContactID__c) Sup_NumOfOrderers
            FROM Supplies_Order__C
            WHERE AccountID__C IN :lAccountIDSET
            GROUP BY AccountID__C
        ];
        for (AggregateResult laggRes : suppliesOrderAggRes) {
            ID lID = ID.valueOf(String.valueOf(laggRes.get('AccountID')));
            Date lSupLastOrderDate = Date.valueOf(String.valueOf(laggRes.get('Sup_LastOrderDate')));
            Date lSupFirstOrderDate = Date.valueOf(String.valueOf(laggRes.get('Sup_FirstOrderDate')));
            Integer lSupNumOfOrderers = Integer.valueOf(String.valueOf(laggRes.get('Sup_NumOfOrderers')));
            if (lAccountIDMap.containsKey(lID)) {
                account lAccount = lAccountIDMap.get(lID);
                lAccount.Sup_DateOfFirstOrder__c = lSupFirstOrderDate;
                lAccount.Sup_DateOfLastOrder__c = lSupLastOrderDate;
                lAccount.Sup_NumberOfOrderers__c = lSupNumOfOrderers;
                lAccountIDMap.put(lAccount.ID, lAccount);
            }
        }
        //Update the Accounts

        System.debug('About to start the Account Updates');
        List<Account> accountUpdateList = new List<Account>();
        accountUpdateList = lAccountIDMap.values();
        System.debug('Account to Update List is');
        System.debug(accountUpdateList);
        Integer updateTracker = DatabaseUtilities.saveToDatabaseTracking(
            accountUpdateList,
            'updateAccountQuoteDates.execute',
            'Account Updates in Execution Queue'
        );
        UCQDrecordsProcessed = UCQDrecordsProcessed + accountUpdateList.size();

        System.debug('Account Records Processed ' + UCQDrecordsProcessed);
        System.debug('The update tracker records for this batch are ' + updateTracker);
    }

    global void finish(Database.BatchableContext bc) {
        System.debug(UCQDrecordsProcessed + ' records processed. Shazam!');
    }
}