unpackaged/main/default/objects/Account/fields/Date_of_First_Order__c.field-meta.xml
<CustomField>
    <fullName>Date_of_First_Order__c</fullName>
    <description>This field is the date of First Order on Account. Used to populate a countdown timer for  BDRs and as a reference.</description>
    <label>Date of First Order</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Number_Orderers__c.field-meta.xml
<CustomField>
    <fullName>Number_Orderers__c</fullName>
    <label># of Buyers</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Number_Quoters__c.field-meta.xml
<CustomField>
    <fullName>Number_Quoters__c</fullName>
    <label># of Quoters</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Date_of_Last_Order__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Last_Order__c</fullName>
    <label>Date of Last Order</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/Order_Erp__c.object-meta.xml
<CustomObject>
    <description>This object cotains the orders from Xometry ERP. An order is created in Salesforce when the Order date is populated. 

Technical Note: Quote and Orders are the same object in the source system but seperated in Salesforce as Orders represent the end of the opportunity process.</description>
    <label>Order ERP</label>
    <nameField>
        <displayFormat>Order-{000000}</displayFormat>
        <label>Order Erp Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders ERP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order_Erp__c/fields/ERP_Contact__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact__c</fullName>
    <inlineHelpText>Search for this contact  in the ERP to see more information about the contact.</inlineHelpText>
    <label>ERP Contact</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/Order_Subtotal__c.field-meta.xml
<CustomField>
    <fullName>Order_Subtotal__c</fullName>
    <label>Order Subtotal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/Order_Total__c.field-meta.xml
<CustomField>
    <fullName>Order_Total__c</fullName>
    <description>The total on the order</description>
    <label>Order Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>credit_card</fullName>
                <label>Credit Card</label>
            </value>
            <value>
                <fullName>purchase_order</fullName>
                <label>Purchase Order</label>
            </value>
            <value>
                <fullName>buy_now_pay_later</fullName>
                <label>Buy Now Pay Later</label>
            </value>
            <value>
                <fullName>no_payment</fullName>
                <label>No Payment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/process_isCNC_Machining__c.field-meta.xml
<CustomField>
    <fullName>process_isCNC_Machining__c</fullName>
    <defaultValue>false</defaultValue>
    <label>process_isCNC_Machining</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/process_isPolyJet_3D__c.field-meta.xml
<CustomField>
    <fullName>process_isPolyJet_3D__c</fullName>
    <defaultValue>false</defaultValue>
    <label>process_isPolyJet_3D</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/updateAccountOrderERPInfoBatch_Test.cls
@isTest
private class updateAccountOrderERPInfoBatch_Test {
    
    @isTest
    static void scheduleJob() {
        //Call job
        Test.startTest();
        String CRON_EXP = '0 0 0 1 1 ? *';
        String jobID = System.schedule('updateAccountOrderERPInfoBatchJob', CRON_EXP, new updateAccountOrderERPInfoBatchJob());
        Test.stopTest();
    }

    @isTest
    static void excecuteBatch() {
        List<Account> testAccountList = TestDataFactory.createTestAccountNonGenerics(2, 'AM', 1);
        Account testAccount = testAccountList[0];
        ID testAccountID = testAccount.ID;
        Contact myretContact = [
            SELECT ID, FirstName, LastName, Email
            FROM Contact
            WHERE AccountID = :testAccountID
            ORDER BY Name
        ];
        
        // Create an Order
        Order_ERP__C ord = TestDataFactory.createOrderERPFromAccContact(
            false,
            'Q00-0000-0000',
            'AAAAA-00004',
            '55555',
            testAccount,
            myretContact,
            Date.newInstance(2019, 10, 22),
            DateTime.newInstance(2019, 10, 22, 11, 15, 0)
        );

        ord.ERP_Contact__c = 'AAAAA';
        ord.Payment_Type__c = 'credit_card';
        ord.process_isCNC_Machining__c = true;
        ord.process_isPolyJet_3D__c = false;
        ord.Order_Total__c = 1500;
        ord.Order_Subtotal__c = 1450;
        insert ord;
        
        Test.startTest();
        updateAccountOrderERPInfoBatch uAQI = new updateAccountOrderERPInfoBatch();
        ID batchID = Database.executeBatch(uAQI, 200);
        Test.stopTest();
        Account myAccount = [
            SELECT
                ID,
                Name,
                Number_Orderers__c,
                Number_Quoters__c,
                Date_of_First_Order__c,
                Date_of_Last_Order__c
            FROM Account
            WHERE ID = :testAccountID
        ];
        
        System.assertEquals(
            date.newInstance(2019, 10, 22),
            myAccount.Date_of_First_Order__c,
            'Account should have supplies first quote date'
        );
    }
    
}