unpackaged/main/default/objects/Account/fields/Date_of_First_Quote__c.field-meta.xml
<CustomField>
    <fullName>Date_of_First_Quote__c</fullName>
    <label>Date of First Quote</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Number_Quoters__c.field-meta.xml
<CustomField>
    <fullName>Number_Quoters__c</fullName>
    <label># of Quoters</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/Quote_ERP__c.object-meta.xml
<CustomObject>
    <description>A quote that is sent over from ERP</description>
    <label>Quote ERP</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote_ERP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes ERP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Quote_ERP__c/fields/AccountID__c.field-meta.xml
<CustomField>
    <fullName>AccountID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Account that the quote belongs to</description>
    <label>AccountID</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Quotes_ERP</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/ContactID__c.field-meta.xml
<CustomField>
    <fullName>ContactID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Contact</description>
    <label>ContactID</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Quotes_ERP</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Quote_ERP_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Quote_ERP_Created_Date__c</fullName>
    <description>The date the quote was created in the ERP system</description>
    <label>Quote Created Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/updateAccountQuoteERPInfoBatch.cls
/*
Batch class that summarizes in the account record what is the first Quote_ERP, the last Quote_ERP and the number of different contacts related to the Quote_ERP records of the account
*/
global class updateAccountQuoteERPInfoBatch implements Database.Batchable<sObject>, Database.Stateful {
    // instance member to retain state across transactions
    global Integer UCQDrecordsProcessed = 0;
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT ID from Account'
        );
    }
    global void execute(Database.BatchableContext bc, List<Account> scope) {
        Map<ID, Account> lAccountIDMap = new Map<ID, Account>(scope);
        SET<ID> lAccountIDSET = lAccountIDMap.keySet();
        
        // Fetch the Quote ERP Dates
        AggregateResult[] quoteAggRes = [
            SELECT
                AccountID__C AccountID,
                Max(Quote_ERP_Created_Date__C) Last_Quote_Date,
                Min(Quote_ERP_Created_Date__C) First_Quote_Date,
                COUNT_DISTINCT(ContactID__c) Num_of_Quoters
            FROM Quote_ERP__C
            WHERE AccountID__C IN :lAccountIDSET
            GROUP BY AccountID__C
        ];
        for (AggregateResult laggRes : quoteAggRes) {
            ID lID = ID.valueOf(String.valueOf(laggRes.get('AccountID')));
            Date lLastQuoteDate = Date.valueOf(String.valueOf(laggRes.get('Last_Quote_Date')));
            Date lFirstQuoteDate = Date.valueOf(String.valueOf(laggRes.get('First_Quote_Date')));
            Integer lNum_of_Quoters = Integer.valueOf(String.valueOf(laggRes.get('Num_of_Quoters')));
            if (lAccountIDMap.containsKey(lID)) {
                Account lAccount = lAccountIDMap.get(lID);
                lAccount.Date_of_First_Quote__c = lFirstQuoteDate;
                lAccount.Date_of_Last_Quote__c = lLastQuoteDate;
                lAccount.Number_Quoters__c = lNum_of_Quoters;
                lAccountIDMap.put(lAccount.ID, lAccount);
            }
        }
        
        //Update the Accounts
        System.debug('About to start the Account Updates');
        List<Account> accountUpdateList = new List<Account>();
        accountUpdateList = lAccountIDMap.values();
        System.debug('Account to Update List is');
        System.debug(accountUpdateList);
        Integer updateTracker = DatabaseUtilities.saveToDatabaseTracking(
            accountUpdateList,
            'updateAccountQuoteERPInfoBatch.execute',
            'Account Updates in Execution updateAccountQuoteERPInfoBatch'
        );
        UCQDrecordsProcessed = UCQDrecordsProcessed + accountUpdateList.size();

        System.debug('Account Records Processed ' + UCQDrecordsProcessed);
        System.debug('The update tracker records for this batch are ' + updateTracker);
    }

    global void finish(Database.BatchableContext bc) {
        System.debug(UCQDrecordsProcessed + ' records processed. Shazam!');
    }
}