unpackaged/main/default/objects/Account/fields/Date_of_First_Quote__c.field-meta.xml
<CustomField>
    <fullName>Date_of_First_Quote__c</fullName>
    <label>Date of First Quote</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Email_Domain__c.field-meta.xml
<CustomField>
    <fullName>Email_Domain__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Use this one for Xom Integrations.</inlineHelpText>
    <label>Email Domain</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/Number_Quoters__c.field-meta.xml
<CustomField>
    <fullName>Number_Quoters__c</fullName>
    <label># of Quoters</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/ERP_Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact_First_Name__c</fullName>
    <description>The first name of a Contact assoicated to a quote coming from the ERP.</description>
    <inlineHelpText>First Name as it was in the ERP when it came to SF</inlineHelpText>
    <label>ERP - Contact First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/ERP_Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact_Last_Name__c</fullName>
    <inlineHelpText>Last Name as it was in the ERP when it came to SF</inlineHelpText>
    <label>ERP - Contact Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/Quote_ERP__c.object-meta.xml
<CustomObject>
    <description>A quote that is sent over from ERP</description>
    <label>Quote ERP</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote_ERP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes ERP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Quote_ERP__c/fields/Account_Domain__c.field-meta.xml
<CustomField>
    <fullName>Account_Domain__c</fullName>
    <description>The domain associated with an account. For generics this will still be a generic domain.</description>
    <label>Account Domain</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/ERP_Contact__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact__c</fullName>
    <description>The ERP Contact identifier that is used to lookup the unique contact on a quote in the ERP.</description>
    <label>ERP Contact ID</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/ERP_Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact_First_Name__c</fullName>
    <label>ERP Contact First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/ERP_Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact_Last_Name__c</fullName>
    <label>ERP Contact Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/ERP_PartPK__c.field-meta.xml
<CustomField>
    <fullName>ERP_PartPK__c</fullName>
    <description>A unique concatenation of Parts that will link to Opportunities and Leads</description>
    <label>ERP PartPK</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/ERP_User_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>ERP_User_Company_Name__c</fullName>
    <description>The Company Name that the user filled out in the ERP</description>
    <inlineHelpText>The Company Name that the user filled out in the Checkout Section.</inlineHelpText>
    <label>ERP Company Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Quote_Email__c.field-meta.xml
<CustomField>
    <fullName>Quote_Email__c</fullName>
    <description>The email that is associated with the quote.</description>
    <label>Quote Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Quote_ERP_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Quote_ERP_Created_Date__c</fullName>
    <description>The date the quote was created in the ERP system</description>
    <label>Quote Created Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Quote_ERP_Created_Time__c.field-meta.xml
<CustomField>
    <fullName>Quote_ERP_Created_Time__c</fullName>
    <label>Quote ERP Created Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Quote_Price__c.field-meta.xml
<CustomField>
    <fullName>Quote_Price__c</fullName>
    <description>The estimated price of the quote</description>
    <label>Quote Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Xometry_ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>Xometry_ERP_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Unique Qoute ID created in Xometry ERP</description>
    <externalId>true</externalId>
    <label>Quote ID</label>
    <length>13</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/updateAccountQuoteERPInfoBatch_Test.cls
@isTest
private class updateAccountQuoteERPInfoBatch_Test {
    
    @isTest
    static void scheduleJob() {
        //Call job
        Test.startTest();
        String CRON_EXP = '0 0 0 1 1 ? *';
        String jobID = System.schedule('updateAccountQuoteERPInfoBatchJob', CRON_EXP, new updateAccountQuoteERPInfoBatchJob());
        Test.stopTest();
    }

    @isTest
    static void excecuteBatch() {
        List<Account> testAccountList = TestDataFactory.createTestAccountNonGenerics(2, 'AM', 1);
        Account testAccount = testAccountList[0];
        ID testAccountID = testAccount.ID;
        Contact myretContact = [
            SELECT ID, FirstName, LastName, Email
            FROM Contact
            WHERE AccountID = :testAccountID
            ORDER BY Name
        ];
        
        // Create a Quote
        Quote_ERP__C quote2 = new Quote_ERP__C();
        quote2.Account_Domain__c = testAccount.Email_Domain__c;
        quote2.Quote_ERP_Created_Date__C = Date.newInstance(2019, 10, 23);
        quote2.Quote_ERP_Created_Time__c = DateTime.newInstance(2019, 10, 23, 11, 15, 0);
        quote2.ERP_User_Company_Name__c = testAccount.name;
        quote2.ERP_Contact__C = 'AAAAA';
        quote2.ERP_Contact_First_Name__c = myretContact.FirstName;
        quote2.ERP_Contact_Last_Name__C = myretContact.LastName;
        quote2.Quote_Email__c = myretContact.Email;
        quote2.Xometry_ERP_ID__c = 'AAAAA-00005';
        quote2.ERP_PartPK__c = '44444';
        quote2.process_isSLS__c = true;
        quote2.Quote_Price__c = 15000;
        insert quote2;

        //Call job
        Test.startTest();
        updateAccountQuoteERPInfoBatch uAQI = new updateAccountQuoteERPInfoBatch();
        ID batchID = Database.executeBatch(uAQI, 200);
        Test.stopTest();

        Account myAccount = [
            SELECT
                ID,
                Name,
                Number_Quoters__c,
                Date_of_First_Quote__c,
                Date_of_Last_Quote__c
            FROM Account
            WHERE ID = :testAccountID
        ];
        
        System.assertEquals(
            date.newInstance(2019, 10, 23),
            myAccount.Date_of_First_Quote__c,
            'Account should have supplies first quote date'
        );
    }
}