unpackaged/main/default/objects/Account/fields/Email_Domain__c.field-meta.xml
<CustomField>
    <fullName>Email_Domain__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Use this one for Xom Integrations.</inlineHelpText>
    <label>Email Domain</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Contact_Form_Status__c.field-meta.xml
<CustomField>
    <fullName>Contact_Form_Status__c</fullName>
    <description>6/29/2023 - Proof of Concept for new Contact Form submissions. Daniel Turkington is POC for the form.</description>
    <label>Contact Form Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Contact_Form_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Contact_Form_Submission_Links__c.field-meta.xml
<CustomField>
    <fullName>Contact_Form_Submission_Links__c</fullName>
    <description>6/29/2023 - Proof of Concept for new Contact Form submissions. Daniel Turkington is POC for the form.</description>
    <label>Contact Form Submission Links</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Email_Domain__c.field-meta.xml
<CustomField>
    <fullName>Email_Domain__c</fullName>
    <externalId>true</externalId>
    <label>Domain</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Contact_Form_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New/Unresolved</fullName>
    </customValue>
    <customValue>
        <fullName>Completed - Resolved</fullName>
    </customValue>
    <customValue>
        <fullName>Completed - No Response</fullName>
    </customValue>
    <masterLabel>Contact Form Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/XomEndpoint_FormSubmissionTest.cls
@isTest
public with sharing class XomEndpoint_FormSubmissionTest {
    @isTest
    static void submitFormFromEndpointBasic() {
        Test.startTest();
        XomEndpoint_FormSubmission.FormSubmissionResponse lr = XomEndpoint_FormSubmission.submitForm(
            'LastName',
            'Other',
            'test@email.com',
            'Test Company',
            new List<XomEndpoint_FormSubmission.FormDataField>{
                new XomEndpoint_FormSubmission.FormDataField(
                    'Contact_Form_Status__c',
                    'New/Unresolved',
                    'String',
                    'Update'
                ),
                new XomEndpoint_FormSubmission.FormDataField(
                    'Contact_Form_Submission_Links__c',
                    'New link',
                    'String',
                    'Append'
                )
            }
        );
        Test.stopTest();

        List<Lead> lResults = [SELECT Id FROM Lead];
        System.assertEquals(lr.ResourceId, lResults[0].Id, 'The lead found should match the results');
    }

    @isTest
    static void submitFormFromEndpointFail() {
        Test.startTest();
        XomEndpoint_FormSubmission.FormSubmissionResponse lr = XomEndpoint_FormSubmission.submitForm(
            '',
            'Other',
            'test@email.com',
            'Test Company',
            new List<XomEndpoint_FormSubmission.FormDataField>()
        );
        Test.stopTest();

        System.assert(lr.Status != 'Success', 'The response should have an error');
    }

    @isTest
    static void submitFormFromEndpointDup() {
        Lead l = new Lead(
            LastName = 'LastName',
            LeadSource = 'Other',
            Email = 'test@email.com',
            Company = 'Test Company'
        );
        insert l;
        Test.startTest();
        XomEndpoint_FormSubmission.FormSubmissionResponse lr = XomEndpoint_FormSubmission.submitForm(
            'LastName',
            'Other',
            'test@email.com',
            'Test Company',
            new List<XomEndpoint_FormSubmission.FormDataField>()
        );
        Test.stopTest();

        List<Lead> lResults = [SELECT Id FROM Lead];
        System.assert(lr.Status == 'Success', 'The response should be a success');
        System.assertEquals(l.Id, lr.ResourceId, 'The first lead should be returned');
    }

    @isTest
    static void submitFormFromEndpointContact() {
        Account a = TestDataFactory.createTestAccountGenerics(1, 'BDR')[0];
        Contact c = [SELECT Id, LastName, Email FROM Contact][0];
        Test.startTest();
        XomEndpoint_FormSubmission.FormSubmissionResponse lr = XomEndpoint_FormSubmission.submitForm(
            c.LastName,
            'Other',
            c.Email,
            a.Email_Domain__c,
            new List<XomEndpoint_FormSubmission.FormDataField>()
        );
        Test.stopTest();

        List<Contact> cResults = [SELECT Id FROM Contact];
        System.assertEquals(lr.ResourceId, cResults[0].Id, 'The contact returned should match the results');
    }

    @isTest
    static void submitFormFromEndpointUpdate() {
        XomEndpoint_FormSubmission.submitForm(
            'LastName',
            'Other',
            'test@email.com',
            'Test Company',
            new List<XomEndpoint_FormSubmission.FormDataField>{
                new XomEndpoint_FormSubmission.FormDataField(
                    'Contact_Form_Status__c',
                    'New/Unresolved',
                    'String',
                    'Update'
                ),
                new XomEndpoint_FormSubmission.FormDataField(
                    'Contact_Form_Submission_Links__c',
                    'Link 1',
                    'String',
                    'Append'
                )
            }
        );

        Test.startTest();
        XomEndpoint_FormSubmission.FormSubmissionResponse lr = XomEndpoint_FormSubmission.submitForm(
            'LastName',
            'Other',
            'test@email.com',
            'Test Company',
            new List<XomEndpoint_FormSubmission.FormDataField>{
                new XomEndpoint_FormSubmission.FormDataField(
                    'Contact_Form_Status__c',
                    'New/Unresolved',
                    'String',
                    'Update'
                ),
                new XomEndpoint_FormSubmission.FormDataField(
                    'Contact_Form_Submission_Links__c',
                    'Link 2',
                    'String',
                    'Append'
                )
            }
        );
        Test.stopTest();

        List<Lead> lResults = [SELECT Id, Contact_Form_Submission_Links__c FROM Lead];
        System.assertEquals(lr.ResourceId, lResults[0].Id, 'The lead found should match the results');
        System.assertEquals(
            'Link 2<br/>Link 1'.stripHtmlTags(),
            lResults[0].Contact_Form_Submission_Links__c.stripHtmlTags(),
            'Field should have both values'
        );
    }
}