unpackaged/main/default/objects/Account/fields/Email_Domain__c.field-meta.xml
<CustomField>
    <fullName>Email_Domain__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Use this one for Xom Integrations.</inlineHelpText>
    <label>Email Domain</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/ERP_Billing_Address__c.field-meta.xml
<CustomField>
    <fullName>ERP_Billing_Address__c</fullName>
    <label>ERP Billing Address</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ERP_Billing_City__c.field-meta.xml
<CustomField>
    <fullName>ERP_Billing_City__c</fullName>
    <label>ERP Billing City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ERP_Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>ERP_Billing_Country__c</fullName>
    <label>ERP Billing Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/ERP_Billing_State_or_Province__c.field-meta.xml
<CustomField>
    <fullName>ERP_Billing_State_or_Province__c</fullName>
    <label>ERP Billing State or Province</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State_or_Province</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/ERP_Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact_First_Name__c</fullName>
    <description>The first name of a Contact assoicated to a quote coming from the ERP.</description>
    <inlineHelpText>First Name as it was in the ERP when it came to SF</inlineHelpText>
    <label>ERP - Contact First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/ERP_Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact_Last_Name__c</fullName>
    <inlineHelpText>Last Name as it was in the ERP when it came to SF</inlineHelpText>
    <label>ERP - Contact Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/ERP_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact_Phone__c</fullName>
    <description>This field contains the ERP User's Phone Field.</description>
    <label>ERP Contact Phone</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <label>Line of Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Line_of_Business</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Quick Reference to the Primary Contact on an Opportunity</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities(PC)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/Order_Erp__c.object-meta.xml
<CustomObject>
    <description>This object cotains the orders from Xometry ERP. An order is created in Salesforce when the Order date is populated. 

Technical Note: Quote and Orders are the same object in the source system but seperated in Salesforce as Orders represent the end of the opportunity process.</description>
    <label>Order ERP</label>
    <nameField>
        <displayFormat>Order-{000000}</displayFormat>
        <label>Order Erp Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders ERP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order_Erp__c/fields/AccountID__c.field-meta.xml
<CustomField>
    <fullName>AccountID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Account that the order is placed for.</description>
    <label>AccountID</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Orders_Erp</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/ERP_Billing_City__c.field-meta.xml
<CustomField>
    <fullName>ERP_Billing_City__c</fullName>
    <label>ERP Billing City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/ERP_Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>ERP_Billing_Country__c</fullName>
    <label>ERP Billing Country</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/ERP_Billing_State_or_Province__c.field-meta.xml
<CustomField>
    <fullName>ERP_Billing_State_or_Province__c</fullName>
    <label>ERP Billing State or Province</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/ERP_Contact__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact__c</fullName>
    <inlineHelpText>Search for this contact  in the ERP to see more information about the contact.</inlineHelpText>
    <label>ERP Contact</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/ERP_Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact_First_Name__c</fullName>
    <description>The first name of the contact who placed the order.</description>
    <label>ERP Contact First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/ERP_Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact_Last_Name__c</fullName>
    <description>Last Name of the Customer who placed the Order.</description>
    <label>ERP Contact Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/ERP_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact_Phone__c</fullName>
    <label>ERP Contact Phone</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/ERP_PartPk__c.field-meta.xml
<CustomField>
    <fullName>ERP_PartPk__c</fullName>
    <description>A concatenation of all parts that were used to create an order.</description>
    <label>ERP PartPk</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <label>Line of Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Line_of_Business</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Orders ERP</relationshipLabel>
    <relationshipName>Orders_ERP</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/Xometry_ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>Xometry_ERP_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>This value is the unique order.id created in erp. The quote ID and Order ID are the same.</description>
    <externalId>true</externalId>
    <inlineHelpText>Value to use to look up an order in the ERP.</inlineHelpText>
    <label>Order ID</label>
    <length>12</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Container for Opportunities that are part of the same project</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <label>Line of Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Line_of_Business</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <inlineHelpText>A short description of this Project</inlineHelpText>
    <label>Project</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/Quote_ERP__c.object-meta.xml
<CustomObject>
    <description>A quote that is sent over from ERP</description>
    <label>Quote ERP</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote_ERP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes ERP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Quote_ERP__c/fields/AccountID__c.field-meta.xml
<CustomField>
    <fullName>AccountID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Account that the quote belongs to</description>
    <label>AccountID</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Quotes_ERP</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/ERP_Billing_Address__c.field-meta.xml
<CustomField>
    <fullName>ERP_Billing_Address__c</fullName>
    <label>ERP Billing Address</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/ERP_Contact__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact__c</fullName>
    <description>The ERP Contact identifier that is used to lookup the unique contact on a quote in the ERP.</description>
    <label>ERP Contact ID</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/ERP_Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact_First_Name__c</fullName>
    <label>ERP Contact First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/ERP_Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact_Last_Name__c</fullName>
    <label>ERP Contact Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/ERP_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact_Phone__c</fullName>
    <label>ERP Contact Phone</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/ERP_PartPK__c.field-meta.xml
<CustomField>
    <fullName>ERP_PartPK__c</fullName>
    <description>A unique concatenation of Parts that will link to Opportunities and Leads</description>
    <label>ERP PartPK</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <label>Line of Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Line_of_Business</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Quotes ERP</relationshipLabel>
    <relationshipName>Quotes_ERP</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Quote_ERP_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Quote_ERP_Created_Date__c</fullName>
    <description>The date the quote was created in the ERP system</description>
    <label>Quote Created Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Quote_Price__c.field-meta.xml
<CustomField>
    <fullName>Quote_Price__c</fullName>
    <description>The estimated price of the quote</description>
    <label>Quote Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Xometry_ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>Xometry_ERP_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Unique Qoute ID created in Xometry ERP</description>
    <externalId>true</externalId>
    <label>Quote ID</label>
    <length>13</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Canada</fullName>
    </customValue>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Hong Kong</fullName>
    </customValue>
    <customValue>
        <fullName>Mexico</fullName>
    </customValue>
    <customValue>
        <fullName>New Zealand</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom</fullName>
    </customValue>
    <customValue>
        <fullName>United States</fullName>
        <default>true</default>
        <label>United States</label>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>United Arab Emirates</fullName>
    </customValue>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Burkina Faso</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgaria</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Burundi</fullName>
    </customValue>
    <description>List of Countries</description>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Line_of_Business.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Instant Quote</fullName>
    </customValue>
    <customValue>
        <fullName>Marketplace</fullName>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <masterLabel>Line of Business</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/State_or_Province.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Australian Capital Territory</fullName>
    </customValue>
    <customValue>
        <fullName>New South Wales</fullName>
    </customValue>
    <customValue>
        <fullName>Northern Territory</fullName>
    </customValue>
    <customValue>
        <fullName>Queensland</fullName>
    </customValue>
    <customValue>
        <fullName>South Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Tasmania</fullName>
    </customValue>
    <customValue>
        <fullName>Victoria</fullName>
    </customValue>
    <customValue>
        <fullName>Western Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Acre</fullName>
    </customValue>
    <customValue>
        <fullName>Alagoas</fullName>
    </customValue>
    <customValue>
        <fullName>Amazonas</fullName>
    </customValue>
    <customValue>
        <fullName>Amapá</fullName>
    </customValue>
    <customValue>
        <fullName>Bahia</fullName>
    </customValue>
    <customValue>
        <fullName>Ceará</fullName>
    </customValue>
    <customValue>
        <fullName>Distrito Federal</fullName>
    </customValue>
    <customValue>
        <fullName>Espírito Santo</fullName>
    </customValue>
    <customValue>
        <fullName>Goiás</fullName>
    </customValue>
    <customValue>
        <fullName>Maranhão</fullName>
    </customValue>
    <customValue>
        <fullName>Minas Gerais</fullName>
    </customValue>
    <customValue>
        <fullName>Mato Grosso do Sul</fullName>
    </customValue>
    <customValue>
        <fullName>Mato Grosso</fullName>
    </customValue>
    <customValue>
        <fullName>Pará</fullName>
    </customValue>
    <customValue>
        <fullName>Paraíba</fullName>
    </customValue>
    <customValue>
        <fullName>Pernambuco</fullName>
    </customValue>
    <customValue>
        <fullName>Piauí</fullName>
    </customValue>
    <customValue>
        <fullName>Paraná</fullName>
    </customValue>
    <customValue>
        <fullName>Rio de Janeiro</fullName>
    </customValue>
    <customValue>
        <fullName>Rio Grande do Norte</fullName>
    </customValue>
    <customValue>
        <fullName>Rondônia</fullName>
    </customValue>
    <customValue>
        <fullName>Roraima</fullName>
    </customValue>
    <customValue>
        <fullName>California</fullName>
    </customValue>
    <description>US States and Canadian Provinces</description>
    <masterLabel>State or Province</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/westCoastContactFlipTest.cls
@isTest
public class westCoastContactFlipTest {
    static final String WEST_COAST_BDR = [
        SELECT UserOrGroupId
        FROM GroupMember
        WHERE GroupID = :AppConstants.WEST_COAST_BDR_GROUP
        LIMIT 1
    ]
    .UserOrGroupId;

    @isTest
    static void westCoastContactFlipTest_assignSingleContactToBDR() {
        //Create Account with Single BDR Contact
        List<Account> account = TestDataFactory.createTestAccountNonGenerics(2, 'BDR', 1);

        Set<Id> accountIdSet = new Set<Id>();
        accountIdSet.add(account[0].ID);

        Test.startTest();
        System.enqueueJob(new westCoastContactFlip(accountIdSet, WEST_COAST_BDR));
        Test.stopTest();

        List<Contact> contacts = [SELECT Id, OwnerId FROM Contact WHERE AccountId = :account[0].Id];

        System.assertEquals(
            WEST_COAST_BDR,
            String.valueOf(contacts[0].OwnerId),
            'Did not set the contact to West Coast BDR'
        );
    }

    @isTest
    static void westCoastContactFlipTest_keepSingleContactAsAM() {
        // Create Account with Single AM Contact
        List<Account> account = TestDataFactory.createTestAccountNonGenerics(2, 'AM', 1, 'SAM');

        Set<Id> accountIdSet = new Set<Id>();
        accountIdSet.add(account[0].ID);

        Test.startTest();
        System.enqueueJob(new westCoastContactFlip(accountIdSet, WEST_COAST_BDR));
        Test.stopTest();

        List<Contact> contacts = [SELECT Id, OwnerId FROM Contact WHERE AccountId = :account[0].Id];

        System.assertNotEquals(
            WEST_COAST_BDR,
            String.valueOf(contacts[0].OwnerId),
            'Did not set the contact to West Coast BDR'
        );
    }

    @isTest
    static void westCoastContactFlipTest_assignThreeContactsToBDR() {
        // Create Account with Three BDR contacts
        List<Account> account = TestDataFactory.createTestAccountNonGenerics(2, 'BDR', 3);

        Set<Id> accountIdSet = new Set<Id>();
        accountIdSet.add(account[0].ID);

        Test.startTest();
        System.enqueueJob(new westCoastContactFlip(accountIdSet, WEST_COAST_BDR));
        Test.stopTest();

        List<Contact> contacts = [SELECT Id, OwnerId FROM Contact WHERE AccountId = :account[0].Id];

        for (Contact c : contacts) {
            System.assertEquals(WEST_COAST_BDR, String.valueOf(c.OwnerId), 'Did not set the contact to West Coast BDR');
        }
    }

    @isTest
    static void westCoastContactFlipTest_assignOpenOpportunity() {
        Opportunity newOpp = TestDataFactory.createOppWithAccContact(false, 'BDR');

        Contact newContact = [SELECT Id, OwnerId, AccountId FROM Contact LIMIT 1];
        Set<Id> accountIdSet = new Set<Id>();
        accountIdSet.add(newContact.AccountId);

        newOpp.OwnerId = newContact.OwnerId;
        newOpp.Amount = 400;
        newOpp.CloseDate = Date.today() + 5;
        newOpp.Line_of_Business__c = null;

        Test.startTest();
        insert newOpp;

        System.enqueueJob(new westCoastContactFlip(accountIdSet, WEST_COAST_BDR));
        Test.stopTest();

        List<Opportunity> opportunities = [SELECT Id, OwnerId FROM Opportunity WHERE AccountID = :newContact.AccountId];

        System.assertEquals(opportunities[0].OwnerId, WEST_COAST_BDR, 'Not reassigned to west coast BDR');
    }
    @isTest
    static void westCoastContactFlipTest_assignQuoteProject() {
        List<Account> account = TestDataFactory.createTestAccountNonGenerics(2, 'BDR', 1);

        Set<Id> accountIdSet = new Set<Id>();
        accountIdSet.add(account[0].ID);

        Contact newContact = [
            SELECT ID, OwnerId, Account.Email_Domain__c, Email
            FROM Contact
            WHERE AccountId = :account[0].ID
        ];

        Quote_ERP__c myQuote = TestDataFactory.createQuote(
            false,
            newContact.Account.Email_Domain__c,
            'John',
            'Doe',
            newContact.Email
        );
        myQuote.ERP_PartPK__c = 'A1234-A5678';
        myQuote.Quote_Price__c = 50.15;
        myQuote.Xometry_ERP_ID__C = 'AAAAA-00001';
        myQuote.Quote_ERP_Created_Date__c = Date.newInstance(2021, 6, 14);
        myQuote.ERP_Contact_Phone__C = '+1 (419) 532-3121';
        myQuote.ERP_Billing_Address__c = '2 Unit E Northway';
        myQuote.ERP_Billing_City__c = 'San Diego';
        myQuote.ERP_Billing_Country__c = 'United States';
        myQuote.ERP_Billing_State_or_Province__c = 'California';

        insert myQuote;

        Test.startTest();
        System.enqueueJob(new westCoastContactFlip(accountIdSet, WEST_COAST_BDR));
        Test.stopTest();

        List<Project__c> projects = [SELECT Id, OwnerId FROM Project__c WHERE AccountId__c = :account[0].Id];

        System.assertEquals(projects[0].OwnerId, WEST_COAST_BDR, 'Project owner should be in West Cost BDR group');
    }

    @isTest
    static void westCoastContactFlipTest_assignOrderProject() {
        List<Account> account = TestDataFactory.createTestAccountNonGenerics(2, 'BDR', 1);

        Set<Id> accountIdSet = new Set<Id>();
        accountIdSet.add(account[0].ID);

        Contact newContact = [
            SELECT ID, OwnerId, Account.Email_Domain__c, Account.Name, Email, FirstName, LastName
            FROM Contact
            WHERE AccountId = :account[0].ID
        ];

        Order_ERP__c newOrder = TestDataFactory.createOrderERPFromAccContact(
            false,
            'Q12-3333-4444',
            'AAAAA-00001',
            'A1234-A5678',
            account[0],
            newContact,
            date.newInstance(2019, 8, 15),
            dateTime.newInstance(2019, 8, 15, 10, 0, 30)
        );
        newOrder.ERP_Contact__c = 'AAAAA';
        newOrder.ERP_Contact_Last_Name__c = 'Doe';
        newOrder.ERP_Contact_First_Name__c = 'John';
        newOrder.ERP_Contact_Phone__C = '+1 (419) 532-3121';
        newOrder.ERP_Billing_Address__c = '2 Unit E Northway';
        newOrder.ERP_Billing_City__c = 'San Diego';
        newOrder.ERP_Billing_Country__c = 'United States';
        newOrder.ERP_Billing_State_or_Province__c = 'California';

        insert newOrder;

        Test.startTest();
        System.enqueueJob(new westCoastContactFlip(accountIdSet, WEST_COAST_BDR));
        Test.stopTest();

        List<Project__c> projects = [SELECT Id, OwnerId FROM Project__c WHERE AccountId__c = :account[0].Id];

        System.assertEquals(projects[0].OwnerId, WEST_COAST_BDR, 'Project owner should be in West Cost BDR group');
    }

    @isTest
    static void westCoastContactFlipTest_skipClosedOpportunities() {
        List<Account> account = TestDataFactory.createTestAccountNonGenerics(2, 'BDR', 1);

        Set<Id> accountIdSet = new Set<Id>();
        accountIdSet.add(account[0].ID);

        Contact newContact = [SELECT ID, OwnerId FROM Contact WHERE AccountId = :account[0].ID];
        Opportunity newOpp = new Opportunity();
        newOpp.PRIMARY_CONTACT__C = newContact.Id;
        newOpp.name = 'TestOpp';
        newOpp.stagename = 'Closed Won';
        newOpp.AccountID = account[0].ID;
        newOpp.Amount = 400;
        newOpp.CloseDate = Date.today() + 5;
        newOpp.OwnerId = newContact.OwnerId;

        Test.startTest();
        insert newOpp;

        System.enqueueJob(new westCoastContactFlip(accountIdSet, WEST_COAST_BDR));
        Test.stopTest();

        List<Opportunity> opportunities = [SELECT Id, OwnerId FROM Opportunity WHERE AccountID = :account[0].Id];

        System.assertNotEquals(opportunities[0].OwnerId, WEST_COAST_BDR, 'Not reassigned to west coast BDR');
    }
}