unpackaged/main/default/objects/Account/fields/Email_Domain__c.field-meta.xml
<CustomField>
    <fullName>Email_Domain__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Use this one for Xom Integrations.</inlineHelpText>
    <label>Email Domain</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/Generic_Account__c.field-meta.xml
<CustomField>
    <fullName>Generic_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Generic Account</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Physical_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Physical_Zip_Code__c</fullName>
    <label>Physical Zip Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/P21_Account_Details__c/P21_Account_Details__c.object-meta.xml
<CustomObject>
    <description>Contains information about P21 Customer mapped to an extension of an account</description>
    <label>P21 Account Details</label>
    <nameField>
        <label>P21 Account Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>P21 Account Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/P21_Account_Details__c/fields/AccountID__c.field-meta.xml
<CustomField>
    <fullName>AccountID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Account</description>
    <label>AccountID</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>P21 Account Details</relationshipLabel>
    <relationshipName>P21_Account_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/P21_Account_Details__c/fields/PartnerID__c.field-meta.xml
<CustomField>
    <fullName>PartnerID__c</fullName>
    <label>PartnerID</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Supplier__c/Supplier__c.object-meta.xml
<CustomObject>
    <label>Supplier</label>
    <nameField>
        <label>﻿Partner ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Supplier__c/fields/AccountID__c.field-meta.xml
<CustomField>
    <fullName>AccountID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AccountID</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Suppliers</relationshipLabel>
    <relationshipName>Suppliers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Supplier__c/fields/P21_Account_Details__c.field-meta.xml
<CustomField>
    <fullName>P21_Account_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>P21 Account Details</label>
    <referenceTo>P21_Account_Details__c</referenceTo>
    <relationshipLabel>Suppliers</relationshipLabel>
    <relationshipName>Suppliers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Supplier__c/fields/PartnerID__c.field-meta.xml
<CustomField>
    <fullName>PartnerID__c</fullName>
    <externalId>true</externalId>
    <label>Partner ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Supplier__c/fields/Sup_Owner_Stamp__c.field-meta.xml
<CustomField>
    <fullName>Sup_Owner_Stamp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sup Owner Stamp</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Suppliers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Supplier__c/fields/ZipCode__c.field-meta.xml
<CustomField>
    <fullName>ZipCode__c</fullName>
    <label>Zip Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/SupplierUtility.cls
public with sharing class SupplierUtility {
    /**
     * @description creates a map of Suppliers from an id set
     * @param partnerIdSet set of Partner Id's
     * @return existingSupplierMap map of orders with primary email as key
     */
    public static Map<String, Supplier__c> fetchSuppliers(Set<String> partnerIdSet) {
        Map<String, Supplier__c> existingSupplierMap = new Map<String, Supplier__c>();
        if (!partnerIdSet.isEmpty()) {
            for (Supplier__c s : [
                SELECT
                    ID,
                    AccountId__c,
                    PartnerID__c,
                    AccountId__r.OwnerId,
                    AccountId__r.Email_Domain__C,
                    AccountId__r.Generic_Account__C,
                    AccountId__r.Physical_Zip_Code__c,
                    P21_Account_Details__c,
                    P21_Account_Details__r.OwnerID,
                    ZipCode__c,
                    Sup_Owner_Stamp__c
                FROM Supplier__c
                WHERE PartnerID__c IN :partnerIdSet AND AccountId__c != NULL
            ]) {
                existingSupplierMap.put(s.PartnerId__c, s);
            }
        }
        return existingSupplierMap;
    }

    /**
     * @description creates a map of Suppliers from an id set
     * @param partnerIdSet set of Salesforce IDs
     * @return existingSupplierMap map of orders with SF ID as the key
     */
    public static Map<ID, Supplier__c> fetchSuppliersbySFID(Set<ID> supIdSet) {
        Map<ID, Supplier__c> existingSupplierMap = new Map<ID, Supplier__c>();
        if (!supIdSet.isEmpty()) {
            for (Supplier__c s : [
                SELECT
                    ID,
                    AccountId__c,
                    PartnerID__c,
                    AccountId__r.OwnerId,
                    AccountId__r.Email_Domain__C,
                    AccountId__r.Generic_Account__C,
                    AccountId__r.Physical_Zip_Code__c,
                    P21_Account_Details__c,
                    P21_Account_Details__r.OwnerID,
                    ZipCode__c,
                    Sup_Owner_Stamp__c
                FROM Supplier__c
                WHERE ID IN :supIdSet AND AccountId__c != NULL
            ]) {
                existingSupplierMap.put(s.ID, s);
            }
        }
        return existingSupplierMap;
    }
}