unpackaged/main/default/objects/Account/fields/Email_Domain__c.field-meta.xml
<CustomField>
    <fullName>Email_Domain__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Use this one for Xom Integrations.</inlineHelpText>
    <label>Email Domain</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/Generic_Account__c.field-meta.xml
<CustomField>
    <fullName>Generic_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Generic Account</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account_Team__c/Account_Team__c.object-meta.xml
<CustomObject>
    <label>Account Team</label>
    <nameField>
        <displayFormat>AT-{000000000}</displayFormat>
        <label>Account Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Account_Team__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Team Members</relationshipLabel>
    <relationshipName>Account_Team_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Account_Team__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Account_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account_Team__c/fields/Team_Role__c.field-meta.xml
<CustomField>
    <fullName>Team_Role__c</fullName>
    <label>Team Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Sales Engineer</fullName>
            </value>
            <value>
                <fullName>Technical Sales Engineer</fullName>
            </value>
            <value>
                <fullName>Enterprise Growth Rep</fullName>
            </value>
            <value>
                <fullName>Spec Team</fullName>
            </value>
            <value>
                <fullName>Sales Development Representative</fullName>
            </value>
            <value>
                <fullName>Injection Molding Specialist</fullName>
            </value>
            <value>
                <fullName>Enterprise Account Manager</fullName>
            </value>
            <value>
                <fullName>Account Manager</fullName>
                <isActive>false</isActive>
                <label>Account Manager</label>
            </value>
            <value>
                <fullName>Customer Success Account Manager</fullName>
                <isActive>false</isActive>
                <label>Customer Success Account Manager</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <formula>IF ( AND (  Account_Owner_Type__c = 'BDR', Account.BDR_Retention_Countdown_Calculation__c &lt; 91, Account.BDR_Retention_Countdown_Calculation__c &gt; 0),'NEW', IF ( AND (  Account_Owner_Type__c = 'BDR', Account.BDR_Retention_Countdown_Calculation__c &lt;= 0), 'RETENTION', IF ( AND (  Account_Owner_Type__c = 'AM',  AM_Retention_Countdown_Calculation__c  &lt; 366,  AM_Retention_Countdown_Calculation__c  &gt; 0),'NEW', IF ( AND (  Account_Owner_Type__c = 'AM',  AM_Retention_Countdown_Calculation__c  &lt;= 0), 'RETENTION',''))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/ERP_Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact_First_Name__c</fullName>
    <description>The first name of a Contact assoicated to a quote coming from the ERP.</description>
    <inlineHelpText>First Name as it was in the ERP when it came to SF</inlineHelpText>
    <label>ERP - Contact First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/ERP_Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact_Last_Name__c</fullName>
    <inlineHelpText>Last Name as it was in the ERP when it came to SF</inlineHelpText>
    <label>ERP - Contact Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Primary_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>The Primary Email of the Contact.</description>
    <externalId>true</externalId>
    <inlineHelpText>Adjust the email above to change the value. The Primary Email Address is a unique email in the system.</inlineHelpText>
    <label>Primary Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Retention_Exemption__c.field-meta.xml
<CustomField>
    <fullName>Retention_Exemption__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Retention Exemption</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Generic_Account__c.field-meta.xml
<CustomField>
    <fullName>Generic_Account__c</fullName>
    <formula>IF(Account.Generic_Account__c = TRUE,"True","False")</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Generic Account</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <label>Line of Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Line_of_Business</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/Order_Erp__c.object-meta.xml
<CustomObject>
    <description>This object cotains the orders from Xometry ERP. An order is created in Salesforce when the Order date is populated. 

Technical Note: Quote and Orders are the same object in the source system but seperated in Salesforce as Orders represent the end of the opportunity process.</description>
    <label>Order ERP</label>
    <nameField>
        <displayFormat>Order-{000000}</displayFormat>
        <label>Order Erp Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders ERP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order_Erp__c/fields/Account_Domain__c.field-meta.xml
<CustomField>
    <fullName>Account_Domain__c</fullName>
    <description>The domain associated with the email address of who placed the order.</description>
    <label>Account Domain</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/ERP_Contact__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact__c</fullName>
    <inlineHelpText>Search for this contact  in the ERP to see more information about the contact.</inlineHelpText>
    <label>ERP Contact</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/ERP_Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact_First_Name__c</fullName>
    <description>The first name of the contact who placed the order.</description>
    <label>ERP Contact First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/ERP_Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact_Last_Name__c</fullName>
    <description>Last Name of the Customer who placed the Order.</description>
    <label>ERP Contact Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/ERP_PartPk__c.field-meta.xml
<CustomField>
    <fullName>ERP_PartPk__c</fullName>
    <description>A concatenation of all parts that were used to create an order.</description>
    <label>ERP PartPk</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/Is_Generic__c.field-meta.xml
<CustomField>
    <fullName>Is_Generic__c</fullName>
    <defaultValue>false</defaultValue>
    <description>A boolean to flag if the order is associated with a generic email or not.</description>
    <label>Is Generic</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <label>Line of Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Line_of_Business</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/Order_Email__c.field-meta.xml
<CustomField>
    <fullName>Order_Email__c</fullName>
    <description>The email address that was used to place the order.</description>
    <label>Order Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/Order_ERP_CreatedDate__c.field-meta.xml
<CustomField>
    <fullName>Order_ERP_CreatedDate__c</fullName>
    <description>Date that an order was placed.</description>
    <label>Order Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/Order_ERP_Time__c.field-meta.xml
<CustomField>
    <fullName>Order_ERP_Time__c</fullName>
    <label>Order Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/Order_Subtotal__c.field-meta.xml
<CustomField>
    <fullName>Order_Subtotal__c</fullName>
    <label>Order Subtotal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/Order_Total__c.field-meta.xml
<CustomField>
    <fullName>Order_Total__c</fullName>
    <description>The total on the order</description>
    <label>Order Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/process_isSLS__c.field-meta.xml
<CustomField>
    <fullName>process_isSLS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>process_isSLS</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Orders ERP</relationshipLabel>
    <relationshipName>Orders_ERP</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/Shipping__c.field-meta.xml
<CustomField>
    <fullName>Shipping__c</fullName>
    <label>Shipping</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Container for Opportunities that are part of the same project</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project__c/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <label>Line of Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Line_of_Business</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <inlineHelpText>A short description of this Project</inlineHelpText>
    <label>Project</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Line_of_Business.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Instant Quote</fullName>
    </customValue>
    <customValue>
        <fullName>Marketplace</fullName>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <masterLabel>Line of Business</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/csamContactFlipTest.cls
@isTest
public class csamContactFlipTest {
    //Customer_Type__c on the Contact is a Formula to get to RETENTION so setup data with Orders over 1 years ago.

    @isTest
    static void csamContactFlipTest1() {
        //Create an Account that is AM
        List<Account> testAccountList = TestDataFactory.createTestAccountNonGenerics(1, 'AM', 2);
        Account testAccount = testAccountList[0];
        List<Order_ERP__C> testOrderList = new List<Order_ERP__C>();

        Order_ERP__C testOrder1 = TestDataFactory.createOrderERP(
            false,
            'Q11-1111-1111',
            'AAA22-00022',
            testAccount.Email_Domain__C,
            null,
            'mrsmith01@' + testAccount.Email_Domain__C,
            false,
            true
        );
        testOrder1.Is_Generic__c = testAccount.Generic_Account__c;
        testOrder1.Order_ERP_CreatedDate__c = date.newInstance(2019, 6, 30);
        testOrder1.Order_ERP_Time__c = dateTime.newInstanceGMT(2019, 6, 30, 18, 0, 0);
        testOrder1.Line_of_Business__c = 'Instant Quote';
        testOrder1.Order_Subtotal__c = 5000;
        testOrder1.Order_Total__c = 5000;
        testOrder1.Shipping__c = null;
        testOrder1.ERP_PartPk__c = '1111A';
        testOrder1.ERP_Contact__c = 'AAA22';
        testOrder1.ERP_Contact_First_Name__c = 'Michael';
        testOrder1.ERP_Contact_Last_Name__c = 'Smith';
        testOrderList.add(testOrder1);

        Order_ERP__C testOrder2 = TestDataFactory.createOrderERP(
            false,
            'Q22-2222-2222',
            'AAA23-00022',
            testAccount.Email_Domain__C,
            null,
            'msbetty01@' + testAccount.Email_Domain__C,
            false,
            true
        );
        testOrder2.Is_Generic__c = testAccount.Generic_Account__c;
        testOrder2.Order_ERP_CreatedDate__c = date.newInstance(2019, 6, 30);
        testOrder2.Order_ERP_Time__c = dateTime.newInstanceGMT(2019, 6, 30, 18, 0, 0);
        testOrder2.Line_of_Business__c = 'Instant Quote';
        testOrder2.Order_Subtotal__c = 5000;
        testOrder2.Order_Total__c = 5000;
        testOrder2.Shipping__c = null;
        testOrder2.ERP_PartPk__c = '1112A';
        testOrder2.ERP_Contact__c = 'AAA23';
        testOrder2.ERP_Contact_First_Name__c = 'Betty';
        testOrder2.ERP_Contact_Last_Name__c = 'Rocket';
        testOrderList.add(testOrder2);
        insert testOrderList;

        List<Contact> testContactList = [
            SELECT ID, AccountID, OwnerID
            FROM Contact
            WHERE AccountID = :testAccount.ID AND Customer_Type__c = 'RETENTION'
        ];
        //Test 1 a Contact with Retention_Exemption__c is True and Retention
        Contact ignoreCAFCon = testContactList[0];
        ignoreCAFCon.Retention_Exemption__c = true;
        update ignoreCAFCon;

        // Test 2 a Contact with  customer Type is Retention
        Contact conRetNoFlag = testContactList[1];
        //Create an Opportunity on Test 2 Contact and confirm that the Opportunity's Owner changes
        Opportunity testOpp = TestDataFactory.createOpportunity(
            true,
            testContactList[1].ID,
            testContactList[1].AccountID,
            testContactList[1].OwnerID,
            date.today() + 30
        );
        Project__c testProject = TestDataFactory.createProject(
            true,
            testContactList[1].ID,
            testContactList[1].AccountID,
            testContactList[1].OwnerID,
            null,
            'New'
        );

        //Test 3 a Contact with Customer Type!= Retention
        Contact custNoRet = TestDataFactory.createContact(false, testAccount);
        custNoRet.firstName = 'Bob';
        custNoRet.lastName = 'Nomad';
        custNoRet.email = 'bobnomad01@' + testAccount.Email_Domain__C;
        insert custNoRet;

        // Now create the second User who will act as the CSAM on the Parent
        User CSAMUser = TestDataFactory.createTestUserSecond()[0];
        Account_Team__c atmCSAM = new Account_Team__c();
        atmCSAM.Account__c = testAccount.ID;
        atmCSAM.Team_Member__c = CSAMUser.ID;
        atmCSAM.Team_Role__c = 'Enterprise Account Manager';
        insert atmCSAM;

        System.debug('Starting the batch job');
        Test.StartTest();
        csamContactFlip myBatchObject = new csamContactFlip();
        Id batchId = Database.executeBatch(myBatchObject);
        Test.StopTest();

        //Test 1 ignoreCAFCon The Account Owner should match this contact Owner
        Contact ignoreCAFConAfterBatch = [SELECT ID, OwnerID FROM Contact WHERE ID = :ignoreCAFCon.ID];
        System.assertEquals(
            ignoreCAFConAfterBatch.OwnerID,
            testAccount.OwnerID,
            'The Accounts Owner and the Contact with flag owner did not match'
        );

        // Test 2 a Contact with  customer Type is Retention
        Contact conRetNoFlagAfterBatch = [SELECT ID, OwnerID FROM Contact WHERE ID = :conRetNoFlag.ID];
        System.assertEquals(
            conRetNoFlagAfterBatch.OwnerID,
            atmCSAM.Team_Member__c,
            'The Contact\'s owner did not match the CSAM owner id'
        );
        System.assertNotEquals(
            conRetNoFlagAfterBatch.OwnerID,
            testAccount.OwnerID,
            'The Contact\'s owner matched the Main Account Owner'
        );

        // Test 2 Confirm that the Opp's Owner is updated
        Opportunity testOppPostBatch = [SELECT ID, OwnerID FROM Opportunity WHERE ID = :testOpp.ID];
        System.assertEquals(
            testOppPostBatch.OwnerID,
            atmCSAM.Team_Member__c,
            'The Opportunity\'s owner did not match the CSAM owner id'
        );

        // Test 2 Confirm that the Project's Owner is updated
        Project__c testProjectPostBatch = [SELECT ID, OwnerID FROM Project__c WHERE ID = :testProject.ID];
        System.assertEquals(
            testProjectPostBatch.OwnerID,
            atmCSAM.Team_Member__c,
            'The Projects\'s owner did not match the CSAM owner id'
        );

        //Test 3 a Contact with Customer Type!= Retention
        Contact custNoRetAfterBatch = [
            SELECT ID, OwnerID
            FROM Contact
            WHERE ID = :custNoRet.ID AND Customer_Type__c != 'RETENTION'
        ];
        System.assertEquals(
            custNoRetAfterBatch.OwnerID,
            testAccount.OwnerID,
            'The Accounts Owner and the Contact that is not Retention did not match'
        );
    }

    @isTest
    static void csamContactOrigTest() {
        //Create an Account that is AM with no Account Team
        //Create an Account that is AM
        List<Account> testAccountList = TestDataFactory.createTestAccountNonGenerics(1, 'AM', 2);
        Account testAccount = testAccountList[0];
        List<Order_ERP__C> testOrderList = new List<Order_ERP__C>();
        String testEmail = 'mrsmith01@' + testAccount.Email_Domain__C;
        testEmail = testEmail.toLowerCase();
        System.debug(testEmail);
        //Create a Contact this is Retention with a different Owner
        Order_ERP__C testOrder1 = TestDataFactory.createOrderERP(
            false,
            'Q12-3333-4444',
            'AAA22-00022',
            testAccount.Email_Domain__C,
            null,
            testEmail,
            false,
            true
        );
        testOrder1.Is_Generic__c = testAccount.Generic_Account__c;
        testOrder1.Order_ERP_CreatedDate__c = date.newInstance(2019, 6, 30);
        testOrder1.Order_ERP_Time__c = dateTime.newInstanceGMT(2019, 6, 30, 18, 0, 0);
        testOrder1.Line_of_Business__c = 'Instant Quote';
        testOrder1.Order_Subtotal__c = 5000;
        testOrder1.Order_Total__c = 5000;
        testOrder1.Shipping__c = null;
        testOrder1.ERP_PartPk__c = '1111A';
        testOrder1.ERP_Contact__c = 'AAA22';
        testOrder1.ERP_Contact_First_Name__c = 'Michael';
        testOrder1.ERP_Contact_Last_Name__c = 'Smith';
        testOrderList.add(testOrder1);

        // Order_ERP__C testOrder1 = TestDataFactory.createOrderERP(false, 'Q22-2222-2222', 'AAA22-00022', testAccount.Email_Domain__C, null, testEmail, false, true);
        // testOrder1.Account_Domain__C = testAccount.Email_Domain__C;
        // testOrder1.Is_Generic__c = testAccount.Generic_Account__c;
        // testOrder1.Order_Email__c = testEmail;
        // testOrder1.Order_ERP_CreatedDate__c = date.newInstance(2019, 6, 30);
        // testOrder1.Order_ERP_Time__c = dateTime.newInstanceGMT(2019, 6, 30, 18, 0, 0);
        // testOrder1.Line_of_Business__c = 'Instant Quote';
        // testOrder1.Order_Subtotal__c = 5000;
        // testOrder1.Order_Total__c = 5000;
        // testOrder1.process_isSLS__c = true;
        // testOrder1.ERP_PartPk__c = '1111A';
        // testOrder1.ERP_Contact__c = 'AAA22';
        // testOrder1.ERP_Contact_First_Name__c = 'Michael';
        // testOrder1.ERP_Contact_Last_Name__c = 'Smith';
        // testOrderList.add(testOrder1);

        insert testOrderList;
        Contact testContact = [SELECT ID, OwnerID FROM Contact WHERE primary_email__c = :testEmail];
        //Confirm that the Account and Contact Owner Match

        System.assertEquals(testContact.OwnerID, testAccount.OwnerID, 'The contact\'s owner did not match');
        //Change the Contact Owner
        //Contact should flip back to Account Owner
        User CSAMUser = TestDataFactory.createTestUserSecond()[0];
        testContact.OwnerID = CSAMUser.ID;
        update testContact;
        System.debug('Starting the batch job');
        test.StartTest();
        csamContactFlip myBatchObject = new csamContactFlip();
        Id batchId = Database.executeBatch(myBatchObject);
        test.StopTest();
        Contact testContactAfterBatch = [SELECT ID, OwnerID FROM Contact WHERE ID = :testContact.ID];
        System.assertEquals(
            testContactAfterBatch.OwnerID,
            testAccount.OwnerID,
            'The Contact was updated to the Accounts Owner'
        );
    }
    @isTest
    static void csamHierarchyTest() {
        //For this Test assign a CSAM at the corporate Parent and flip a contact at the subdivision
        map<String, List<SObject>> mapResult = TestDataFactory.createHierarchyTestCustomATeam(false, false);

        Account accountParent = (Account) mapResult.get('Account')[0];
        Account accountChild = (Account) mapResult.get('Account')[1];
        Order_ERP__C parentOrder = (Order_ERP__C) mapResult.get('Order_ERP__C')[0];
        Order_ERP__C childOrder = (Order_ERP__C) mapResult.get('Order_ERP__C')[1];
        Account_Team__c atmCSAM = (Account_Team__c) mapResult.get('Account_Team__c')[0];
        User CSAMUser = (User) mapResult.get('User')[0];

        // Now create the second User who will act as the CSAM on the Parent
        System.debug('We have finished setting the orders up for tests.');
        System.debug(Limits.getQueries());
        System.debug('Starting the batch Job');
        System.debug('About to start the Tests');

        Contact testContactbeforeBatch;
        test.StartTest();

        insert atmCSAM;
        insert childOrder;
        testContactbeforeBatch = [
            SELECT ID, OwnerID, Account.OwnerID
            FROM Contact
            WHERE AccountID = :accountChild.ID
            LIMIT 1
        ];
        csamContactFlip myBatchObject = new csamContactFlip();
        Id batchId = Database.executeBatch(myBatchObject);
        System.debug('At the end of stop Test');
        System.debug(Limits.getQueries());
        test.StopTest();
        System.debug('Finished the Testing');
        System.debug(Limits.getQueries());
        Contact testContactafterBatch = [
            SELECT ID, OwnerID, Account.OwnerID
            FROM Contact
            WHERE AccountID = :accountChild.ID
        ][0];
        System.debug(testContactafterBatch);
        System.assertNotEquals(
            testContactbeforeBatch.OwnerID,
            testContactafterBatch.OwnerID,
            'The contacts owner did not change'
        );
        System.assertEquals(testContactafterBatch.OwnerID, CSAMUser.ID, 'The Contacts Owner was not the CSAM');
        System.assertNotEquals(
            testContactafterBatch.OwnerID,
            testContactafterBatch.Account.OwnerID,
            'The Contact and Account Owner Ids are the same'
        );
    }
}