unpackaged/main/default/objects/Account/fields/Email_Domain__c.field-meta.xml
<CustomField>
    <fullName>Email_Domain__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Use this one for Xom Integrations.</inlineHelpText>
    <label>Email Domain</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Generated_by_Sales__c.field-meta.xml
<CustomField>
    <fullName>Generated_by_Sales__c</fullName>
    <defaultValue>"FALSE"</defaultValue>
    <label>Generated by Sales</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Primary_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>The Primary Email of the Contact.</description>
    <externalId>true</externalId>
    <inlineHelpText>Adjust the email above to change the value. The Primary Email Address is a unique email in the system.</inlineHelpText>
    <label>Primary Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Email_Domain__c.field-meta.xml
<CustomField>
    <fullName>Email_Domain__c</fullName>
    <externalId>true</externalId>
    <label>Domain</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Generated_by_Sales__c.field-meta.xml
<CustomField>
    <fullName>Generated_by_Sales__c</fullName>
    <formula>IF(
 HS_Generated_by_Sales__c = "True" ||
 (
  ISPICKVAL(LeadSource, "Outreach") ||
  ISPICKVAL(LeadSource, "ZoomInfo") ||
  ISPICKVAL(LeadSource, "Webinar") ||
  ISPICKVAL(LeadSource, "Sales Generated")
 ) ||
 (
  CreatedBy.UserRole.Name = "TSE" ||
  CreatedBy.UserRole.Name = "AE-I" ||
  CreatedBy.UserRole.Name = "AE-II" ||
  CreatedBy.UserRole.Name = "AE-III" ||
  CreatedBy.UserRole.Name = "BDR" ||
  CreatedBy.UserRole.Name = "CSAM" ||
  CreatedBy.UserRole.Name = "EAM" ||
  CreatedBy.UserRole.Name = "CSS" ||
  CreatedBy.UserRole.Name = "EBDR" ||
  CreatedBy.UserRole.Name = "EGR" ||
  CreatedBy.UserRole.Name = "IMS" ||
  CreatedBy.UserRole.Name = "SAE" ||
  CreatedBy.UserRole.Name = "SAM" ||
  CreatedBy.UserRole.Name = "SDR" ||
  CreatedBy.UserRole.Name = "VMS"
 ) ||
 (
  Ultimate_Created_By_Role__c = "TSE" ||
  Ultimate_Created_By_Role__c = "AE-I" ||
  Ultimate_Created_By_Role__c = "AE-II" ||
  Ultimate_Created_By_Role__c = "AE-III" ||
  Ultimate_Created_By_Role__c = "BDR" ||
  Ultimate_Created_By_Role__c = "CSAM" ||
  Ultimate_Created_By_Role__c = "EAM" ||
  Ultimate_Created_By_Role__c = "CSS" ||
  Ultimate_Created_By_Role__c = "EBDR" ||
  Ultimate_Created_By_Role__c = "EGR" ||
  Ultimate_Created_By_Role__c = "IMS" ||
  Ultimate_Created_By_Role__c = "SAE" ||
  Ultimate_Created_By_Role__c = "SAM" ||
  Ultimate_Created_By_Role__c = "SDR" ||
  Ultimate_Created_By_Role__c = "VMS"
 ),
 "TRUE","FALSE"
)</formula>
    <inlineHelpText>Formula that looks at HS info, Lead Source, Created By and Ultimate Created By to determine if this was generated by Sales</inlineHelpText>
    <label>Generated by Sales</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Primary_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Primary Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/LeadConvertToContactBatchJob.cls
global class LeadConvertToContactBatchJob implements Database.Batchable<sObject> {
    String batchQuery = ' SELECT Id, Primary_Email__c, Email_Domain__c, CreatedDate, Generated_by_Sales__c, LeadSource FROM Lead WHERE IsConverted = FALSE';
    LeadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted = TRUE LIMIT 1];

    public LeadConvertToContactBatchJob(String whereClause) {
        if (!String.isEmpty(whereClause)) {
            batchQuery += ' AND ( ' + whereClause + ') ';
        }
        batchQuery += ' ORDER BY CreatedDate ASC';
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(batchQuery);
    }

    global void execute(Database.BatchableContext BC, list<Lead> leadList) {
        Map<Id, List<Database.LeadConvert>> leadsToConvertMap = new Map<Id, List<Database.LeadConvert>>();
        Map<String, List<Lead>> emailLeadsMap = new Map<String, List<Lead>>();
        Map<String, Id> checkAccountDomains = new Map<String, Id>();
        List<Database.LeadConvert> leadsToConvert = new List<Database.LeadConvert>();

        //Getting all Lead emails to compare against Contacts
        for (Lead l : leadList) {
            if (!String.isBlank(l.Primary_Email__c)) {
                if (!emailLeadsMap.containsKey(l.Primary_Email__c)) {
                    emailLeadsMap.put(l.Primary_Email__c, new List<Lead>());
                }
                emailLeadsMap.get(l.Primary_Email__c).add(l);

                if (!String.isBlank(l.Email_Domain__c)) {
                    checkAccountDomains.put(l.Email_Domain__c, null);
                }
            }
        }

        //Mapping Accounts by unique Domain to avoid error assigning same value to another Account with null Domain
        if (!checkAccountDomains.isEmpty()) {
            for (Account acc : [
                SELECT Id, Email_Domain__c
                FROM Account
                WHERE Email_Domain__c = :checkAccountDomains.keySet()
            ]) {
                checkAccountDomains.put(acc.Email_Domain__c, acc.Id);
            }
        }

        Map<Id, Contact> contactsToUpdateMap = new Map<Id, Contact>();
        List<Lead> lstUpdate = new List<Lead>();

        //Quering contacts and sending matching leads to convert
        for (Contact c : [
            SELECT Account.Email_Domain__c, Email, CreatedDate, Generated_by_Sales__c, OwnerId, Owner.isActive
            FROM Contact
            WHERE Email IN :emailLeadsMap.keySet()
        ]) {
            for (Lead l : emailLeadsMap.get(c.Email)) {
                Database.LeadConvert lc = new Database.LeadConvert();
                lc.setLeadId(l.Id);
                lc.setAccountId(c.AccountId);
                lc.setContactId(c.Id);
                lc.setConvertedStatus(convertStatus.MasterLabel);
                lc.setDoNotCreateOpportunity(true);

                if(c.Owner.isActive)
                {
                    lc.setOwnerID(c.OwnerId);
                }
                else
                {
                    l.ownerId = c.OwnerId;
                    lstUpdate.add(l);
                    lc.setOwnerID(AppConstants.SALES_API_USER);
                }

                if (
                    c.Account.Email_Domain__c != null ||
                    !checkAccountDomains.containsKey(l.Email_Domain__c) ||
                    checkAccountDomains.get(l.Email_Domain__c) == c.AccountId
                ) {
                    leadsToConvert.add(lc);
                }

                if (!contactsToUpdateMap.containsKey(c.Id) && c.CreatedDate > l.CreatedDate) {
                    c.LeadSource = l.LeadSource;

                    if (c.Generated_by_Sales__c == 'FALSE' && l.Generated_by_Sales__c == 'TRUE') {
                        c.Generated_by_Sales__c = l.Generated_by_Sales__c;
                        contactsToUpdateMap.put(c.Id, c);
                    }
                }
            }
        }

        DatabaseUtilities.leadConvert(
            leadsToConvert,
            'LeadConvertToContactBatchJob',
            'Convert Lead to Matching Contact'
        );

        DatabaseUtilities.saveToDatabase(
            contactsToUpdateMap.values(),
            'LeadConvertToContactBatchJob',
            'Update Contact with older Lead info'
        );

        DatabaseUtilities.saveToDatabase(
            lstUpdate,
            'LeadConvertToContactBatchJob',
            'Update inactive owner Lead'
        );
    }

    global void finish(Database.BatchableContext BC) {
    }
}