unpackaged/main/default/objects/Account/fields/Email_Domain__c.field-meta.xml
<CustomField>
    <fullName>Email_Domain__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Use this one for Xom Integrations.</inlineHelpText>
    <label>Email Domain</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Contact_s_Date_of_First_Order__c.field-meta.xml
<CustomField>
    <fullName>Contact_s_Date_of_First_Order__c</fullName>
    <description>First date that the contact placed an order</description>
    <label>Date of First Order</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Date_of_Last_Order__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Last_Order__c</fullName>
    <label>Date of Last Order</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/ERP_Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact_First_Name__c</fullName>
    <description>The first name of a Contact assoicated to a quote coming from the ERP.</description>
    <inlineHelpText>First Name as it was in the ERP when it came to SF</inlineHelpText>
    <label>ERP - Contact First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/ERP_Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact_Last_Name__c</fullName>
    <inlineHelpText>Last Name as it was in the ERP when it came to SF</inlineHelpText>
    <label>ERP - Contact Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/P21_ContactID__c.field-meta.xml
<CustomField>
    <fullName>P21_ContactID__c</fullName>
    <externalId>true</externalId>
    <label>P21 ContactID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/Order_Erp__c.object-meta.xml
<CustomObject>
    <description>This object cotains the orders from Xometry ERP. An order is created in Salesforce when the Order date is populated. 

Technical Note: Quote and Orders are the same object in the source system but seperated in Salesforce as Orders represent the end of the opportunity process.</description>
    <label>Order ERP</label>
    <nameField>
        <displayFormat>Order-{000000}</displayFormat>
        <label>Order Erp Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders ERP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order_Erp__c/fields/Account_Domain__c.field-meta.xml
<CustomField>
    <fullName>Account_Domain__c</fullName>
    <description>The domain associated with the email address of who placed the order.</description>
    <label>Account Domain</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/ERP_Contact__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact__c</fullName>
    <inlineHelpText>Search for this contact  in the ERP to see more information about the contact.</inlineHelpText>
    <label>ERP Contact</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/ERP_Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact_First_Name__c</fullName>
    <description>The first name of the contact who placed the order.</description>
    <label>ERP Contact First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/ERP_Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact_Last_Name__c</fullName>
    <description>Last Name of the Customer who placed the Order.</description>
    <label>ERP Contact Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/ERP_PartPk__c.field-meta.xml
<CustomField>
    <fullName>ERP_PartPk__c</fullName>
    <description>A concatenation of all parts that were used to create an order.</description>
    <label>ERP PartPk</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/Is_Generic__c.field-meta.xml
<CustomField>
    <fullName>Is_Generic__c</fullName>
    <defaultValue>false</defaultValue>
    <description>A boolean to flag if the order is associated with a generic email or not.</description>
    <label>Is Generic</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/Order_Subtotal__c.field-meta.xml
<CustomField>
    <fullName>Order_Subtotal__c</fullName>
    <label>Order Subtotal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/Order_Total__c.field-meta.xml
<CustomField>
    <fullName>Order_Total__c</fullName>
    <description>The total on the order</description>
    <label>Order Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>credit_card</fullName>
                <label>Credit Card</label>
            </value>
            <value>
                <fullName>purchase_order</fullName>
                <label>Purchase Order</label>
            </value>
            <value>
                <fullName>buy_now_pay_later</fullName>
                <label>Buy Now Pay Later</label>
            </value>
            <value>
                <fullName>no_payment</fullName>
                <label>No Payment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/process_isCNC_Machining__c.field-meta.xml
<CustomField>
    <fullName>process_isCNC_Machining__c</fullName>
    <defaultValue>false</defaultValue>
    <label>process_isCNC_Machining</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/process_isPolyJet_3D__c.field-meta.xml
<CustomField>
    <fullName>process_isPolyJet_3D__c</fullName>
    <defaultValue>false</defaultValue>
    <label>process_isPolyJet_3D</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/process_isSLS__c.field-meta.xml
<CustomField>
    <fullName>process_isSLS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>process_isSLS</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/Xometry_ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>Xometry_ERP_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>This value is the unique order.id created in erp. The quote ID and Order ID are the same.</description>
    <externalId>true</externalId>
    <inlineHelpText>Value to use to look up an order in the ERP.</inlineHelpText>
    <label>Order ID</label>
    <length>12</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/Quote_ERP__c.object-meta.xml
<CustomObject>
    <description>A quote that is sent over from ERP</description>
    <label>Quote ERP</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote_ERP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes ERP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Quote_ERP__c/fields/Account_Domain__c.field-meta.xml
<CustomField>
    <fullName>Account_Domain__c</fullName>
    <description>The domain associated with an account. For generics this will still be a generic domain.</description>
    <label>Account Domain</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/ERP_Contact__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact__c</fullName>
    <description>The ERP Contact identifier that is used to lookup the unique contact on a quote in the ERP.</description>
    <label>ERP Contact ID</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/ERP_Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact_First_Name__c</fullName>
    <label>ERP Contact First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/ERP_Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact_Last_Name__c</fullName>
    <label>ERP Contact Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/ERP_PartPK__c.field-meta.xml
<CustomField>
    <fullName>ERP_PartPK__c</fullName>
    <description>A unique concatenation of Parts that will link to Opportunities and Leads</description>
    <label>ERP PartPK</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/ERP_User_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>ERP_User_Company_Name__c</fullName>
    <description>The Company Name that the user filled out in the ERP</description>
    <inlineHelpText>The Company Name that the user filled out in the Checkout Section.</inlineHelpText>
    <label>ERP Company Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/IS_Generic__c.field-meta.xml
<CustomField>
    <fullName>IS_Generic__c</fullName>
    <defaultValue>false</defaultValue>
    <description>A checkbox associated whether the quote ties to a a generic email or not.</description>
    <label>IS Generic</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/process_isCNC_Machining__c.field-meta.xml
<CustomField>
    <fullName>process_isCNC_Machining__c</fullName>
    <defaultValue>false</defaultValue>
    <label>process_isCNC_Machining</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Quote_Email__c.field-meta.xml
<CustomField>
    <fullName>Quote_Email__c</fullName>
    <description>The email that is associated with the quote.</description>
    <label>Quote Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Quote_ERP_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Quote_ERP_Created_Date__c</fullName>
    <description>The date the quote was created in the ERP system</description>
    <label>Quote Created Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Quote_ERP_Created_Time__c.field-meta.xml
<CustomField>
    <fullName>Quote_ERP_Created_Time__c</fullName>
    <label>Quote ERP Created Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Quote_Price__c.field-meta.xml
<CustomField>
    <fullName>Quote_Price__c</fullName>
    <description>The estimated price of the quote</description>
    <label>Quote Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Xometry_ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>Xometry_ERP_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Unique Qoute ID created in Xometry ERP</description>
    <externalId>true</externalId>
    <label>Quote ID</label>
    <length>13</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Supplies_Order__c/Supplies_Order__c.object-meta.xml
<CustomObject>
    <label>Supplies Order</label>
    <nameField>
        <label>Supplies Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplies Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Supplies_Order__c/fields/Order_Total__c.field-meta.xml
<CustomField>
    <fullName>Order_Total__c</fullName>
    <label>Order Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Order__c/fields/P21_CustomerID__c.field-meta.xml
<CustomField>
    <fullName>P21_CustomerID__c</fullName>
    <externalId>true</externalId>
    <label>P21 CustomerID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Quote__c/Supplies_Quote__c.object-meta.xml
<CustomObject>
    <description>This stores the P21 Quotes as records in Salesforce before transformation.</description>
    <label>Supplies Quote</label>
    <nameField>
        <label>Supplies Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplies Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Supplies_Quote__c/fields/Account_Domain__c.field-meta.xml
<CustomField>
    <fullName>Account_Domain__c</fullName>
    <label>Account Domain</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Quote__c/fields/Is_Generic__c.field-meta.xml
<CustomField>
    <fullName>Is_Generic__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Generic</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Quote__c/fields/P21_Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>P21_Contact_First_Name__c</fullName>
    <label>P21 Contact First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Quote__c/fields/P21_Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>P21_Contact_Last_Name__c</fullName>
    <label>P21 Contact Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Quote__c/fields/P21_ContactID__c.field-meta.xml
<CustomField>
    <fullName>P21_ContactID__c</fullName>
    <label>P21 ContactID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Quote__c/fields/P21_CustomerID__c.field-meta.xml
<CustomField>
    <fullName>P21_CustomerID__c</fullName>
    <externalId>true</externalId>
    <label>P21 CustomerID</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Quote__c/fields/P21_ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>P21_ERP_ID__c</fullName>
    <description>The unique Order ID which can be a Quote from P21 Order Entry.</description>
    <externalId>true</externalId>
    <label>P21 ERP ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Supplies_Quote__c/fields/Quote_Email__c.field-meta.xml
<CustomField>
    <fullName>Quote_Email__c</fullName>
    <label>Quote Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Quote__c/fields/Quote_Price__c.field-meta.xml
<CustomField>
    <fullName>Quote_Price__c</fullName>
    <label>Quote Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/classes/updateContactQuoteDatesTest.cls
@isTest
private class updateContactQuoteDatesTest {
    @isTest
    static void updateContactQuoteDatesTestv1() {
        List<Account> testAccountList = TestDataFactory.createTestAccountNonGenerics(2, 'AM', 1);
        Account testAccount = testAccountList[0];
        ID testAccountID = testAccount.ID;
        Contact myretContact = [
            SELECT ID, FirstName, LastName, Email
            FROM Contact
            WHERE AccountID = :testAccountID
            ORDER BY Name
        ];
        String lemail = myretContact.Email;
        Date myDate = Date.today();
        Datetime myDateTime = Datetime.now();
        List<Contact> myContactList = [SELECT ID, Name, Email FROM Contact];
        for (contact c : myContactList) {
            System.debug('Start The name is ' + c.Name);
            System.debug('Start The name is ' + c.Email);
        }
        // Create an Order
        // Create a Quote
        String CRON_EXP = '0 0 0 1 1 ? *';
        //Call job
        Test.startTest();
        Order_ERP__C ord = TestDataFactory.createOrderERPFromAccContact(
            false,
            'Q12-3333-4444',
            'AAAAA-00004',
            '55555',
            testAccount,
            myretContact,
            Date.newInstance(2019, 10, 22),
            DateTime.newInstance(2019, 10, 22, 11, 15, 0)
        );
        ord.ERP_Contact__c = 'AAAAA';
        ord.Payment_Type__c = 'credit_card';
        ord.process_isCNC_Machining__c = true;
        ord.process_isPolyJet_3D__c = false;
        ord.Order_Total__c = 1500;
        ord.Order_Subtotal__c = 1450;
        insert ord;

        Quote_ERP__C quote2 = new Quote_ERP__C();
        quote2.Account_Domain__c = testAccount.Email_Domain__c;
        quote2.Quote_ERP_Created_Date__C = Date.newInstance(2019, 10, 23);
        quote2.Quote_ERP_Created_Time__c = DateTime.newInstance(2019, 10, 23, 11, 15, 0);
        quote2.ERP_User_Company_Name__c = testAccount.name;
        quote2.ERP_Contact__C = 'AAAAA';
        quote2.ERP_Contact_First_Name__c = myretContact.FirstName;
        quote2.ERP_Contact_Last_Name__C = myretContact.LastName;
        quote2.Quote_Email__c = myretContact.Email;
        quote2.Xometry_ERP_ID__c = 'Q12-333-5555';
        quote2.ERP_PartPK__c = '44444';
        quote2.process_isSLS__c = true;
        quote2.Quote_Price__c = 15000;
        insert quote2;
        String jobID = System.schedule('UpdateContactQuoteScheduleTest', CRON_EXP, new updateContactQuoteSchedule());
        Test.stopTest();
        Contact myContact = [
            SELECT
                ID,
                Name,
                Contact_s_Date_of_First_Order__c,
                First_Quote_Date__c,
                Date_of_Last_Order__c,
                Date_of_Last_Quote__c
            FROM Contact
            WHERE ID = :myretContact.ID
        ];
        System.debug('The First Order Date should be : ' + myContact.Contact_s_Date_of_First_Order__c);
        System.debug('The First Quote Date should be : ' + myContact.First_Quote_Date__c);
        Integer myInt = [SELECT COUNT() FROM Contact];
        List<Contact> myContactList1 = [SELECT ID, Name, Email FROM Contact];
        for (contact c : myContactList1) {
            System.debug('The name is ' + c.Name);
            System.debug('The name is ' + c.Email);
        }
        System.debug('The number of Contacts is : ' + myInt);
    }

    @isTest
    static void updateContactSuppliesQuoteDatesTestv1() {
        List<Account> testAccountList = TestDataFactory.createTestAccountNonGenerics(2, 'AM', 1);
        Account testAccount = testAccountList[0];
        ID testAccountID = testAccount.ID;
        Contact myretContact = [
            SELECT ID, FirstName, LastName, Email
            FROM Contact
            WHERE AccountID = :testAccountID
            ORDER BY Name
        ];
        String lemail = myretContact.Email;
        Date myDate = Date.today();
        Datetime myDateTime = Datetime.now();
        List<Contact> myContactList = [SELECT ID, Name, Email FROM Contact];
        for (contact c : myContactList) {
            System.debug('Start The name is ' + c.Name);
            System.debug('Start The name is ' + c.Email);
        }
        Supplies_Quote__C sQuoteTest = new Supplies_Quote__C();
        sQuoteTest.P21_ERP_ID__c = 'OE23477';
        sQuoteTest.P21_ContactID__c = 'A1265';
        sQuoteTest.P21_CustomerID__c = 'CA144';
        sQuoteTest.Quote_Email__c = myretContact.Email;
        sQuoteTest.Account_Domain__c = testAccount.Email_Domain__c;
        sQuoteTest.PartnerID__c = 'P33465';
        sQuoteTest.Is_Generic__c = true;
        sQuoteTest.P21_Contact_First_Name__c = myretContact.FirstName;
        sQuoteTest.P21_Contact_Last_Name__c = myretContact.LastName;
        sQuoteTest.P21_Contact_Phone__c = '5553334444';
        sQuoteTest.P21_OE_Status__c = 'Processing';
        sQuoteTest.P21_Physical_Address__c = '555 Test Address Fast St.';
        sQuoteTest.P21_Physical_City__c = 'MadeupTown';
        sQuoteTest.P21_Physical_Country__c = 'United States';
        sQuoteTest.P21_Physical_State__c = 'Maryland';
        sQuoteTest.P21_Physical_Zip_Code__c = '23455';
        sQuoteTest.Quote_P21_Created_Date__c = date.newInstance(2021, 10, 28);
        sQuoteTest.Quote_P21_Last_Updated_Time__c = datetime.newInstance(2021, 10, 28, 10, 0, 30);
        sQuoteTest.Quote_Price__c = 500.50;
        insert sQuoteTest;
        Supplies_Order__C sOrderTest = new Supplies_Order__C();
        sOrderTest.P21_Quote_OE_ERP_ID__C = 'OE23477';
        sOrderTest.P21_Order_OE_ERP_ID__C = 'OE24455';
        sOrderTest.P21_ContactID__c = 'A1265';
        sOrderTest.P21_CustomerID__c = 'CA144';
        sOrderTest.Order_Email__c = myretContact.Email;
        sOrderTest.Account_Domain__c = testAccount.Email_Domain__c;
        sOrderTest.PartnerID__c = 'P33465';
        sOrderTest.Is_Generic__c = true;
        sOrderTest.P21_Contact_First_Name__c = myretContact.FirstName;
        sOrderTest.P21_Contact_Last_Name__c = myretContact.LastName;
        sOrderTest.P21_Contact_Phone__c = '5553334444';
        sOrderTest.P21_OE_Status__c = 'Processing';
        sOrderTest.P21_Physical_Address__c = '555 Test Address Fast St.';
        sOrderTest.P21_Physical_City__c = 'MadeupTown';
        sOrderTest.P21_Physical_Country__c = 'United States';
        sOrderTest.P21_Physical_State__c = 'Maryland';
        sOrderTest.P21_Physical_Zip_Code__c = '23455';
        sOrderTest.Order_Date__c = date.newInstance(2021, 10, 28);
        sOrderTest.Order_P21_Last_Updated_Time__c = datetime.newInstance(2021, 10, 28, 10, 0, 30);
        sOrderTest.Order_Total__c = 500.50;
        insert sOrderTest;
        Test.startTest();
        updateContactQuoteDates uCQD = new updateContactQuoteDates();
        ID batchID = Database.executeBatch(uCQD);
        System.debug('The batchID is : ' + batchID);
        Test.stopTest();
        Contact myContact = [
            SELECT
                ID,
                Name,
                Sup_NumberQuotes__c,
                Sup_DateOfFirstOrder__c,
                Sup_DateOfFirstQuote__c,
                Sup_DateOfLastOrder__c,
                Sup_DateOfLastQuote__c
            FROM Contact
            WHERE ID = :myretContact.ID
        ];
        Integer myInt = [SELECT COUNT() FROM Contact];
        List<Contact> myContactList1 = [SELECT ID, Name, Email FROM Contact];
        for (contact c : myContactList1) {
            System.debug('The name is ' + c.Name);
            System.debug('The name is ' + c.Email);
        }
        System.debug('The number of Contacts is : ' + myInt);

        System.assertEquals(
            date.newInstance(2021, 10, 28),
            myContact.Sup_DateOfFirstQuote__c,
            'Contact should have supplies first quote date'
        );
        System.assertEquals(
            date.newInstance(2021, 10, 28),
            myContact.Sup_DateOfLastOrder__c,
            'Contact should have supplies last order date'
        );
        System.assertEquals(1, myContact.Sup_NumberQuotes__c, 'Contact should have one quote count');
    }
}