unpackaged/main/default/objects/Account/fields/Email_Domain__c.field-meta.xml
<CustomField>
    <fullName>Email_Domain__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Use this one for Xom Integrations.</inlineHelpText>
    <label>Email Domain</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Contact/fields/ERP_Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact_First_Name__c</fullName>
    <description>The first name of a Contact assoicated to a quote coming from the ERP.</description>
    <inlineHelpText>First Name as it was in the ERP when it came to SF</inlineHelpText>
    <label>ERP - Contact First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/ERP_Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact_Last_Name__c</fullName>
    <inlineHelpText>Last Name as it was in the ERP when it came to SF</inlineHelpText>
    <label>ERP - Contact Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/Order_Erp__c.object-meta.xml
<CustomObject>
    <description>This object cotains the orders from Xometry ERP. An order is created in Salesforce when the Order date is populated. 

Technical Note: Quote and Orders are the same object in the source system but seperated in Salesforce as Orders represent the end of the opportunity process.</description>
    <label>Order ERP</label>
    <nameField>
        <displayFormat>Order-{000000}</displayFormat>
        <label>Order Erp Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders ERP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order_Erp__c/fields/Account_Domain__c.field-meta.xml
<CustomField>
    <fullName>Account_Domain__c</fullName>
    <description>The domain associated with the email address of who placed the order.</description>
    <label>Account Domain</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/ERP_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>ERP_Company_Name__c</fullName>
    <label>ERP Company Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/ERP_Contact__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact__c</fullName>
    <inlineHelpText>Search for this contact  in the ERP to see more information about the contact.</inlineHelpText>
    <label>ERP Contact</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/ERP_Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact_First_Name__c</fullName>
    <description>The first name of the contact who placed the order.</description>
    <label>ERP Contact First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/ERP_Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact_Last_Name__c</fullName>
    <description>Last Name of the Customer who placed the Order.</description>
    <label>ERP Contact Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/ERP_PartPk__c.field-meta.xml
<CustomField>
    <fullName>ERP_PartPk__c</fullName>
    <description>A concatenation of all parts that were used to create an order.</description>
    <label>ERP PartPk</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/Is_Generic__c.field-meta.xml
<CustomField>
    <fullName>Is_Generic__c</fullName>
    <defaultValue>false</defaultValue>
    <description>A boolean to flag if the order is associated with a generic email or not.</description>
    <label>Is Generic</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/OpportunityID__c.field-meta.xml
<CustomField>
    <fullName>OpportunityID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OpportunityID</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Orders_Erp</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/Order_Email__c.field-meta.xml
<CustomField>
    <fullName>Order_Email__c</fullName>
    <description>The email address that was used to place the order.</description>
    <label>Order Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/Order_ERP_CreatedDate__c.field-meta.xml
<CustomField>
    <fullName>Order_ERP_CreatedDate__c</fullName>
    <description>Date that an order was placed.</description>
    <label>Order Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/Order_ERP_Time__c.field-meta.xml
<CustomField>
    <fullName>Order_ERP_Time__c</fullName>
    <label>Order Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/process_isCNC_Machining__c.field-meta.xml
<CustomField>
    <fullName>process_isCNC_Machining__c</fullName>
    <defaultValue>false</defaultValue>
    <label>process_isCNC_Machining</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/Xometry_ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>Xometry_ERP_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>This value is the unique order.id created in erp. The quote ID and Order ID are the same.</description>
    <externalId>true</externalId>
    <inlineHelpText>Value to use to look up an order in the ERP.</inlineHelpText>
    <label>Order ID</label>
    <length>12</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/Quote_ERP__c.object-meta.xml
<CustomObject>
    <description>A quote that is sent over from ERP</description>
    <label>Quote ERP</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote_ERP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes ERP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Quote_ERP__c/fields/Account_Domain__c.field-meta.xml
<CustomField>
    <fullName>Account_Domain__c</fullName>
    <description>The domain associated with an account. For generics this will still be a generic domain.</description>
    <label>Account Domain</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/ERP_Contact__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact__c</fullName>
    <description>The ERP Contact identifier that is used to lookup the unique contact on a quote in the ERP.</description>
    <label>ERP Contact ID</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/ERP_Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact_First_Name__c</fullName>
    <label>ERP Contact First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/ERP_Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact_Last_Name__c</fullName>
    <label>ERP Contact Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/ERP_PartPK__c.field-meta.xml
<CustomField>
    <fullName>ERP_PartPK__c</fullName>
    <description>A unique concatenation of Parts that will link to Opportunities and Leads</description>
    <label>ERP PartPK</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/IS_Generic__c.field-meta.xml
<CustomField>
    <fullName>IS_Generic__c</fullName>
    <defaultValue>false</defaultValue>
    <description>A checkbox associated whether the quote ties to a a generic email or not.</description>
    <label>IS Generic</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/OpportunityID__c.field-meta.xml
<CustomField>
    <fullName>OpportunityID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the related opportunity</description>
    <label>OpportunityID</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Quotes_ERP</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/process_isCNC_Machining__c.field-meta.xml
<CustomField>
    <fullName>process_isCNC_Machining__c</fullName>
    <defaultValue>false</defaultValue>
    <label>process_isCNC_Machining</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Quote_Email__c.field-meta.xml
<CustomField>
    <fullName>Quote_Email__c</fullName>
    <description>The email that is associated with the quote.</description>
    <label>Quote Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Quote_ERP_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Quote_ERP_Created_Date__c</fullName>
    <description>The date the quote was created in the ERP system</description>
    <label>Quote Created Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Quote_Price__c.field-meta.xml
<CustomField>
    <fullName>Quote_Price__c</fullName>
    <description>The estimated price of the quote</description>
    <label>Quote Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Xometry_ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>Xometry_ERP_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Unique Qoute ID created in Xometry ERP</description>
    <externalId>true</externalId>
    <label>Quote ID</label>
    <length>13</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/quoteToOppHelperTest.cls
@isTest
public class quoteToOppHelperTest {
    @isTest
    static void quoteToOppCreationTest() {
        //Create an Account AM
        List<Account> testAccountList = TestDataFactory.createTestAccountNonGenerics(2, 'AM', 1);
        Account testAccount = testAccountList[0];
        ID testAccountID = testAccount.ID;
        List<Contact> myContactList = [
            SELECT ID, FirstName, LastName, Email
            FROM Contact
            WHERE AccountID = :testAccountID
        ];
        Contact testContact = myContactList[0];

        //Create an Order on a Contact
        Order_ERP__C testOrder = TestDataFactory.createDefaultOrderERP(false);
        testOrder.Account_Domain__c = testAccount.Email_Domain__C;
        testOrder.ERP_Company_Name__C = testAccount.Name;
        testOrder.ERP_Contact_First_Name__c = testContact.FirstName;
        testOrder.ERP_Contact_Last_Name__c = testContact.LastName;
        testOrder.Order_ERP_CreatedDate__c = date.newInstance(2021, 12, 2);
        testOrder.Order_ERP_Time__c = dateTime.newInstance(2021, 12, 2, 10, 0, 0);
        testOrder.Order_Email__c = testContact.Email;
        testOrder.process_isCNC_Machining__c = true;
        insert testOrder;

        Quote_ERP__C testQuote = new Quote_ERP__C();
        testQuote.Account_Domain__C = testAccount.Email_Domain__C;
        testQuote.ERP_PartPK__c = 'A1234-A5678';
        testQuote.Quote_Price__c = 1;
        testQuote.Xometry_ERP_ID__C = 'Q12-3333-5555';
        testQuote.ERP_Contact__c = 'BBBBB';
        testQuote.IS_Generic__c = false;
        testQuote.Quote_Email__c = testContact.Email;
        testQuote.Quote_ERP_Created_Date__c = Date.newInstance(2021, 12, 2);
        //Create a quote for less than $250 CNC
        insert testQuote;

        ID testQuoteID = testQuote.ID;
        Test.StartTest();
        Quote_ERP__C insertedQuote = [SELECT ID, OpportunityID__C FROM Quote_ERP__C WHERE ID = :testQuoteID];
        boolean beforeApexOpp;
        if (String.isblank(insertedQuote.OpportunityID__C)) {
            beforeApexOpp = false;
        } else {
            beforeApexOpp = true;
        }
        System.assertEquals(true, beforeApexOpp, 'The Quote has an Opportunity!');
        quoteToOppHelper.createOppFromQuoteSubmit(testQuoteID);
        Test.StopTest();
        //Confirm no OpportunityID
        Quote_ERP__C afterApexQuote = [SELECT ID, OpportunityID__C FROM Quote_ERP__C WHERE ID = :testQuoteID];
        boolean newOppQuote;
        if (!String.isblank(afterApexQuote.OpportunityID__C)) {
            newOppQuote = true;
        }
        System.debug('Here is the OpportunityID : ' + afterApexQuote.OpportunityID__C);
        System.assertEquals(newOppQuote, true);
        //Call Apex
        // Confirm Quote now has an OpportunityID
    }
}