unpackaged/main/default/objects/Account/fields/Email_Domain__c.field-meta.xml
<CustomField>
    <fullName>Email_Domain__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Use this one for Xom Integrations.</inlineHelpText>
    <label>Email Domain</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Audit_Trail_Error__c/Audit_Trail_Error__c.object-meta.xml
<CustomObject>
    <label>Audit Trail Error</label>
    <nameField>
        <displayFormat>AER-{0}</displayFormat>
        <label>Audit Trail Error Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit Trail Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Contact/fields/Generated_by_Sales__c.field-meta.xml
<CustomField>
    <fullName>Generated_by_Sales__c</fullName>
    <defaultValue>"FALSE"</defaultValue>
    <label>Generated by Sales</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Primary_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>The Primary Email of the Contact.</description>
    <externalId>true</externalId>
    <inlineHelpText>Adjust the email above to change the value. The Primary Email Address is a unique email in the system.</inlineHelpText>
    <label>Primary Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Email_Domain__c.field-meta.xml
<CustomField>
    <fullName>Email_Domain__c</fullName>
    <externalId>true</externalId>
    <label>Domain</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Generated_by_Sales__c.field-meta.xml
<CustomField>
    <fullName>Generated_by_Sales__c</fullName>
    <formula>IF(
 HS_Generated_by_Sales__c = "True" ||
 (
  ISPICKVAL(LeadSource, "Outreach") ||
  ISPICKVAL(LeadSource, "ZoomInfo") ||
  ISPICKVAL(LeadSource, "Webinar") ||
  ISPICKVAL(LeadSource, "Sales Generated")
 ) ||
 (
  CreatedBy.UserRole.Name = "TSE" ||
  CreatedBy.UserRole.Name = "AE-I" ||
  CreatedBy.UserRole.Name = "AE-II" ||
  CreatedBy.UserRole.Name = "AE-III" ||
  CreatedBy.UserRole.Name = "BDR" ||
  CreatedBy.UserRole.Name = "CSAM" ||
  CreatedBy.UserRole.Name = "EAM" ||
  CreatedBy.UserRole.Name = "CSS" ||
  CreatedBy.UserRole.Name = "EBDR" ||
  CreatedBy.UserRole.Name = "EGR" ||
  CreatedBy.UserRole.Name = "IMS" ||
  CreatedBy.UserRole.Name = "SAE" ||
  CreatedBy.UserRole.Name = "SAM" ||
  CreatedBy.UserRole.Name = "SDR" ||
  CreatedBy.UserRole.Name = "VMS"
 ) ||
 (
  Ultimate_Created_By_Role__c = "TSE" ||
  Ultimate_Created_By_Role__c = "AE-I" ||
  Ultimate_Created_By_Role__c = "AE-II" ||
  Ultimate_Created_By_Role__c = "AE-III" ||
  Ultimate_Created_By_Role__c = "BDR" ||
  Ultimate_Created_By_Role__c = "CSAM" ||
  Ultimate_Created_By_Role__c = "EAM" ||
  Ultimate_Created_By_Role__c = "CSS" ||
  Ultimate_Created_By_Role__c = "EBDR" ||
  Ultimate_Created_By_Role__c = "EGR" ||
  Ultimate_Created_By_Role__c = "IMS" ||
  Ultimate_Created_By_Role__c = "SAE" ||
  Ultimate_Created_By_Role__c = "SAM" ||
  Ultimate_Created_By_Role__c = "SDR" ||
  Ultimate_Created_By_Role__c = "VMS"
 ),
 "TRUE","FALSE"
)</formula>
    <inlineHelpText>Formula that looks at HS info, Lead Source, Created By and Ultimate Created By to determine if this was generated by Sales</inlineHelpText>
    <label>Generated by Sales</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/HS_Generated_by_Sales__c.field-meta.xml
<CustomField>
    <fullName>HS_Generated_by_Sales__c</fullName>
    <label>HS Generated by Sales</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Primary_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Primary Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/LeadConvertToContactBatchJobTest.cls
@isTest
private class LeadConvertToContactBatchJobTest {
    @isTest
    static void LeadConvertToContactBatchJobTest() {
        LeadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted = TRUE LIMIT 1];

        Account acc1 = new Account(Name = 'Acc1', Email_Domain__c = null);
        Account acc2 = new Account(Name = 'Acc2', Email_Domain__c = 'xomdomain.com');
        insert new List<Account>{ acc1, acc2 };

        Contact con1 = new Contact(
            FirstName = 'con1',
            LastName = 'Test',
            Email = 'contact1@xomdomain.com',
            AccountId = acc1.Id
        );
        Contact con2 = new Contact(
            FirstName = 'con2',
            LastName = 'Test',
            Email = 'contact2@xomdomain.com',
            AccountId = acc2.Id
        );
        insert new List<Contact>{ con1, con2 };

        Lead leadTest1 = new Lead(
            Lastname = 'leadTest1',
            Company = 'Test',
            Primary_Email__c = 'contact1@xomdomain.com',
            Email_Domain__c = 'xomdomain.com'
        );
        Lead leadTest2 = new Lead(
            Lastname = 'leadTest2',
            Company = 'Test',
            Primary_Email__c = 'contact2@xomdomain.com',
            Email_Domain__c = 'xomdomain2.com'
        );
        insert new List<Lead>{ leadTest1, leadTest2 };

        Test.startTest();
        Database.executeBatch(new LeadConvertToContactBatchJob(''));
        Test.stopTest();

        Map<Id, Lead> leadResult = new Map<Id, Lead>([SELECT Id, IsConverted FROM Lead]);

        System.assertEquals(false, leadResult.get(leadTest1.Id).IsConverted, 'Lead should not be converted');
        System.assertEquals(true, leadResult.get(leadTest2.Id).IsConverted, 'Lead should be converted');
        System.assertEquals(0, [SELECT Id FROM Audit_Trail_Error__c].size(), 'No audit records should be recorded');
    }

    @isTest
    static void LeadConvertToContactBatchJobTest2() {
        LeadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted = TRUE LIMIT 1];

        Account acc1 = new Account(Name = 'Acc1', Email_Domain__c = null);
        Account acc2 = new Account(Name = 'Acc2', Email_Domain__c = 'xomdomain.com');
        insert new List<Account>{ acc1, acc2 };

        Lead leadTest1 = new Lead(
            Lastname = 'leadTest1',
            Company = 'Test',
            Primary_Email__c = 'contact1@xomdomain.com',
            Email_Domain__c = 'xomdomain.com',
            HS_Generated_by_Sales__c = 'True'
        );

        insert leadTest1;

        Contact con1 = new Contact(
            FirstName = 'con1',
            LastName = 'Test',
            Email = 'contact1@xomdomain.com',
            AccountId = acc1.Id
        );
        Contact con2 = new Contact(
            FirstName = 'con2',
            LastName = 'Test',
            Email = 'contact2@xomdomain.com',
            AccountId = acc2.Id
        );
        insert new List<Contact>{ con1, con2 };

        Lead leadTest2 = new Lead(
            Lastname = 'leadTest2',
            Company = 'Test',
            Primary_Email__c = 'contact2@xomdomain.com',
            Email_Domain__c = 'xomdomain2.com',
            HS_Generated_by_Sales__c = 'True'
        );

        insert leadTest2;

        Test.startTest();
        Database.executeBatch(new LeadConvertToContactBatchJob(''));
        Test.stopTest();

        Map<Id, Lead> leadResult = new Map<Id, Lead>([SELECT Id, IsConverted FROM Lead]);

        System.assertEquals(false, leadResult.get(leadTest1.Id).IsConverted, 'Lead should not be converted');
        System.assertEquals(true, leadResult.get(leadTest2.Id).IsConverted, 'Lead should be converted');
        System.assertEquals(0, [SELECT Id FROM Audit_Trail_Error__c].size(), 'No audit records should be recorded');

        Map<Id, Contact> contactResult = new Map<Id, Contact>([SELECT Id, Generated_by_Sales__c FROM Contact]);

        System.assertEquals('TRUE', contactResult.get(con1.Id).Generated_by_Sales__c);
        System.assertNotEquals('TRUE', contactResult.get(con2.Id).Generated_by_Sales__c);
    }

    @isTest
    static void LeadConvertToContactBatchJobTest_ownerGroup() {
        LeadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted = TRUE LIMIT 1];
        Group lstG = [SELECT Id FROM Group WHERE Type = 'Queue' AND DeveloperName = 'MarketplaceLeadQueueGeneral' Limit 1];
        List<User> testUsers = [SELECT Id FROM User WHERE isActive = false];        

        Account acc1 = new Account(Name = 'Acc1', Email_Domain__c = null);
        Account acc2 = new Account(Name = 'Acc2', Email_Domain__c = 'xomdomain.com');
        insert new List<Account>{ acc1, acc2 };

        Contact con1 = new Contact(
            FirstName = 'con1',
            LastName = 'Test',
            Email = 'contact1@xomdomain.com',
            AccountId = acc1.Id
        );
        Contact con2 = new Contact(
            FirstName = 'con2',
            LastName = 'Test',
            Email = 'contact2@xomdomain.com',
            Generated_by_Sales__c = 'FALSE',
            AccountId = acc2.Id,
            ownerId = testUsers[0].id
        );
        insert new List<Contact>{ con1, con2 };

        Lead leadTest1 = new Lead(
            Lastname = 'leadTest1',
            Company = 'Test',
            Primary_Email__c = 'contact1@xomdomain.com',
            Email_Domain__c = 'xomdomain.com',
            HS_Generated_by_Sales__c  = 'TRUE',
            OwnerId = lstG.Id
        );
        Lead leadTest2 = new Lead(
            Lastname = 'leadTest2',
            Company = 'Test',
            Primary_Email__c = 'contact2@xomdomain.com',
            Email_Domain__c = 'xomdomain2.com',
            OwnerId = lstG.Id
        );
        insert new List<Lead>{ leadTest1, leadTest2 };

        Test.startTest();
        Database.executeBatch(new LeadConvertToContactBatchJob('Id != null'));
        Test.stopTest();

        Map<Id, Lead> leadResult = new Map<Id, Lead>([SELECT Id, IsConverted, OwnerId FROM Lead]);

        System.assertEquals(false, leadResult.get(leadTest1.Id).IsConverted, 'Lead should not be converted');
        System.assertEquals(true, leadResult.get(leadTest2.Id).IsConverted, 'Lead should be converted');
        System.assertEquals(0, [SELECT Id FROM Audit_Trail_Error__c].size(), 'No audit records should be recorded');
    }

    @isTest
    public static void LeadConvertToContactBatchJobSchedulerTest() {
        String CRON_EXP = '0 0 23 * * ? *';
        Test.startTest();
        String jobID = System.schedule(
            'LeadConvertToContactBatchJobSchedulerTest',
            CRON_EXP,
            new LeadConvertToContactBatchJobScheduler()
        );
        Test.stopTest();
        System.assertNotEquals(null, jobID, 'Job id is not null');
    }
}