unpackaged/main/default/objects/Account/fields/Email_Domain__c.field-meta.xml
<CustomField>
    <fullName>Email_Domain__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Use this one for Xom Integrations.</inlineHelpText>
    <label>Email Domain</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/Sup_NumberQuoters__c.field-meta.xml
<CustomField>
    <fullName>Sup_NumberQuoters__c</fullName>
    <label>Supplies Number of Quoters</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/P21_ContactID__c.field-meta.xml
<CustomField>
    <fullName>P21_ContactID__c</fullName>
    <externalId>true</externalId>
    <label>P21 ContactID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Sup_DateOfFirstQuote__c.field-meta.xml
<CustomField>
    <fullName>Sup_DateOfFirstQuote__c</fullName>
    <label>Supplies Date of First Quote</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Sup_DateOfLastQuote__c.field-meta.xml
<CustomField>
    <fullName>Sup_DateOfLastQuote__c</fullName>
    <label>Supplies Date of Last Quote</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Quote__c/Supplies_Quote__c.object-meta.xml
<CustomObject>
    <description>This stores the P21 Quotes as records in Salesforce before transformation.</description>
    <label>Supplies Quote</label>
    <nameField>
        <label>Supplies Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplies Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Supplies_Quote__c/fields/Account_Domain__c.field-meta.xml
<CustomField>
    <fullName>Account_Domain__c</fullName>
    <label>Account Domain</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Quote__c/fields/Is_Generic__c.field-meta.xml
<CustomField>
    <fullName>Is_Generic__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Generic</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Quote__c/fields/P21_Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>P21_Contact_First_Name__c</fullName>
    <label>P21 Contact First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Quote__c/fields/P21_Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>P21_Contact_Last_Name__c</fullName>
    <label>P21 Contact Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Quote__c/fields/P21_ContactID__c.field-meta.xml
<CustomField>
    <fullName>P21_ContactID__c</fullName>
    <label>P21 ContactID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Quote__c/fields/P21_CustomerID__c.field-meta.xml
<CustomField>
    <fullName>P21_CustomerID__c</fullName>
    <externalId>true</externalId>
    <label>P21 CustomerID</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Quote__c/fields/P21_ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>P21_ERP_ID__c</fullName>
    <description>The unique Order ID which can be a Quote from P21 Order Entry.</description>
    <externalId>true</externalId>
    <label>P21 ERP ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Supplies_Quote__c/fields/P21_OE_Status__c.field-meta.xml
<CustomField>
    <fullName>P21_OE_Status__c</fullName>
    <label>P21 OE Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Quote__c/fields/P21_Physical_Address__c.field-meta.xml
<CustomField>
    <fullName>P21_Physical_Address__c</fullName>
    <label>P21 Physical Address</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Quote__c/fields/P21_Physical_City__c.field-meta.xml
<CustomField>
    <fullName>P21_Physical_City__c</fullName>
    <label>P21 Physical City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Quote__c/fields/P21_Physical_Country__c.field-meta.xml
<CustomField>
    <fullName>P21_Physical_Country__c</fullName>
    <label>P21 Physical Country</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Quote__c/fields/Quote_Email__c.field-meta.xml
<CustomField>
    <fullName>Quote_Email__c</fullName>
    <label>Quote Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Quote__c/fields/Quote_P21_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Quote_P21_Created_Date__c</fullName>
    <label>Quote Created Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Quote__c/fields/Quote_P21_Last_Updated_Time__c.field-meta.xml
<CustomField>
    <fullName>Quote_P21_Last_Updated_Time__c</fullName>
    <label>Quote P21 Last Updated Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Quote__c/fields/Quote_Price__c.field-meta.xml
<CustomField>
    <fullName>Quote_Price__c</fullName>
    <label>Quote Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/classes/updateAccountSupQuoteInfoBatch_Test.cls
@isTest
private class updateAccountSupQuoteInfoBatch_Test {

    @isTest
    static void scheduleJob() {
        //Call job
        Test.startTest();
        String CRON_EXP = '0 0 0 1 1 ? *';
        String jobID = System.schedule('updateAccountSupQuoteInfoBatchJob', CRON_EXP, new updateAccountSupQuoteInfoBatchJob());
        Test.stopTest();
    }

    @isTest
    static void excecuteBatch() {
        List<Account> testAccountList = TestDataFactory.createTestAccountNonGenerics(2, 'AM', 1);
        Account testAccount = testAccountList[0];
        ID testAccountID = testAccount.ID;
        Contact myretContact = [
            SELECT ID, FirstName, LastName, Email
            FROM Contact
            WHERE AccountID = :testAccountID
            ORDER BY Name
        ];
        
        Supplies_Quote__C sQuoteTest = new Supplies_Quote__C();
        sQuoteTest.P21_ERP_ID__c = 'OE23477';
        sQuoteTest.P21_ContactID__c = 'A1265';
        sQuoteTest.P21_CustomerID__c = 'CA144';
        sQuoteTest.Quote_Email__c = myretContact.Email;
        sQuoteTest.Account_Domain__c = testAccount.Email_Domain__c;
        sQuoteTest.PartnerID__c = 'P33465';
        sQuoteTest.Is_Generic__c = true;
        sQuoteTest.P21_Contact_First_Name__c = myretContact.FirstName;
        sQuoteTest.P21_Contact_Last_Name__c = myretContact.LastName;
        sQuoteTest.P21_Contact_Phone__c = '5553334444';
        sQuoteTest.P21_OE_Status__c = 'Processing';
        sQuoteTest.P21_Physical_Address__c = '555 Test Address Fast St.';
        sQuoteTest.P21_Physical_City__c = 'MadeupTown';
        sQuoteTest.P21_Physical_Country__c = 'United States';
        sQuoteTest.P21_Physical_State__c = 'Maryland';
        sQuoteTest.P21_Physical_Zip_Code__c = '23455';
        sQuoteTest.Quote_P21_Created_Date__c = date.newInstance(2021, 10, 28);
        sQuoteTest.Quote_P21_Last_Updated_Time__c = datetime.newInstance(2021, 10, 28, 10, 0, 30);
        sQuoteTest.Quote_Price__c = 500.50;
        insert sQuoteTest;
        
        Test.startTest();
        updateAccountSupQuoteInfoBatch uAQD = new updateAccountSupQuoteInfoBatch();
        ID batchID = Database.executeBatch(uAQD);
        System.debug('The batchID is : ' + batchID);
        Test.stopTest();

        Account myAccount = [
            SELECT
                ID,
                Name,
                Sup_NumberQuoters__c,
                Sup_DateOfFirstQuote__c,
                Sup_DateOfLastQuote__c
            FROM Account
            WHERE ID = :testAccountID
        ];
        
        System.assertEquals(
            date.newInstance(2021, 10, 28),
            myAccount.Sup_DateOfFirstQuote__c,
            'Account should have supplies first quote date'
        );
    }
}