unpackaged/main/default/objects/Account/fields/Email_Domain__c.field-meta.xml
<CustomField>
    <fullName>Email_Domain__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Use this one for Xom Integrations.</inlineHelpText>
    <label>Email Domain</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Contact/fields/ERP_Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact_First_Name__c</fullName>
    <description>The first name of a Contact assoicated to a quote coming from the ERP.</description>
    <inlineHelpText>First Name as it was in the ERP when it came to SF</inlineHelpText>
    <label>ERP - Contact First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/ERP_Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact_Last_Name__c</fullName>
    <inlineHelpText>Last Name as it was in the ERP when it came to SF</inlineHelpText>
    <label>ERP - Contact Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Primary_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>The Primary Email of the Contact.</description>
    <externalId>true</externalId>
    <inlineHelpText>Adjust the email above to change the value. The Primary Email Address is a unique email in the system.</inlineHelpText>
    <label>Primary Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Email_Domain__c.field-meta.xml
<CustomField>
    <fullName>Email_Domain__c</fullName>
    <externalId>true</externalId>
    <label>Domain</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Primary_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Primary Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/Order_Erp__c.object-meta.xml
<CustomObject>
    <description>This object cotains the orders from Xometry ERP. An order is created in Salesforce when the Order date is populated. 

Technical Note: Quote and Orders are the same object in the source system but seperated in Salesforce as Orders represent the end of the opportunity process.</description>
    <label>Order ERP</label>
    <nameField>
        <displayFormat>Order-{000000}</displayFormat>
        <label>Order Erp Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders ERP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order_Erp__c/fields/Account_Domain__c.field-meta.xml
<CustomField>
    <fullName>Account_Domain__c</fullName>
    <description>The domain associated with the email address of who placed the order.</description>
    <label>Account Domain</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/AccountID__c.field-meta.xml
<CustomField>
    <fullName>AccountID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Account that the order is placed for.</description>
    <label>AccountID</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Orders_Erp</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/ContactID__c.field-meta.xml
<CustomField>
    <fullName>ContactID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ContactID</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Orders_Erp</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/ERP_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>ERP_Company_Name__c</fullName>
    <label>ERP Company Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/ERP_Contact__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact__c</fullName>
    <inlineHelpText>Search for this contact  in the ERP to see more information about the contact.</inlineHelpText>
    <label>ERP Contact</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/ERP_Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact_First_Name__c</fullName>
    <description>The first name of the contact who placed the order.</description>
    <label>ERP Contact First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/ERP_Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact_Last_Name__c</fullName>
    <description>Last Name of the Customer who placed the Order.</description>
    <label>ERP Contact Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/ERP_PartPk__c.field-meta.xml
<CustomField>
    <fullName>ERP_PartPk__c</fullName>
    <description>A concatenation of all parts that were used to create an order.</description>
    <label>ERP PartPk</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/Is_Generic__c.field-meta.xml
<CustomField>
    <fullName>Is_Generic__c</fullName>
    <defaultValue>false</defaultValue>
    <description>A boolean to flag if the order is associated with a generic email or not.</description>
    <label>Is Generic</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/LeadID__c.field-meta.xml
<CustomField>
    <fullName>LeadID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LeadID</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>Orders_Erp</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/Order_Email__c.field-meta.xml
<CustomField>
    <fullName>Order_Email__c</fullName>
    <description>The email address that was used to place the order.</description>
    <label>Order Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/Order_ERP_CreatedDate__c.field-meta.xml
<CustomField>
    <fullName>Order_ERP_CreatedDate__c</fullName>
    <description>Date that an order was placed.</description>
    <label>Order Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/Order_ERP_Time__c.field-meta.xml
<CustomField>
    <fullName>Order_ERP_Time__c</fullName>
    <label>Order Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/Order_Subtotal__c.field-meta.xml
<CustomField>
    <fullName>Order_Subtotal__c</fullName>
    <label>Order Subtotal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/Order_Total__c.field-meta.xml
<CustomField>
    <fullName>Order_Total__c</fullName>
    <description>The total on the order</description>
    <label>Order Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/process_isCNC_Machining__c.field-meta.xml
<CustomField>
    <fullName>process_isCNC_Machining__c</fullName>
    <defaultValue>false</defaultValue>
    <label>process_isCNC_Machining</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/Shipping__c.field-meta.xml
<CustomField>
    <fullName>Shipping__c</fullName>
    <label>Shipping</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/Xometry_ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>Xometry_ERP_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>This value is the unique order.id created in erp. The quote ID and Order ID are the same.</description>
    <externalId>true</externalId>
    <inlineHelpText>Value to use to look up an order in the ERP.</inlineHelpText>
    <label>Order ID</label>
    <length>12</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/Quote_ERP__c.object-meta.xml
<CustomObject>
    <description>A quote that is sent over from ERP</description>
    <label>Quote ERP</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote_ERP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes ERP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Quote_ERP__c/fields/Account_Domain__c.field-meta.xml
<CustomField>
    <fullName>Account_Domain__c</fullName>
    <description>The domain associated with an account. For generics this will still be a generic domain.</description>
    <label>Account Domain</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/AccountID__c.field-meta.xml
<CustomField>
    <fullName>AccountID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Account that the quote belongs to</description>
    <label>AccountID</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Quotes_ERP</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/ContactID__c.field-meta.xml
<CustomField>
    <fullName>ContactID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Contact</description>
    <label>ContactID</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Quotes_ERP</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/ERP_Contact__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact__c</fullName>
    <description>The ERP Contact identifier that is used to lookup the unique contact on a quote in the ERP.</description>
    <label>ERP Contact ID</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/ERP_Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact_First_Name__c</fullName>
    <label>ERP Contact First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/ERP_Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact_Last_Name__c</fullName>
    <label>ERP Contact Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/ERP_PartPK__c.field-meta.xml
<CustomField>
    <fullName>ERP_PartPK__c</fullName>
    <description>A unique concatenation of Parts that will link to Opportunities and Leads</description>
    <label>ERP PartPK</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/IS_Generic__c.field-meta.xml
<CustomField>
    <fullName>IS_Generic__c</fullName>
    <defaultValue>false</defaultValue>
    <description>A checkbox associated whether the quote ties to a a generic email or not.</description>
    <label>IS Generic</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/LeadID__c.field-meta.xml
<CustomField>
    <fullName>LeadID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the lead a quote is associated with</description>
    <label>LeadID</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>Quotes_ERP</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/process_isCNC_Machining__c.field-meta.xml
<CustomField>
    <fullName>process_isCNC_Machining__c</fullName>
    <defaultValue>false</defaultValue>
    <label>process_isCNC_Machining</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Quote_Email__c.field-meta.xml
<CustomField>
    <fullName>Quote_Email__c</fullName>
    <description>The email that is associated with the quote.</description>
    <label>Quote Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Quote_ERP_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Quote_ERP_Created_Date__c</fullName>
    <description>The date the quote was created in the ERP system</description>
    <label>Quote Created Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Quote_Price__c.field-meta.xml
<CustomField>
    <fullName>Quote_Price__c</fullName>
    <description>The estimated price of the quote</description>
    <label>Quote Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Xometry_ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>Xometry_ERP_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Unique Qoute ID created in Xometry ERP</description>
    <externalId>true</externalId>
    <label>Quote ID</label>
    <length>13</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/HandlerUtil_Test.cls
@isTest
public with sharing class HandlerUtil_Test {
    @isTest(seeAllData=false)
    public static void leadConverterFromQuoteTest() {
        Account testAccount = new Account();
        testAccount.Name = 'NewAccount';
        testAccount.Email_Domain__c = 'mydomain.com';
        insert testAccount;

        Contact testContact = new Contact(
            AccountId = testAccount.Id,
            Primary_Email__c = 'test@test123.com',
            FirstName = 'Test',
            LastName = 'Contact'
        );
        insert testContact;

        Quote_ERP__c myQuote = new Quote_ERP__C();
        myQuote.Account_Domain__C = 'SuperCompany2.com';
        myQuote.ERP_PartPK__c = 'A1234-A5678';
        myQuote.Quote_Price__c = 50.15;
        myQuote.Xometry_ERP_ID__C = 'AAAAA-00001';
        myQuote.ERP_Contact__c = 'AAAAA';
        myQuote.IS_Generic__c = true;
        myQuote.Quote_Email__c = 'johndoe@SuperCompany2.com';
        myQuote.Quote_ERP_Created_Date__c = Date.newInstance(2019, 6, 14);
        myQuote.ContactID__c = testContact.Id;
        myQuote.AccountId__c = testAccount.Id;
        insert myQuote;

        Lead l = new Lead();
        l.Primary_Email__c = myQuote.Quote_Email__c;
        l.LastName = 'Test';
        l.Company = 'TestCompany';
        insert l;

        System.assertEquals(false, [SELECT isConverted FROM Lead WHERE Id = :l.Id].isConverted);

        Test.startTest();

        List<Database.LeadConvertResult> convertResult = HandlerUtil.leadConverter(new List<Quote_ERP__c>{ myQuote });

        Test.stopTest();

        System.assertEquals(true, convertResult[0].isSuccess());
        System.assertEquals(true, [SELECT isConverted FROM Lead WHERE Id = :l.Id].isConverted);
    }

    @isTest(seeAllData=false)
    public static void leadConverterFromOrderTest() {
        Lead l = new Lead();
        l.Primary_Email__c = 'janedoe@SuperCompany.com';
        l.LastName = 'Test';
        l.Company = 'SuperCompany';
        insert l;

        Quote_ERP__c myQuote = new Quote_ERP__C();
        myQuote.Account_Domain__C = 'SuperCompany2.com';
        myQuote.ERP_PartPK__c = 'A1234-A5678';
        myQuote.Quote_Price__c = 50.15;
        myQuote.Xometry_ERP_ID__C = 'AAAAC-00123';
        myQuote.ERP_Contact__c = 'AAAAA';
        myQuote.IS_Generic__c = true;
        myQuote.Quote_Email__c = 'johndoe@SuperCompany2.com';
        myQuote.Quote_ERP_Created_Date__c = Date.newInstance(2019, 6, 14);
        insert myQuote;

        Integer thisYear = Date.today().year();
        Order_ERP__C order = new Order_ERP__C();
        order.Account_Domain__C = 'mydomain.com';
        order.ERP_Company_Name__c = 'MyCompanyName';
        order.ERP_Contact_First_Name__c = 'Amy';
        order.ERP_Contact_Last_Name__c = 'Adams';
        order.ERP_Contact__c = 'AAAAC';
        order.ERP_PartPk__c = '44444-555123';
        order.Is_Generic__c = false;
        order.Order_Email__c = 'amyadam@mydomain.com';
        order.Order_ERP_CreatedDate__c = Date.newInstance(thisYear - 2, 12, 5);
        order.Order_ERP_Time__c = Datetime.newInstanceGMT(thisYear - 2, 12, 5, 18, 0, 0);
        order.Order_Subtotal__c = 450.00;
        order.Order_Total__c = 500.00;
        order.process_isCNC_Machining__c = true;
        order.Shipping__c = 50.00;
        order.LeadID__c = l.Id;
        order.Xometry_ERP_ID__c = 'AAAAC-00123';
        insert order;

        myQuote.LeadID__c = l.Id;
        update myQuote;

        System.assertEquals(false, [SELECT isConverted FROM Lead WHERE Id = :l.Id].isConverted);

        Test.startTest();

        List<Database.LeadConvertResult> convertResult = HandlerUtil.leadConverter(new List<Order_Erp__c>{ order });

        Test.stopTest();

        System.assertEquals(true, convertResult[0].isSuccess());
        System.assertEquals(true, [SELECT isConverted FROM Lead WHERE Id = :l.Id].isConverted);
    }

    @isTest(seeAllData=false)
    public static void leadConverterFromContactTest() {
        Account testAccount = new Account();
        testAccount.Name = 'NewAccount';
        testAccount.Email_Domain__c = 'mydomain.com';
        insert testAccount;

        Contact testContact = new Contact(
            AccountId = testAccount.Id,
            Primary_Email__c = 'test@test123.com',
            FirstName = 'Test',
            LastName = 'Contact'
        );
        insert testContact;

        Lead l = new Lead();
        l.Primary_Email__c = testContact.Primary_Email__c;
        l.LastName = 'Test';
        l.Company = 'TestCompany';
        insert l;

        System.assertEquals(false, [SELECT isConverted FROM Lead WHERE Id = :l.Id].isConverted);

        Test.startTest();

        List<Database.LeadConvertResult> convertResult = HandlerUtil.leadConverter(new List<Contact>{ testContact });

        Test.stopTest();

        System.assertEquals(true, convertResult[0].isSuccess());
        System.assertEquals(true, [SELECT isConverted FROM Lead WHERE Id = :l.Id].isConverted);
    }
}