unpackaged/main/default/objects/Account/fields/Email_Domain__c.field-meta.xml
<CustomField>
    <fullName>Email_Domain__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Use this one for Xom Integrations.</inlineHelpText>
    <label>Email Domain</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/has_quoted_CNC_Machining__c.field-meta.xml
<CustomField>
    <fullName>has_quoted_CNC_Machining__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Quoted: CNC Machining</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/has_quoted_Carbon__c.field-meta.xml
<CustomField>
    <fullName>has_quoted_Carbon__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Quoted: Carbon</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/Quote_ERP__c.object-meta.xml
<CustomObject>
    <description>A quote that is sent over from ERP</description>
    <label>Quote ERP</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote_ERP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes ERP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Quote_ERP__c/fields/ContactID__c.field-meta.xml
<CustomField>
    <fullName>ContactID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Contact</description>
    <label>ContactID</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Quotes_ERP</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/IS_Generic__c.field-meta.xml
<CustomField>
    <fullName>IS_Generic__c</fullName>
    <defaultValue>false</defaultValue>
    <description>A checkbox associated whether the quote ties to a a generic email or not.</description>
    <label>IS Generic</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/process_isAssembly__c.field-meta.xml
<CustomField>
    <fullName>process_isAssembly__c</fullName>
    <defaultValue>false</defaultValue>
    <label>process_isAssembly</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/process_isBinderJetting__c.field-meta.xml
<CustomField>
    <fullName>process_isBinderJetting__c</fullName>
    <defaultValue>false</defaultValue>
    <label>process_isBinderJetting</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/process_isCarbon__c.field-meta.xml
<CustomField>
    <fullName>process_isCarbon__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field that shows if Quote is connected with process of Carbon</description>
    <label>process_isCarbon</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/process_isCNC_Machining__c.field-meta.xml
<CustomField>
    <fullName>process_isCNC_Machining__c</fullName>
    <defaultValue>false</defaultValue>
    <label>process_isCNC_Machining</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/process_isDirect_Sourced__c.field-meta.xml
<CustomField>
    <fullName>process_isDirect_Sourced__c</fullName>
    <defaultValue>false</defaultValue>
    <label>process_isDirect_Sourced</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/process_isExtrusion__c.field-meta.xml
<CustomField>
    <fullName>process_isExtrusion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>process_isMetalExtrusion</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/process_isFDM__c.field-meta.xml
<CustomField>
    <fullName>process_isFDM__c</fullName>
    <defaultValue>false</defaultValue>
    <label>process_isFDM</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/process_isInjection_Molding__c.field-meta.xml
<CustomField>
    <fullName>process_isInjection_Molding__c</fullName>
    <defaultValue>false</defaultValue>
    <label>process_isInjection_Molding</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/process_isSheet_metal__c.field-meta.xml
<CustomField>
    <fullName>process_isSheet_metal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>process_isSheet_metal</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/process_isSheetCutting__c.field-meta.xml
<CustomField>
    <fullName>process_isSheetCutting__c</fullName>
    <defaultValue>false</defaultValue>
    <label>process_isSheetCutting</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/process_isTubeBending__c.field-meta.xml
<CustomField>
    <fullName>process_isTubeBending__c</fullName>
    <defaultValue>false</defaultValue>
    <label>process_isTubeBending</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/process_isTubeCutting__c.field-meta.xml
<CustomField>
    <fullName>process_isTubeCutting__c</fullName>
    <defaultValue>false</defaultValue>
    <label>process_isTubeCutting</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Quote_ERP_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Quote_ERP_Created_Date__c</fullName>
    <description>The date the quote was created in the ERP system</description>
    <label>Quote Created Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Quote_ERP_Created_Time__c.field-meta.xml
<CustomField>
    <fullName>Quote_ERP_Created_Time__c</fullName>
    <label>Quote ERP Created Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Xometry_ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>Xometry_ERP_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Unique Qoute ID created in Xometry ERP</description>
    <externalId>true</externalId>
    <label>Quote ID</label>
    <length>13</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/ContactQuoteProcessUpdatesBatchTest.cls
@isTest
private class ContactQuoteProcessUpdatesBatchTest {

    @isTest
    static void ExecuteTest() {
        
        List<Account> retAccounts = TestDataFactory.createTestAccountNonGenerics(2, 'BDR', 1);
        Account myTestAccount = retAccounts[0];
        Contact myretContact = [
            SELECT ID, FirstName, OwnerID, LastName, Email, has_quoted_CNC_Machining__c
            FROM Contact
            WHERE AccountID = :retAccounts[0].ID
            ORDER BY Name
        ];

        Quote_ERP__c myQuote = TestDataFactory.createQuote(
            false,
            myTestAccount.Email_Domain__c,
            myretContact.FirstName,
            myretContact.LastName,
            myretContact.email
        );
        //BDR Opps for Days
        myQuote.Xometry_ERP_ID__C = 'Q12-3333-4444';
        myQuote.IS_Generic__c = false;
        myQuote.Quote_ERP_Created_Date__c = Date.newInstance(2021, 8, 28);
        myQuote.Quote_ERP_Created_Time__c = DateTime.newInstance(2021, 8, 28, 4, 5, 50);
        myQuote.ContactID__C = myretContact.Id;
        myQuote.process_isUrethane_Casting__c = false;
        myQuote.process_isCarbon__c = true;
        myQuote.process_isCNC_Machining__c = true;
        myQuote.process_isDie_Casting__c = true;
        myQuote.process_isDMLS__c = true;
        myQuote.process_isDirect_Sourced__c = true;
        myQuote.process_isExtrusion__c = true;

        Quote_ERP__c myQuote2 = myQuote.clone();
        myQuote2.Xometry_ERP_ID__C = 'Q12-3333-4445';
        myQuote2.process_isFDM__c = true;
        myQuote2.process_isHPMultJetFusion__c = true;
        myQuote2.process_isInjection_Molding__c = true;
        myQuote2.process_isPolyJet_3D__c = true;
        myQuote2.process_isSLS__c = true;
        myQuote2.process_isSheet_metal__c = true;
        myQuote2.process_isStamping__c = true;
        myQuote2.process_isSLA__c = true;
        myQuote2.process_isUrethane_Casting__c = true;
        myQuote2.process_isBinderJetting__c = true;
        myQuote2.process_isSheetCutting__c = true;
        myQuote2.process_isTubeBending__c = true;
        myQuote2.process_isTubeCutting__c = true;
        myQuote2.process_isPlasticExtrusion__c = true;
        myQuote2.process_isOther__c = true;
        myQuote2.process_isOther_NotIncluded__c = true;
        myQuote2.process_isLSPc__c = true;
        myQuote2.process_isAssembly__c = true;
        myQuote2.ContactID__C = myretContact.Id;
        insert new List<Quote_ERP__c>{myQuote,myQuote2};

        
        Contact contactTest = [SELECT has_quoted_CNC_Machining__c,has_quoted_Carbon__c FROM Contact WHERE Id = :myretContact.Id];
        Assert.areEqual(false, contactTest.has_quoted_CNC_Machining__c, 'the default field should be false');
        Assert.areEqual(false, contactTest.has_quoted_Carbon__c, 'the default field should be false');

        Test.startTest();

        Database.executeBatch(new ContactQuoteProcessUpdatesBatch());

        Test.stopTest();

        Contact contactTestResult = [SELECT has_quoted_CNC_Machining__c,has_quoted_Carbon__c FROM Contact WHERE Id = :myretContact.Id];
        Assert.areEqual(true, contactTestResult.has_quoted_CNC_Machining__c, 'Contact should be updated');
        Assert.areEqual(true, contactTestResult.has_quoted_Carbon__c, 'Contact should be updated');

    }

    @isTest
    public static void SchedulerTest() {

        //once each 6 hour
        String CRON_EXP = '0 0 */6 * * ? *';

        Test.startTest();
        String jobID = System.schedule(
            'ContactQuoteProcessUpdatesSchedulerTest',
            CRON_EXP,
            new ContactQuoteProcessUpdatesScheduler()
        );
        Test.stopTest();

        Assert.areNotEqual(null, jobID, 'Job id is not null');
    }

}