unpackaged/main/default/objects/Account/fields/Email_Domain__c.field-meta.xml
<CustomField>
    <fullName>Email_Domain__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Use this one for Xom Integrations.</inlineHelpText>
    <label>Email Domain</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/Sup_DateOfLastOrder__c.field-meta.xml
<CustomField>
    <fullName>Sup_DateOfLastOrder__c</fullName>
    <label>Supplies Date of Last Order</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Sup_NumberOfOrderers__c.field-meta.xml
<CustomField>
    <fullName>Sup_NumberOfOrderers__c</fullName>
    <label>Supplies Number of Orderers</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/P21_ContactID__c.field-meta.xml
<CustomField>
    <fullName>P21_ContactID__c</fullName>
    <externalId>true</externalId>
    <label>P21 ContactID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Sup_DateOfFirstOrder__c.field-meta.xml
<CustomField>
    <fullName>Sup_DateOfFirstOrder__c</fullName>
    <label>Supplies Date of First Order</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Order__c/Supplies_Order__c.object-meta.xml
<CustomObject>
    <label>Supplies Order</label>
    <nameField>
        <label>Supplies Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplies Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Supplies_Order__c/fields/Order_Email__c.field-meta.xml
<CustomField>
    <fullName>Order_Email__c</fullName>
    <label>Order Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Order__c/fields/Order_P21_Last_Updated_Time__c.field-meta.xml
<CustomField>
    <fullName>Order_P21_Last_Updated_Time__c</fullName>
    <label>Order P21 Last Updated Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Order__c/fields/Order_Total__c.field-meta.xml
<CustomField>
    <fullName>Order_Total__c</fullName>
    <label>Order Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Order__c/fields/P21_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>P21_Contact_Phone__c</fullName>
    <label>P21 Contact Phone</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Order__c/fields/P21_CustomerID__c.field-meta.xml
<CustomField>
    <fullName>P21_CustomerID__c</fullName>
    <externalId>true</externalId>
    <label>P21 CustomerID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Order__c/fields/P21_OE_Status__c.field-meta.xml
<CustomField>
    <fullName>P21_OE_Status__c</fullName>
    <label>P21 OE Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Order__c/fields/P21_Order_OE_ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>P21_Order_OE_ERP_ID__c</fullName>
    <description>The unique Order Entry field.</description>
    <externalId>true</externalId>
    <label>P21 Order OE ERP ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Supplies_Order__c/fields/P21_Physical_State__c.field-meta.xml
<CustomField>
    <fullName>P21_Physical_State__c</fullName>
    <label>P21 Physical State</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Order__c/fields/P21_Physical_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>P21_Physical_Zip_Code__c</fullName>
    <label>P21 Physical Zip Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Order__c/fields/P21_Quote_OE_ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>P21_Quote_OE_ERP_ID__c</fullName>
    <label>P21 Quote OE ERP ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/updateAccountSupOrderInfoBatch_Test.cls
@isTest
private class updateAccountSupOrderInfoBatch_Test {
    @isTest
    static void scheduleJob() {
        //Call job
        Test.startTest();
        String CRON_EXP = '0 0 0 1 1 ? *';
        String jobID = System.schedule('updateAccountSupOrderInfoBatchJob', CRON_EXP, new updateAccountSupOrderInfoBatchJob());
        Test.stopTest();
    }

    @isTest
    static void excecuteBatch() {
        List<Account> testAccountList = TestDataFactory.createTestAccountNonGenerics(2, 'AM', 1);
        Account testAccount = testAccountList[0];
        ID testAccountID = testAccount.ID;
        Contact myretContact = [
            SELECT ID, FirstName, LastName, Email
            FROM Contact
            WHERE AccountID = :testAccountID
            ORDER BY Name
        ];
                
        Supplies_Order__C sOrderTest = new Supplies_Order__C();
        sOrderTest.P21_Quote_OE_ERP_ID__C = 'OE23477';
        sOrderTest.P21_Order_OE_ERP_ID__C = 'OE24455';
        sOrderTest.P21_ContactID__c = 'A1265';
        sOrderTest.P21_CustomerID__c = 'CA144';
        sOrderTest.Order_Email__c = myretContact.Email;
        sOrderTest.Account_Domain__c = testAccount.Email_Domain__c;
        sOrderTest.PartnerID__c = 'P33465';
        sOrderTest.Is_Generic__c = true;
        sOrderTest.P21_Contact_First_Name__c = myretContact.FirstName;
        sOrderTest.P21_Contact_Last_Name__c = myretContact.LastName;
        sOrderTest.P21_Contact_Phone__c = '5553334444';
        sOrderTest.P21_OE_Status__c = 'Processing';
        sOrderTest.P21_Physical_Address__c = '555 Test Address Fast St.';
        sOrderTest.P21_Physical_City__c = 'MadeupTown';
        sOrderTest.P21_Physical_Country__c = 'United States';
        sOrderTest.P21_Physical_State__c = 'Maryland';
        sOrderTest.P21_Physical_Zip_Code__c = '23455';
        sOrderTest.Order_Date__c = date.newInstance(2021, 10, 28);
        sOrderTest.Order_P21_Last_Updated_Time__c = datetime.newInstance(2021, 10, 28, 10, 0, 30);
        sOrderTest.Order_Total__c = 500.50;
        insert sOrderTest;

        Test.startTest();
        updateAccountSupOrderInfoBatch uAQD = new updateAccountSupOrderInfoBatch();
        ID batchID = Database.executeBatch(uAQD);
        System.debug('The batchID is : ' + batchID);
        Test.stopTest();
        Account myAccount = [
            SELECT
                ID,
                Name,
                Sup_NumberOfOrderers__c,
                Sup_DateOfFirstOrder__c,
                Sup_DateOfLastOrder__c
            FROM Account
            Limit 1
        ];
        
        System.assertEquals(
            date.newInstance(2021, 10, 28),
            myAccount.Sup_DateOfFirstOrder__c,
            'Account should have supplies first quote date'
        );
    }
}