unpackaged/main/default/objects/Account/fields/EUD_EmailOptOut__c.field-meta.xml
<CustomField>
    <fullName>EUD_EmailOptOut__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Do not send automated emails about missing End Use Data to any contacts from this account</description>
    <label>EUD Email Opt-Out</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>[AP] - New Vendor/Supplier Set-up</fullName>
            </value>
            <value>
                <fullName>[AP] - Stripe Account Issue</fullName>
            </value>
            <value>
                <fullName>[AP] - Vendor Invoice</fullName>
            </value>
            <value>
                <fullName>[AR] - Unconverted Invoices</fullName>
            </value>
            <value>
                <fullName>[AR] - Unpaid Credit Card Invoices</fullName>
            </value>
            <value>
                <fullName>[AR- Collections] - Portal Customer</fullName>
            </value>
            <value>
                <fullName>[Partner Management] - Account Inquiries</fullName>
            </value>
            <value>
                <fullName>[Partner Management] - Partner Relations</fullName>
            </value>
            <value>
                <fullName>[Partner Management] - Supplier Onboarding</fullName>
            </value>
            <value>
                <fullName>Auto Quote Review</fullName>
            </value>
            <value>
                <fullName>Auto response</fullName>
            </value>
            <value>
                <fullName>Bank Info Request</fullName>
            </value>
            <value>
                <fullName>Billing Account Update</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
                <label>Cancellations</label>
            </value>
            <value>
                <fullName>Capability Questions</fullName>
            </value>
            <value>
                <fullName>Case Management</fullName>
            </value>
            <value>
                <fullName>Certifications</fullName>
            </value>
            <value>
                <fullName>Collections</fullName>
            </value>
            <value>
                <fullName>Commercial Invoice</fullName>
            </value>
            <value>
                <fullName>Communication</fullName>
            </value>
            <value>
                <fullName>Credit Applications</fullName>
            </value>
            <value>
                <fullName>Credit Card Payments</fullName>
            </value>
            <value>
                <fullName>Credit Key</fullName>
            </value>
            <value>
                <fullName>Credit Limit Increase</fullName>
            </value>
            <value>
                <fullName>Customer Account Deletion</fullName>
            </value>
            <value>
                <fullName>CustomerOrderCertifications</fullName>
                <label>Customer::Order::Certifications</label>
            </value>
            <value>
                <fullName>CustomerOrderDocument</fullName>
                <label>Customer::Order::Document</label>
            </value>
            <value>
                <fullName>Customer Order Question/Issue</fullName>
            </value>
            <value>
                <fullName>DFM</fullName>
            </value>
            <value>
                <fullName>Document Request - NDA</fullName>
            </value>
            <value>
                <fullName>End-use definition</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/EUD_Email_Count__c.field-meta.xml
<CustomField>
    <fullName>EUD_Email_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <description>How many times an EUD email has been tried to be sent</description>
    <label>[EUD] Email Count</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/EUD_Work_Stage__c.field-meta.xml
<CustomField>
    <fullName>EUD_Work_Stage__c</fullName>
    <label>[EUD] Work Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Reach Out Yet</fullName>
                <default>true</default>
                <label>No Reach Out Yet</label>
            </value>
            <value>
                <fullName>1st Attempt Sent</fullName>
            </value>
            <value>
                <fullName>2nd Attempt Sent - WARNING SENT</fullName>
            </value>
            <value>
                <fullName>VI Required</fullName>
            </value>
            <value>
                <fullName>End Use Received</fullName>
            </value>
            <value>
                <fullName>Escalated To Sales</fullName>
            </value>
            <value>
                <fullName>Invoice Sent</fullName>
            </value>
            <value>
                <fullName>Order Cancelled</fullName>
            </value>
            <value>
                <fullName>Sent to FedEx</fullName>
            </value>
            <value>
                <fullName>Shipped without Full End Use</fullName>
            </value>
            <value>
                <fullName>US Partner or Zetwork</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/ShadowXometryOrderID__c.field-meta.xml
<CustomField>
    <fullName>ShadowXometryOrderID__c</fullName>
    <label>Shadow Xometry Order ID</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EUD_EmailOptOut__c.field-meta.xml
<CustomField>
    <fullName>EUD_EmailOptOut__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check the box if this contact would no longer like to receive automated emails about Missing End Use Data.</description>
    <label>EUD Email Opt-Out</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/DailyEUDEmailBatch.cls
global class DailyEUDEmailBatch implements Database.Batchable<sObject>, Database.Stateful, schedulable {
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            [
                SELECT
                    Id,
                    EUD_Work_Stage__c,
                    Category__c,
                    ShadowXometryOrderID__c,
                    Account.EUD_EmailOptOut__c,
                    Contact.EUD_EmailOptOut__c
                FROM Case
                WHERE
                    Category__c = 'End-use definition'
                    AND EUD_Work_Stage__c = 'No Reach Out Yet'
                    AND isClosed = FALSE
                    AND Account.EUD_EmailOptOut__c = FALSE
                    AND Contact.EUD_EmailOptOut__c = FALSE
                    AND EUD_Email_Count__c < 2
            ]
        );
    }

    global void execute(Database.BatchableContext bc, List<Case> scope) {
        Map<ID, String> eudCaseToOrderMap = new Map<ID, String>();
        for (Case c : scope) {
            eudCaseToOrderMap.put(c.Id, c.ShadowXometryOrderID__c);
        }

        OrderERPHandler.sendEUDEmail(eudCaseToOrderMap.keySet());
    }

    global void finish(Database.BatchableContext bc) {
    }

    global void execute(SchedulableContext sc) {
        Database.executebatch(new DailyEUDEmailBatch(), 5);
    }
}