unpackaged/main/default/objects/Account/fields/has_ordered_BinderJetting__c.field-meta.xml
<CustomField>
    <fullName>has_ordered_BinderJetting__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Ordered: Binder Jetting</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/has_ordered_Carbon__c.field-meta.xml
<CustomField>
    <fullName>has_ordered_Carbon__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Ordered: Carbon</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/has_ordered_CNC_Machining__c.field-meta.xml
<CustomField>
    <fullName>has_ordered_CNC_Machining__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Ordered: CNC Machining</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/has_ordered_Direct_Sourced__c.field-meta.xml
<CustomField>
    <fullName>has_ordered_Direct_Sourced__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Ordered: Direct Sourced</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/has_ordered_Extrusion__c.field-meta.xml
<CustomField>
    <fullName>has_ordered_Extrusion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Ordered: Metal Extrusion</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/has_ordered_FDM__c.field-meta.xml
<CustomField>
    <fullName>has_ordered_FDM__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Ordered: FDM</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/has_ordered_PolyJet_3D__c.field-meta.xml
<CustomField>
    <fullName>has_ordered_PolyJet_3D__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Ordered: PolyJet 3D</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/has_ordered_Sheet_metal__c.field-meta.xml
<CustomField>
    <fullName>has_ordered_Sheet_metal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Ordered: Sheet Metal</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/has_ordered_SLS__c.field-meta.xml
<CustomField>
    <fullName>has_ordered_SLS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Ordered: SLS</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/has_ordered_Stamping__c.field-meta.xml
<CustomField>
    <fullName>has_ordered_Stamping__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Ordered: Stamping</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Lifetime_Spend__c.field-meta.xml
<CustomField>
    <fullName>Lifetime_Spend__c</fullName>
    <label>Lifetime Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Number_Orders__c.field-meta.xml
<CustomField>
    <fullName>Number_Orders__c</fullName>
    <label>Lifetime No. of Orders</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Rolling_12_Spend__c.field-meta.xml
<CustomField>
    <fullName>Rolling_12_Spend__c</fullName>
    <inlineHelpText>Rolling 12 months spend for the Account. For example, If  the date is March 2019 the rolling 12 month spend would be all won Opportunities through April 2018 through today.</inlineHelpText>
    <label>Rolling 12 Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/YTDSpend__c.field-meta.xml
<CustomField>
    <fullName>YTDSpend__c</fullName>
    <description>Calculated amount of how much the account has Ordered this Year.</description>
    <inlineHelpText>Sum of Won Opportunities associated to the account.</inlineHelpText>
    <label>YTDSpend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/has_ordered_Die_Casting__c.field-meta.xml
<CustomField>
    <fullName>has_ordered_Die_Casting__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Ordered: Die Casting</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/has_ordered_DMLS__c.field-meta.xml
<CustomField>
    <fullName>has_ordered_DMLS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Ordered: DMLS</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/has_ordered_HPMultiJetFusion__c.field-meta.xml
<CustomField>
    <fullName>has_ordered_HPMultiJetFusion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Ordered: HP Multi Jet Fusion</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/has_ordered_Injection_Molding__c.field-meta.xml
<CustomField>
    <fullName>has_ordered_Injection_Molding__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Ordered: Injection Molding</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Has_Ordered_Other__c.field-meta.xml
<CustomField>
    <fullName>Has_Ordered_Other__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Ordered: Other</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/has_ordered_Other_NotIncluded__c.field-meta.xml
<CustomField>
    <fullName>has_ordered_Other_NotIncluded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Ordered: Other (Not Included)</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/has_ordered_SheetCutting__c.field-meta.xml
<CustomField>
    <fullName>has_ordered_SheetCutting__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Ordered: Sheet Cutting</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/has_ordered_SLA__c.field-meta.xml
<CustomField>
    <fullName>has_ordered_SLA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Ordered: SLA</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Has_Ordered_Tube_Bending__c.field-meta.xml
<CustomField>
    <fullName>Has_Ordered_Tube_Bending__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Ordered: Tube Bending</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Has_Ordered_Tube_Cutting__c.field-meta.xml
<CustomField>
    <fullName>Has_Ordered_Tube_Cutting__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Ordered: Tube Cutting</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/has_ordered_Urethane_Casting__c.field-meta.xml
<CustomField>
    <fullName>has_ordered_Urethane_Casting__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Ordered: Urethane Casting</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Number_Orders__c.field-meta.xml
<CustomField>
    <fullName>Number_Orders__c</fullName>
    <label># of Orders</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Rolling_12_Spend__c.field-meta.xml
<CustomField>
    <fullName>Rolling_12_Spend__c</fullName>
    <label>Rolling 12 Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/has_ordered_BinderJetting__c.field-meta.xml
<CustomField>
    <fullName>has_ordered_BinderJetting__c</fullName>
    <defaultValue>false</defaultValue>
    <label>has_ordered_BinderJetting</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/has_ordered_Carbon__c.field-meta.xml
<CustomField>
    <fullName>has_ordered_Carbon__c</fullName>
    <defaultValue>false</defaultValue>
    <label>has_ordered_Carbon</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/has_ordered_DMLS__c.field-meta.xml
<CustomField>
    <fullName>has_ordered_DMLS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>has_ordered_DMLS</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/has_ordered_HPMultiJetFusion__c.field-meta.xml
<CustomField>
    <fullName>has_ordered_HPMultiJetFusion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>has_ordered_HPMultiJetFusion</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/has_ordered_Injection_Molding__c.field-meta.xml
<CustomField>
    <fullName>has_ordered_Injection_Molding__c</fullName>
    <defaultValue>false</defaultValue>
    <label>has_ordered_Injection_Molding</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/has_ordered_Other__c.field-meta.xml
<CustomField>
    <fullName>has_ordered_Other__c</fullName>
    <defaultValue>false</defaultValue>
    <label>has_ordered_Other</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/has_ordered_SheetCutting__c.field-meta.xml
<CustomField>
    <fullName>has_ordered_SheetCutting__c</fullName>
    <defaultValue>false</defaultValue>
    <label>has_ordered_SheetCutting</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Order_ERP_Xom_ID__c.field-meta.xml
<CustomField>
    <fullName>Order_ERP_Xom_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>The ERP ID for this Order</inlineHelpText>
    <label>Order ID</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/Manufacturing_Services.recordType-meta.xml
<RecordType>
    <fullName>Manufacturing_Services</fullName>
    <active>true</active>
    <businessProcess>Xometry Sales Process</businessProcess>
    <description>Core Services: Instant Quote, Marketplace, etc.</description>
    <label>Manufacturing Services</label>
</RecordType>

unpackaged/main/default/objects/Order_Erp__c/Order_Erp__c.object-meta.xml
<CustomObject>
    <description>This object cotains the orders from Xometry ERP. An order is created in Salesforce when the Order date is populated. 

Technical Note: Quote and Orders are the same object in the source system but seperated in Salesforce as Orders represent the end of the opportunity process.</description>
    <label>Order ERP</label>
    <nameField>
        <displayFormat>Order-{000000}</displayFormat>
        <label>Order Erp Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders ERP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order_Erp__c/fields/AccountID__c.field-meta.xml
<CustomField>
    <fullName>AccountID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Account that the order is placed for.</description>
    <label>AccountID</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Orders_Erp</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/ContactID__c.field-meta.xml
<CustomField>
    <fullName>ContactID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ContactID</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Orders_Erp</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/process_isCarbon__c.field-meta.xml
<CustomField>
    <fullName>process_isCarbon__c</fullName>
    <defaultValue>false</defaultValue>
    <label>process_isCarbon</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/process_isCNC_Machining__c.field-meta.xml
<CustomField>
    <fullName>process_isCNC_Machining__c</fullName>
    <defaultValue>false</defaultValue>
    <label>process_isCNC_Machining</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/process_isDie_Casting__c.field-meta.xml
<CustomField>
    <fullName>process_isDie_Casting__c</fullName>
    <defaultValue>false</defaultValue>
    <label>process_isDie_Casting</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/process_isDMLS__c.field-meta.xml
<CustomField>
    <fullName>process_isDMLS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>process_isDMLS</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/process_isHPMultJetFusion__c.field-meta.xml
<CustomField>
    <fullName>process_isHPMultJetFusion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>process_isHPMultJetFusion</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/process_isInjection_Molding__c.field-meta.xml
<CustomField>
    <fullName>process_isInjection_Molding__c</fullName>
    <defaultValue>false</defaultValue>
    <label>process_isInjection_Molding</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/process_isLSPc__c.field-meta.xml
<CustomField>
    <fullName>process_isLSPc__c</fullName>
    <defaultValue>false</defaultValue>
    <label>process_isLSPc</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/process_isOther__c.field-meta.xml
<CustomField>
    <fullName>process_isOther__c</fullName>
    <defaultValue>false</defaultValue>
    <label>process_isOther</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/process_isOther_NotIncluded__c.field-meta.xml
<CustomField>
    <fullName>process_isOther_NotIncluded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>process_isOther (Not Included)</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/process_isPlasticExtrusion__c.field-meta.xml
<CustomField>
    <fullName>process_isPlasticExtrusion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>process_isPlasticExtrusion</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/process_isPolyJet_3D__c.field-meta.xml
<CustomField>
    <fullName>process_isPolyJet_3D__c</fullName>
    <defaultValue>false</defaultValue>
    <label>process_isPolyJet_3D</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/process_isSheet_metal__c.field-meta.xml
<CustomField>
    <fullName>process_isSheet_metal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>process_isSheet_metal</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/process_isSLA__c.field-meta.xml
<CustomField>
    <fullName>process_isSLA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>process_isSLA</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/process_isSLS__c.field-meta.xml
<CustomField>
    <fullName>process_isSLS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>process_isSLS</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/process_isStamping__c.field-meta.xml
<CustomField>
    <fullName>process_isStamping__c</fullName>
    <defaultValue>false</defaultValue>
    <label>process_isStamping</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/process_isUrethane_Casting__c.field-meta.xml
<CustomField>
    <fullName>process_isUrethane_Casting__c</fullName>
    <defaultValue>false</defaultValue>
    <label>process_isUrethane_Casting</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/recordTypes/Manufacturing_Services.recordType-meta.xml
<RecordType>
    <fullName>Manufacturing_Services</fullName>
    <active>true</active>
    <description>Core Services: Instant Quote, Marketplace, etc.</description>
    <label>Manufacturing Services</label>
</RecordType>

unpackaged/main/default/classes/ordAggUpdates.cls
public with sharing class ordAggUpdates implements Queueable {
    private Set<ID> accountIDSet = new Set<ID>();
    private Set<ID> contactIDSet;
    private Date currentDate;
    private Integer currentMonth;
    private Integer currentYear;
    private Integer previousYear;
    private Integer rollingMonth;
    private Integer rollingYear;
    private Date rollingDate;
    static ID oppManufacturingServRTypeID = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName()
        .get('Manufacturing_Services')
        .getRecordTypeID();
    Map<ID, manufacturingProcesses> contactIDToManuProcMap = new Map<ID, manufacturingProcesses>();

    public ordAggUpdates(List<Order_ERP__C> inOrdersList) {
        this.currentDate = Date.today();
        this.currentMonth = this.currentDate.month();
        this.currentYear = this.currentDate.year();
        this.previousYear = this.currentYear - 1;
        if (this.currentMonth == 12) {
            this.rollingMonth = 1;
            this.rollingYear = this.currentYear;
        } else {
            this.rollingMonth = this.currentMonth + 1;
            this.rollingYear = this.previousYear;
        }
        this.rollingDate = Date.newInstance(this.rollingYear, this.rollingMonth, 1);
        
        for (Order_ERP__C o : inOrdersList) {

            System.debug('We are in the order agg list lets rolls!');
            System.debug(o);
            System.debug('Here is the accountIDOutside!' + o.AccountID__c);

            if (!String.isBlank(o.AccountID__c)) {
                System.debug('Here is the accountID' + o.AccountID__c);
                accountIDSet.add(o.AccountID__c);
            }

            System.debug('We are passed the account');

            if (!String.isblank(o.ContactID__C)) {

                if (!contactIDToManuProcMap.containsKey(o.ContactID__C)) {
                    contactIDToManuProcMap.put(o.ContactID__C, new manufacturingProcesses() );
                }

                manufacturingProcesses lorderManuProcess = contactIDToManuProcMap.get(o.ContactID__C);
                if ( o.process_isCarbon__c == true ) {
                    lorderManuProcess.Carbon = o.process_isCarbon__c;
                }
                if ( o.process_isCNC_Machining__c == true ) {
                    lorderManuProcess.CNC_Machining = o.process_isCNC_Machining__c;
                }
                if ( o.process_isDie_Casting__c == true ) {
                    lorderManuProcess.Die_Casting = o.process_isDie_Casting__c;
                }
                if ( o.process_isDMLS__c == true ) {
                    lorderManuProcess.Direct_Metal_Laser_Sintering = o.process_isDMLS__c;
                }
                if ( o.process_isDirect_Sourced__c == true ) {
                    lorderManuProcess.Direct_Sourced = o.process_isDirect_Sourced__c;
                }
                if ( o.process_isExtrusion__c == true ) {
                    lorderManuProcess.Extrusion = o.process_isExtrusion__c;
                }
                if ( o.process_isFDM__c == true ) {
                    lorderManuProcess.Fused_Deposition_Modeling = o.process_isFDM__c;
                }
                if ( o.process_isHPMultJetFusion__c == true ) {
                    lorderManuProcess.HP_Mult_Jet_Fusion = o.process_isHPMultJetFusion__c;
                }
                if ( o.process_isInjection_Molding__c == true ) {
                    lorderManuProcess.Injection_Molding = o.process_isInjection_Molding__c;
                }
                if ( o.process_isPolyJet_3D__c == true ) {
                    lorderManuProcess.PolyJet_3D = o.process_isPolyJet_3D__c;
                }
                if ( o.process_isPlasticExtrusion__c == true ) {
                    lorderManuProcess.Plastic_Extrusion = o.process_isPlasticExtrusion__c;
                }
                if ( o.process_isSLS__c == true ) {
                    lorderManuProcess.Selective_Laser_Sintering = o.process_isSLS__c;
                }
                if ( o.process_isSheet_metal__c == true ) {
                    lorderManuProcess.Sheet_Metal = o.process_isSheet_metal__c;
                }
                if ( o.process_isSLS__c == true ) {
                    lorderManuProcess.Selective_Laser_Sintering = o.process_isSLS__c;
                }
                if ( o.process_isStamping__c == true ) {
                    lorderManuProcess.Stamping = o.process_isStamping__c;
                }
                if ( o.process_isSLA__c == true ) {
                    lorderManuProcess.Stereolithography = o.process_isSLA__c;
                }
                if ( o.process_isUrethane_Casting__c == true ) {
                    lorderManuProcess.Urethane_Casting = o.process_isUrethane_Casting__c;
                }
                if ( o.process_isBinderJetting__c == true ) {
                    lorderManuProcess.Binder_Jetting = o.process_isBinderJetting__c;
                }
                if ( o.process_isSheetCutting__c == true ) {
                    lorderManuProcess.Sheet_Cutting = o.process_isSheetCutting__c;
                }
                if ( o.process_isTubeBending__c == true ) {
                    lorderManuProcess.Tube_Bending = o.process_isTubeBending__c;
                }
                if ( o.process_isTubeCutting__c == true ) {
                    lorderManuProcess.Tube_Cutting = o.process_isTubeCutting__c;
                }
                if ( o.process_isOther__c == true ) {
                    lorderManuProcess.Other = o.process_isOther__c;
                }
                if ( o.process_isOther_NotIncluded__c == true ) {
                    lorderManuProcess.Other_NotIncluded = o.process_isOther_NotIncluded__c;
                }
                if ( o.process_isLSPc__c == true ) {
                    lorderManuProcess.LSPc = o.process_isLSPc__c;
                }
                if ( o.process_isAssembly__c == true ) {
                    lorderManuProcess.Assembly = o.process_isAssembly__c;
                }  
                contactIDToManuProcMap.put(o.ContactID__C, lorderManuProcess);
            }
        }
    }

    public void execute(QueueableContext context) {
        System.debug('Fetching the contacts');
        //Query Contacts
        Set<ID> contactIDSet = contactIDToManuProcMap.keyset();
        updateAccountInfo(accountIDSet, currentYear, rollingDate);
        updateContacts(contactIDSet, contactIDToManuProcMap);
    }

    private static void updateAccountInfo(Set<ID> accountIDSet, Integer currentYear, Date rollingDate) {
        System.debug('Firing Off the PostOrderAggUpdates execute method!');
        Map<ID, Account> accountsToUpdateMap = new Map<ID, Account>();
        for (ID acctID : accountIDSet) {
            Account a = new Account(ID = acctID);
            accountsToUpdateMap.put(a.ID, a);
        }

        List<Opportunity> lstOpp = [SELECT AccountID, Amount, Order_ERP_Xom_ID__c, closeDate
                                    FROM Opportunity
                                    WHERE
                                        Stagename = 'Closed Won'
                                        AND AccountID IN :accountIDSet
                                        AND RecordTypeId = :oppManufacturingServRTypeID
                                    ORDER BY AccountID];
        
        Map<ID, set<String>> accountMap_orderERP = new Map<ID, set<String>>();
        set<String> setOrderERP;
        for(Opportunity oppRecord : lstOpp)
        {
            ID lID = oppRecord.AccountID;
            Account a = accountsToUpdateMap.get(lID);

            if(!accountMap_orderERP.containsKey(lID))
            {
                setOrderERP = new set<String>();
                accountMap_orderERP.put(lID, setOrderERP);
                a.Lifetime_Spend__c = 0;
                a.YTDSpend__c = 0;
                a.Rolling_12_Spend__c = 0;
            }
            
            setOrderERP.add(oppRecord.Order_ERP_Xom_ID__c);
            a.Lifetime_Spend__c += oppRecord.Amount != null ? oppRecord.Amount : 0;
            a.Number_Orders__c = setOrderERP.size();
            
            //Calculate YTD information
            if(oppRecord.closeDate.year() == currentYear)
            {
                a.YTDSpend__c += oppRecord.Amount != null ? oppRecord.Amount : 0;                
            }
            
            //Calculate Rolling12
            if(oppRecord.closeDate >= rollingDate)
            {
                a.Rolling_12_Spend__c += oppRecord.Amount != null ? oppRecord.Amount : 0;                
            }
            
            accountsToUpdateMap.put(lID, a);
        }
        
        System.debug('About to start the Account Order Updates');
        DatabaseUtilities.saveToDatabase(
            accountsToUpdateMap.values(),
            'postOrderAggUpdates.execute',
            'Account Updates in Execution Queue'
        );
    }

    private static void updateContacts(Set<ID> contactIDSet, Map<ID, manufacturingProcesses> contactIDToManuProcMap) {
        
        List<Contact> contactsToUpdate = new List<Contact>();

        for (Contact c : [
            SELECT
                ID,
                has_ordered_Carbon__c,
                has_ordered_CNC_Machining__c,
                has_ordered_Die_Casting__c,
                has_ordered_Direct_Sourced__c,
                has_ordered_DMLS__c,
                has_ordered_Extrusion__c,
                has_ordered_FDM__c,
                has_ordered_HPMultiJetFusion__c,
                has_ordered_Injection_Molding__c,
                has_ordered_PolyJet_3D__c,
                has_ordered_Sheet_metal__c,
                has_ordered_SLA__c,
                has_ordered_SLS__c,
                has_ordered_Stamping__c,
                has_ordered_Urethane_Casting__c,
                has_ordered_BinderJetting__c,
                has_ordered_SheetCutting__c,
                has_ordered_Tube_Bending__c,
                has_ordered_Tube_Cutting__c,
                has_ordered_Other__c,
                has_ordered_Other_NotIncluded__c,
                has_ordered_LSPc__c,
                has_ordered_Assembly__c
            FROM Contact
            WHERE ID IN :contactIDSet
        ]) {

            if ( contactIDToManuProcMap.containsKey(c.ID) ) {

                Boolean updateRecord = false;
                manufacturingProcesses lorderManuProcess = contactIDToManuProcMap.get(c.ID);
                
                if (c.has_ordered_Carbon__c == false && lorderManuProcess.Carbon == true ) {
                    c.has_ordered_Carbon__c = lorderManuProcess.Carbon;
                    updateRecord = true;
                }
                if (c.has_ordered_CNC_Machining__c == false && lorderManuProcess.CNC_Machining == true ) {
                    c.has_ordered_CNC_Machining__c = lorderManuProcess.CNC_Machining;
                    updateRecord = true;
                }
                if (c.has_ordered_Die_Casting__c == false && lorderManuProcess.Die_Casting == true ) {
                    c.has_ordered_Die_Casting__c = lorderManuProcess.Die_Casting;
                    updateRecord = true;
                }
                if (c.has_ordered_Direct_Sourced__c == false && lorderManuProcess.Direct_Sourced == true ) {
                    c.has_ordered_Direct_Sourced__c = lorderManuProcess.Direct_Sourced;
                    updateRecord = true;
                }
                if (c.has_ordered_DMLS__c == false && lorderManuProcess.Direct_Metal_Laser_Sintering == true ) {
                    c.has_ordered_DMLS__c = lorderManuProcess.Direct_Metal_Laser_Sintering;
                    updateRecord = true;
                }
                if (c.has_ordered_Extrusion__c == false && lorderManuProcess.Extrusion == true ) {
                    c.has_ordered_Extrusion__c = lorderManuProcess.Extrusion;
                    updateRecord = true;
                }
                if (c.has_ordered_FDM__c == false && lorderManuProcess.Fused_Deposition_Modeling == true ) {
                    c.has_ordered_FDM__c = lorderManuProcess.Fused_Deposition_Modeling;
                    updateRecord = true;
                }
                if (c.has_ordered_HPMultiJetFusion__c == false && lorderManuProcess.HP_Mult_Jet_Fusion == true ) {
                    c.has_ordered_HPMultiJetFusion__c = lorderManuProcess.HP_Mult_Jet_Fusion;
                    updateRecord = true;
                }
                if (c.has_ordered_Injection_Molding__c == false && lorderManuProcess.Injection_Molding == true ) {
                    c.has_ordered_Injection_Molding__c = lorderManuProcess.Injection_Molding;
                    updateRecord = true;
                }
                if (c.has_ordered_PolyJet_3D__c == false && lorderManuProcess.PolyJet_3D == true ) {
                    c.has_ordered_PolyJet_3D__c = lorderManuProcess.PolyJet_3D;
                    updateRecord = true;
                }
                if (c.has_ordered_Sheet_metal__c == false && lorderManuProcess.Sheet_Metal == true ) {
                    c.has_ordered_Sheet_metal__c = lorderManuProcess.Sheet_Metal;
                    updateRecord = true;
                }
                if (c.has_ordered_SLA__c == false && lorderManuProcess.Stereolithography == true ) {
                    c.has_ordered_SLA__c = lorderManuProcess.Stereolithography;
                    updateRecord = true;
                }
                if (c.has_ordered_SLS__c == false && lorderManuProcess.Selective_Laser_Sintering == true ) {
                    c.has_ordered_SLS__c = lorderManuProcess.Selective_Laser_Sintering;
                    updateRecord = true;
                }
                if (c.has_ordered_Stamping__c == false && lorderManuProcess.Stamping == true ) {
                    c.has_ordered_Stamping__c = lorderManuProcess.Stamping;
                    updateRecord = true;
                }
                if (c.has_ordered_Urethane_Casting__c == false && lorderManuProcess.Urethane_Casting == true ) {
                    c.has_ordered_Urethane_Casting__c = lorderManuProcess.Urethane_Casting;
                    updateRecord = true;
                }
                if (c.has_ordered_BinderJetting__c == false && lorderManuProcess.Binder_Jetting == true ) {
                    c.has_ordered_BinderJetting__c = lorderManuProcess.Binder_Jetting;
                    updateRecord = true;
                }
                if (c.has_ordered_SheetCutting__c == false && lorderManuProcess.Sheet_Cutting == true ) {
                    c.has_ordered_SheetCutting__c = lorderManuProcess.Sheet_Cutting;
                    updateRecord = true;
                }
                if (c.has_ordered_Tube_Bending__c == false && lorderManuProcess.Tube_Bending == true ) {
                    c.has_ordered_Tube_Bending__c = lorderManuProcess.Tube_Bending;
                    updateRecord = true;
                }
                if (c.has_ordered_Tube_Cutting__c == false && lorderManuProcess.Tube_Cutting == true ) {
                    c.has_ordered_Tube_Cutting__c = lorderManuProcess.Tube_Cutting;
                    updateRecord = true;
                }
                if (c.has_ordered_Other__c == false && lorderManuProcess.Other == true ) {
                    c.has_ordered_Other__c = lorderManuProcess.Other;
                    updateRecord = true;
                }
                if (c.has_ordered_Other_NotIncluded__c == false && lorderManuProcess.Other_NotIncluded == true ) {
                    c.has_ordered_Other_NotIncluded__c = lorderManuProcess.Other_NotIncluded;
                    updateRecord = true;
                }
                if (c.has_ordered_LSPc__c == false && lorderManuProcess.LSPc == true ) {
                    c.has_ordered_LSPc__c = lorderManuProcess.LSPc;
                    updateRecord = true;
                }
                if (c.has_ordered_Assembly__c == false && lorderManuProcess.Assembly == true ) {
                    c.has_ordered_Assembly__c = lorderManuProcess.Assembly;
                    updateRecord = true;
                }

                if( updateRecord ){
                    contactsToUpdate.add(c);
                }
            }
        }
        System.debug('About to start the Contact Order Updates');
        DatabaseUtilities.saveToDatabase(
            contactsToUpdate,
            'contactOrderProcessUpdates.execute',
            'Contact Orders in Execution Queu'
        );
    }
}