unpackaged/main/default/objects/Account/fields/Lifetime_Spend__c.field-meta.xml
<CustomField>
    <fullName>Lifetime_Spend__c</fullName>
    <label>Lifetime Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Number_Orders__c.field-meta.xml
<CustomField>
    <fullName>Number_Orders__c</fullName>
    <label>Lifetime No. of Orders</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Rolling_12_Spend__c.field-meta.xml
<CustomField>
    <fullName>Rolling_12_Spend__c</fullName>
    <inlineHelpText>Rolling 12 months spend for the Account. For example, If  the date is March 2019 the rolling 12 month spend would be all won Opportunities through April 2018 through today.</inlineHelpText>
    <label>Rolling 12 Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Number_of_Open_Opportunities__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Open_Opportunities__c</fullName>
    <label># of Open Opportunities</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Number_Orders__c.field-meta.xml
<CustomField>
    <fullName>Number_Orders__c</fullName>
    <label># of Orders</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Rolling_12_Spend__c.field-meta.xml
<CustomField>
    <fullName>Rolling_12_Spend__c</fullName>
    <label>Rolling 12 Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/YTD_Spend__c.field-meta.xml
<CustomField>
    <fullName>YTD_Spend__c</fullName>
    <label>YTD Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Quick Reference to the Primary Contact on an Opportunity</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities(PC)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/Manufacturing_Services.recordType-meta.xml
<RecordType>
    <fullName>Manufacturing_Services</fullName>
    <active>true</active>
    <businessProcess>Xometry Sales Process</businessProcess>
    <description>Core Services: Instant Quote, Marketplace, etc.</description>
    <label>Manufacturing Services</label>
</RecordType>

unpackaged/main/default/objects/Order_Erp__c/Order_Erp__c.object-meta.xml
<CustomObject>
    <description>This object cotains the orders from Xometry ERP. An order is created in Salesforce when the Order date is populated. 

Technical Note: Quote and Orders are the same object in the source system but seperated in Salesforce as Orders represent the end of the opportunity process.</description>
    <label>Order ERP</label>
    <nameField>
        <displayFormat>Order-{000000}</displayFormat>
        <label>Order Erp Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders ERP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order_Erp__c/recordTypes/Manufacturing_Services.recordType-meta.xml
<RecordType>
    <fullName>Manufacturing_Services</fullName>
    <active>true</active>
    <description>Core Services: Instant Quote, Marketplace, etc.</description>
    <label>Manufacturing Services</label>
</RecordType>

unpackaged/main/default/classes/monthlyContAggReCalcTest.cls
@isTest
private class monthlyContAggReCalcTest {
    @TestSetup
    private static void setup() {
        ID oppManufacturingServRTypeID = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName()
            .get('Manufacturing_Services')
            .getRecordTypeID();
        List<Account> testAccountList = TestDataFactory.createTestAccountNonGenerics(2, 'AM', 3);
        Account testAccount = testAccountList[0];
        ID testAccountID = testAccount.ID;
        List<Order_ERP__C> newOrdersList = new List<Order_ERP__C>();
        List<Contact> myretContactList = [
            SELECT Id, FirstName, LastName, Email
            FROM Contact
            WHERE AccountID = :testAccountID
            ORDER BY Name
        ];
        Date myDate = Date.today();
        Datetime myDateTime = Datetime.now();
        Contact contact1 = myretContactList[0];
        Contact contact2 = myretContactList[1];
        Opportunity testOpp = new Opportunity();
        testOpp.RecordTypeId = oppManufacturingServRTypeID;
        testOpp.Name = 'Test';
        testOpp.Primary_Contact__c = contact1.Id;
        testOpp.AccountId = testAccount.Id;
        testOpp.Amount = 10000;
        testOpp.StageName = 'Open';
        testOpp.CloseDate = Date.today();
        insert testOpp;

        Order_ERP__C order1 = TestDataFactory.createOrderERPFromAccContact(
            false,
            'Q00-0000-0001',
            'BBBBB-34567',
            '56564-55667',
            testAccount,
            contact1,
            myDate,
            myDateTime
        );
        newOrdersList.add(order1);

        Order_ERP__C order2 = TestDataFactory.createOrderERPFromAccContact(
            false,
            'Q00-0000-0002',
            'BBBBB-34568',
            '56564-55668',
            testAccount,
            contact1,
            myDate,
            myDateTime
        );
        newOrdersList.add(order2);
        insert newOrdersList;
    }

    @isTest
    private static void monthlyAggTest() {
        Test.startTest();
        monthlyContAggReCalc batch = new monthlyContAggReCalc();
        Database.executeBatch(batch);
        Test.stopTest();
        Contact testContact = [
            SELECT
                Id,
                YTD_Spend__c,
                Rolling_12_Spend__c,
                Number_of_Open_Opportunities__c,
                Lifetime_Spend__c,
                Number_Orders__c
            FROM Contact
            LIMIT 1
        ];
        System.assertEquals(10000, testContact.YTD_Spend__c, 'YTD_Spend__c was wrong');
        System.assertEquals(10000, testContact.Rolling_12_Spend__c, 'Rolling_12_Spend__c was wrong');
        System.assertEquals(10000, testContact.Lifetime_Spend__c, 'Lifetime_Spend__c was wrong');
        System.assertEquals(2, testContact.Number_Orders__c, 'Number_Orders__c was wrong');
        System.assertEquals(
            1,
            testContact.Number_of_Open_Opportunities__c,
            'Number_of_Open_Opportunities__c was wrong'
        );
    }
}