unpackaged/main/default/objects/Account/fields/Lifetime_Spend__c.field-meta.xml
<CustomField>
    <fullName>Lifetime_Spend__c</fullName>
    <label>Lifetime Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Rolling_12_Spend__c.field-meta.xml
<CustomField>
    <fullName>Rolling_12_Spend__c</fullName>
    <inlineHelpText>Rolling 12 months spend for the Account. For example, If  the date is March 2019 the rolling 12 month spend would be all won Opportunities through April 2018 through today.</inlineHelpText>
    <label>Rolling 12 Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Rolling_12_Spend__c.field-meta.xml
<CustomField>
    <fullName>Rolling_12_Spend__c</fullName>
    <label>Rolling 12 Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/YTD_Spend__c.field-meta.xml
<CustomField>
    <fullName>YTD_Spend__c</fullName>
    <label>YTD Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/Order_Erp__c.object-meta.xml
<CustomObject>
    <description>This object cotains the orders from Xometry ERP. An order is created in Salesforce when the Order date is populated. 

Technical Note: Quote and Orders are the same object in the source system but seperated in Salesforce as Orders represent the end of the opportunity process.</description>
    <label>Order ERP</label>
    <nameField>
        <displayFormat>Order-{000000}</displayFormat>
        <label>Order Erp Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders ERP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/classes/monthlyContactAggReCalcScheduleTest.cls
@isTest
global class monthlyContactAggReCalcScheduleTest {
    @isTest
    static void monthlyAggSchedTest1() {
        //Integer
        List<Account> testAccountList = TestDataFactory.createTestAccountNonGenerics(2, 'AM', 3);
        Account testAccount = testAccountList[0];
        ID testAccountID = testAccount.ID;
        //
        List<Order_ERP__C> newOrdersList = new List<Order_ERP__C>();
        List<Contact> myretContactList = [
            SELECT ID, FirstName, LastName, Email
            FROM Contact
            WHERE AccountID = :testAccountID
            ORDER BY Name
        ];
        Date myDate = Date.today();
        Datetime myDateTime = Datetime.now();
        //Create two orders for contact1
        //Create one order for contact2
        //Create zero orders for contact3
        Contact contact1 = myretContactList[0];

        Order_ERP__C order1 = TestDataFactory.createOrderERPFromAccContact(
            false,
            'Q00-0000-0001',
            'BBBBB-34567',
            '56564-55667',
            testAccount,
            contact1,
            myDate,
            myDateTime
        );
        Order_ERP__C order2 = TestDataFactory.createOrderERPFromAccContact(
            false,
            'Q00-0000-0002',
            'BBBBB-34568',
            '56564-55668',
            testAccount,
            contact1,
            myDate,
            myDateTime
        );
        newOrdersList.add(order1);
        newOrdersList.add(order2);
        insert newOrdersList;

        String CRON_EXP = '0 0 0 1 1 ? *';
        // String jobID = System.schedule('MonthlyConAggCalcSchedTest', CRON_EXP, new monthlyAggCalcSchedule());
        String jobID = System.schedule('MonthlyConAggCalcSchedTest', CRON_EXP, new monthlyContAggReCalcSchedule());
        Test.startTest();
        Test.stopTest();
        Contact retContact = [
            SELECT ID, Lifetime_Spend__c, Rolling_12_Spend__c, YTD_Spend__c
            FROM Contact
            WHERE ID = :contact1.ID
        ];
        System.debug(
            'The total spending for Contact 1 is  LifeTime_Spend__C : ' +
            retContact.LifeTime_Spend__C +
            ' YTD_Spend__C : ' +
            retContact.YTD_Spend__C
        );
    }
}