unpackaged/main/default/objects/Account/fields/YTDSpend__c.field-meta.xml
<CustomField>
    <fullName>YTDSpend__c</fullName>
    <description>Calculated amount of how much the account has Ordered this Year.</description>
    <inlineHelpText>Sum of Won Opportunities associated to the account.</inlineHelpText>
    <label>YTDSpend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Loss_Reason__c.field-meta.xml
<CustomField>
    <fullName>Loss_Reason__c</fullName>
    <label>Loss Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No Response</fullName>
            </value>
            <value>
                <fullName>No Bid</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Lead Time</fullName>
            </value>
            <value>
                <fullName>Service Concerns</fullName>
            </value>
            <value>
                <fullName>Project Canceled</fullName>
            </value>
            <value>
                <fullName>Purchasing from Different Opportunity</fullName>
            </value>
            <value>
                <fullName>On-Demand Competition</fullName>
            </value>
            <value>
                <fullName>Local Competition</fullName>
            </value>
            <value>
                <fullName>Budgetary</fullName>
            </value>
            <value>
                <fullName>Late quote</fullName>
            </value>
            <value>
                <fullName>Customer Made In-House</fullName>
            </value>
            <value>
                <fullName>Ordered Online</fullName>
                <label>Ordered Online - Supply Record Only</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/Order_Erp__c.object-meta.xml
<CustomObject>
    <description>This object cotains the orders from Xometry ERP. An order is created in Salesforce when the Order date is populated. 

Technical Note: Quote and Orders are the same object in the source system but seperated in Salesforce as Orders represent the end of the opportunity process.</description>
    <label>Order ERP</label>
    <nameField>
        <displayFormat>Order-{000000}</displayFormat>
        <label>Order Erp Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders ERP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order_Erp__c/fields/Order_Canceled_Flag__c.field-meta.xml
<CustomField>
    <fullName>Order_Canceled_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>A flag that shows that an order has been canceled.</description>
    <label>Order Canceled Flag</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/monthlyAggCalcScheduleTest.cls
@isTest
public class monthlyAggCalcScheduleTest {
    @isTest
    static void monthlyTest1() {
        System.debug('Starting the schedule test');

        User objUser = [
            SELECT Id
            FROM User
            WHERE
                Id IN (SELECT AssigneeId FROM PermissionSetAssignment WHERE PermissionSet.Label = 'Ignore All VR')
                AND IsActive = TRUE
            LIMIT 1
        ];

        System.runAs(objUser) {
            //Integer
            List<Account> testAccountList = TestDataFactory.createTestAccountNonGenerics(2, 'AM', 1);
            Account testAccount = testAccountList[0];
            ID testAccountID = testAccount.ID;
            //
            List<Order_ERP__C> newOrdersList = new List<Order_ERP__C>();
            Contact myretContact = [
                SELECT ID, FirstName, LastName, Email
                FROM Contact
                WHERE AccountID = :testAccountID
                ORDER BY Name
            ];
            ID myretContactID = myretContact.ID;
            List<Order_ERP__C> insertOrdersList = new List<Order_ERP__C>();
            Date myDate = Date.today();
            Datetime myDateTime = Datetime.now();

            //Different Name Should Create new Opportunity on Existing BDR Account
            Order_ERP__C ord = TestDataFactory.createOrderERPFromAccContact(
                false,
                'Q00-0000-0000',
                'BBBBB-34567',
                '56564-55667',
                testAccount,
                myretContact,
                myDate,
                myDateTime
            );
            insertOrdersList.add(ord);

            //Different Name Should Create new Opportunity on Existing BDR Account
            Order_ERP__C ord1 = TestDataFactory.createOrderERPFromAccContact(
                false,
                'Q00-0000-0001',
                'BBBBB-34568',
                '56564-55668',
                testAccount,
                myretContact,
                myDate,
                myDateTime
            );
            insertOrdersList.add(ord1);

            //Different Name Should Create new Opportunity on Existing BDR Account
            Order_ERP__C ord2 = TestDataFactory.createOrderERPFromAccContact(
                false,
                'Q00-0000-0002',
                'BBBBB-34569',
                '56564-55669',
                testAccount,
                myretContact,
                myDate,
                myDateTime
            );
            insertOrdersList.add(ord2);
            insert insertOrdersList;

            ord2.Order_Canceled_Flag__c = true;
            List<Opportunity> myOpps = [
                SELECT Id, Stagename, Amount, AccountID
                FROM Opportunity
                WHERE AccountID = :testAccountID
            ];
            Opportunity myOpp = myOpps[0];
            myOpp.Stagename = 'Closed Lost';
            myOpp.Loss_Reason__c = 'Order Cancelled';
            update myOpp;
            Account resAcct = [SELECT ID, YTDSpend__c FROM Account WHERE ID = :testAccountID];
            System.debug('The initial YTDSpend__C is: ' + resAcct.YTDSpend__c);
            // Dummy CRON expression: midnight on March 15.
            // Because this is a test, job executes
            // immediately after test stop test
            String CRON_EXP = '0 0 0 1 1 ? *';
            Test.startTest();
            System.debug('Here are the opportunities and their stages');
            myOpps = [SELECT Id, Stagename, Amount, AccountID FROM Opportunity WHERE AccountID = :testAccountID];
            for (Opportunity o : myOpps) {
                system.debug(o);
            }
            String jobID = System.schedule('MonthlyAggCalcSchedTest', CRON_EXP, new monthlyAggCalcSchedule());
            Test.stopTest();
            //Test Jobs Fire after job is run
            resAcct = [SELECT ID, YTDSpend__c FROM Account WHERE ID = :testAccountID];
            Decimal expRes = 10000.00;
            Decimal myamount = resAcct.YTDSpend__c;
            System.assertequals(expRes, myamount, 'The amounts are not equal');
        }

    }
}