unpackaged/main/default/objects/Lead/fields/Last_Quote_Xometry_ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>Last_Quote_Xometry_ERP_ID__c</fullName>
    <externalId>true</externalId>
    <label>Quote ID</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Last_Quote_Xometry_ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>Last_Quote_Xometry_ERP_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>The Last Quote associated to this Opportunity</inlineHelpText>
    <label>Quote ID</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <label>Line of Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Line_of_Business</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Quick Reference to the Primary Contact on an Opportunity</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities(PC)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/Quote_ERP__c.object-meta.xml
<CustomObject>
    <description>A quote that is sent over from ERP</description>
    <label>Quote ERP</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote_ERP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes ERP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Quote_ERP__c/fields/AccountID__c.field-meta.xml
<CustomField>
    <fullName>AccountID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Account that the quote belongs to</description>
    <label>AccountID</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Quotes_ERP</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/ContactID__c.field-meta.xml
<CustomField>
    <fullName>ContactID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Contact</description>
    <label>ContactID</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Quotes_ERP</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/LeadID__c.field-meta.xml
<CustomField>
    <fullName>LeadID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the lead a quote is associated with</description>
    <label>LeadID</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>Quotes_ERP</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <label>Line of Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Line_of_Business</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/OpportunityID__c.field-meta.xml
<CustomField>
    <fullName>OpportunityID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the related opportunity</description>
    <label>OpportunityID</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Quotes_ERP</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Xometry_ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>Xometry_ERP_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Unique Qoute ID created in Xometry ERP</description>
    <externalId>true</externalId>
    <label>Quote ID</label>
    <length>13</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/globalValueSets/Line_of_Business.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Instant Quote</fullName>
    </customValue>
    <customValue>
        <fullName>Marketplace</fullName>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <masterLabel>Line of Business</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/leadConverterCustom.cls
public with sharing class leadConverterCustom {
    static final String DEFAULT_LINE_OF_BUSINESS = 'Instant Quote';
    /**
     * @description When a lead is converted, update the quote of origin
     * @param inConvertedLeadList list of leads converted
     */
    @InvocableMethod(label='Lead Convert Update Quote' description='Update Quotes with Lead Convert Information')
    public static void LeadConvertUpdateQuote(List<Lead> inConvertedLeadList) {
        Set<ID> inConvertedLeadIDSet = new Set<ID>();
        Map<ID, Lead> convertedLeadMap = new Map<Id, Lead>();
        Set<ID> inConvertedOpportunityIDSet = new Set<ID>();
        Set<ID> inConvertedContactIDSet = new Set<ID>();
        Map<ID, ID> oppToContactMap = new Map<ID, ID>();
        Map<ID, String> oppToLOBMap = new Map<ID, String>();
        for (Lead l : inConvertedLeadList) {
            inConvertedLeadIDSet.add(l.id);
            convertedLeadMap.put(l.id, l);
            if (!String.isblank(l.ConvertedContactId) && !String.isblank(l.ConvertedOpportunityId)) {
                oppToContactMap.put(l.ConvertedOpportunityId, l.ConvertedContactId);
                inConvertedOpportunityIDSet.add(l.ConvertedOpportunityId);
            }
        }

        List<Quote_ERP__C> existingQuoteList = [
            SELECT ID, LeadID__C, Xometry_ERP_ID__C, Line_of_Business__c
            FROM Quote_ERP__C
            WHERE LeadID__C IN :inConvertedLeadIDSet
        ];
        SET<Quote_ERP__C> quoteToUpDateSET = new Set<Quote_ERP__C>();
        List<Quote_ERP__C> quoteToUpDateList = new List<Quote_ERP__C>();

        Integer i = 0;
        if (!existingQuoteList.isEmpty()) {
            for (Quote_ERP__C q : existingQuoteList) {
                i = i + 1;
                System.debug('Outside matching quote to opp make : ' + i);
                if (convertedLeadMap.containsKey(q.LeadID__C)) {
                    Lead l = convertedLeadMap.get(q.LeadID__C);
                    q.AccountID__c = l.ConvertedAccountId;
                    System.debug('The Quotes Xom id is : ' + q.Xometry_ERP_ID__C);
                    System.debug('The Leads las Xom id is : ' + l.Last_Quote_Xometry_ERP_ID__C);
                    if (q.Xometry_ERP_ID__C == l.Last_Quote_Xometry_ERP_ID__C) {
                        System.debug('Inside matching quote to opp maker : ' + i);
                        q.OpportunityID__c = l.ConvertedOpportunityId;
                        if (String.isNotBlank(q.Line_of_Business__c)) {
                            oppToLOBMap.put(l.ConvertedOpportunityId, q.Line_of_Business__c);
                        }
                    }

                    q.ContactID__c = l.ConvertedContactId;
                    quoteToUpDateSET.add(q);
                }
            }
        }
        quoteToUpDateList.addAll(quoteToUpDateSET);
        System.debug('Starting the Quote Updates');
        System.debug('The size of the Quotes to Update is ' + quoteToUpDateList.size());
        DatabaseUtilities.saveToDatabase(
            quoteToUpDateList,
            'leadConverterCustom.LeadConvertUpdateQuote',
            'Quote Updates after Lead Conversion'
        );

        List<Opportunity> updateOptList = new List<Opportunity>();
        //Update the Primary Contact
        for (ID mID : inConvertedOpportunityIDSet) {
            Opportunity opp = new Opportunity();
            opp.ID = mID;
            opp.Primary_Contact__c = oppToContactMap.get(mID);
            if (oppToLOBMap.containsKey(mID)) {
                opp.Line_of_Business__c = oppToLOBMap.get(mID);
            } else {
                opp.Line_of_Business__c = DEFAULT_LINE_OF_BUSINESS;
            }
            updateOptList.add(opp);
        }

        System.debug('Starting the Opportunity Updates');
        System.debug('The size of the Opportunity to Update is ' + updateOptList.size());
        DatabaseUtilities.saveToDatabase(
            updateOptList,
            'leadConverterCustom.LeadConvertUpdateQuote',
            'Opportunity Updates after Lead Conversion'
        );
    }
}