unpackaged/main/default/objects/Case/fields/AcceptedJobID__c.field-meta.xml
<CustomField>
    <fullName>AcceptedJobID__c</fullName>
    <label>Accepted Job ID</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Job ID Associated with the Case</description>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/PreviousJobsList__c.field-meta.xml
<CustomField>
    <fullName>PreviousJobsList__c</fullName>
    <label>Previous Jobs List</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>GNO Jobs</description>
    <label>Job</label>
    <nameField>
        <label>Job ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/XometryJobID__c.field-meta.xml
<CustomField>
    <fullName>XometryJobID__c</fullName>
    <externalId>true</externalId>
    <label>Xometry Job ID</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/XometryOpsOrderID__c.field-meta.xml
<CustomField>
    <fullName>XometryOpsOrderID__c</fullName>
    <label>Xometry Ops Order ID</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/UpdateSourcingCasesTest.cls
@isTest
private class UpdateSourcingCasesTest {

    @isTest(seeAllData=false)
    static void executeTest() {

        String firstXomJobID = 'J0000001';
        String secondXomJobID = 'J0000002';
        String opsOrderID = '00000-00001';

        Job__c firstJob = new Job__c();
        firstJob.XometryJobID__c = firstXomJobID;
        firstJob.XometryOpsOrderID__c = opsOrderID;
        insert firstJob;

        Case c = new Case();
        c.RecordTypeID = AppConstants.caseSourcingRTypeId;
        c.AcceptedJobID__c = firstXomJobID;
        c.Job__c = firstJob.Id;
        insert c;

        Job__c secondJob = new Job__c();
        secondJob.XometryOpsOrderID__c = opsOrderID;
        secondJob.XometryJobID__c = secondXomJobID;
        insert secondJob;

        c.PreviousJobsList__c = firstXomJobID + ', ' + secondXomJobID;
        update c;

        Test.startTest();

        Database.executeBatch( new UpdateSourcingCasesBatch() );

        Test.stopTest();

        Case resultCase = [SELECT ID, AcceptedJobID__c, Job__c FROM Case WHERE Id = :c.Id];

        System.assertEquals(secondJob.Id, resultCase.Job__c, 'The old job is still associated to the case');

    }

    @isTest(seeAllData=false)
    static void scheduleTest() {
        // Seconds Minutes Hours Day_of_month Month Day_of_week optional_year
        String CRON_EXP = '0 0 1 * * ?';

        Test.startTest();
        String jobID = System.schedule('UpdateSourcingCasesScheduleTest', CRON_EXP, new UpdateSourcingCasesSchedule());
        Test.stopTest();

        System.assertNotEquals(null, jobID, 'Job id is null');

    }

}