unpackaged/main/default/objects/Case/fields/AttachmentStatus__c.field-meta.xml
<CustomField>
    <fullName>AttachmentStatus__c</fullName>
    <label>Attachment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None Submitted</fullName>
            </value>
            <value>
                <fullName>Pending Upload</fullName>
            </value>
            <value>
                <fullName>Upload Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/GNOOrder__c.field-meta.xml
<CustomField>
    <fullName>GNOOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Ops_Order__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Job ID Associated with the Case</description>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Job_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Number__c</fullName>
    <description>Created During PSE Service Migration Project</description>
    <label>Job Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/OrderID__c.field-meta.xml
<CustomField>
    <fullName>OrderID__c</fullName>
    <label>Order ID</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/POD__c.field-meta.xml
<CustomField>
    <fullName>POD__c</fullName>
    <label>POD</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Albatrosses</fullName>
            </value>
            <value>
                <fullName>Atomic Rocks</fullName>
            </value>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Rocket Power</fullName>
            </value>
            <value>
                <fullName>SpaceTechs</fullName>
            </value>
            <value>
                <fullName>Triple Threat</fullName>
            </value>
            <value>
                <fullName>Amazing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Supplier__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/ThirdPartyCreationID__c.field-meta.xml
<CustomField>
    <fullName>ThirdPartyCreationID__c</fullName>
    <label>Third Party Creation ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Who_In_Pod__c.field-meta.xml
<CustomField>
    <fullName>Who_In_Pod__c</fullName>
    <description>Used to case assist in case routing from workcenter.</description>
    <label>Who In Pod</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Work_Center_Category__c.field-meta.xml
<CustomField>
    <fullName>Work_Center_Category__c</fullName>
    <label>Work Center Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Print/CAD discrepancy</fullName>
            </value>
            <value>
                <fullName>Can I substitute?</fullName>
            </value>
            <value>
                <fullName>Where is the customer supplied material/inserts?</fullName>
            </value>
            <value>
                <fullName>I'm not sure what my requirements are.</fullName>
            </value>
            <value>
                <fullName>Where is the report/template/drawing?</fullName>
            </value>
            <value>
                <fullName>How should I ship this?</fullName>
            </value>
            <value>
                <fullName>I have a freight shipment.</fullName>
            </value>
            <value>
                <fullName>DFM Question</fullName>
            </value>
            <value>
                <fullName>Production/Build Question</fullName>
            </value>
            <value>
                <fullName>Finishing Question</fullName>
            </value>
            <value>
                <fullName>Delayed</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Can I Cancel This Job</fullName>
            </value>
            <value>
                <fullName>Can't Find it / Substitution Request</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/recordTypes/CaseMgmt.recordType-meta.xml
<RecordType>
    <fullName>CaseMgmt</fullName>
    <active>true</active>
    <businessProcess>Cmgmt Process</businessProcess>
    <description>Order Management Issue for the Case Managers</description>
    <label>Case Mgmt</label>
</RecordType>

unpackaged/main/default/objects/Case/recordTypes/DFM_Case.recordType-meta.xml
<RecordType>
    <fullName>DFM_Case</fullName>
    <active>true</active>
    <businessProcess>DFM Support Process</businessProcess>
    <description>Post Order DFM review</description>
    <label>DFM Case</label>
</RecordType>

unpackaged/main/default/objects/Case/recordTypes/VQC_Case.recordType-meta.xml
<RecordType>
    <fullName>VQC_Case</fullName>
    <active>true</active>
    <businessProcess>VQC Support Process</businessProcess>
    <description>Quality Team</description>
    <label>VQC Case</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Supplier__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>GNO Jobs</description>
    <label>Job</label>
    <nameField>
        <label>Job ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/OrderID__c.field-meta.xml
<CustomField>
    <fullName>OrderID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Order associated with this job</description>
    <label>Order ID</label>
    <referenceTo>Ops_Order__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Supplier__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/XometryJobID__c.field-meta.xml
<CustomField>
    <fullName>XometryJobID__c</fullName>
    <externalId>true</externalId>
    <label>Xometry Job ID</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/XometryOpsOrderID__c.field-meta.xml
<CustomField>
    <fullName>XometryOpsOrderID__c</fullName>
    <label>Xometry Ops Order ID</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Ops_Order__c/Ops_Order__c.object-meta.xml
<CustomObject>
    <description>Order object for the GNO Team. Used for purposes of tracking orders and jobs.</description>
    <label>Ops Order</label>
    <nameField>
        <label>Ops Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ops Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Ops_Order__c/fields/POD__c.field-meta.xml
<CustomField>
    <fullName>POD__c</fullName>
    <label>POD</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Albatrosses</fullName>
            </value>
            <value>
                <fullName>Atomic Rocks</fullName>
            </value>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>First Impressions</fullName>
            </value>
            <value>
                <fullName>Impodsters</fullName>
            </value>
            <value>
                <fullName>Rocket Power</fullName>
            </value>
            <value>
                <fullName>SpaceTechs</fullName>
            </value>
            <value>
                <fullName>Triple Threat</fullName>
            </value>
            <value>
                <fullName>Amazing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Ops_Order__c/fields/XometryOpsOrderID__c.field-meta.xml
<CustomField>
    <fullName>XometryOpsOrderID__c</fullName>
    <externalId>true</externalId>
    <label>Xometry Ops Order ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Supplier__c/Supplier__c.object-meta.xml
<CustomObject>
    <label>Supplier</label>
    <nameField>
        <label>﻿Partner ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Supplier__c/fields/ContactID__c.field-meta.xml
<CustomField>
    <fullName>ContactID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ContactID</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Suppliers</relationshipLabel>
    <relationshipName>Suppliers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Supplier__c/fields/PartnerID__c.field-meta.xml
<CustomField>
    <fullName>PartnerID__c</fullName>
    <externalId>true</externalId>
    <label>Partner ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/XomEndpoint_WorkcenterFormSubmission_V2.cls
/**
 * @description Integration for workcenter center forms.
 */
@RestResource(UrlMapping='/WorkcenterFormSubmission/v2/*')
global class XomEndpoint_WorkcenterFormSubmission_V2 {
    global class XomEndpoint_WorkcenterFormSubmission_V2Exception extends Exception { }
    global class FormDataField {

        String key { get; set; }
        String value { get; set; }
        String type { get; set; }
        public FormDataField() { }
        public FormDataField(String key, String value, String type) {
            this.key = key;
            this.value = value;
            this.type = type;
        }
    }

    global class FormResponse {
        public String CaseNumber;
        public String CaseId;

        public FormResponse(String CaseId, String CaseNumber) {
            this.CaseId = CaseId;
            this.CaseNumber = CaseNumber;
        }
    }

    @HttpPost
    /**
     * @description Used for form submission
     * @param email Email to be used as the contact on the case
     * @param formId Third party id for reference
     * @param origin Where the form is being submitted
     * @param type The type of submission and will be used for routing
     * @param partnerId The id of the partner that should be linked to the case
     * @param jobId The id of the job that should be linked to the case
     * @param subject The subject for the case
     * @param attachmentStatus Determines if files are pending or none needed
     * @param recordTypeName The Developer Name of the record type for the case
     * @param category The workcenter category
     * @param whoInPod Role of the person handling the request within the pod
     * @param otherFields A list is other form data fields that are not required
     */
    global static XomEndpoint_WorkcenterFormSubmission_V2.FormResponse createCaseFromSubmission(
            String email,
            String formId,
            String origin,
            String type,
            String partnerId,
            String jobId,
            String subject,
            String attachmentStatus,
            String recordTypeName,
            String category,
            String whoInPod,
            List<XomEndpoint_WorkcenterFormSubmission_V2.FormDataField> otherFields
    ) {
        try{
            System.debug('Request headers: ' + RestContext.request.headers);
            System.debug('Request method: ' + RestContext.request.httpMethod);
            System.debug('Request parameters: ' + RestContext.request.params);
            System.debug('Request remote address: ' + RestContext.request.remoteAddress);
            System.debug('Request body: ' + RestContext.request.requestBody);
            System.debug('Request requestURI: ' + RestContext.request.requestURI);
            System.debug('Request resourcePath: ' + RestContext.request.resourcePath);
            System.debug('email: ' + email);
            System.debug('formId: ' + formId);
            System.debug('origin: ' + origin);
            System.debug('type: ' + type);
            System.debug('partnerId: ' + partnerId);
            System.debug('jobId: ' + jobId);
            System.debug('subject: ' + subject);
            System.debug('attachmentStatus: ' + attachmentStatus);
            System.debug('recordTypeName: ' + recordTypeName);
            System.debug('category: ' + category);
            System.debug('Who In Pod: ' + whoInPod);
            Case cse
                = createCase(email,formId,origin,type,partnerId,jobId,subject,
                             attachmentStatus,recordTypeName,category,whoInPod,
                             otherFields);
            System.debug('>>>>> Case Id: ' + cse.Id);
            return new FormResponse(cse.Id,cse.CaseNumber);
        }
        catch (Exception e) {
            throw new XomEndpoint_WorkcenterFormSubmission_V2Exception(e);
        }
    }


    private static Case createCase(
        String email,
        String formId,
        String origin,
        String type,
        String partnerId,
        String jobId,
        String subject,
        String attachmentStatus,
        String recordTypeName,
        String category,
        String whoInPod,
        List<XomEndpoint_WorkcenterFormSubmission_V2.FormDataField> otherFields)
    {
        Case cse = new Case(
            SuppliedEmail = email,
            ThirdPartyCreationID__c = formId,
            Origin = origin,
            Type = type,
            Job_Number__c = jobId,
            Subject = subject,
            AttachmentStatus__c = attachmentStatus,
            RecordTypeId
                = recordTypeName == 'VQC_Case'
                ? getCaseRecordTypeByDevName(recordTypeName)
                : getCaseRecordTypeByPod(whoInPod)
        );
        if(String.isNotBlank(category)){
            cse.Work_Center_Category__c = category;
        }
        if(String.isNotBlank(whoInPod)){
            cse.Who_In_Pod__c = whoInPod;
        }
        if (!String.isBlank(partnerId)) {
            List<Supplier__c> suppliers
                    = [SELECT Id, ContactID__c FROM Supplier__c WHERE PartnerID__c = :partnerId];
            if (!suppliers.isEmpty()) {
                Supplier__c s = suppliers[0];
                cse.Supplier__c = s.Id;
                cse.ContactId = s.ContactID__c;
            }
        }
        if (!String.isBlank(jobId)) {
            List<Job__c> jobs =
            [SELECT Id, OrderID__c, OrderID__r.POD__c, XometryOpsOrderID__c
            FROM Job__c
            WHERE XometryJobID__c = :jobId];
            if (!jobs.isEmpty()) {
                Job__c job = jobs[0];
                cse.Job__c = job.Id;
                cse.GNOOrder__c = job.OrderID__c;
                cse.OrderID__c = job.XometryOpsOrderID__c;
                if(job.OrderID__c!=null && String.isNotBlank(job.OrderID__r.POD__c)){
                    cse.POD__c = job.OrderID__r.POD__c;
                }
            }
        }
        // Loop through other fields
        if (!otherFields.isEmpty()) {
            for (FormDataField otherField : otherFields) {
                if (otherField.type.toLowerCase() == 'date') {
                    Date newValue = Date.valueOf(otherField.value);
                    cse.put(otherField.key, newValue);
                } else if (otherField.type.toLowerCase() == 'boolean') {
                    Boolean newValue = Boolean.valueOf(otherField.value);
                    cse.put(otherField.key, newValue);
                } else {
                    if(otherField.key.toLowerCase() == 'description')
                    {
                        if(subject.contains(':'))
                        {
                            String strTopic = subject.split(': ')[1];
                            otherField.value = otherField.value.replace('Topic: '+strTopic, 'Topic: '+strTopic+'\nDetails:');
                        }
                        otherField.value = otherField.value.replace('Topic:','\nTopic:');
                    }
                    cse.put(otherField.key, otherField.value);
                }
            }
        }

        Database.DMLOptions dmlOpts = new Database.DMLOptions();
        dmlOpts.assignmentRuleHeader.assignmentRuleId = [
                SELECT Id
                FROM AssignmentRule
                WHERE SobjectType = 'Case' AND Active = TRUE LIMIT 1].Id;
        cse.setOptions(dmlOpts);
        insert cse;

        return [SELECT Id, CaseNumber FROM Case WHERE Id = :cse.Id];
    }

    private static Id getCaseRecordTypeByPod(String whoInPod) {
        String recordTypeDevName;
        switch on whoInPod {
            when 'CM' {
                recordTypeDevName = 'CaseMgmt';
            }
            when 'POD/DFM' {
                recordTypeDevName = 'DFM_Case';
            }
        }
        return getCaseRecordTypeByDevName(recordTypeDevName);
    }

    private static Id getCaseRecordTypeByDevName(String recordTypeDevName) {
        return Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName()
                .get(recordTypeDevName)
                .getRecordTypeId();
    }

}