unpackaged/main/default/objects/Case/fields/AttachmentStatus__c.field-meta.xml
<CustomField>
    <fullName>AttachmentStatus__c</fullName>
    <label>Attachment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None Submitted</fullName>
            </value>
            <value>
                <fullName>Pending Upload</fullName>
            </value>
            <value>
                <fullName>Upload Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/GNOOrder__c.field-meta.xml
<CustomField>
    <fullName>GNOOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Ops_Order__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Job ID Associated with the Case</description>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Job_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Number__c</fullName>
    <description>Created During PSE Service Migration Project</description>
    <label>Job Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/OrderID__c.field-meta.xml
<CustomField>
    <fullName>OrderID__c</fullName>
    <label>Order ID</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Supplier__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/ThirdPartyCreationID__c.field-meta.xml
<CustomField>
    <fullName>ThirdPartyCreationID__c</fullName>
    <label>Third Party Creation ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Supplier__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>GNO Jobs</description>
    <label>Job</label>
    <nameField>
        <label>Job ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/OrderID__c.field-meta.xml
<CustomField>
    <fullName>OrderID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Order associated with this job</description>
    <label>Order ID</label>
    <referenceTo>Ops_Order__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Supplier__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/XometryJobID__c.field-meta.xml
<CustomField>
    <fullName>XometryJobID__c</fullName>
    <externalId>true</externalId>
    <label>Xometry Job ID</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/XometryOpsOrderID__c.field-meta.xml
<CustomField>
    <fullName>XometryOpsOrderID__c</fullName>
    <label>Xometry Ops Order ID</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Supplier__c/Supplier__c.object-meta.xml
<CustomObject>
    <label>Supplier</label>
    <nameField>
        <label>﻿Partner ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Supplier__c/fields/ContactID__c.field-meta.xml
<CustomField>
    <fullName>ContactID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ContactID</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Suppliers</relationshipLabel>
    <relationshipName>Suppliers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Supplier__c/fields/PartnerID__c.field-meta.xml
<CustomField>
    <fullName>PartnerID__c</fullName>
    <externalId>true</externalId>
    <label>Partner ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/XomEndpoint_WorkcenterFormSubmission.cls
@RestResource(urlMapping='/WorkcenterFormSubmission/v1/*')
global class XomEndpoint_WorkcenterFormSubmission {
    global class FormDataField {
        String key { get; set; }
        String value { get; set; }
        String type { get; set; }
        public FormDataField() {
        }
        public FormDataField(String key, String value, String type) {
            this.key = key;
            this.value = value;
            this.type = type;
        }
    }

    global class FormResponse {
        public string CaseNumber;
        public string CaseId;

        public FormResponse(String CaseId, String CaseNumber) {
            this.CaseId = CaseId;
            this.CaseNumber = CaseNumber;
        }
    }

    @HttpPost
    /**
     * @description Used for form submission
     * @param email Email to be used as the contact on the case
     * @param formId Third party id for reference
     * @param origin Where the form is being submitted
     * @param type The type of submission and will be used for routing
     * @param partnerId The id of the partner that should be linked to the case
     * @param jobId The id of the job that should be linked to the case
     * @param subject The subject for the case
     * @param attachmentStatus Determines if files are pending or none needed
     * @param recordTypeName The Developer Name of the record type for the case
     * @param otherFields A list is other form data fields that are not required
     */
    global static FormResponse createCaseFromSubmission(
        String email,
        String formId,
        String origin,
        String type,
        String partnerId,
        String jobId,
        String subject,
        String attachmentStatus,
        String recordTypeName,
        List<FormDataField> otherFields
    ) {
        // default to General Record Type
        // TODO: Add routing based on info
        Case c = new Case(
            SuppliedEmail = email,
            ThirdPartyCreationID__c = formId,
            Origin = origin,
            Type = type,
            Job_Number__c = jobId,
            Subject = subject,
            AttachmentStatus__c = attachmentStatus,
            RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName()
                .get(recordTypeName)
                .getRecordTypeId()
        );

        // Handle associations
        if (!String.isBlank(partnerId)) {
            List<Supplier__c> sList = [SELECT Id, ContactId__c FROM Supplier__c WHERE PartnerID__c = :partnerId];
            if (!sList.isEmpty()) {
                Supplier__c s = sList[0];
                c.Supplier__c = s.Id;
                c.ContactId = s.ContactId__c;
            }
        }

        if (!String.isBlank(jobId)) {
            List<Job__c> jList = [
                SELECT Id, OrderId__c, XometryOpsOrderID__c
                FROM Job__c
                WHERE XometryJobID__c = :jobId
            ];
            if (!jList.isEmpty()) {
                Job__c j = jList[0];
                c.Job__c = j.Id;
                c.GNOOrder__c = j.OrderId__c;
                c.OrderId__c = j.XometryOpsOrderID__c;
            }
        }

        // Loop through other fields
        if (!otherFields.isEmpty()) {
            for (FormDataField d : otherFields) {
                if (d.type.toLowerCase() == 'date') {
                    Date newValue = Date.valueOf(d.value);
                    c.put(d.key, newValue);
                } else if (d.type.toLowerCase() == 'boolean') {
                    Boolean newValue = Boolean.valueOf(d.value);
                    c.put(d.key, newValue);
                } else {
                    if(d.key.toLowerCase() == 'description')
                    {
                        if(subject.contains(':'))
                        {
                            String strTopic = subject.split(': ')[1];
                            d.value = d.value.replace('Topic: '+strTopic, 'Topic: '+strTopic+'\nDetails:');
                        }
                        d.value = d.value.replace('Topic:','\nTopic:');
                    }

                    c.put(d.key, d.value);
                }
            }
        }

        //Fetching the assignment rules on case
        AssignmentRule AR = new AssignmentRule();
        AR = [select id from AssignmentRule where SobjectType = 'Case' and Active = true limit 1];

        //Creating the DMLOptions for "Assign using active assignment rules" checkbox
        Database.DMLOptions dmlOpts = new Database.DMLOptions();
        dmlOpts.assignmentRuleHeader.assignmentRuleId= AR.id;

        c.setOptions(dmlOpts);

        DatabaseUtilities.insertToDatabase(
            new List<Case>{ c },
            'createCaseFromSubmission',
            'Insert case from WorkcenterFormSubmission'
        );
        Case caseResult = [SELECT Id, CaseNumber FROM Case WHERE Id = :c.Id][0];
        return new FormResponse(caseResult.Id, caseResult.CaseNumber);
    }
}