unpackaged/main/default/objects/Case/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>[AP] - New Vendor/Supplier Set-up</fullName>
            </value>
            <value>
                <fullName>[AP] - Stripe Account Issue</fullName>
            </value>
            <value>
                <fullName>[AP] - Vendor Invoice</fullName>
            </value>
            <value>
                <fullName>[AR] - Unconverted Invoices</fullName>
            </value>
            <value>
                <fullName>[AR] - Unpaid Credit Card Invoices</fullName>
            </value>
            <value>
                <fullName>[AR- Collections] - Portal Customer</fullName>
            </value>
            <value>
                <fullName>[Partner Management] - Account Inquiries</fullName>
            </value>
            <value>
                <fullName>[Partner Management] - Partner Relations</fullName>
            </value>
            <value>
                <fullName>[Partner Management] - Supplier Onboarding</fullName>
            </value>
            <value>
                <fullName>Auto Quote Review</fullName>
            </value>
            <value>
                <fullName>Auto response</fullName>
            </value>
            <value>
                <fullName>Bank Info Request</fullName>
            </value>
            <value>
                <fullName>Billing Account Update</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
                <label>Cancellations</label>
            </value>
            <value>
                <fullName>Capability Questions</fullName>
            </value>
            <value>
                <fullName>Case Management</fullName>
            </value>
            <value>
                <fullName>Certifications</fullName>
            </value>
            <value>
                <fullName>Collections</fullName>
            </value>
            <value>
                <fullName>Commercial Invoice</fullName>
            </value>
            <value>
                <fullName>Communication</fullName>
            </value>
            <value>
                <fullName>Credit Applications</fullName>
            </value>
            <value>
                <fullName>Credit Card Payments</fullName>
            </value>
            <value>
                <fullName>Credit Key</fullName>
            </value>
            <value>
                <fullName>Credit Limit Increase</fullName>
            </value>
            <value>
                <fullName>Customer Account Deletion</fullName>
            </value>
            <value>
                <fullName>CustomerOrderCertifications</fullName>
                <label>Customer::Order::Certifications</label>
            </value>
            <value>
                <fullName>CustomerOrderDocument</fullName>
                <label>Customer::Order::Document</label>
            </value>
            <value>
                <fullName>Customer Order Question/Issue</fullName>
            </value>
            <value>
                <fullName>DFM</fullName>
            </value>
            <value>
                <fullName>Document Request - NDA</fullName>
            </value>
            <value>
                <fullName>End-use definition</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/EUD_Email_Count__c.field-meta.xml
<CustomField>
    <fullName>EUD_Email_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <description>How many times an EUD email has been tried to be sent</description>
    <label>[EUD] Email Count</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/EUD_HTSCode__c.field-meta.xml
<CustomField>
    <fullName>EUD_HTSCode__c</fullName>
    <defaultValue>false</defaultValue>
    <label>[EUD] HTS Code</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/EUD_ImportReason__c.field-meta.xml
<CustomField>
    <fullName>EUD_ImportReason__c</fullName>
    <defaultValue>false</defaultValue>
    <label>[EUD] Import Reason</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/EUD_Industry__c.field-meta.xml
<CustomField>
    <fullName>EUD_Industry__c</fullName>
    <defaultValue>false</defaultValue>
    <label>[EUD] Industry</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/EUD_LineItemBreakdown__c.field-meta.xml
<CustomField>
    <fullName>EUD_LineItemBreakdown__c</fullName>
    <label>[EUD] Missing Data Per Line Item</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/EUD_MissingEndUseData__c.field-meta.xml
<CustomField>
    <fullName>EUD_MissingEndUseData__c</fullName>
    <defaultValue>false</defaultValue>
    <label>[EUD] Missing EUD</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/EUD_PartDescription__c.field-meta.xml
<CustomField>
    <fullName>EUD_PartDescription__c</fullName>
    <defaultValue>false</defaultValue>
    <label>[EUD] Part Description</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/EUD_Work_Stage__c.field-meta.xml
<CustomField>
    <fullName>EUD_Work_Stage__c</fullName>
    <label>[EUD] Work Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Reach Out Yet</fullName>
                <default>true</default>
                <label>No Reach Out Yet</label>
            </value>
            <value>
                <fullName>1st Attempt Sent</fullName>
            </value>
            <value>
                <fullName>2nd Attempt Sent - WARNING SENT</fullName>
            </value>
            <value>
                <fullName>VI Required</fullName>
            </value>
            <value>
                <fullName>End Use Received</fullName>
            </value>
            <value>
                <fullName>Escalated To Sales</fullName>
            </value>
            <value>
                <fullName>Invoice Sent</fullName>
            </value>
            <value>
                <fullName>Order Cancelled</fullName>
            </value>
            <value>
                <fullName>Sent to FedEx</fullName>
            </value>
            <value>
                <fullName>Shipped without Full End Use</fullName>
            </value>
            <value>
                <fullName>US Partner or Zetwork</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/OrderID__c.field-meta.xml
<CustomField>
    <fullName>OrderID__c</fullName>
    <label>Order ID</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Shadow_Xometry_ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>Shadow_Xometry_ERP_ID__c</fullName>
    <description>This field is for ensuring deduplication and is to be used for Integration purposes.</description>
    <externalId>true</externalId>
    <label>Quote ID</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/ShadowXometryOrderID__c.field-meta.xml
<CustomField>
    <fullName>ShadowXometryOrderID__c</fullName>
    <label>Shadow Xometry Order ID</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/DailyEUDEmailBatchTest.cls
@isTest
public with sharing class DailyEUDEmailBatchTest {
    @isTest
    public static void emailEUDWithNoReachOut() {
        String orderId = '12345-12345';
        Group eudGroup = [SELECT ID FROM Group WHERE DeveloperName = 'EUD_Queue'][0];
        List<Case> eudCaseList = new List<Case>();
        Case eudCase = new Case();
        eudCase.RecordTypeId = AppConstants.caseGeneralSupportRTypeId;
        eudCase.OwnerId = eudGroup.Id;
        eudCase.Subject = orderId + ' Missing End Use Data';
        eudCase.OrderID__c = orderId;
        eudCase.ShadowXometryOrderID__c = orderId;
        eudCase.Shadow_Xometry_ERP_ID__c = 'Q12-3424-1244';
        eudCase.SuppliedEmail = 'email@test.com';
        eudCase.Origin = 'Internal';
        eudCase.Category__c = 'End-use definition';
        eudCase.EUD_MissingEndUseData__c = true;
        eudCase.EUD_HTSCode__c = true;
        eudCase.EUD_ImportReason__c = true;
        eudCase.EUD_Industry__c = true;
        eudCase.EUD_PartDescription__c = false;
        eudCase.EUD_LineItemBreakdown__c = '02E3CD3: HTS Code';
        eudCase.EUD_Work_Stage__c = 'No Reach Out Yet';
        eudCase.Category__c = 'End-use definition';
        eudCase.Status = 'Open';
        eudCaseList.add(eudCase);

        String orderId2 = '23456-23456';
        Case eudCase2 = new Case();
        eudCase2.RecordTypeId = AppConstants.caseGeneralSupportRTypeId;
        eudCase2.OwnerId = eudGroup.Id;
        eudCase2.Subject = orderId2 + ' Missing End Use Data';
        eudCase2.OrderID__c = orderId2;
        eudCase2.ShadowXometryOrderID__c = orderId2;
        eudCase2.Shadow_Xometry_ERP_ID__c = 'Q12-4246-1246';
        eudCase2.SuppliedEmail = 'email@test.com';
        eudCase2.Origin = 'Internal';
        eudCase2.Category__c = 'End-use definition';
        eudCase2.EUD_MissingEndUseData__c = true;
        eudCase2.EUD_HTSCode__c = true;
        eudCase2.EUD_ImportReason__c = true;
        eudCase2.EUD_Industry__c = true;
        eudCase2.EUD_PartDescription__c = false;
        eudCase2.EUD_LineItemBreakdown__c = '02E3CD3: HTS Code';
        eudCase2.EUD_Work_Stage__c = 'No Reach Out Yet';
        eudCase2.Category__c = 'End-use definition';
        eudCase2.Status = 'Open';
        eudCase2.EUD_Email_Count__c = 2;
        eudCaseList.add(eudCase2);

        insert eudCaseList;

        Test.startTest();
        DailyEUDEmailBatch batch = new DailyEUDEmailBatch();
        Database.executeBatch(batch);
        Test.stopTest();

        List<Case> caseResults = [SELECT Id, EUD_Work_Stage__c, EUD_Email_Count__c, ShadowXometryOrderID__c FROM Case];
        for (Case c : caseResults) {
            if (c.ShadowXometryOrderID__c == orderId) {
                System.assertEquals('1st Attempt Sent', c.EUD_Work_Stage__c, 'EUD Work Stage was not updated');
                System.assertEquals(1, c.EUD_Email_Count__c, 'count should be increased');
            }
            if (c.ShadowXometryOrderID__c == orderId2) {
                System.assertEquals(2, c.EUD_Email_Count__c, 'count should have stayed the same');
            }
        }
    }
}