unpackaged/main/default/objects/Case/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>[AP] - New Vendor/Supplier Set-up</fullName>
            </value>
            <value>
                <fullName>[AP] - Stripe Account Issue</fullName>
            </value>
            <value>
                <fullName>[AP] - Vendor Invoice</fullName>
            </value>
            <value>
                <fullName>[AR] - Unconverted Invoices</fullName>
            </value>
            <value>
                <fullName>[AR] - Unpaid Credit Card Invoices</fullName>
            </value>
            <value>
                <fullName>[AR- Collections] - Portal Customer</fullName>
            </value>
            <value>
                <fullName>[Partner Management] - Account Inquiries</fullName>
            </value>
            <value>
                <fullName>[Partner Management] - Partner Relations</fullName>
            </value>
            <value>
                <fullName>[Partner Management] - Supplier Onboarding</fullName>
            </value>
            <value>
                <fullName>Auto Quote Review</fullName>
            </value>
            <value>
                <fullName>Auto response</fullName>
            </value>
            <value>
                <fullName>Bank Info Request</fullName>
            </value>
            <value>
                <fullName>Billing Account Update</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
                <label>Cancellations</label>
            </value>
            <value>
                <fullName>Capability Questions</fullName>
            </value>
            <value>
                <fullName>Case Management</fullName>
            </value>
            <value>
                <fullName>Certifications</fullName>
            </value>
            <value>
                <fullName>Collections</fullName>
            </value>
            <value>
                <fullName>Commercial Invoice</fullName>
            </value>
            <value>
                <fullName>Communication</fullName>
            </value>
            <value>
                <fullName>Credit Applications</fullName>
            </value>
            <value>
                <fullName>Credit Card Payments</fullName>
            </value>
            <value>
                <fullName>Credit Key</fullName>
            </value>
            <value>
                <fullName>Credit Limit Increase</fullName>
            </value>
            <value>
                <fullName>Customer Account Deletion</fullName>
            </value>
            <value>
                <fullName>CustomerOrderCertifications</fullName>
                <label>Customer::Order::Certifications</label>
            </value>
            <value>
                <fullName>CustomerOrderDocument</fullName>
                <label>Customer::Order::Document</label>
            </value>
            <value>
                <fullName>Customer Order Question/Issue</fullName>
            </value>
            <value>
                <fullName>DFM</fullName>
            </value>
            <value>
                <fullName>Document Request - NDA</fullName>
            </value>
            <value>
                <fullName>PPU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/GNOOrder__c.field-meta.xml
<CustomField>
    <fullName>GNOOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Ops_Order__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Job ID Associated with the Case</description>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Ordered_Part_ID__c.field-meta.xml
<CustomField>
    <fullName>Ordered_Part_ID__c</fullName>
    <label>Ordered Part ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/OrderedPartID__c.field-meta.xml
<CustomField>
    <fullName>OrderedPartID__c</fullName>
    <externalId>true</externalId>
    <label>Ordered Part ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/PartID__c.field-meta.xml
<CustomField>
    <fullName>PartID__c</fullName>
    <label>Part ID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/POD__c.field-meta.xml
<CustomField>
    <fullName>POD__c</fullName>
    <label>POD</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Albatrosses</fullName>
            </value>
            <value>
                <fullName>Atomic Rocks</fullName>
            </value>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Rocket Power</fullName>
            </value>
            <value>
                <fullName>SpaceTechs</fullName>
            </value>
            <value>
                <fullName>Triple Threat</fullName>
            </value>
            <value>
                <fullName>Amazing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/PP_Bucket__c.field-meta.xml
<CustomField>
    <fullName>PP_Bucket__c</fullName>
    <label>[PP] Bucket</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/PP_EventOrigin__c.field-meta.xml
<CustomField>
    <fullName>PP_EventOrigin__c</fullName>
    <label>[PP] Event Origin</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Question</fullName>
            </value>
            <value>
                <fullName>Issue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/PP_FabricationStarted__c.field-meta.xml
<CustomField>
    <fullName>PP_FabricationStarted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>[PP] Fabrication Started?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/PP_Message__c.field-meta.xml
<CustomField>
    <fullName>PP_Message__c</fullName>
    <label>[PP] Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/PP_SubBucket__c.field-meta.xml
<CustomField>
    <fullName>PP_SubBucket__c</fullName>
    <label>[PP] SubBucket</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/PP_XometryMaterials__c.field-meta.xml
<CustomField>
    <fullName>PP_XometryMaterials__c</fullName>
    <defaultValue>false</defaultValue>
    <label>[PP] Xometry Materials?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/ShadowXometryJobID__c.field-meta.xml
<CustomField>
    <fullName>ShadowXometryJobID__c</fullName>
    <label>Shadow Xometry Job ID</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/ShadowXometryOrderID__c.field-meta.xml
<CustomField>
    <fullName>ShadowXometryOrderID__c</fullName>
    <label>Shadow Xometry Order ID</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Supplier__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/ThirdPartyCreationID__c.field-meta.xml
<CustomField>
    <fullName>ThirdPartyCreationID__c</fullName>
    <label>Third Party Creation ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>GNO Jobs</description>
    <label>Job</label>
    <nameField>
        <label>Job ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Supplier__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/XometryJobID__c.field-meta.xml
<CustomField>
    <fullName>XometryJobID__c</fullName>
    <externalId>true</externalId>
    <label>Xometry Job ID</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/XometryOpsOrderID__c.field-meta.xml
<CustomField>
    <fullName>XometryOpsOrderID__c</fullName>
    <label>Xometry Ops Order ID</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Ops_Order__c/Ops_Order__c.object-meta.xml
<CustomObject>
    <description>Order object for the GNO Team. Used for purposes of tracking orders and jobs.</description>
    <label>Ops Order</label>
    <nameField>
        <label>Ops Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ops Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Ops_Order__c/fields/POD__c.field-meta.xml
<CustomField>
    <fullName>POD__c</fullName>
    <label>POD</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Albatrosses</fullName>
            </value>
            <value>
                <fullName>Atomic Rocks</fullName>
            </value>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>First Impressions</fullName>
            </value>
            <value>
                <fullName>Impodsters</fullName>
            </value>
            <value>
                <fullName>Rocket Power</fullName>
            </value>
            <value>
                <fullName>SpaceTechs</fullName>
            </value>
            <value>
                <fullName>Triple Threat</fullName>
            </value>
            <value>
                <fullName>Amazing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Ops_Order__c/fields/XometryOpsOrderID__c.field-meta.xml
<CustomField>
    <fullName>XometryOpsOrderID__c</fullName>
    <externalId>true</externalId>
    <label>Xometry Ops Order ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Supplier__c/Supplier__c.object-meta.xml
<CustomObject>
    <label>Supplier</label>
    <nameField>
        <label>﻿Partner ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Supplier__c/fields/AccountID__c.field-meta.xml
<CustomField>
    <fullName>AccountID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AccountID</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Suppliers</relationshipLabel>
    <relationshipName>Suppliers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Supplier__c/fields/ContactID__c.field-meta.xml
<CustomField>
    <fullName>ContactID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ContactID</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Suppliers</relationshipLabel>
    <relationshipName>Suppliers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/XomEndpoint_PartnerPortalResource.cls
@RestResource(urlMapping='/PartnerPortalResource/v1/*')
global with sharing class XomEndpoint_PartnerPortalResource {
    /**
     * @description Creates cases for Partner Portal Questions/Issues
     * @param replyAddress --Supplier provided email address
     * @param eventOrigin - Where was the request sent from (Currently Available: Issue or Question)
     * @param bucket - Main category selection
     * @param subbucket - Subcategory selection
     * @param subject - Subject of concatenated string (from sampleNotification.json)
     * @param message - Supplier provided message with more information
     * @param jobID - Job ID
     * @param orderedPartID - Xom Ordered Part ID (not used yet)
     * @param partID - Customer Part ID (not used yet)
     * @param orderID - Order ID
     * @param fabricationStarted - Supplier has indicated if they have started fabricating the part
     * @param xomMaterials - Supplier has indicated that they are using Xom materials to manufacture the part
     * @param thirdPartyCreationID - AWS Event ID for traceability
     */
    @HttpPost
    global static Id createPartnerPortalCase(
        String replyAddress,
        String eventOrigin,
        String bucket,
        String subbucket,
        String subject,
        String message,
        String jobID,
        String orderedPartID,
        String partID,
        String orderID,
        Boolean fabricationStarted,
        Boolean xomMaterials,
        String thirdPartyCreationID
    ) {
        //Future: Creation ID and last updated Event ID  (for upserts)
        Id returnCaseID,
            jobRecordID,
            supplierRecordID,
            supplierAccountRecordID,
            supplierContactRecordID,
            opsOrderRecordID;
        String podQueueName;

        List<Case> existingCase = new List<Case>(
            [SELECT ID FROM Case WHERE ThirdPartyCreationID__c = :thirdPartyCreationID]
        );
        if (existingCase.isEmpty()) {
            List<Job__c> jobFinder = [
                SELECT ID, Supplier__c, Supplier__r.AccountID__c, Supplier__r.ContactID__c
                FROM Job__c
                WHERE XometryJobID__c = :jobID
                LIMIT 1
            ];
            if (!jobFinder.isEmpty()) {
                //TODO: Create a shell job if the PP event comes in before the Job
                jobRecordID = jobFinder[0].Id;
                supplierRecordID = jobFinder[0].Supplier__c;
                supplierAccountRecordID = jobFinder[0].Supplier__r.AccountID__c;
                supplierContactRecordID = jobFinder[0].Supplier__r.ContactID__c;
            }
            List<Ops_Order__c> opsOrderFinder = [
                SELECT ID, POD__c
                FROM Ops_Order__c
                WHERE XometryOpsOrderID__c = :orderID
                LIMIT 1
            ];
            if (!opsOrderFinder.isEmpty()) {
                opsOrderRecordID = opsOrderFinder[0].ID;
                if (String.isBlank(opsOrderFinder[0].POD__c)) {
                    podQueueName = 'First_Impressions';
                } else {
                    podQueueName = opsOrderFinder[0].POD__c.replace(' ', '_');
                }
            } else {
                podQueueName = 'First_Impressions';
            }

            Id queueGroupId = [SELECT Id FROM Group WHERE Type = 'Queue' AND DeveloperName = :podQueueName].Id;

            Case ppCase = new Case(
                RecordTypeID = AppConstants.caseManagementRTypeId,
                OwnerId = queueGroupId,
                Subject = subject,
                Status = 'New',
                Origin = 'Partner Portal',
                Type = eventOrigin,
                Category__c = 'PPU',
                SuppliedEmail = replyAddress,
                PP_EventOrigin__c = eventOrigin,
                PP_Message__c = message,
                PP_Bucket__c = bucket,
                PP_SubBucket__c = subbucket,
                PP_XometryMaterials__c = xomMaterials,
                PP_FabricationStarted__c = fabricationStarted,
                GNOOrder__c = opsOrderRecordID,
                Supplier__c = supplierRecordID,
                Job__c = jobRecordID,
                Ordered_Part_ID__c = orderedPartID,
                ShadowXometryJobID__c = jobID,
                ShadowXometryOrderID__c = orderID,
                OrderedPartID__c = orderedPartID,
                PartID__c = partID,
                ContactId = supplierContactRecordID,
                AccountId = supplierAccountRecordID,
                ThirdPartyCreationID__c = thirdPartyCreationID
            );

            insert ppCase;
            returnCaseID = ppCase.Id;
        } else {
            returnCaseID = existingCase[0].Id;
        }

        return returnCaseID;
    }
}