unpackaged/main/default/objects/Case/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>[AP] - New Vendor/Supplier Set-up</fullName>
            </value>
            <value>
                <fullName>[AP] - Stripe Account Issue</fullName>
            </value>
            <value>
                <fullName>[AP] - Vendor Invoice</fullName>
            </value>
            <value>
                <fullName>[AR] - Unconverted Invoices</fullName>
            </value>
            <value>
                <fullName>[AR] - Unpaid Credit Card Invoices</fullName>
            </value>
            <value>
                <fullName>[AR- Collections] - Portal Customer</fullName>
            </value>
            <value>
                <fullName>[Partner Management] - Account Inquiries</fullName>
            </value>
            <value>
                <fullName>[Partner Management] - Partner Relations</fullName>
            </value>
            <value>
                <fullName>[Partner Management] - Supplier Onboarding</fullName>
            </value>
            <value>
                <fullName>Auto Quote Review</fullName>
            </value>
            <value>
                <fullName>Auto response</fullName>
            </value>
            <value>
                <fullName>Bank Info Request</fullName>
            </value>
            <value>
                <fullName>Billing Account Update</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
                <label>Cancellations</label>
            </value>
            <value>
                <fullName>Capability Questions</fullName>
            </value>
            <value>
                <fullName>Case Management</fullName>
            </value>
            <value>
                <fullName>Certifications</fullName>
            </value>
            <value>
                <fullName>Collections</fullName>
            </value>
            <value>
                <fullName>Commercial Invoice</fullName>
            </value>
            <value>
                <fullName>Communication</fullName>
            </value>
            <value>
                <fullName>Credit Applications</fullName>
            </value>
            <value>
                <fullName>Credit Card Payments</fullName>
            </value>
            <value>
                <fullName>Credit Key</fullName>
            </value>
            <value>
                <fullName>Credit Limit Increase</fullName>
            </value>
            <value>
                <fullName>Customer Account Deletion</fullName>
            </value>
            <value>
                <fullName>CustomerOrderCertifications</fullName>
                <label>Customer::Order::Certifications</label>
            </value>
            <value>
                <fullName>CustomerOrderDocument</fullName>
                <label>Customer::Order::Document</label>
            </value>
            <value>
                <fullName>Customer Order Question/Issue</fullName>
            </value>
            <value>
                <fullName>DFM</fullName>
            </value>
            <value>
                <fullName>Document Request - NDA</fullName>
            </value>
            <value>
                <fullName>End-use definition</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/EUD_ProductionType__c.field-meta.xml
<CustomField>
    <fullName>EUD_ProductionType__c</fullName>
    <label>Ordered Part Production Type(s)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Process__c.field-meta.xml
<CustomField>
    <fullName>Process__c</fullName>
    <formula>IF(ProcessCarbon__c, 'Carbon : ', '') +
IF(ProcessCNC__c ,'CNC : ', '') +
IF(ProcessDMLS__c ,'DMLS : ', '') +
IF(ProcessFDM__c,'FDM : ', '') +
IF(ProcessInjectionMolding__c,'Injection Molding : ', '') +
IF(ProcessMJF__c,'MJF : ', '') +
IF(ProcessSheetMetal__c, 'Sheet Metal : ', '') +
IF(ProcessSLA__c,'SLA : ','')+
IF(ProcessSLS__c,'SLS : ', '') +
IF(ProcessUrethaneCasting__c, 'Urethane Casting', '')</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Process</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/ShadowXometryOrderID__c.field-meta.xml
<CustomField>
    <fullName>ShadowXometryOrderID__c</fullName>
    <label>Shadow Xometry Order ID</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>GNO Jobs</description>
    <label>Job</label>
    <nameField>
        <label>Job ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/XometryOpsOrderID__c.field-meta.xml
<CustomField>
    <fullName>XometryOpsOrderID__c</fullName>
    <label>Xometry Ops Order ID</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Ops_Order__c/Ops_Order__c.object-meta.xml
<CustomObject>
    <description>Order object for the GNO Team. Used for purposes of tracking orders and jobs.</description>
    <label>Ops Order</label>
    <nameField>
        <label>Ops Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ops Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Ops_Order__c/fields/ExpiredPart__c.field-meta.xml
<CustomField>
    <fullName>ExpiredPart__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Have any of the parts expired?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Ops_Order__c/fields/XometryOpsOrderID__c.field-meta.xml
<CustomField>
    <fullName>XometryOpsOrderID__c</fullName>
    <externalId>true</externalId>
    <label>Xometry Ops Order ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Order_Event__c/Order_Event__c.object-meta.xml
<CustomObject>
    <label>Order Event</label>
    <nameField>
        <label>Order Event</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order_Event__c/fields/Ops_Order__c.field-meta.xml
<CustomField>
    <fullName>Ops_Order__c</fullName>
    <label>Ops Order</label>
    <referenceTo>Ops_Order__c</referenceTo>
    <relationshipLabel>Order Events</relationshipLabel>
    <relationshipName>Order_Events</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/Ordered_Part__c/Ordered_Part__c.object-meta.xml
<CustomObject>
    <label>Ordered Part</label>
    <nameField>
        <label>Xometry Ordered Part ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ordered Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Ordered_Part__c/fields/CurrentlyExpired__c.field-meta.xml
<CustomField>
    <fullName>CurrentlyExpired__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that a part is currently in an Expired status</description>
    <label>Currently Expired</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Ordered_Part__c/fields/EUD_ProductionType__c.field-meta.xml
<CustomField>
    <fullName>EUD_ProductionType__c</fullName>
    <label>[EUD] Production Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Value1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Ordered_Part__c/fields/HasEverExpired__c.field-meta.xml
<CustomField>
    <fullName>HasEverExpired__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicated if a part has ever been in an expired status</description>
    <label>Has Ever Expired?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Ordered_Part__c/fields/Ops_Order__c.field-meta.xml
<CustomField>
    <fullName>Ops_Order__c</fullName>
    <label>Ops Order</label>
    <referenceTo>Ops_Order__c</referenceTo>
    <relationshipLabel>Ordered Parts</relationshipLabel>
    <relationshipName>Ordered_Parts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Ordered_Part__c/fields/PartStatus__c.field-meta.xml
<CustomField>
    <fullName>PartStatus__c</fullName>
    <label>Part Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Value1</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Outsourced</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Validated</fullName>
            </value>
            <value>
                <fullName>Offers Made</fullName>
            </value>
            <value>
                <fullName>Final Inspection Failed</fullName>
            </value>
            <value>
                <fullName>All Offers Expired</fullName>
            </value>
            <value>
                <fullName>Customer Approved</fullName>
            </value>
            <value>
                <fullName>Received by Xometry</fullName>
            </value>
            <value>
                <fullName>Post-processing</fullName>
            </value>
            <value>
                <fullName>Finishing Started</fullName>
            </value>
            <value>
                <fullName>To Be Outsourced</fullName>
            </value>
            <value>
                <fullName>Partner Rework</fullName>
            </value>
            <value>
                <fullName>Build Started</fullName>
            </value>
            <value>
                <fullName>Inhouse Rework</fullName>
            </value>
            <value>
                <fullName>Partner Remake</fullName>
            </value>
            <value>
                <fullName>Partner Cancelled</fullName>
            </value>
            <value>
                <fullName>Packed</fullName>
            </value>
            <value>
                <fullName>Ready for Production</fullName>
            </value>
            <value>
                <fullName>Built Unsuccessfully</fullName>
            </value>
            <value>
                <fullName>Ready for Final Inspection</fullName>
            </value>
            <value>
                <fullName>Final Inspection Done</fullName>
            </value>
            <value>
                <fullName>Materials Ordered</fullName>
            </value>
            <value>
                <fullName>Op 1 CYCLE Paused</fullName>
            </value>
            <value>
                <fullName>Op 1 PRG Done</fullName>
            </value>
            <value>
                <fullName>Ordered</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Auto-Quoted</fullName>
            </value>
            <value>
                <fullName>Manually-Quoted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Ordered_Part__c/fields/Process__c.field-meta.xml
<CustomField>
    <fullName>Process__c</fullName>
    <label>Process</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Value1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Ordered_Part__c/fields/Unique_Ordered_Part_ID__c.field-meta.xml
<CustomField>
    <fullName>Unique_Ordered_Part_ID__c</fullName>
    <externalId>true</externalId>
    <label>Unique Ordered Part ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Ordered_Part__c/fields/Xometry_Order_ID__c.field-meta.xml
<CustomField>
    <fullName>Xometry_Order_ID__c</fullName>
    <label>Xometry Order ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Ordered_Part__c/fields/Xometry_Ordered_Part_ID__c.field-meta.xml
<CustomField>
    <fullName>Xometry_Ordered_Part_ID__c</fullName>
    <externalId>true</externalId>
    <label>Xometry Ordered Part ID</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Ordered_Part_Event__c/Ordered_Part_Event__c.object-meta.xml
<CustomObject>
    <label>Ordered Part Event</label>
    <nameField>
        <label>Ordered Part Event</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ordered Part Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Ordered_Part_Event__c/fields/Ordered_Part__c.field-meta.xml
<CustomField>
    <fullName>Ordered_Part__c</fullName>
    <label>Ordered Part</label>
    <referenceTo>Ordered_Part__c</referenceTo>
    <relationshipLabel>Ordered Part Events</relationshipLabel>
    <relationshipName>Ordered_Part_Events</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/Ordered_Part_Event__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Process_Exceptions_Types</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Ordered_Part_Event__c/fields/Xometry_Order_ID__c.field-meta.xml
<CustomField>
    <fullName>Xometry_Order_ID__c</fullName>
    <label>Xometry Order ID</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Process_Exceptions_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>POD</fullName>
    </customValue>
    <customValue>
        <fullName>T- Days Out</fullName>
    </customValue>
    <customValue>
        <fullName>Manufacturing Process</fullName>
    </customValue>
    <customValue>
        <fullName>Expedited</fullName>
    </customValue>
    <customValue>
        <fullName>Expired</fullName>
    </customValue>
    <customValue>
        <fullName>Fully Shipped</fullName>
    </customValue>
    <customValue>
        <fullName>Partially Shipped</fullName>
    </customValue>
    <customValue>
        <fullName>Job Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected Part</fullName>
    </customValue>
    <customValue>
        <fullName>Top 20 Customer</fullName>
    </customValue>
    <customValue>
        <fullName>MQ w/ Custom Finish</fullName>
    </customValue>
    <customValue>
        <fullName>Additive Only &amp; Past Due</fullName>
    </customValue>
    <customValue>
        <fullName>Created in ERP</fullName>
    </customValue>
    <customValue>
        <fullName>MQ &gt; $ Threshold</fullName>
    </customValue>
    <customValue>
        <fullName>Managed Process</fullName>
    </customValue>
    <customValue>
        <fullName>Non-Standard Inspection</fullName>
    </customValue>
    <customValue>
        <fullName>Late Bad Outcome</fullName>
    </customValue>
    <customValue>
        <fullName>Reject Bad Outcome</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>SPOC Supplier</fullName>
    </customValue>
    <customValue>
        <fullName>Estimated Completion Date</fullName>
    </customValue>
    <customValue>
        <fullName>Job Bad Outcome</fullName>
    </customValue>
    <customValue>
        <fullName>Top Quality Account</fullName>
    </customValue>
    <customValue>
        <fullName>Additive Job Past Due</fullName>
    </customValue>
    <customValue>
        <fullName>&gt; Additive Job Value Threshold</fullName>
    </customValue>
    <customValue>
        <fullName>Bad Outcomes - Order Bad Outcome</fullName>
    </customValue>
    <customValue>
        <fullName>Past Due</fullName>
    </customValue>
    <customValue>
        <fullName>Bad Outcome</fullName>
    </customValue>
    <customValue>
        <fullName>Part Late Bad Outcome</fullName>
    </customValue>
    <customValue>
        <fullName>Part Reject Bad Outcome</fullName>
    </customValue>
    <masterLabel>Process Exceptions Types</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/orderedPartHandlerTest.cls
@isTest
public class orderedPartHandlerTest {
    @isTest
    static void linkOrderedPartToOpsOrders() {
        //Create 4 OrderedParts
        // 2 OrderedParts belong to an Existing Ops Order
        // 2 OrderedParts need to have an Ops Order Created

        List<Ordered_Part__c> newOrderedPartsList = new List<Ordered_Part__c>();

        String xomOrder1Id = 'AAAA2-00004';
        String xomOrder2Id = 'AAAA2-00005';

        Ops_Order__c order1 = new Ops_Order__c();
        order1.name = xomOrder1Id;
        order1.XometryOpsOrderID__c = xomOrder1Id;
        insert order1;

        for (Integer i = 0; i < 4; i++) {
            Ordered_Part__C op = new Ordered_Part__C();
            op.Unique_Ordered_Part_ID__c = 'AAABBBCCaeidhgt' + i;
            op.Xometry_Ordered_Part_ID__c = '12322AB' + i;
            if (i < 2) {
                op.Xometry_Order_ID__c = xomOrder1Id;
            } else {
                op.Xometry_Order_ID__c = xomOrder2Id;
            }
            newOrderedPartsList.add(op);
        }

        test.startTest();
        insert newOrderedPartsList;
        test.stopTest();

        List<Ordered_Part__c> orderedPartInsertList = [
            SELECT Id, Xometry_Order_ID__c, Ops_Order__c
            FROM Ordered_Part__C
        ];
        System.assertEquals(4, orderedPartInsertList.size(), 'There were not 4 ordered Parts');
        for (Ordered_Part__C op : orderedPartInsertList) {
            if (op.Xometry_Order_ID__c == xomOrder1Id) {
                System.assertEquals(order1.id, op.Ops_Order__c, 'The Ordered Part was linked to the wrong Ops Order');
            }
            if (op.Ops_Order__c == null) {
                System.assert(false, 'An Ordered Part did not get is Ops Order');
            }
        }
    }

    @isTest(seeAllData=false)
    static void fillProductTypesTest() {
        Case testCase = new Case();
        testCase.Category__c = 'End-use definition';
        testCase.ShadowXometryOrderID__c = 'AAAA2-00003';

        Case testCase2 = new Case();
        testCase2.Category__c = 'End-use definition';
        testCase2.ShadowXometryOrderID__c = 'AAAA2-00004';

        insert new List<Case>{ testCase, testCase2 };

        Ops_Order__c order1 = new Ops_Order__c();
        order1.name = 'AAAA2-00003';
        order1.XometryOpsOrderID__c = 'AAAA2-00003';

        Ops_Order__c order2 = new Ops_Order__c();
        order2.name = 'AAAA2-00004';
        order2.XometryOpsOrderID__c = 'AAAA2-00004';
        insert new List<Ops_Order__c>{ order1, order2 };

        Ordered_Part__c op = new Ordered_Part__c();
        op.Unique_Ordered_Part_ID__c = 'AAABBBCCaeidhgt';
        op.Xometry_Ordered_Part_ID__c = '12322AB1';
        op.Xometry_Order_ID__c = 'AAAA2-00003';
        op.EUD_ProductionType__c = 'Prototype';

        Ordered_Part__c op2 = new Ordered_Part__c();
        op2.Unique_Ordered_Part_ID__c = 'AAABBBCCaeidhgu';
        op2.Xometry_Ordered_Part_ID__c = '12322AB2';
        op2.Xometry_Order_ID__c = 'AAAA2-00003';
        op2.EUD_ProductionType__c = 'Production';

        Ordered_Part__c op3 = new Ordered_Part__c();
        op3.Unique_Ordered_Part_ID__c = 'AAABBBCCaeidhgv';
        op3.Xometry_Ordered_Part_ID__c = '12322AB3';
        op3.Xometry_Order_ID__c = 'AAAA2-00004';
        op3.EUD_ProductionType__c = 'Prototype';

        Ordered_Part__c op4 = new Ordered_Part__c();
        op4.Unique_Ordered_Part_ID__c = 'AAABBBCCaeidhgw';
        op4.Xometry_Ordered_Part_ID__c = '12322AB4';
        op4.Xometry_Order_ID__c = 'AAAA2-00004';
        op4.EUD_ProductionType__c = 'Prototype';

        test.startTest();
        insert new List<Ordered_Part__c>{ op, op2, op3, op4 };
        test.stopTest();

        Map<Id, Case> testResult = new Map<Id, Case>([SELECT EUD_ProductionType__c FROM Case]);
        System.assertEquals('Production, Prototype', testResult.get(testCase.Id).EUD_ProductionType__c);
        System.assertEquals('Prototype', testResult.get(testCase2.Id).EUD_ProductionType__c);
    }

    @isTest(seeAllData=false)
    static void fillProductTypesUpdateTest() {
        Case testCase = new Case();
        testCase.Category__c = 'End-use definition';
        testCase.ShadowXometryOrderID__c = 'AAAA2-00003';
        insert testCase;

        Ops_Order__c order1 = new Ops_Order__c();
        order1.name = 'AAAA2-00003';
        order1.XometryOpsOrderID__c = 'AAAA2-00003';
        insert order1;

        Ordered_Part__c op = new Ordered_Part__c();
        op.Unique_Ordered_Part_ID__c = 'AAABBBCCaeidhgt';
        op.Xometry_Ordered_Part_ID__c = '12322AB1';
        op.Xometry_Order_ID__c = 'AAAA2-00003';
        op.EUD_ProductionType__c = 'Prototype';

        Map<Id, Case> testResult = new Map<Id, Case>([SELECT EUD_ProductionType__c FROM Case]);
        System.assertEquals(null, testResult.get(testCase.Id).EUD_ProductionType__c);

        insert op;

        testResult = new Map<Id, Case>([SELECT EUD_ProductionType__c FROM Case]);
        System.assertEquals('Prototype', testResult.get(testCase.Id).EUD_ProductionType__c);

        Ordered_Part__c op2 = new Ordered_Part__c();
        op2.Unique_Ordered_Part_ID__c = 'AAABBBCCaeidhgu';
        op2.Xometry_Ordered_Part_ID__c = '12322AB2';
        op2.Xometry_Order_ID__c = 'AAAA2-00003';
        op2.EUD_ProductionType__c = 'Production';

        test.startTest();
        insert op2;
        test.stopTest();

        testResult = new Map<Id, Case>([SELECT EUD_ProductionType__c FROM Case]);
        System.assertEquals('Production, Prototype', testResult.get(testCase.Id).EUD_ProductionType__c);
    }

    @isTest
    static void partExpiresOnInsert_noOpsOrder() {
        String xomOrderID = 'AAAA2-00001';

        Test.startTest();
        Ordered_Part__c part = TestDataFactory.createOrderedPart(true, 'All Offers Expired', xomOrderID, false, false);
        Test.stopTest();

        Ops_Order__c resultOpsOrder = [
            SELECT ID, ExpiredPart__c
            FROM Ops_Order__c
            WHERE XometryOpsOrderID__c = :xomOrderID
            LIMIT 1
        ][0];
        Ordered_Part__c resultPart = [
            SELECT ID, CurrentlyExpired__c
            FROM Ordered_Part__c
            WHERE Xometry_Order_ID__c = :xomOrderID
            LIMIT 1
        ][0];

        System.assertEquals(true, resultOpsOrder.ExpiredPart__c, 'The Ops Order was not updated when a part expired');
        System.assertEquals(
            true,
            resultPart.CurrentlyExpired__c,
            'CurrentlyExpired was not stamped once the part expired'
        );
    }

    @isTest
    static void partExpiresOnInsert_OpsOrderExists() {
        String xomOrderID = 'AAAA2-00001';

        Test.startTest();
        Ordered_Part__c part = TestDataFactory.createOrderedPart(true, 'All Offers Expired', xomOrderID, true, true);
        Test.stopTest();

        Ops_Order__c resultOpsOrder = [
            SELECT ID, ExpiredPart__c
            FROM Ops_Order__c
            WHERE XometryOpsOrderID__c = :xomOrderID
            LIMIT 1
        ][0];
        Ordered_Part__c resultPart = [
            SELECT ID, CurrentlyExpired__c
            FROM Ordered_Part__c
            WHERE Xometry_Order_ID__c = :xomOrderID
            LIMIT 1
        ][0];

        System.assertEquals(true, resultOpsOrder.ExpiredPart__c, 'The Ops Order was not updated when a part expired');
        System.assertEquals(
            true,
            resultPart.CurrentlyExpired__c,
            'CurrentlyExpired was not stamped once the part expired'
        );
    }

    @isTest
    static void partExpiresOnUpdate_OpsOrderExists() {
        String xomOrderID = 'AAAA2-00001';

        Ordered_Part__c part = TestDataFactory.createOrderedPart(true, 'Offers Made', xomOrderID, true, true);

        Test.startTest();
        part.PartStatus__c = 'All Offers Expired';
        update part;
        Test.stopTest();

        Ops_Order__c resultOpsOrder = [
            SELECT ID, ExpiredPart__c
            FROM Ops_Order__c
            WHERE XometryOpsOrderID__c = :xomOrderID
            LIMIT 1
        ][0];
        Ordered_Part__c resultPart = [
            SELECT ID, CurrentlyExpired__c
            FROM Ordered_Part__c
            WHERE Xometry_Order_ID__c = :xomOrderID
            LIMIT 1
        ][0];

        System.assertEquals(true, resultOpsOrder.ExpiredPart__c, 'The Ops Order was not updated when a part expired');
        System.assertEquals(
            true,
            resultPart.CurrentlyExpired__c,
            'CurrentlyExpired was not stamped once the part expired'
        );
    }

    @isTest
    static void partExpiresOnMissedETLUpdate_OpsOrderExists() {
        String xomOrderID = 'AAAA2-00001';

        Ordered_Part__c part = TestDataFactory.createOrderedPart(true, 'Offers Made', xomOrderID, true, true);

        Test.startTest();
        part.HasEverExpired__c = true;
        update part;
        Test.stopTest();

        Ops_Order__c resultOpsOrder = [
            SELECT ID, ExpiredPart__c
            FROM Ops_Order__c
            WHERE XometryOpsOrderID__c = :xomOrderID
            LIMIT 1
        ][0];
        Ordered_Part__c resultPart = [
            SELECT ID, CurrentlyExpired__c
            FROM Ordered_Part__c
            WHERE Xometry_Order_ID__c = :xomOrderID
            LIMIT 1
        ][0];

        System.assertEquals(
            true,
            resultOpsOrder.ExpiredPart__c,
            'The Ops Order was not updated when a part had expired but was missed in the ETL'
        );
        System.assertEquals(false, resultPart.CurrentlyExpired__c, 'The part should not be currently expired');
    }

    @isTest
    static void partIsNoLongerExpiredTest() {
        String xomOrderID = 'AAAA2-00001';

        Ordered_Part__c part = TestDataFactory.createOrderedPart(true, 'All Offers Expired', xomOrderID, true, true);

        Test.startTest();
        part.PartStatus__c = 'Offers Made';
        update part;
        Test.stopTest();

        Ops_Order__c resultOpsOrder = [
            SELECT ID, ExpiredPart__c
            FROM Ops_Order__c
            WHERE XometryOpsOrderID__c = :xomOrderID
            LIMIT 1
        ][0];
        Ordered_Part__c resultPart = [
            SELECT ID, CurrentlyExpired__c
            FROM Ordered_Part__c
            WHERE Xometry_Order_ID__c = :xomOrderID
            LIMIT 1
        ][0];

        System.assertEquals(
            true,
            resultOpsOrder.ExpiredPart__c,
            'The Ops Order was incorrectly updated when a previously expired part was resourced'
        );
        System.assertEquals(
            false,
            resultPart.CurrentlyExpired__c,
            'CurrentlyExpired was not updated once the part was resourced'
        );
    }

    @isTest
    static void eventConditionals_basicInsert_OrderOnly() {
        String xomOrderID = 'AAAA2-00001';

        Ordered_Part__c part = TestDataFactory.createOrderedPart(false, 'All Offers Expired', xomOrderID, true, true);
        part.Process__c = 'Die Casting';
        part.InspectionType__c = 'cust';

        Test.startTest();
        insert part;

        Test.stopTest();

        List<Ordered_Part_Event__c> opEventList = new List<Ordered_Part_Event__c>(
            [SELECT ID, Order_Event__c, Job_Event__c, Type__c FROM Ordered_Part_Event__c]
        );

        List<Order_Event__c> orderEventList = new List<Order_Event__c>(
            [SELECT ID, Ops_Order__c, Type__c, Qualifying_Object__c FROM Order_Event__c]
        );

        System.assertEquals(3, opEventList.size(), 'The incorrect number of Ordered Part Junction events were created');
        System.assertEquals(3, orderEventList.size(), 'The incorrect number of Order Events were created');

        for (Ordered_Part_Event__c opEvent : opEventList) {
            for (Integer i = 0; i < orderEventList.size(); i++) {
                if (opEvent.Type__c == orderEventList[i].Type__c) {
                    System.assertEquals(
                        orderEventList[i].ID,
                        opEvent.Order_Event__c,
                        'The Ordered Part Junction Event was associated to the wrong Order Event'
                    );
                }
            }
        }
    }

    @isTest
    static void eventConditionals_basicInsert_OrderAndJob() {
        String xomOrderID = 'AAAA2-00001';
        String xomJobID = 'J0012345';

        Job__c job = new Job__c();
        job.XometryOpsOrderID__c = xomOrderID;
        job.XometryJobID__c = xomJobID;
        insert job;

        Ordered_Part__c part = TestDataFactory.createOrderedPart(false, 'All Offers Expired', xomOrderID, true, false);
        part.Process__c = 'Die Casting';
        part.InspectionType__c = 'cust';
        part.CurrentJobID__c = xomJobID;

        Test.startTest();
        insert part;

        Test.stopTest();

        List<Ordered_Part_Event__c> opEventList = new List<Ordered_Part_Event__c>(
            [SELECT ID, Order_Event__c, Job_Event__c, Type__c FROM Ordered_Part_Event__c]
        );

        List<Order_Event__c> orderEventList = new List<Order_Event__c>(
            [SELECT ID, Ops_Order__c, Type__c FROM Order_Event__c]
        );

        List<Job_Event__c> jobEventList = new List<Job_Event__c>([SELECT ID, Job__c, Type__c FROM Job_Event__c]);

        System.assertEquals(3, opEventList.size(), 'The incorrect number of Ordered Part Junction events were created');
        System.assertEquals(3, orderEventList.size(), 'The incorrect number of Order Events were created');
        System.assertEquals(3, jobEventList.size(), 'The incorrect number of Job Events were created');

        for (Ordered_Part_Event__c opEvent : opEventList) {
            System.debug(opEvent);
            for (Integer i = 0; i < orderEventList.size(); i++) {
                if (opEvent.Type__c == orderEventList[i].Type__c) {
                    System.assertEquals(
                        orderEventList[i].ID,
                        opEvent.Order_Event__c,
                        'The Ordered Part Junction Event was associated to the wrong Order Event'
                    );
                }
            }
            for (Integer i = 0; i < jobEventList.size(); i++) {
                if (opEvent.Type__c == jobEventList[i].Type__c) {
                    System.assertEquals(
                        jobEventList[i].ID,
                        opEvent.Job_Event__c,
                        'The Ordered Part Junction Event was associated to the wrong Job Event'
                    );
                }
            }
        }
    }
}