unpackaged/main/default/objects/Case/fields/DFM_Description__c.field-meta.xml
<CustomField>
    <fullName>DFM_Description__c</fullName>
    <label>DFM Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/LineItemCount__c.field-meta.xml
<CustomField>
    <fullName>LineItemCount__c</fullName>
    <label>Line Item Count (Old)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created During PSE Service Migration Project</description>
    <inlineHelpText>Opportunity Related to the Case</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Reorder__c.field-meta.xml
<CustomField>
    <fullName>Reorder__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reorder?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Shadow_Xometry_ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>Shadow_Xometry_ERP_ID__c</fullName>
    <description>This field is for ensuring deduplication and is to be used for Integration purposes.</description>
    <externalId>true</externalId>
    <label>Quote ID</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/Quote_ERP__c.object-meta.xml
<CustomObject>
    <description>A quote that is sent over from ERP</description>
    <label>Quote ERP</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote_ERP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes ERP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Quote_ERP__c/fields/DFM_Description__c.field-meta.xml
<CustomField>
    <fullName>DFM_Description__c</fullName>
    <label>DFM Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Quote_ERP_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Quote_ERP_Created_Date__c</fullName>
    <description>The date the quote was created in the ERP system</description>
    <label>Quote Created Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Reorder__c.field-meta.xml
<CustomField>
    <fullName>Reorder__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reorder?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Requested_Manual_Quote_Flag__c.field-meta.xml
<CustomField>
    <fullName>Requested_Manual_Quote_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to allow for Case firings for PSE team.</description>
    <label>Requested Manual Quote Flag</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Requested_Manual_Quote_Time__c.field-meta.xml
<CustomField>
    <fullName>Requested_Manual_Quote_Time__c</fullName>
    <description>The first time the status in the erp became 'RFQ submitted'</description>
    <label>Requested Manual Quote Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Xometry_ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>Xometry_ERP_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Unique Qoute ID created in Xometry ERP</description>
    <externalId>true</externalId>
    <label>Quote ID</label>
    <length>13</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/NYOPCaseTest.cls
@isTest
public with sharing class NYOPCaseTest {
    @isTest
    static void nyopCaseFirstThenPSE() {
        //Create an NYOP Case
        //Create a PSE Case
        Quote_ERP__C testPseQuote = TestDataFactory.createQuote(false);
        String testQuoteNumber = 'Q21-300-4445';
        testPseQuote.Xometry_ERP_ID__C = testQuoteNumber;
        testPseQuote.DFM_Description__c = 'This is a reason that this needs to be a dfm case, or something like that.';
        testPseQuote.LineItemCount__c = 1;
        testPseQuote.Reorder__c = true;
        testPseQuote.Quote_ERP_Created_Date__c = Date.today();
        testPseQuote.Requested_Manual_Quote_Flag__c = true;
        testPseQuote.Requested_Manual_Quote_Time__C = DateTime.now();
        Case nyopCase = new Case();
        nyopCase.recordTypeID = AppConstants.nyopRTypeID;
        nyopCase.Shadow_Xometry_ERP_ID__C = testQuoteNumber;
        insert nyopCase;
        insert testPseQuote;
        test.StartTest();
        List<Case> nyopCaseList = new List<Case>();
        nyopCaseList.add(nyopCase);
        updateNYOPCaseQue nyopQue = new updateNYOPCaseQue(nyopCaseList);
        ID jobID = System.enqueueJob(nyopQue);
        test.StopTest();
        //Get the PSE Case
        Case pseCase = [
            SELECT ID, Shadow_Xometry_ERP_ID__C, Opportunity__c
            FROM Case
            WHERE recordTypeID = :AppConstants.casePSERecordTypeId AND Shadow_Xometry_ERP_ID__C = :testQuoteNumber
        ][0];
        Case testNYOPCase = [
            SELECT ID, Shadow_Xometry_ERP_ID__C, Opportunity__c, ParentID
            FROM Case
            WHERE ID = :nyopCase.ID
        ];

        System.assertEquals(pseCase.Opportunity__c, testNYOPCase.Opportunity__c, 'The Opportunities did not match');
        System.assertEquals(pseCase.ID, testNYOPCase.ParentID, 'The NYOP case does not have the right parent');
    }

    @isTest
    static void pseFirstThenNYOP() {
        //Create a PSE Case
        //Create the NYOP Case
        Quote_ERP__C testPseQuote = TestDataFactory.createQuote(false);
        String testQuoteNumber = 'Q21-300-4445';
        testPseQuote.Xometry_ERP_ID__C = testQuoteNumber;
        testPseQuote.DFM_Description__c = 'This is a reason that this needs to be a dfm case, or something like that.';
        testPseQuote.LineItemCount__c = 1;
        testPseQuote.Reorder__c = true;
        testPseQuote.Quote_ERP_Created_Date__c = Date.today();
        testPseQuote.Requested_Manual_Quote_Flag__c = true;
        testPseQuote.Requested_Manual_Quote_Time__C = DateTime.now();
        Case nyopCase = new Case();
        nyopCase.recordTypeID = AppConstants.nyopRTypeID;
        nyopCase.Shadow_Xometry_ERP_ID__C = testQuoteNumber;
        insert testPseQuote;
        test.StartTest();
        insert nyopCase;
        test.StopTest();
        //Get the PSE Case
        Case pseCase = [
            SELECT ID, Shadow_Xometry_ERP_ID__C, Opportunity__c
            FROM Case
            WHERE recordTypeID = :AppConstants.casePSERecordTypeId AND Shadow_Xometry_ERP_ID__C = :testQuoteNumber
        ][0];
        Case testNYOPCase = [
            SELECT ID, Shadow_Xometry_ERP_ID__C, Opportunity__c, ParentID
            FROM Case
            WHERE ID = :nyopCase.ID
        ];

        System.assertEquals(pseCase.Opportunity__c, testNYOPCase.Opportunity__c, 'The Opportunities did not match');
        System.assertEquals(pseCase.ID, testNYOPCase.ParentID, 'The NYOP case does not have the right parent');
    }
}