unpackaged/main/default/objects/Case/fields/GNOOrder__c.field-meta.xml
<CustomField>
    <fullName>GNOOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Ops_Order__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Ops_Order__c/Ops_Order__c.object-meta.xml
<CustomObject>
    <description>Order object for the GNO Team. Used for purposes of tracking orders and jobs.</description>
    <label>Ops Order</label>
    <nameField>
        <label>Ops Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ops Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Ops_Order__c/fields/Is_Large_Order__c.field-meta.xml
<CustomField>
    <fullName>Is_Large_Order__c</fullName>
    <formula>AND(AllOrdersTotal__c  &gt;  $CustomMetadata.Admin_Ref_Variable__mdt.LargeOrderAmount.Number_Ref_Value__c,
 Order_Date__c  &gt;=  $CustomMetadata.Admin_Ref_Variable__mdt.LargeOrderAmount.Date_Ref_Value__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Large Order</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/OpsOrderPopulateBusinessHoursBatch.cls
/**
 * Batch job to backfill the old cases with the businesshour
 */
global class OpsOrderPopulateBusinessHoursBatch implements Database.Batchable<sObject> {
    public String query = 'SELECT Id FROM Ops_Order__c WHERE Is_Large_Order__c = TRUE';

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, list<Ops_Order__c> scope) {

        Set<Id> opsIds = new Set<Id>();
        for(Ops_Order__c ops : scope){
            opsIds.add(ops.Id);
        }

        Map<String, BusinessHours> hoursMap = new Map<String, BusinessHours>();
        for (BusinessHours bHours : [SELECT Id, Name FROM BusinessHours]) {
            hoursMap.put(bHours.Name, bHours);
        }

        List<Case> casesToUpdate = new List<Case>();
        for(Case oneCase : [SELECT Id FROM Case WHERE GNOOrder__c IN :opsIds AND Type IN ('Technical Review', 'Large Order Review', 'Large Order Approval')]){
            oneCase.BusinessHoursId = hoursMap.get('POD Business Hours - EST').Id;
            casesToUpdate.add(oneCase);
        }

        DatabaseUtilities.saveToDatabase(casesToUpdate, 'OpsOrderPopulateBusinessHoursBatch', 'Case populate Business Hours');

    }

    global void finish(Database.BatchableContext BC) {

    }
}