unpackaged/main/default/objects/Case/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Job ID Associated with the Case</description>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/recordTypes/Sourcing.recordType-meta.xml
<RecordType>
    <fullName>Sourcing</fullName>
    <active>true</active>
    <businessProcess>GNO Sourcing Team</businessProcess>
    <description>Cases for jobs that were cancelled, rejected, expired or need to be remade.</description>
    <label>Sourcing</label>
</RecordType>

unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>GNO Jobs</description>
    <label>Job</label>
    <nameField>
        <label>Job ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/Open_Cases__c.field-meta.xml
<CustomField>
    <fullName>Open_Cases__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Open Cases</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/OrderDueDate__c.field-meta.xml
<CustomField>
    <fullName>OrderDueDate__c</fullName>
    <label>Order Due Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/XometryJobID__c.field-meta.xml
<CustomField>
    <fullName>XometryJobID__c</fullName>
    <externalId>true</externalId>
    <label>Xometry Job ID</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/XometryOpsOrderID__c.field-meta.xml
<CustomField>
    <fullName>XometryOpsOrderID__c</fullName>
    <label>Xometry Ops Order ID</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/JobRollUpOpenCasesBatchTest.cls
@isTest
private class JobRollUpOpenCasesBatchTest {
    @isTest(seeAllData=false)
    static void JobRollUpOpenCasesBatchTest() {
        RecordType sourcingCaseRecordType = [
            SELECT Id, DeveloperName
            FROM RecordType
            WHERE DeveloperName = 'Sourcing'
            LIMIT 1
        ];

        Job__c testJob = new Job__c();
        testJob.Name = 'Test-Job';
        testJob.XometryJobID__c = 'Test-Job';
        testJob.XometryOpsOrderID__c = '1234';
        testJob.OrderDueDate__c = Date.today() + 7;
        insert testJob;

        Case testCase = new Case(Job__c = testJob.Id);
        insert testCase;

        testCase.RecordTypeId = sourcingCaseRecordType.Id;
        update testCase;

        System.assertEquals(
            0,
            [SELECT Open_Cases__c FROM Job__c WHERE Id = :testJob.Id]
            .Open_Cases__c,
            'Rollup should be 0 before the Batch'
        );

        Test.startTest();

        JobRollUpOpenCasesBatch jb = new JobRollUpOpenCasesBatch();
        Database.executeBatch(jb);

        Test.stopTest();

        System.assertEquals(
            1,
            [SELECT Open_Cases__c FROM Job__c WHERE Id = :testJob.Id]
            .Open_Cases__c,
            'Rollup should be updated after the Batch run.'
        );
    }
}