unpackaged/main/default/objects/Case/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Job ID Associated with the Case</description>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/PreviousJobsList__c.field-meta.xml
<CustomField>
    <fullName>PreviousJobsList__c</fullName>
    <label>Previous Jobs List</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Case/recordTypes/Sourcing.recordType-meta.xml
<RecordType>
    <fullName>Sourcing</fullName>
    <active>true</active>
    <businessProcess>GNO Sourcing Team</businessProcess>
    <description>Cases for jobs that were cancelled, rejected, expired or need to be remade.</description>
    <label>Sourcing</label>
</RecordType>

unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>GNO Jobs</description>
    <label>Job</label>
    <nameField>
        <label>Job ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/XometryJobID__c.field-meta.xml
<CustomField>
    <fullName>XometryJobID__c</fullName>
    <externalId>true</externalId>
    <label>Xometry Job ID</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/UpdateSourcingCasesBatch.cls
global class UpdateSourcingCasesBatch implements Database.Batchable<sObject> {
    public Datetime startDate;

    global UpdateSourcingCasesBatch() {
        startDate = Date.today().addDays(-1);
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {

        Id caseSourcingRTypeId = AppConstants.caseSourcingRTypeId;

        String query = ' SELECT Id, Job__c, PreviousJobsList__c FROM Case WHERE RecordTypeID = :caseSourcingRTypeId AND LastModifiedDate >= :startDate ORDER BY LastModifiedDate ASC';

        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, list<Case> scope) {
        
        Map<String, List<Case>> jobXomIdCaseMap = new Map<String, List<Case>>();

        for (Case oneCase : scope) {

            if( !String.isBlank(oneCase.PreviousJobsList__c) ){

                List<String> prevJobsList = oneCase.PreviousJobsList__c.split(', ');

                if( !prevJobsList.isEmpty() ){
                    String lastJobXomId = prevJobsList.get( prevJobsList.size() - 1 );
                    if( !jobXomIdCaseMap.containsKey(lastJobXomId) ){
                        jobXomIdCaseMap.put( lastJobXomId, new List<Case>() );
                    }
                    jobXomIdCaseMap.get( lastJobXomId ).add( oneCase );
                }

            }

        }

        List<Case> casesToUpdate = new List<Case>();
        for (Job__c oneJob : [
            SELECT Id, XometryJobID__c
            FROM Job__c
            WHERE XometryJobID__c IN :jobXomIdCaseMap.keySet()
        ]) {

            for( Case oneCase : jobXomIdCaseMap.get( oneJob.XometryJobID__c ) ){
                if( oneCase.Job__c != oneJob.Id ){
                    oneCase.Job__c = oneJob.Id;
                    casesToUpdate.add(oneCase);
                }
            }

        }

        if (!casesToUpdate.isEmpty()) {
            DatabaseUtilities.saveToDatabase(
                casesToUpdate,
                'UpdateSourcingCasesBatch.execute',
                'Updating sourcing cases with latest Job ID from PreviousJobsList__c'
            );
        }

    }

    global void finish(Database.BatchableContext BC) {

    }
}