unpackaged/main/default/objects/Case/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Job ID Associated with the Case</description>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/OrderID__c.field-meta.xml
<CustomField>
    <fullName>OrderID__c</fullName>
    <label>Order ID</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/POD__c.field-meta.xml
<CustomField>
    <fullName>POD__c</fullName>
    <label>POD</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Albatrosses</fullName>
            </value>
            <value>
                <fullName>Atomic Rocks</fullName>
            </value>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Rocket Power</fullName>
            </value>
            <value>
                <fullName>SpaceTechs</fullName>
            </value>
            <value>
                <fullName>Triple Threat</fullName>
            </value>
            <value>
                <fullName>Amazing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>GNO Jobs</description>
    <label>Job</label>
    <nameField>
        <label>Job ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/OrderID__c.field-meta.xml
<CustomField>
    <fullName>OrderID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Order associated with this job</description>
    <label>Order ID</label>
    <referenceTo>Ops_Order__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Job_Event__c/Job_Event__c.object-meta.xml
<CustomObject>
    <label>Job Event</label>
    <nameField>
        <label>Job Event</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job_Event__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Job Events</relationshipLabel>
    <relationshipName>Job_Events</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/Ops_Order__c/Ops_Order__c.object-meta.xml
<CustomObject>
    <description>Order object for the GNO Team. Used for purposes of tracking orders and jobs.</description>
    <label>Ops Order</label>
    <nameField>
        <label>Ops Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ops Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Ops_Order__c/fields/Is_Large_Order__c.field-meta.xml
<CustomField>
    <fullName>Is_Large_Order__c</fullName>
    <formula>AND(AllOrdersTotal__c  &gt;  $CustomMetadata.Admin_Ref_Variable__mdt.LargeOrderAmount.Number_Ref_Value__c,
 Order_Date__c  &gt;=  $CustomMetadata.Admin_Ref_Variable__mdt.LargeOrderAmount.Date_Ref_Value__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Large Order</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Ops_Order__c/fields/LargeOrderStatus__c.field-meta.xml
<CustomField>
    <fullName>LargeOrderStatus__c</fullName>
    <label>Large Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DFM-Pending Review</fullName>
            </value>
            <value>
                <fullName>DFM-Review Complete</fullName>
            </value>
            <value>
                <fullName>Job(s) Pending Technical Review</fullName>
            </value>
            <value>
                <fullName>Large Order Review Process Complete</fullName>
            </value>
            <value>
                <fullName>DFM Initial Review Complete</fullName>
                <isActive>false</isActive>
                <label>DFM Initial Review Complete</label>
            </value>
            <value>
                <fullName>DFM LOR Complete</fullName>
                <isActive>false</isActive>
                <label>DFM LOR Complete</label>
            </value>
            <value>
                <fullName>Job(s) Accepted</fullName>
                <isActive>false</isActive>
                <label>Job(s) Accepted</label>
            </value>
            <value>
                <fullName>Job(s) Pushed</fullName>
                <isActive>false</isActive>
                <label>Job(s) Pushed</label>
            </value>
            <value>
                <fullName>New</fullName>
                <isActive>false</isActive>
                <label>New</label>
            </value>
            <value>
                <fullName>Order Placed</fullName>
                <isActive>false</isActive>
                <label>Order Placed</label>
            </value>
            <value>
                <fullName>Tech Review (MPC) Complete</fullName>
                <isActive>false</isActive>
                <label>Tech Review (MPC) Complete</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Ops_Order__c/fields/POD__c.field-meta.xml
<CustomField>
    <fullName>POD__c</fullName>
    <label>POD</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Albatrosses</fullName>
            </value>
            <value>
                <fullName>Atomic Rocks</fullName>
            </value>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>First Impressions</fullName>
            </value>
            <value>
                <fullName>Impodsters</fullName>
            </value>
            <value>
                <fullName>Rocket Power</fullName>
            </value>
            <value>
                <fullName>SpaceTechs</fullName>
            </value>
            <value>
                <fullName>Triple Threat</fullName>
            </value>
            <value>
                <fullName>Amazing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order_Event__c/Order_Event__c.object-meta.xml
<CustomObject>
    <label>Order Event</label>
    <nameField>
        <label>Order Event</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order_Event__c/fields/Job_Event__c.field-meta.xml
<CustomField>
    <fullName>Job_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Event</label>
    <referenceTo>Job_Event__c</referenceTo>
    <relationshipLabel>Job Triggered Events</relationshipLabel>
    <relationshipName>Job_Triggered_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Event__c/fields/Ops_Order__c.field-meta.xml
<CustomField>
    <fullName>Ops_Order__c</fullName>
    <label>Ops Order</label>
    <referenceTo>Ops_Order__c</referenceTo>
    <relationshipLabel>Order Events</relationshipLabel>
    <relationshipName>Order_Events</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/Order_Event__c/fields/OrderID__c.field-meta.xml
<CustomField>
    <fullName>OrderID__c</fullName>
    <label>Order ID</label>
    <length>11</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ProcessException/fields/Icon_indicator_type__c.field-meta.xml
<CustomField>
    <fullName>Icon_indicator_type__c</fullName>
    <formula>IF(
    OR(
								Type__c = "Subtractive &amp; Past Due",
								Type__c = "Additive Only &amp; Past Due",
								Type__c = "T-3 Days Out",
								Type__c = "Additive Job Past Due"
				),
				"standard:scheduling_constraint",
				IF(
								OR(
            Type__c = "Top 20 Customer",
								    Type__c = "Bad Outcomes - Order Bad Outcome",
								    Type__c = "MQ &gt; $ Threshold",
								    Type__c = "Expired",
								    Type__c = "Created in ERP",
								    Type__c = "Bad Outcomes - Job Bad Outcome",
								    Type__c = "Created in ERP",
								    Type__c = "Expedited",
								    Type__c = "Rejected Part",
								    Type__c = "MQ w/ Custom Finish",
								    Type__c = "Non-Standard Inspection",
								    Type__c = "SPOC Supplier",
								    Type__c = "Top Quality Account",
								    Type__c = "&gt; Additive Job Value Threshold"
								),
								"standard:problem",
								IF(
												Type__c = "POD",
												"standard:checkout",
												""
								)
				)
)</formula>
    <label>Icon indicator type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ProcessException/fields/Ops_Order__c.field-meta.xml
<CustomField>
    <fullName>Ops_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ops Order</label>
    <referenceTo>Ops_Order__c</referenceTo>
    <relationshipLabel>Process Exceptions</relationshipLabel>
    <relationshipName>Process_Exceptions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/ProcessExceptionViewController.cls
public class ProcessExceptionViewController{

    /**
     * @description method to fetch all open ProcessException related to the OpsOrder or Job record
     * @param recordId id of the OpsOrder or Job record
     * @return List of the ProcessException related
     */
    @AuraEnabled
    public static List<ProcessException> getAllProcessExceptions(Id recordId){
        if(recordId != null){
            String strObjectId = findObjectNameFromRecordIdPrefix(recordId);
            List<ProcessException> processExceptionsList = new List<ProcessException>();

            String strQuery = 'SELECT Id, '
                                +'(SELECT Id, ProcessExceptionNumber, AttachedToId, Status, Message, Priority, Category, Severity, CreatedDate, Owner.Name, Case.CaseNumber, Icon_indicator_type__c '
                                +'FROM ProcessExceptions '
                                +'WHERE Status != \'Resolved\' Order By Id DESC) ';

            if(strObjectId == 'Ops_Order__c')
            {
                List<Order_Event__c> lstOrdersEvents = Database.Query(strQuery+'FROM Order_Event__c WHERE Ops_Order__c = \''+recordId+'\'');
                List<Job_Event__c> lstJobsEvents = Database.Query(strQuery+'FROM Job_Event__c  WHERE Job__r.OrderID__c = \''+recordId+'\'');
                
                for(Order_Event__c obj : lstOrdersEvents)
                {
                    processExceptionsList.addAll(obj.ProcessExceptions);
                }

                for(Job_Event__c obj : lstJobsEvents)
                {
                    processExceptionsList.addAll(obj.ProcessExceptions);
                }
            }
            else if(strObjectId == 'Job__c')
            {
                List<Job_Event__c> lstJobsEvents = Database.Query(strQuery+'FROM Job_Event__c  WHERE Job__c = \''+recordId+'\'');
                
                for(Job_Event__c obj : lstJobsEvents)
                {
                    processExceptionsList.addAll(obj.ProcessExceptions);
                }
            }

            System.debug('processExceptionsList '+processExceptionsList);

            if(processExceptionsList != null && processExceptionsList.size() > 0){
                return processExceptionsList;
            }
        }

        return null;
    }

    /**
     * @description method to get the info of the OpsOrder
     * @param recordId id of the OpsOrder or Job record
     * @return OpsOrder record
     */
    @AuraEnabled
    public static Ops_Order__c getOpsOrderInfo(Id recordId){
        Ops_Order__c objOrder;
        if(recordId != null){
            String strObjectId = findObjectNameFromRecordIdPrefix(recordId);
            String strQuery = 'SELECT POD__c, LargeOrderStatus__c, Is_Large_Order__c FROM Ops_Order__c';
            if(strObjectId == 'Ops_Order__c')
            {
                objOrder = Database.query(strQuery+' WHERE Id = \''+recordId+'\'');
            }
            else if(strObjectId == 'Job__c')
            {
                objOrder = Database.query(strQuery+' WHERE Id IN (SELECT OrderID__c FROM Job__c WHERE Id = \''+recordId+'\')');
            }
        }

        return objOrder;
    }
    
    /**
     * @description get the Sobject type of the some Id
     * @param recordIdOrPrefix id of the record
     * @return the Sobject type of the some Id
     */
    public static String findObjectNameFromRecordIdPrefix(String recordIdOrPrefix){
        String objectName = '';
        try{
            String myIdPrefix = String.valueOf(recordIdOrPrefix).substring(0,3);
            Map<String, Schema.SObjectType> gd =  Schema.getGlobalDescribe(); 

            for(Schema.SObjectType stype : gd.values()){
                Schema.DescribeSObjectResult r = stype.getDescribe();
                String prefix = r.getKeyPrefix();
                if(prefix!=null && prefix.equals(myIdPrefix)){
                    objectName = r.getName();
                    break;
                }
            }
        }catch(Exception e){
            System.debug(e);
        }
        return objectName;
    }
}