unpackaged/main/default/objects/Case/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Job ID Associated with the Case</description>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/recordTypes/Sourcing.recordType-meta.xml
<RecordType>
    <fullName>Sourcing</fullName>
    <active>true</active>
    <businessProcess>GNO Sourcing Team</businessProcess>
    <description>Cases for jobs that were cancelled, rejected, expired or need to be remade.</description>
    <label>Sourcing</label>
</RecordType>

unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>GNO Jobs</description>
    <label>Job</label>
    <nameField>
        <label>Job ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/Open_Cases__c.field-meta.xml
<CustomField>
    <fullName>Open_Cases__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Open Cases</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/JobRollUpOpenCasesBatch.cls
global class JobRollUpOpenCasesBatch implements Database.Batchable<sObject> {
    static final String PROJECT_BATCH_METHOD_NAME = 'JobRollUpOpenCasesBatch.execute';
    static final String PROJECT_BATCH_DEV_NOTE = 'Keep Job__c in sync with the amount of Cases';

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([SELECT Id FROM Job__c]);
    }

    global void execute(Database.BatchableContext BC, List<Job__c> scope) {
        Map<Id, Job__c> jobsMap = new Map<Id, Job__c>();
        for (Job__c j : scope) {
            j.Open_Cases__c = 0;
            jobsMap.put(j.Id, j);
        }

        for (AggregateResult aggRes : [
            SELECT Job__c, count(Id) OpenCases
            FROM Case
            WHERE RecordType.Name = 'Sourcing' AND Status != 'Closed' AND Job__c IN :jobsMap.keySet()
            GROUP BY Job__c
            HAVING count(Id) > 0
        ]) {
            jobsMap.get((Id) aggRes.get('Job__c')).Open_Cases__c = (Integer) aggRes.get('OpenCases');
        }

        DatabaseUtilities.upsertToDatabase(jobsMap.values(), PROJECT_BATCH_METHOD_NAME, PROJECT_BATCH_DEV_NOTE);
    }

    global void finish(Database.BatchableContext BC) {
    }
}