unpackaged/main/default/objects/Case/fields/LineItemCount__c.field-meta.xml
<CustomField>
    <fullName>LineItemCount__c</fullName>
    <label>Line Item Count (Old)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created During PSE Service Migration Project</description>
    <inlineHelpText>Opportunity Related to the Case</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Total_Amount_Opps__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Opps__c</fullName>
    <label>Total Opps Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Total_LineItem_Opps__c.field-meta.xml
<CustomField>
    <fullName>Total_LineItem_Opps__c</fullName>
    <label>Total Line Item Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Total_Quantity_Opps__c.field-meta.xml
<CustomField>
    <fullName>Total_Quantity_Opps__c</fullName>
    <label>Total # of opps</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/TotalAmountClosedLostOpps__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountClosedLostOpps__c</fullName>
    <label>Total Closed Lost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/TotalAmountClosedWonOpps__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountClosedWonOpps__c</fullName>
    <label>Total Closed Won</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/CaseOpportunity__c/CaseOpportunity__c.object-meta.xml
<CustomObject>
    <description>Junction object between Opportunities and Cases to allow many to many relations.</description>
    <label>CaseOpportunity</label>
    <nameField>
        <label>CaseOpportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CaseOpportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CaseOpportunity__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>CaseOpportunities</relationshipLabel>
    <relationshipName>CaseOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CaseOpportunity__c/fields/IsPrimaryOppOnCase__c.field-meta.xml
<CustomField>
    <fullName>IsPrimaryOppOnCase__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Mark Primary Opportunity on the Case</description>
    <label>IsPrimaryOppOnCase</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/CaseOpportunity__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>CaseOpportunities</relationshipLabel>
    <relationshipName>CaseOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CaseOpportunity__c/fields/Xometry_ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>Xometry_ERP_ID__c</fullName>
    <label>Quote ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Last_Quote_Xometry_ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>Last_Quote_Xometry_ERP_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>The Last Quote associated to this Opportunity</inlineHelpText>
    <label>Quote ID</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/LineItemCount__c.field-meta.xml
<CustomField>
    <fullName>LineItemCount__c</fullName>
    <label>Line Item Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Quote_ERP_XOM_CREATE_ID__c.field-meta.xml
<CustomField>
    <fullName>Quote_ERP_XOM_CREATE_ID__c</fullName>
    <description>This field is ERP Quote that initially created the Opportunity. The quote here is the initial quote in the process that started the opporutnity.</description>
    <externalId>true</externalId>
    <inlineHelpText>Auto populated by Quote_ERP__C trigger when a Quote creates an new</inlineHelpText>
    <label>Original Quote ID</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Total_Amt_BinderJetting__c.field-meta.xml
<CustomField>
    <fullName>Total_Amt_BinderJetting__c</fullName>
    <label>Total Amt BinderJetting</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Total_Amt_Carbon__c.field-meta.xml
<CustomField>
    <fullName>Total_Amt_Carbon__c</fullName>
    <label>Total Amt Carbon</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Total_Amt_CNC__c.field-meta.xml
<CustomField>
    <fullName>Total_Amt_CNC__c</fullName>
    <label>Total Amt CNC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Total_Amt_DieCasting__c.field-meta.xml
<CustomField>
    <fullName>Total_Amt_DieCasting__c</fullName>
    <label>Total Amt DieCasting</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Total_Amt_DirectSourced__c.field-meta.xml
<CustomField>
    <fullName>Total_Amt_DirectSourced__c</fullName>
    <label>Total Amt DirectSourced</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Total_Amt_DMLS__c.field-meta.xml
<CustomField>
    <fullName>Total_Amt_DMLS__c</fullName>
    <label>Total Amt DMLS</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Total_Amt_Extrusion__c.field-meta.xml
<CustomField>
    <fullName>Total_Amt_Extrusion__c</fullName>
    <label>Total Amt Metal Extrusion</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Total_Amt_FDM__c.field-meta.xml
<CustomField>
    <fullName>Total_Amt_FDM__c</fullName>
    <label>Total Amt FDM</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Total_Amt_HPMultJetFusion__c.field-meta.xml
<CustomField>
    <fullName>Total_Amt_HPMultJetFusion__c</fullName>
    <label>Total Amt HPMultJetFusion</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Total_Amt_InjectionMolding__c.field-meta.xml
<CustomField>
    <fullName>Total_Amt_InjectionMolding__c</fullName>
    <label>Total Amt InjectionMolding</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Total_Amt_InjectionMoldingTool__c.field-meta.xml
<CustomField>
    <fullName>Total_Amt_InjectionMoldingTool__c</fullName>
    <label>Total Amt InjectionMoldingTool</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Total_Amt_PolyJet3D__c.field-meta.xml
<CustomField>
    <fullName>Total_Amt_PolyJet3D__c</fullName>
    <label>Total Amt PolyJet3D</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Total_Amt_SheetCutting__c.field-meta.xml
<CustomField>
    <fullName>Total_Amt_SheetCutting__c</fullName>
    <label>Total Amt SheetCutting</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Total_Amt_SheetMetal__c.field-meta.xml
<CustomField>
    <fullName>Total_Amt_SheetMetal__c</fullName>
    <label>Total Amt SheetMetal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Total_Amt_SLA__c.field-meta.xml
<CustomField>
    <fullName>Total_Amt_SLA__c</fullName>
    <label>Total Amt SLA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Total_Amt_SLS__c.field-meta.xml
<CustomField>
    <fullName>Total_Amt_SLS__c</fullName>
    <label>Total Amt SLS</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Total_Amt_Stamping__c.field-meta.xml
<CustomField>
    <fullName>Total_Amt_Stamping__c</fullName>
    <label>Total Amt Stamping</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Total_Amt_UrethaneCasting__c.field-meta.xml
<CustomField>
    <fullName>Total_Amt_UrethaneCasting__c</fullName>
    <label>Total Amt UrethaneCasting</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/Quote_ERP__c.object-meta.xml
<CustomObject>
    <description>A quote that is sent over from ERP</description>
    <label>Quote ERP</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote_ERP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes ERP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Quote_ERP__c/fields/Account_Domain__c.field-meta.xml
<CustomField>
    <fullName>Account_Domain__c</fullName>
    <description>The domain associated with an account. For generics this will still be a generic domain.</description>
    <label>Account Domain</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/ERP_Contact__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact__c</fullName>
    <description>The ERP Contact identifier that is used to lookup the unique contact on a quote in the ERP.</description>
    <label>ERP Contact ID</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/ERP_PartPK__c.field-meta.xml
<CustomField>
    <fullName>ERP_PartPK__c</fullName>
    <description>A unique concatenation of Parts that will link to Opportunities and Leads</description>
    <label>ERP PartPK</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/IS_Generic__c.field-meta.xml
<CustomField>
    <fullName>IS_Generic__c</fullName>
    <defaultValue>false</defaultValue>
    <description>A checkbox associated whether the quote ties to a a generic email or not.</description>
    <label>IS Generic</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Quote_Email__c.field-meta.xml
<CustomField>
    <fullName>Quote_Email__c</fullName>
    <description>The email that is associated with the quote.</description>
    <label>Quote Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Quote_ERP_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Quote_ERP_Created_Date__c</fullName>
    <description>The date the quote was created in the ERP system</description>
    <label>Quote Created Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Quote_Price__c.field-meta.xml
<CustomField>
    <fullName>Quote_Price__c</fullName>
    <description>The estimated price of the quote</description>
    <label>Quote Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Requested_Manual_Quote_Flag__c.field-meta.xml
<CustomField>
    <fullName>Requested_Manual_Quote_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to allow for Case firings for PSE team.</description>
    <label>Requested Manual Quote Flag</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Requested_Manual_Quote_Time__c.field-meta.xml
<CustomField>
    <fullName>Requested_Manual_Quote_Time__c</fullName>
    <description>The first time the status in the erp became 'RFQ submitted'</description>
    <label>Requested Manual Quote Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Xometry_ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>Xometry_ERP_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Unique Qoute ID created in Xometry ERP</description>
    <externalId>true</externalId>
    <label>Quote ID</label>
    <length>13</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/CaseOpportunityHandlerTest.cls
@isTest
private class CaseOpportunityHandlerTest {
    @isTest(seeAllData=false)
    static void keepRelationsUpdatedTest() {
        Quote_ERP__c testQuote = new Quote_ERP__C(
            Account_Domain__C = 'SuperAccount',
            ERP_PartPK__c = 'A1234-A5678',
            Quote_Price__c = 50.15,
            Xometry_ERP_ID__C = 'Q01-0000-1111',
            ERP_Contact__c = 'AAAAA',
            IS_Generic__c = false,
            Quote_Email__c = 'johndoe@superaccount.com',
            Quote_ERP_Created_Date__c = Date.newInstance(2021, 6, 14),
            Requested_Manual_Quote_Flag__c = true,
            Requested_Manual_Quote_Time__C = DateTime.newInstance(2021, 5, 21, 6, 0, 0)
        );
        insert testQuote;

        Id caseId = [SELECT Id FROM Case LIMIT 1].Id;
        Id testOppId = [SELECT Id FROM Opportunity WHERE Quote_ERP_XOM_CREATE_ID__c = 'Q01-0000-1111' LIMIT 1].Id;

        Test.startTest();

        insert new CaseOpportunity__c(Case__c = caseId, Xometry_ERP_ID__c = 'Q01-0000-1111');

        Test.stopTest();

        CaseOpportunity__c caseOppAfter = [SELECT Opportunity__c FROM CaseOpportunity__c LIMIT 1];
        System.assertEquals(
            testOppId,
            caseOppAfter.Opportunity__c,
            'Junction should be linked to the Opp with the same ERP Id'
        );
    }

    @isTest(seeAllData=false)
    static void renameOnCreateTest() {
        Quote_ERP__c testQuote = new Quote_ERP__C(
            Account_Domain__C = 'SuperAccount',
            ERP_PartPK__c = 'A1234-A5678',
            Quote_Price__c = 50.15,
            Xometry_ERP_ID__C = 'Q01-0000-1111',
            ERP_Contact__c = 'AAAAA',
            IS_Generic__c = false,
            Quote_Email__c = 'johndoe@superaccount.com',
            Quote_ERP_Created_Date__c = Date.newInstance(2021, 6, 14),
            Requested_Manual_Quote_Flag__c = true,
            Requested_Manual_Quote_Time__C = DateTime.newInstance(2021, 5, 21, 6, 0, 0)
        );
        insert testQuote;

        Case testCase = [SELECT Id, CaseNumber FROM Case LIMIT 1];
        Id testOppId = [SELECT Id FROM Opportunity WHERE Quote_ERP_XOM_CREATE_ID__c = 'Q01-0000-1111' LIMIT 1].Id;

        Test.startTest();

        insert new CaseOpportunity__c(Case__c = testCase.Id, Xometry_ERP_ID__c = 'Q01-0000-1111');

        Test.stopTest();

        System.assertEquals(
            testCase.CaseNumber +
            '-' +
            testQuote.Xometry_ERP_ID__C,
            [SELECT Name FROM CaseOpportunity__c LIMIT 1]
            .Name,
            'Junction should be renamed'
        );
    }

    @isTest(seeAllData=false)
    static void renameOnCreate2Test() {
        Opportunity opp = new Opportunity(Name = 'Test');
        opp.StageName = 'Open';
        opp.CloseDate = System.today().addDays(10);
        insert opp;

        Case testCase = new Case(Opportunity__c = opp.Id);

        Test.startTest();
        insert testCase;
        Test.stopTest();

        testCase = [SELECT Id, CaseNumber FROM Case LIMIT 1];

        System.assertEquals(
            testCase.CaseNumber,
            [SELECT Name FROM CaseOpportunity__c LIMIT 1]
            .Name,
            'Junction should be renamed'
        );
    }

    @isTest(seeAllData=false)
    static void testKeepTotalFieldsCase() {
        List<Opportunity> lstOpportunities = new List<Opportunity>();
        List<Case> lstCases = new List<Case>();

        Opportunity opp = new Opportunity();
        opp.Name = 'Test';
        opp.StageName = 'Closed Won';
        opp.Amount = 100;
        opp.LineItemCount__c = 2;
        opp.Total_Amt_BinderJetting__c = 200;
        opp.Total_Amt_Carbon__c = 300;
        opp.Total_Amt_CNC__c = 400;
        opp.CloseDate = System.today().addDays(10);
        lstOpportunities.add(opp);

        Opportunity opp1 = new Opportunity();
        opp1.Name = 'Test1';
        opp1.StageName = 'Closed Lost';
        opp1.Amount = 100;
        opp1.LineItemCount__c = 2;
        opp1.Total_Amt_DieCasting__c = 200;
        opp1.Total_Amt_DirectSourced__c = 300;
        opp1.Total_Amt_DMLS__c = 400;
        opp1.CloseDate = System.today().addDays(10);
        lstOpportunities.add(opp1);

        Opportunity opp2 = new Opportunity();
        opp2.Name = 'Test2';
        opp2.StageName = 'Closed Won';
        opp2.Amount = 100;
        opp2.LineItemCount__c = 2;
        opp2.Total_Amt_Extrusion__c = 100;
        opp2.Total_Amt_FDM__c = 200;
        opp2.Total_Amt_HPMultJetFusion__c = 300;
        opp2.Total_Amt_InjectionMolding__c = 400;
        opp2.CloseDate = System.today().addDays(10);
        lstOpportunities.add(opp2);

        Opportunity opp3 = new Opportunity();
        opp3.Name = 'Test3';
        opp3.StageName = 'Closed Lost';
        opp3.Amount = 100;
        opp3.LineItemCount__c = 2;
        opp3.Total_Amt_InjectionMoldingTool__c = 100;
        opp3.Total_Amt_PolyJet3D__c = 300;
        opp3.Total_Amt_SheetCutting__c = 400;
        opp3.CloseDate = System.today().addDays(10);
        lstOpportunities.add(opp3);

        Opportunity opp4 = new Opportunity(Name = 'Test4');
        opp4.StageName = 'Open';
        opp4.Amount = 100;
        opp4.LineItemCount__c = 2;
        opp4.Total_Amt_SheetMetal__c = 100;
        opp4.Total_Amt_SLA__c = 200;
        opp4.Total_Amt_SLS__c = 300;
        opp4.CloseDate = System.today().addDays(10);
        lstOpportunities.add(opp4);

        Opportunity opp5 = new Opportunity(Name = 'Test5');
        opp5.StageName = 'Open';
        opp5.Amount = 100;
        opp5.LineItemCount__c = 2;
        opp5.Total_Amt_Stamping__c = 100;
        opp5.Total_Amt_UrethaneCasting__c = 200;
        opp5.CloseDate = System.today().addDays(10);
        lstOpportunities.add(opp5);
        insert lstOpportunities;

        Case testCase = new Case(Opportunity__c = opp.Id);
        lstCases.add(testCase);

        Case testCase1 = new Case(Opportunity__c = opp1.Id);
        lstCases.add(testCase1);

        Case testCase2 = new Case(Opportunity__c = opp2.Id);
        lstCases.add(testCase2);

        Case testCase3 = new Case(Opportunity__c = opp.Id);
        lstCases.add(testCase3);

        Test.startTest();
        insert lstCases;

        lstCases[0].Opportunity__c = opp3.Id;
        update lstCases[0];

        lstCases[0].Opportunity__c = opp4.Id;
        update lstCases[0];

        lstCases[1].Opportunity__c = opp5.Id;
        update lstCases[1];
        Test.stopTest();

        testCase = [
            SELECT
                Id,
                Total_Amount_Opps__c,
                Total_LineItem_Opps__c,
                Total_Quantity_Opps__c,
                TotalAmountClosedWonOpps__c,
                TotalAmountClosedLostOpps__c
            FROM Case
            WHERE Id = :lstCases[0].Id
            LIMIT 1
        ];
        testCase1 = [
            SELECT
                Id,
                Total_Amount_Opps__c,
                Total_LineItem_Opps__c,
                Total_Quantity_Opps__c,
                TotalAmountClosedWonOpps__c,
                TotalAmountClosedLostOpps__c
            FROM Case
            WHERE Id = :lstCases[1].Id
            LIMIT 1
        ];
        testCase2 = [
            SELECT
                Id,
                Total_Amount_Opps__c,
                Total_LineItem_Opps__c,
                Total_Quantity_Opps__c,
                TotalAmountClosedWonOpps__c,
                TotalAmountClosedLostOpps__c
            FROM Case
            WHERE Id = :lstCases[2].Id
            LIMIT 1
        ];
        testCase3 = [
            SELECT
                Id,
                Total_Amount_Opps__c,
                Total_LineItem_Opps__c,
                Total_Quantity_Opps__c,
                TotalAmountClosedWonOpps__c,
                TotalAmountClosedLostOpps__c
            FROM Case
            WHERE Id = :lstCases[3].Id
            LIMIT 1
        ];

        System.assertEquals(3, testCase.Total_Quantity_Opps__c, 'The number of opportunities does not match');
        System.assertEquals(
            6,
            testCase.Total_LineItem_Opps__c,
            'The total line item quantity of opportunities does not match'
        );
        System.assertEquals(300, testCase.Total_Amount_Opps__c, 'The total amount of opportunities does not match');
        System.assertEquals(
            100,
            testCase.TotalAmountClosedWonOpps__c,
            'The total amount of opportunities won does not match'
        );
        System.assertEquals(
            100,
            testCase.TotalAmountClosedLostOpps__c,
            'The total amount of opportunities lost does not match'
        );

        System.assertEquals(2, testCase1.Total_Quantity_Opps__c, 'The number of opportunities does not match');
        System.assertEquals(
            4,
            testCase1.Total_LineItem_Opps__c,
            'The total line item quantity of opportunities does not match'
        );
        System.assertEquals(200, testCase1.Total_Amount_Opps__c, 'The total amount of opportunities does not match');
        System.assertEquals(
            0,
            testCase1.TotalAmountClosedWonOpps__c,
            'The total amount of opportunities won does not match'
        );
        System.assertEquals(
            100,
            testCase1.TotalAmountClosedLostOpps__c,
            'The total amount of opportunities lost does not match'
        );

        System.assertEquals(1, testCase2.Total_Quantity_Opps__c, 'The number of opportunities does not match');
        System.assertEquals(
            2,
            testCase2.Total_LineItem_Opps__c,
            'The total line item quantity of opportunities does not match'
        );
        System.assertEquals(100, testCase2.Total_Amount_Opps__c, 'The total amount of opportunities does not match');
        System.assertEquals(
            100,
            testCase2.TotalAmountClosedWonOpps__c,
            'The total amount of opportunities won does not match'
        );
        System.assertEquals(
            0,
            testCase2.TotalAmountClosedLostOpps__c,
            'The total amount of opportunities lost does not match'
        );

        System.assertEquals(1, testCase3.Total_Quantity_Opps__c, 'The number of opportunities does not match');
        System.assertEquals(
            2,
            testCase3.Total_LineItem_Opps__c,
            'The total line item quantity of opportunities does not match'
        );
        System.assertEquals(100, testCase3.Total_Amount_Opps__c, 'The total amount of opportunities does not match');
        System.assertEquals(
            100,
            testCase3.TotalAmountClosedWonOpps__c,
            'The total amount of opportunities won does not match'
        );
        System.assertEquals(
            0,
            testCase3.TotalAmountClosedLostOpps__c,
            'The total amount of opportunities lost does not match'
        );
    }

    @isTest(seeAllData=false)
    static void testKeepTotalFieldsCase_Delete() {
        List<Opportunity> lstOpportunities = new List<Opportunity>();

        Opportunity opp = new Opportunity(Name = 'Test');
        opp.StageName = 'Closed Won';
        opp.Amount = 100;
        opp.LineItemCount__c = 2;
        opp.CloseDate = System.today().addDays(10);
        opp.Total_Amt_BinderJetting__c = 100;
        opp.Total_Amt_Carbon__c = 100;
        opp.Total_Amt_CNC__c = 100;
        opp.Total_Amt_DieCasting__c = 100;
        opp.Total_Amt_DirectSourced__c = 100;
        opp.Total_Amt_DMLS__c = 100;
        lstOpportunities.add(opp);

        Opportunity opp1 = new Opportunity(Name = 'Test1');
        opp1.StageName = 'Closed Lost';
        opp1.Amount = 100;
        opp1.LineItemCount__c = 2;
        opp1.CloseDate = System.today().addDays(10);
        opp1.Total_Amt_BinderJetting__c = 100;
        opp1.Total_Amt_Carbon__c = 100;
        opp1.Total_Amt_CNC__c = 100;
        opp1.Total_Amt_DieCasting__c = 100;
        opp1.Total_Amt_DirectSourced__c = 100;
        opp1.Total_Amt_DMLS__c = 100;
        lstOpportunities.add(opp1);

        insert lstOpportunities;

        Case testCase = new Case(Opportunity__c = opp.Id);
        insert testCase;

        testCase.Opportunity__c = opp1.Id;
        update testCase;

        testCase = [
            SELECT
                Id,
                Total_Amount_Opps__c,
                Total_LineItem_Opps__c,
                Total_Quantity_Opps__c,
                TotalAmountClosedWonOpps__c,
                TotalAmountClosedLostOpps__c
            FROM Case
            WHERE Id = :testCase.Id
            LIMIT 1
        ];

        CaseOpportunity__c objCaseOppsDel = [
            SELECT Id
            FROM CaseOpportunity__c
            WHERE Case__c = :testCase.Id AND Opportunity__c = :lstOpportunities[0].Id
        ];

        Test.startTest();
        delete objCaseOppsDel;
        Test.stopTest();

        testCase = [
            SELECT
                Id,
                Total_Amount_Opps__c,
                Total_LineItem_Opps__c,
                Total_Quantity_Opps__c,
                TotalAmountClosedWonOpps__c,
                TotalAmountClosedLostOpps__c
            FROM Case
            WHERE Id = :testCase.Id
            LIMIT 1
        ];

        System.assertEquals(1, testCase.Total_Quantity_Opps__c, 'The number of opportunities does not match');
        System.assertEquals(
            2,
            testCase.Total_LineItem_Opps__c,
            'The total line item quantity of opportunities does not match'
        );
        System.assertEquals(100, testCase.Total_Amount_Opps__c, 'The total amount of opportunities does not match');
        System.assertEquals(
            0,
            testCase.TotalAmountClosedWonOpps__c,
            'The total amount of opportunities won does not match'
        );
        System.assertEquals(
            100,
            testCase.TotalAmountClosedLostOpps__c,
            'The total amount of opportunities lost does not match'
        );
    }

    @isTest(seeAllData=false)
    static void updateRelatedCaseTest() {
        Opportunity opp = new Opportunity(Name = 'Test');
        opp.StageName = 'Open';
        opp.CloseDate = System.today().addDays(10);
        opp.Last_Quote_Xometry_ERP_ID__c = 'AAAAA-00001';

        Opportunity opp2 = new Opportunity(Name = 'Test2');
        opp2.StageName = 'Open';
        opp2.CloseDate = System.today().addDays(11);
        opp2.Last_Quote_Xometry_ERP_ID__c = 'AAAAA-00002';

        insert new List<Opportunity>{ opp, opp2 };

        Case testCase = new Case(SuppliedEmail = 'test@xomtest.com');
        Case testCase2 = new Case(SuppliedEmail = 'test2@xomtest.com');
        insert new List<Case>{ testCase, testCase2 };

        CaseOpportunity__c caseOppTest = new CaseOpportunity__c(
            Xometry_ERP_ID__c = 'AAAAA-00002',
            IsPrimaryOppOnCase__c = true,
            Opportunity__c = opp2.Id,
            Case__c = testCase.Id
        );
        CaseOpportunity__c caseOppTest2 = new CaseOpportunity__c(
            Xometry_ERP_ID__c = 'AAAAA-00002',
            IsPrimaryOppOnCase__c = true,
            Opportunity__c = opp2.Id,
            Case__c = testCase2.Id
        );
        insert new List<CaseOpportunity__c>{ caseOppTest, caseOppTest2 };

        CaseOpportunity__c caseOppTest3 = new CaseOpportunity__c(
            Xometry_ERP_ID__c = 'AAAAA-00001',
            IsPrimaryOppOnCase__c = true,
            Opportunity__c = opp.Id,
            Case__c = testCase.Id
        );

        Test.startTest();
        insert caseOppTest3;
        Test.stopTest();

        Map<Id, Case> testCaseResult = new Map<Id, Case>([SELECT Id, Opportunity__c FROM Case]);

        System.assertEquals(opp.Id, testCaseResult.get(testCase.Id).Opportunity__c, 'Case should be updated');
        System.assertEquals(opp2.Id, testCaseResult.get(testCase2.Id).Opportunity__c, 'Case should not be updated');

        Map<Id, CaseOpportunity__c> testCaseOppResult = new Map<Id, CaseOpportunity__c>(
            [SELECT Id, IsPrimaryOppOnCase__c FROM CaseOpportunity__c]
        );
        System.assertEquals(
            true,
            testCaseOppResult.get(caseOppTest2.Id).IsPrimaryOppOnCase__c,
            'CaseOpp should be updated'
        );
        System.assertEquals(
            false,
            testCaseOppResult.get(caseOppTest.Id).IsPrimaryOppOnCase__c,
            'CaseOpp should be updated'
        );
    }
}