unpackaged/main/default/objects/Case/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created During PSE Service Migration Project</description>
    <inlineHelpText>Opportunity Related to the Case</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/PSE_Form__c.field-meta.xml
<CustomField>
    <fullName>PSE_Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PSE Form</label>
    <referenceTo>PSE_Form__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Last_Quote_Xometry_ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>Last_Quote_Xometry_ERP_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>The Last Quote associated to this Opportunity</inlineHelpText>
    <label>Quote ID</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/PSE_Form__c/PSE_Form__c.object-meta.xml
<CustomObject>
    <description>Manual Quote Forms that gather additional information when a customer needs a Manual Quote created.
Currently, only applies to IM, CNC, Additive, and Die Casting (2021-04-29)
Currently, the forms exist in Hubspot and are being connected to Salesforce via Hubspot -&gt; Snowflake -&gt; Workato -&gt; Salesforce (2021-04-29)</description>
    <label>PSE Form</label>
    <nameField>
        <displayFormat>PSE Form # {00000000}</displayFormat>
        <label>PSE Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSE Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/PSE_Form__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>ORIGINAL Case that the Quote is/was associated with.</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>PSE Forms</relationshipLabel>
    <relationshipName>PSE_Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/PSE_Form__c/fields/Quote_ERP__c.field-meta.xml
<CustomField>
    <fullName>Quote_ERP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote ERP</label>
    <referenceTo>Quote_ERP__c</referenceTo>
    <relationshipLabel>PSE Forms</relationshipLabel>
    <relationshipName>PSE_Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/PSE_Form__c/fields/Quote_ID__c.field-meta.xml
<CustomField>
    <fullName>Quote_ID__c</fullName>
    <externalId>true</externalId>
    <label>Quote ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/Quote_ERP__c.object-meta.xml
<CustomObject>
    <description>A quote that is sent over from ERP</description>
    <label>Quote ERP</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote_ERP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes ERP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Quote_ERP__c/fields/Account_Domain__c.field-meta.xml
<CustomField>
    <fullName>Account_Domain__c</fullName>
    <description>The domain associated with an account. For generics this will still be a generic domain.</description>
    <label>Account Domain</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/ERP_Contact__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact__c</fullName>
    <description>The ERP Contact identifier that is used to lookup the unique contact on a quote in the ERP.</description>
    <label>ERP Contact ID</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/ERP_Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contact_Last_Name__c</fullName>
    <label>ERP Contact Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/ERP_PartPK__c.field-meta.xml
<CustomField>
    <fullName>ERP_PartPK__c</fullName>
    <description>A unique concatenation of Parts that will link to Opportunities and Leads</description>
    <label>ERP PartPK</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/IS_Generic__c.field-meta.xml
<CustomField>
    <fullName>IS_Generic__c</fullName>
    <defaultValue>false</defaultValue>
    <description>A checkbox associated whether the quote ties to a a generic email or not.</description>
    <label>IS Generic</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Quote_Email__c.field-meta.xml
<CustomField>
    <fullName>Quote_Email__c</fullName>
    <description>The email that is associated with the quote.</description>
    <label>Quote Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Quote_ERP_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Quote_ERP_Created_Date__c</fullName>
    <description>The date the quote was created in the ERP system</description>
    <label>Quote Created Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Quote_Price__c.field-meta.xml
<CustomField>
    <fullName>Quote_Price__c</fullName>
    <description>The estimated price of the quote</description>
    <label>Quote Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Requested_Manual_Quote_Flag__c.field-meta.xml
<CustomField>
    <fullName>Requested_Manual_Quote_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to allow for Case firings for PSE team.</description>
    <label>Requested Manual Quote Flag</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Requested_Manual_Quote_Time__c.field-meta.xml
<CustomField>
    <fullName>Requested_Manual_Quote_Time__c</fullName>
    <description>The first time the status in the erp became 'RFQ submitted'</description>
    <label>Requested Manual Quote Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Xometry_ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>Xometry_ERP_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Unique Qoute ID created in Xometry ERP</description>
    <externalId>true</externalId>
    <label>Quote ID</label>
    <length>13</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/PSEFormBatchTest.cls
@isTest
public class PSEFormBatchTest {
    @TestSetup
    private static void setup() {
        Quote_ERP__c quote = new Quote_ERP__C(
            Account_Domain__C = 'SuperCompany2.com',
            ERP_PartPK__c = 'A1234-A5678',
            Quote_Price__c = 50.15,
            Xometry_ERP_ID__C = 'AAAAA-00001',
            ERP_Contact__c = 'AAAAA',
            IS_Generic__c = false,
            Quote_Email__c = 'johndoe@SuperCompany2.com',
            Quote_ERP_Created_Date__c = Date.newInstance(2021, 6, 14),
            ERP_Contact_Last_Name__c = 'Doe',
            Requested_Manual_Quote_Flag__c = true,
            Requested_Manual_Quote_Time__C = dateTime.newInstanceGMT(2021, 7, 21, 0, 0, 0)
        );

        PSE_Form__c pse_withFutureQuote = new PSE_Form__c(Quote_ID__c = 'AAAAA-00001');
        PSE_Form__c pse_noQuote = new PSE_Form__c(Quote_ID__c = 'AAAAA-00002');
        PSE_Form__c pse_nullQuote = new PSE_Form__c(Quote_ID__c = null);

        insert pse_withFutureQuote;
        insert pse_noQuote;
        insert pse_nullQuote;

        insert quote;
    }

    @isTest
    static void PSEFormBatchTest() {
        Test.startTest();
        PSEFormBatch batch = new PSEFormBatch();
        Database.executeBatch(batch);
        Test.stopTest();

        List<PSE_Form__c> pseForms = [
            SELECT Id, Quote_ERP__c, Quote_ID__c, Case__c
            FROM PSE_Form__c
            ORDER BY Quote_ID__c NULLS LAST
        ];

        List<Case> resultCase = [
            SELECT Id, PSE_Form__c, Opportunity__r.Last_Quote_Xometry_ERP_ID__c
            FROM Case
            WHERE Opportunity__r.Last_Quote_Xometry_ERP_ID__c = :pseForms[0].Quote_ID__c
        ];

        // future form match
        System.assertEquals('AAAAA-00001', pseForms[0].Quote_ID__c, 'Quote Id does not match');
        System.assertNotEquals(null, pseForms[0].Quote_ERP__c, 'Quote lookup should not be null');

        // future form case match
        System.assertEquals(1, resultCase.size(), 'There should only be one created Case');
        System.assertNotEquals(null, resultCase[0].PSE_Form__c, 'Lookup should not be null');
        System.assertEquals(
            pseForms[0].Id,
            resultCase[0].PSE_Form__c,
            'Form Lookup should match Form with matching id'
        );
        System.assertEquals(
            resultCase[0].Id,
            pseForms[0].Case__c,
            'Case Lookup should match Case with matching id'
        );

        // no quote no match

        System.assertEquals('AAAAA-00002', pseForms[1].Quote_ID__c, 'Quote Id does not match');
        System.assertEquals(null, pseForms[1].Quote_ERP__c, 'Quote Id should be set to null');

        // null quote no match
        System.assertEquals(null, pseForms[2].Quote_ID__c, 'Quote Id does not match');
        System.assertEquals(null, pseForms[2].Quote_ERP__c, 'Quote Id should be set to null');
    }
}