unpackaged/main/default/objects/Case/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created During PSE Service Migration Project</description>
    <inlineHelpText>Opportunity Related to the Case</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/PSE_Form__c.field-meta.xml
<CustomField>
    <fullName>PSE_Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PSE Form</label>
    <referenceTo>PSE_Form__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Last_Quote_Xometry_ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>Last_Quote_Xometry_ERP_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>The Last Quote associated to this Opportunity</inlineHelpText>
    <label>Quote ID</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/PSE_Form__c/PSE_Form__c.object-meta.xml
<CustomObject>
    <description>Manual Quote Forms that gather additional information when a customer needs a Manual Quote created.
Currently, only applies to IM, CNC, Additive, and Die Casting (2021-04-29)
Currently, the forms exist in Hubspot and are being connected to Salesforce via Hubspot -&gt; Snowflake -&gt; Workato -&gt; Salesforce (2021-04-29)</description>
    <label>PSE Form</label>
    <nameField>
        <displayFormat>PSE Form # {00000000}</displayFormat>
        <label>PSE Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSE Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/PSE_Form__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>ORIGINAL Case that the Quote is/was associated with.</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>PSE Forms</relationshipLabel>
    <relationshipName>PSE_Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/PSE_Form__c/fields/Quote_ERP__c.field-meta.xml
<CustomField>
    <fullName>Quote_ERP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote ERP</label>
    <referenceTo>Quote_ERP__c</referenceTo>
    <relationshipLabel>PSE Forms</relationshipLabel>
    <relationshipName>PSE_Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/PSE_Form__c/fields/Quote_ID__c.field-meta.xml
<CustomField>
    <fullName>Quote_ID__c</fullName>
    <externalId>true</externalId>
    <label>Quote ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/Quote_ERP__c.object-meta.xml
<CustomObject>
    <description>A quote that is sent over from ERP</description>
    <label>Quote ERP</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote_ERP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes ERP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Quote_ERP__c/fields/Xometry_ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>Xometry_ERP_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Unique Qoute ID created in Xometry ERP</description>
    <externalId>true</externalId>
    <label>Quote ID</label>
    <length>13</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/PSEFormBatch.cls
global class PSEFormBatch implements Database.Batchable<sObject>, Database.Stateful {
    static final String PROJECT_BATCH_METHOD_NAME = 'ProjectBatch.execute';
    static final String PROJECT_BATCH_DEV_NOTE = 'Project Batch update';

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            [
                SELECT Id, Quote_ID__c, Case__c
                FROM PSE_Form__c
                WHERE (Quote_ERP__c = NULL OR (Quote_ERP__c != NULL AND Case__c = NULL)) AND Quote_ID__c != NULL
            ]
        );
    }

    global void execute(Database.BatchableContext bc, List<PSE_Form__c> scope) {
        Map<String, PSE_Form__c> quoteIdToPSEFormMap = new Map<String, PSE_Form__c>();
        Map<String, PSE_Form__c> pseFormUpdateMap = new Map<String, PSE_Form__c>();

        for (PSE_Form__c f : scope) {
            quoteIdToPSEFormMap.put(f.Quote_ID__c, f);
        }

        // These quotes may or may not be in the system. They were not during initial load for the Form
        for (Quote_ERP__C q : [
            SELECT Id, Xometry_ERP_ID__c
            FROM Quote_ERP__C
            WHERE Xometry_ERP_ID__c IN :quoteIdToPSEFormMap.keySet()
        ]) {
            PSE_FORM__C lPSEForm = quoteIdToPSEFormMap.get(q.Xometry_ERP_ID__c);

            lPSEForm.Quote_ERP__c = q.Id;
            pseFormUpdateMap.put(q.Xometry_ERP_ID__c, lPSEForm);
        }

        List<Case> casesToUpdate = new List<Case>();
        for (Case c : [
            SELECT Id, PSE_Form__c, Opportunity__r.Last_Quote_Xometry_ERP_ID__c
            FROM Case
            WHERE PSE_Form__c = NULL AND Opportunity__r.Last_Quote_Xometry_ERP_ID__c IN :quoteIdToPSEFormMap.keySet()
            ORDER BY Createddate ASC
        ]) {
            PSE_FORM__C existingPSEForm = quoteIdToPSEFormMap.get(c.Opportunity__r.Last_Quote_Xometry_ERP_ID__c);
            c.PSE_Form__c = existingPSEForm.Id;
            casesToUpdate.add(c);

            if (quoteIdToPSEFormMap.get(c.Opportunity__r.Last_Quote_Xometry_ERP_ID__c).Case__c == null) {
                PSE_Form__c lPSEForm = new PSE_Form__C();
                if (pseFormUpdateMap.containsKey(c.Opportunity__r.Last_Quote_Xometry_ERP_ID__c)) {
                    lPSEForm = pseFormUpdateMap.get(c.Opportunity__r.Last_Quote_Xometry_ERP_ID__c);
                } else {
                    lPSEForm = existingPSEForm;
                }
                lPSEForm.Case__c = c.Id;
                pseFormUpdateMap.put(c.Opportunity__r.Last_Quote_Xometry_ERP_ID__c, lPSEForm);
            }
        }

        DatabaseUtilities.saveToDatabase(
            pseFormUpdateMap.values(),
            'PSEFormBatch',
            'Update PSE Form with Quote Lookup'
        );

        DatabaseUtilities.saveToDatabase(
            casesToUpdate,
            'PSEFormBatch.updateAssociatedCase',
            'Failed to update PSE lookup to Case'
        );
    }

    global void finish(Database.BatchableContext bc) {
    }
}