unpackaged/main/default/objects/Case/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created During PSE Service Migration Project</description>
    <inlineHelpText>Opportunity Related to the Case</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CaseHistory__c/CaseHistory__c.object-meta.xml
<CustomObject>
    <label>Case Owner History</label>
    <nameField>
        <label>Case Owner History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Owner Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CaseHistory__c/fields/DurationMinutes__c.field-meta.xml
<CustomField>
    <fullName>DurationMinutes__c</fullName>
    <label>Duration (Minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/CaseHistory__c/fields/NewOwnerText__c.field-meta.xml
<CustomField>
    <fullName>NewOwnerText__c</fullName>
    <label>New Owner Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CaseHistory__c/fields/NewUserOwner__c.field-meta.xml
<CustomField>
    <fullName>NewUserOwner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New User Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>NewUserCasesHistory</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CaseHistory__c/fields/OldOwnerText__c.field-meta.xml
<CustomField>
    <fullName>OldOwnerText__c</fullName>
    <label>Old Owner Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CaseHistory__c/fields/OldUserOwner__c.field-meta.xml
<CustomField>
    <fullName>OldUserOwner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Old User Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases_History</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CaseHistory__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Case Owner Histories</relationshipLabel>
    <relationshipName>Case_Owner_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/BatchCaseHistoryRecalcLastInteractTest.cls
@isTest
private class BatchCaseHistoryRecalcLastInteractTest {

    @isTest(seeAllData=false)
    static void testMethod1() {

        User testUser2 = TestDataFactory.createTestUserSecond()[0];

        Opportunity testOpp = new Opportunity(Name = 'Test', CloseDate = Date.today(), StageName = 'Open');
        insert testOpp;
        
        Case testCase = new Case(SuppliedEmail = 'test@test.com', Opportunity__c = testOpp.Id);
        testCase.RecordTypeId = AppConstants.casePSERecordTypeId;
        insert testCase;

        Group objQueue = [SELECT Id, Name FROM Group WHERE Type = 'Queue' LIMIT 1];

        testCase.OwnerId = testUser2.Id;
        update testCase;

        List<CaseHistory__c> lstCaseHistry = [
            SELECT Id, OldOwnerText__c, NewOwnerText__c, OldUserOwner__c, NewUserOwner__c, DurationMinutes__c
            FROM CaseHistory__c
            ORDER BY Id DESC
        ];

        System.assertEquals( 1, lstCaseHistry.size() );

        Test.setCreatedDate(lstCaseHistry[0].Id, Datetime.now().addDays(-10));

        testCase.Status = 'In Progress';
        update testCase;

        lstCaseHistry = [
            SELECT Id, OldOwnerText__c, NewOwnerText__c, OldUserOwner__c, NewUserOwner__c, DurationMinutes__c
            FROM CaseHistory__c
            ORDER BY Id DESC
        ];

        testCase.OwnerId = UserInfo.getUserId();
        update testCase;

        lstCaseHistry = [
            SELECT Id, OldOwnerText__c, NewOwnerText__c, OldUserOwner__c, NewUserOwner__c, DurationMinutes__c
            FROM CaseHistory__c
            ORDER BY Id DESC
        ];

        lstCaseHistry[0].DurationMinutes__c = 0;
        update lstCaseHistry[0];

        test.StartTest();

        Database.executeBatch( new BatchCaseHistoryRecalcLastInteraction() );

        test.StopTest();

        lstCaseHistry = [
            SELECT Id, OldOwnerText__c, NewOwnerText__c, OldUserOwner__c, NewUserOwner__c, DurationMinutes__c
            FROM CaseHistory__c
            ORDER BY Id DESC
        ];

        System.assertNotEquals(
            0,
            lstCaseHistry[0].DurationMinutes__c,
            'The Duration of CaseHistory record was not populated'
        );

    }
}