unpackaged/main/default/objects/Case/fields/PSE_Form__c.field-meta.xml
<CustomField>
    <fullName>PSE_Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PSE Form</label>
    <referenceTo>PSE_Form__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/recordTypes/PSE_Case.recordType-meta.xml
<RecordType>
    <fullName>PSE_Case</fullName>
    <active>true</active>
    <businessProcess>PSE Support Process</businessProcess>
    <description>To request Quote pricing and configuration from PSE and/or Sales Operations</description>
    <label>PSE Case</label>
</RecordType>

unpackaged/main/default/objects/PSE_Form__c/PSE_Form__c.object-meta.xml
<CustomObject>
    <description>Manual Quote Forms that gather additional information when a customer needs a Manual Quote created.
Currently, only applies to IM, CNC, Additive, and Die Casting (2021-04-29)
Currently, the forms exist in Hubspot and are being connected to Salesforce via Hubspot -&gt; Snowflake -&gt; Workato -&gt; Salesforce (2021-04-29)</description>
    <label>PSE Form</label>
    <nameField>
        <displayFormat>PSE Form # {00000000}</displayFormat>
        <label>PSE Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSE Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/PSE_Form__c/fields/Additional_Info__c.field-meta.xml
<CustomField>
    <fullName>Additional_Info__c</fullName>
    <inlineHelpText>Is there anything else you would like us to know about your project as we begin quoting your design?</inlineHelpText>
    <label>Is there anything else we should know?</label>
    <length>65536</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/PSE_Form__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>ORIGINAL Case that the Quote is/was associated with.</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>PSE Forms</relationshipLabel>
    <relationshipName>PSE_Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/pseFormDisplayControllerTest.cls
@isTest
public class pseFormDisplayControllerTest {
    @isTest
    static void testPseFormWithNoPopulatedFields() {
        Case testCase = TestDataFactory.createTestCases(1, 'Web', 'PSE_Case')[0];

        PSE_Form__c pseForm = new PSE_Form__c(Case__c = testCase.Id);

        insert pseForm;

        Test.startTest();
        pseFormDisplayController.PSEFormFoundResult result = pseFormDisplayController.getPSEQuestionsForCaseId(
            testCase.Id
        );
        Test.stopTest();

        System.assertEquals(result.pseFormId, pseForm.Id);
        // Note this is an important test - it is not only verifying that we
        // behave as expected when a PSEForm is not populated, it is also
        // verifying that our "Null state" - that is, the state from which we
        // will begin to detect whether fields are not null, and thusly
        // determine if they should be displayed - is in fact empty.
        System.assertEquals(result.pseFormFieldNames.size(), 0);
    }

    @isTest
    static void testPseFormWithAPopulatedField() {
        Case testCase = TestDataFactory.createTestCases(1, 'Web', 'PSE_Case')[0];

        PSE_Form__c pseForm = new PSE_Form__c(
            Case__c = testCase.Id,
            Additional_Info__c = 'Here is some additional info!'
        );

        insert pseForm;

        Test.startTest();
        pseFormDisplayController.PSEFormFoundResult result = pseFormDisplayController.getPSEQuestionsForCaseId(
            testCase.Id
        );
        Test.stopTest();

        System.assertEquals(result.pseFormId, pseForm.Id);
        System.assertEquals(result.pseFormFieldNames.size(), 1);
        System.assertEquals(result.pseFormFieldNames[0], 'Additional_Info__c');
    }

    @isTest
    static void testCaseWithNoPSEForm() {
        Case testCase = TestDataFactory.createTestCases(1, 'Web', 'PSE_Case')[0];

        Test.startTest();
        pseFormDisplayController.PSEFormFoundResult result = pseFormDisplayController.getPSEQuestionsForCaseId(
            testCase.Id
        );
        Test.stopTest();

        System.assertEquals(result, null);
    }
}