unpackaged/main/default/objects/Case/fields/PSE_Form__c.field-meta.xml
<CustomField>
    <fullName>PSE_Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PSE Form</label>
    <referenceTo>PSE_Form__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Primary_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>The Primary Email of the Contact.</description>
    <externalId>true</externalId>
    <inlineHelpText>Adjust the email above to change the value. The Primary Email Address is a unique email in the system.</inlineHelpText>
    <label>Primary Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/PSE_Form__c/PSE_Form__c.object-meta.xml
<CustomObject>
    <description>Manual Quote Forms that gather additional information when a customer needs a Manual Quote created.
Currently, only applies to IM, CNC, Additive, and Die Casting (2021-04-29)
Currently, the forms exist in Hubspot and are being connected to Salesforce via Hubspot -&gt; Snowflake -&gt; Workato -&gt; Salesforce (2021-04-29)</description>
    <label>PSE Form</label>
    <nameField>
        <displayFormat>PSE Form # {00000000}</displayFormat>
        <label>PSE Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSE Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/PSE_Form__c/fields/additional_information__c.field-meta.xml
<CustomField>
    <fullName>additional_information__c</fullName>
    <label>Additional Information</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/PSE_Form__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>ORIGINAL Case that the Quote is/was associated with.</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>PSE Forms</relationshipLabel>
    <relationshipName>PSE_Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/PSE_Form__c/fields/estimated_delivery_date__c.field-meta.xml
<CustomField>
    <fullName>estimated_delivery_date__c</fullName>
    <description>What will be the estimated final delivery date?</description>
    <label>What is the est. final delivery date?</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/PSE_Form__c/fields/Manufacturing_Approach__c.field-meta.xml
<CustomField>
    <fullName>Manufacturing_Approach__c</fullName>
    <inlineHelpText>Did you have a particular manufacturing approach in mind for your design?</inlineHelpText>
    <label>What process will you need?</label>
    <length>65536</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/PSE_Form__c/fields/Part_Links__c.field-meta.xml
<CustomField>
    <fullName>Part_Links__c</fullName>
    <inlineHelpText>Add links to associated order parts.</inlineHelpText>
    <label>Links to Parts</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/PSE_Form__c/fields/previously_ordered_bool__c.field-meta.xml
<CustomField>
    <fullName>previously_ordered_bool__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Have these (or similar) parts previously been quoted/ordered with Xometry?</description>
    <inlineHelpText>Have you quoted or ordered these parts from Xometry before?</inlineHelpText>
    <label>Parts (or similar) previously ordered</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/BulkUploadRequestEndpointTest.cls
@IsTest
private class BulkUploadRequestEndpointTest {
    @isTest
    static void createRequestNoContact() {
        BulkUploadRequestEndpoint.BulkUploadFiles file1 = new BulkUploadRequestEndpoint.BulkUploadFiles();
        file1.fileLink = '7bce1d07-7615-4d9b-a47a-954a058f629f';
        file1.fileName = 'theFile.pdf';
        BulkUploadRequestEndpoint.BulkUploadFiles file2 = new BulkUploadRequestEndpoint.BulkUploadFiles();
        file2.fileLink = '7bce1d07-7615-4d9b-a47a-954a058f629g';
        file2.fileName = 'Long <File> Name?.stp';
        BulkUploadRequestEndpoint.BulkUploadFiles file3 = new BulkUploadRequestEndpoint.BulkUploadFiles();
        file3.fileLink = '7bce1d07-7615-4d9b-a47a-954a058f629g';
        file3.fileName = 'Boxy Box.stp';
        List<BulkUploadRequestEndpoint.BulkUploadFiles> files = new List<BulkUploadRequestEndpoint.BulkUploadFiles>{
            file1,
            file2,
            file3
        };
        BulkUploadRequestEndpoint.BulkUploadFields previously_ordered = new BulkUploadRequestEndpoint.BulkUploadFields();
        previously_ordered.key = 'previously_ordered_bool__c';
        previously_ordered.value = 'true';
        previously_ordered.type = 'boolean';
        BulkUploadRequestEndpoint.BulkUploadFields est_delivery = new BulkUploadRequestEndpoint.BulkUploadFields();
        est_delivery.key = 'estimated_delivery_date__c';
        est_delivery.value = '2020-05-24';
        est_delivery.type = 'date';
        BulkUploadRequestEndpoint.BulkUploadFields additional_info = new BulkUploadRequestEndpoint.BulkUploadFields();
        additional_info.key = 'additional_information__c';
        additional_info.value = 'Please add whipped cream and a cherry on top.';
        additional_info.type = 'string';
        BulkUploadRequestEndpoint.BulkUploadFields dummy_field = new BulkUploadRequestEndpoint.BulkUploadFields();
        dummy_field.key = 'not_a_real_field';
        dummy_field.value = 'This should not break the endpoint even though it does not exist on PSE form.';
        dummy_field.type = 'string';
        List<BulkUploadRequestEndpoint.BulkUploadFields> responses = new List<BulkUploadRequestEndpoint.BulkUploadFields>{
            previously_ordered,
            est_delivery,
            additional_info,
            dummy_field
        };
        Datetime dt = DateTime.parse('10/14/2011, 11:46 AM');

        Test.startTest();
        BulkUploadRequestEndpoint.BulkUploadResponseObject respObj = BulkUploadRequestEndpoint.createBulkUploadRequest(
            dt,
            'hello@fake.com',
            files,
            responses,
            '5b9bc3d5aa734f0038541b2b',
            '99999',
            'lastName',
            'www.xometry.com'
        );
        Test.stopTest();
        System.debug(respObj);
        System.assert(respObj.success, 'Creation of BulkUploadResponseObject failed');
        System.debug('Case created with ID of ' + respObj.caseID);
        Case thisCase = [
            SELECT Id, OwnerID, Origin, RecordTypeID, SuppliedEmail, PSE_Form__c, ContactId, AccountId
            FROM Case
            WHERE Id = :respObj.caseID
            LIMIT 1
        ];
        PSE_Form__c thisPSE = [
            SELECT Id, previously_ordered_bool__c, Case__c, Part_Links__c
            FROM PSE_Form__c
            WHERE Case__c = :thisCase.Id
            LIMIT 1
        ];
        System.debug(thisPSE.Part_Links__c);
        System.assert(thisCase != null);
        System.assert(thisPSE != null);
        System.assertEquals('Bulk Upload', thisCase.Origin);
        System.assertEquals(true, thisPSE.previously_ordered_bool__c);
        System.assertEquals(thisPSE.ID, thisCase.PSE_Form__c);
        System.assertEquals(thisCase.ID, thisPSE.Case__c);

        Contact thisContact = [
            SELECT Id, LeadSource, AccountId, OwnerId
            FROM Contact
            WHERE Primary_Email__c = :thisCase.SuppliedEmail
            LIMIT 1
        ];
        System.assert(thisContact != null);
        System.assert(thisContact.AccountId != null);
        System.assertEquals('Quoter', thisContact.LeadSource);
        System.assertEquals(thisCase.ContactId, thisContact.Id);
        System.assertEquals(thisCase.AccountID, thisContact.AccountId);
        System.assertEquals(thisCase.OwnerId, thisContact.OwnerId);
    }

    @isTest
    static void createRequestWithContact() {
        BulkUploadRequestEndpoint.BulkUploadFiles file1 = new BulkUploadRequestEndpoint.BulkUploadFiles();
        file1.fileLink = '7bce1d07-7615-4d9b-a47a-954a058f629f';
        file1.fileName = 'theFile.pdf';
        BulkUploadRequestEndpoint.BulkUploadFiles file2 = new BulkUploadRequestEndpoint.BulkUploadFiles();
        file2.fileLink = '7bce1d07-7615-4d9b-a47a-954a058f629g';
        file2.fileName = 'anotherFile.stp';
        BulkUploadRequestEndpoint.BulkUploadFiles file3 = new BulkUploadRequestEndpoint.BulkUploadFiles();
        file3.fileLink = '7bce1d07-7615-4d9b-a47a-954a058f629h';
        file3.fileName = 'moreFiles.dxf';
        List<BulkUploadRequestEndpoint.BulkUploadFiles> files = new List<BulkUploadRequestEndpoint.BulkUploadFiles>{
            file1,
            file2,
            file3
        };
        BulkUploadRequestEndpoint.BulkUploadFields manufacturing = new BulkUploadRequestEndpoint.BulkUploadFields();
        manufacturing.key = 'Manufacturing_Approach__c';
        manufacturing.value = '3d printing';
        manufacturing.type = 'string';
        List<BulkUploadRequestEndpoint.BulkUploadFields> responses = new List<BulkUploadRequestEndpoint.BulkUploadFields>{
            manufacturing
        };
        Datetime dt = DateTime.parse('10/27/2022, 11:46 AM');

        List<Account> newAccounts = TestDataFactory.createTestAccountNonGenerics(1, 'BDR', 1, 0);
        String email = [SELECT Email FROM Contact LIMIT 1][0].Email;

        Test.startTest();
        BulkUploadRequestEndpoint.BulkUploadResponseObject respObj = BulkUploadRequestEndpoint.createBulkUploadRequest(
            dt,
            email,
            files,
            responses,
            '5235235325325325325',
            '07787',
            'Doe',
            'www.xometry.com'
        );
        Test.stopTest();

        System.assert(respObj.success, 'Creation of BulkUploadResponseObject failed');
        Case thisCase = [
            SELECT SuppliedEmail, AccountId, ContactId, OwnerId
            FROM Case
            WHERE Id = :respObj.caseID
            LIMIT 1
        ];
        Contact thisContact = [SELECT Name, Email, OwnerId FROM Contact WHERE Id = :thisCase.ContactId];
        Account thisAccount = [SELECT Name FROM Account WHERE Id = :thisCase.AccountId];
        System.assertEquals('John Doe0', thisContact.Name);
        System.assertEquals(thisCase.SuppliedEmail, thisContact.Email);
        System.assertEquals('TestAccount0', thisAccount.Name);
        System.assertEquals(thisCase.OwnerId, thisContact.OwnerId);
    }
}