unpackaged/main/default/objects/CaseOpsOrder__c/CaseOpsOrder__c.object-meta.xml
<CustomObject>
    <label>CaseOpsOrder</label>
    <nameField>
        <label>CaseOpsOrder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CaseOpsOrders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CaseOpsOrder__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>CaseOpsOrders</relationshipLabel>
    <relationshipName>CaseOpsOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CaseOpsOrder__c/fields/CaseOpsOrderKey__c.field-meta.xml
<CustomField>
    <fullName>CaseOpsOrderKey__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>CaseOpsOrderKey</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/CaseOpsOrder__c/fields/Ops_Order__c.field-meta.xml
<CustomField>
    <fullName>Ops_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ops Order</label>
    <referenceTo>Ops_Order__c</referenceTo>
    <relationshipLabel>CaseOpsOrders</relationshipLabel>
    <relationshipName>CaseOpsOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Ops_Order__c/Ops_Order__c.object-meta.xml
<CustomObject>
    <description>Order object for the GNO Team. Used for purposes of tracking orders and jobs.</description>
    <label>Ops Order</label>
    <nameField>
        <label>Ops Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ops Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Ops_Order__c/fields/XometryOpsOrderID__c.field-meta.xml
<CustomField>
    <fullName>XometryOpsOrderID__c</fullName>
    <externalId>true</externalId>
    <label>Xometry Ops Order ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/CaseOpsOrderHandlerTest.cls
@isTest
private class CaseOpsOrderHandlerTest {

    @isTest(seeAllData=false)
    static void renameOnCreateTest() {

        Ops_Order__c testOpsOrder = new Ops_Order__c(
            XometryOpsOrderID__c = 'AAAAA-00001'
        );
        insert testOpsOrder;

        Case testCase = new Case(SuppliedEmail = 'test@test.com', RecordTypeId = AppConstants.casePSERecordTypeId);
        insert testCase;

        testCase = [SELECT CaseNumber From Case Where Id =: testCase.Id];
        
        CaseOpsOrder__c objCaseOrder = new CaseOpsOrder__c(Case__c = testCase.Id, Ops_Order__c = testOpsOrder.Id);

        Test.startTest();
        insert objCaseOrder;
        Test.stopTest();

        System.assertEquals(
            testOpsOrder.XometryOpsOrderID__c +
            ' : ' +
            testCase.CaseNumber,
            [SELECT CaseOpsOrderKey__c FROM CaseOpsOrder__c LIMIT 1].CaseOpsOrderKey__c,
            'Junction should be renamed'
        );

    }
}