unpackaged/main/default/objects/CaseOpsOrder__c/CaseOpsOrder__c.object-meta.xml
<CustomObject>
    <label>CaseOpsOrder</label>
    <nameField>
        <label>CaseOpsOrder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CaseOpsOrders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CaseOpsOrder__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>CaseOpsOrders</relationshipLabel>
    <relationshipName>CaseOpsOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CaseOpsOrder__c/fields/CaseOpsOrderKey__c.field-meta.xml
<CustomField>
    <fullName>CaseOpsOrderKey__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>CaseOpsOrderKey</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/CaseOpsOrder__c/fields/Xometry_Order_ID__c.field-meta.xml
<CustomField>
    <fullName>Xometry_Order_ID__c</fullName>
    <formula>Ops_Order__r.XometryOpsOrderID__c</formula>
    <label>Order ID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/CaseOpsOrderHandler.cls
public with sharing class CaseOpsOrderHandler {
    /**
     * @description changes the Name in the junction record to a more readeable identifier
     * @param newCaseOpsOrderList - list of new CaseOpsOrder__c
     */
    public static void renameOnCreate(List<CaseOpsOrder__c> newCaseOpsOrderList) {

        Map<Id, List<CaseOpsOrder__c>> caseOpsOrderMap = new Map<Id, List<CaseOpsOrder__c>>();
        for (CaseOpsOrder__c caseOpsOrder : newCaseOpsOrderList) {

            if( caseOpsOrder.CaseOpsOrderKey__c == null ){
                if (!caseOpsOrderMap.containsKey(caseOpsOrder.Case__c)) {
                    caseOpsOrderMap.put(caseOpsOrder.Case__c, new List<CaseOpsOrder__c>());
                }
                caseOpsOrderMap.get(caseOpsOrder.Case__c).add(caseOpsOrder);
            }

        }

        if(!caseOpsOrderMap.isEmpty()){
            for (Case c : [SELECT Id, CaseNumber FROM Case WHERE Id IN :caseOpsOrderMap.keySet()]) {

                for (CaseOpsOrder__c caseOpsOrder : caseOpsOrderMap.get(c.Id)) {
                    caseOpsOrder.CaseOpsOrderKey__c = caseOpsOrder.Xometry_Order_ID__c + ' : ' + c.CaseNumber;
                }

            }
        }

        for (CaseOpsOrder__c caseOpsOrder : newCaseOpsOrderList) {
            caseOpsOrder.Name = caseOpsOrder.CaseOpsOrderKey__c;
        }

    }
}