unpackaged/main/default/objects/Admin_Ref_Variable__mdt/Admin_Ref_Variable__mdt.object-meta.xml
<CustomObject>
    <description>This custom metadata is used to allow admins to adjust variables that are used in Apex flows</description>
    <label>Admin Ref Variable</label>
    <pluralLabel>Admin Ref Variables</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Admin_Ref_Variable__mdt/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>The name of the variable to be referenced in apex metadata queries</description>
    <label>Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Admin_Ref_Variable__mdt/fields/Text_Ref_Var__c.field-meta.xml
<CustomField>
    <fullName>Text_Ref_Var__c</fullName>
    <description>If the variable to be referenced by apex or elsewhere is a text variable</description>
    <label>Text Ref Var</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Primary_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>The Primary Email of the Contact.</description>
    <externalId>true</externalId>
    <inlineHelpText>Adjust the email above to change the value. The Primary Email Address is a unique email in the system.</inlineHelpText>
    <label>Primary Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Last_Quote_Xometry_Create_Time__c.field-meta.xml
<CustomField>
    <fullName>Last_Quote_Xometry_Create_Time__c</fullName>
    <description>Hidden field for Automated Processing to compare last time an Opps quote occured.</description>
    <label>Last Quote Modification Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Quick Reference to the Primary Contact on an Opportunity</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities(PC)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Container for Opportunities that are part of the same project</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <inlineHelpText>A short description of this Project</inlineHelpText>
    <label>Project</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Initial Engagement</fullName>
            </value>
            <value>
                <fullName>Negotiation / Revision</fullName>
            </value>
            <value>
                <fullName>Pending Payment</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ProjectAutoCloseNoFutureTaskBatchTest.cls
@isTest
private class ProjectAutoCloseNoFutureTaskBatchTest {
    @isTest
    private static void projectAutoCloseNoFutureTaskBatchTestWon() {
        Account testAccount = TestDataFactory.createTestAccountNonGenerics(5, 'AM', 1)[0];
        update testAccount;

        Contact testContact = new Contact(
            AccountId = testAccount.Id,
            Primary_Email__c = 'test@test123.com',
            FirstName = 'Test',
            LastName = 'Contact'
        );
        insert testContact;

        Project__c testProject = new Project__c(
            AccountId__c = testAccount.Id,
            Name = 'Test Project',
            Stage__c = 'New',
            Primary_Contact__c = testContact.Id,
            CreatedById = AppConstants.API_USER
        );
        insert testProject;

        for (Admin_Ref_Variable__mdt adminRefVarValues : [
            SELECT Text_Ref_Var__c, DeveloperName
            FROM Admin_Ref_Variable__mdt
            WHERE Name__c = 'ProjectAutoCloseNoFutureTaskBatchLastProject'
        ]) {
            Integer rangeInDays = Integer.valueOf(adminRefVarValues.Text_Ref_Var__c) * -1;
            Date dateSince = System.today().addDays(rangeInDays).addDays(-2);

            Test.setCreatedDate(testProject.Id, dateSince);
        }

        Opportunity testOpp = new Opportunity();
        testOpp.Name = 'Test';
        testOpp.CloseDate = System.today().addDays(2);
        testOpp.Project__c = testProject.Id;
        testOpp.StageName = 'Closed Won';
        insert testOpp;

        Test.startTest();
        ProjectAutoCloseNoFutureTaskBatch batch = new ProjectAutoCloseNoFutureTaskBatch();
        Database.executeBatch(batch);
        Test.stopTest();

        System.assertEquals(
            'Closed Won',
            [SELECT Stage__c FROM Project__c WHERE Id = :testProject.Id]
            .Stage__c,
            'Project should be closed.'
        );
    }

    @isTest
    private static void projectAutoCloseNoFutureTaskBatchTestLost() {
        Account testAccount = TestDataFactory.createTestAccountNonGenerics(5, 'AM', 1)[0];
        update testAccount;

        Contact testContact = new Contact(
            AccountId = testAccount.Id,
            Primary_Email__c = 'test@test123.com',
            FirstName = 'Test',
            LastName = 'Contact'
        );
        insert testContact;

        Project__c testProject = new Project__c(
            AccountId__c = testAccount.Id,
            Name = 'Test Project',
            Stage__c = 'New',
            Primary_Contact__c = testContact.Id,
            CreatedById = AppConstants.API_USER
        );
        insert testProject;

        for (Admin_Ref_Variable__mdt adminRefVarValues : [
            SELECT Text_Ref_Var__c, DeveloperName
            FROM Admin_Ref_Variable__mdt
            WHERE Name__c = 'ProjectAutoCloseNoFutureTaskBatchLastProject'
        ]) {
            Integer rangeInDays = Integer.valueOf(adminRefVarValues.Text_Ref_Var__c) * -1;
            Date dateSince = System.today().addDays(rangeInDays).addDays(-2);

            Test.setCreatedDate(testProject.Id, dateSince);
        }

        Opportunity testOpp = new Opportunity();
        testOpp.Name = 'Test';
        testOpp.CloseDate = System.today().addDays(2);
        testOpp.Project__c = testProject.Id;
        testOpp.StageName = 'Closed Lost';
        insert testOpp;

        Test.startTest();
        ProjectAutoCloseNoFutureTaskBatch batch = new ProjectAutoCloseNoFutureTaskBatch();
        Database.executeBatch(batch);
        Test.stopTest();

        System.assertEquals(
            'Closed Lost',
            [SELECT Stage__c FROM Project__c WHERE Id = :testProject.Id]
            .Stage__c,
            'Project should be closed.'
        );
    }

    @isTest
    private static void projectAutoCloseNoFutureTaskBatchTestSkip() {
        Account testAccount = TestDataFactory.createTestAccountNonGenerics(5, 'AM', 1)[0];
        update testAccount;

        Contact testContact = new Contact(
            AccountId = testAccount.Id,
            Primary_Email__c = 'test@test123.com',
            FirstName = 'Test',
            LastName = 'Contact'
        );
        insert testContact;

        Project__c testProject = new Project__c(
            AccountId__c = testAccount.Id,
            Name = 'Test Project',
            Stage__c = 'New',
            Primary_Contact__c = testContact.Id
        );
        insert testProject;

        for (Admin_Ref_Variable__mdt adminRefVarValues : [
            SELECT Text_Ref_Var__c, DeveloperName
            FROM Admin_Ref_Variable__mdt
            WHERE Name__c = 'ProjectAutoCloseNoFutureTaskBatchLastProject'
        ]) {
            Integer rangeInDays = Integer.valueOf(adminRefVarValues.Text_Ref_Var__c) * -1;
            Date dateSince = System.today().addDays(rangeInDays).addDays(-2);

            Test.setCreatedDate(testProject.Id, dateSince);
        }

        Opportunity testOpp = new Opportunity();
        testOpp.Name = 'Test';
        testOpp.CloseDate = System.today().addDays(2);
        testOpp.Project__c = testProject.Id;
        testOpp.StageName = 'Closed Lost';
        insert testOpp;

        Opportunity testOpp2 = new Opportunity();
        testOpp2.Name = 'Test';
        testOpp2.CloseDate = System.today().addDays(2);
        testOpp2.Project__c = testProject.Id;
        testOpp2.StageName = 'Open';
        insert testOpp2;

        Test.startTest();
        ProjectAutoCloseNoFutureTaskBatch batch = new ProjectAutoCloseNoFutureTaskBatch();
        Database.executeBatch(batch);
        Test.stopTest();

        System.assertEquals(
            'New',
            [SELECT Stage__c FROM Project__c WHERE Id = :testProject.Id]
            .Stage__c,
            'Project stage shouldnt be updated.'
        );
    }

    @isTest
    private static void projectAutoCloseNoFutureTaskBatchTestCriteria2() {
        Account testAccount = TestDataFactory.createTestAccountNonGenerics(5, 'AM', 1)[0];

        Contact testContact = new Contact(
            AccountId = testAccount.Id,
            Primary_Email__c = 'test@test123.com',
            FirstName = 'Test',
            LastName = 'Contact',
            Outreach_Actively_Being_Sequenced__c = FALSE
        );
        insert testContact;

        Task callTask = new Task(
            Type = 'Call',
            CallType = 'Internal',
            WhoId = testContact.Id,
            Status = 'Completed'
        );

        Project__c testProject = new Project__c(
            AccountId__c = testAccount.Id,
            Name = 'Test Project',
            Stage__c = 'New',
            Primary_Contact__c = testContact.Id,
            CreatedById = AppConstants.API_USER
        );

        insert testProject;

        Opportunity testOpp = new Opportunity(
            Name = 'Test',
            Project__c = testProject.Id,
            StageName = 'New',
            CloseDate = Date.today().addDays(12)
        );

        Datetime dateSinceCreatedProject;
        Datetime dateSinceCreatedOpp;
        Date dateSinceLastAct;

        for (Admin_Ref_Variable__mdt adminRefVarValues : [
            SELECT Text_Ref_Var__c, Name__c
            FROM Admin_Ref_Variable__mdt
            WHERE Name__c LIKE 'ProjectAutoCloseNoFutureTaskBatch%'
        ]) {
            Integer rangeInDays = Integer.valueOf(adminRefVarValues.Text_Ref_Var__c) * -1;
            Date dateSince = System.today().addDays(rangeInDays).addDays(-1);
            if (adminRefVarValues.Name__c.contains('ProjectAutoCloseNoFutureTaskBatchLastQuoteNew') ) {
                testOpp.Last_Quote_Xometry_Create_Time__c = dateSince;
            }
            if (adminRefVarValues.Name__c.contains('ProjectAutoCloseNoFutureTaskBatchLastOppNew') ) {
                dateSinceCreatedOpp = dateSince;
            }
            if (adminRefVarValues.Name__c.contains('ProjectAutoCloseNoFutureTaskBatchLastAct') ) {
                dateSinceLastAct = dateSince;
            }
        }

        callTask.ActivityDate = dateSinceLastAct;
        insert callTask;

        insert testOpp;

        Test.setCreatedDate(testOpp.Id, dateSinceCreatedOpp);

        Test.startTest();
        ProjectAutoCloseNoFutureTaskBatch batch = new ProjectAutoCloseNoFutureTaskBatch();
        Database.executeBatch(batch);
        Test.stopTest();

        System.assertEquals(
            'Closed Lost',
            [SELECT Stage__c FROM Project__c WHERE Id = :testProject.Id]
            .Stage__c,
            'Project should be closed.'
        );
    }

    @isTest
    static void projectAutoCloseNoFutureTaskScheduleTest() {
        String CRON_EXP = '0 0 1 * * ?';
        Test.startTest();
        String jobID = System.schedule(
            'ProjectCloseInactiveBatchTest',
            CRON_EXP,
            new ProjectAutoCloseNoFutureTaskSchedule()
        );
        Test.stopTest();
        System.assertNotEquals(null, jobID, 'Job id is not null');
    }
}