unpackaged/main/default/objects/Admin_Ref_Variable__mdt/Admin_Ref_Variable__mdt.object-meta.xml
<CustomObject>
    <description>This custom metadata is used to allow admins to adjust variables that are used in Apex flows</description>
    <label>Admin Ref Variable</label>
    <pluralLabel>Admin Ref Variables</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Admin_Ref_Variable__mdt/fields/Number_Ref_Value__c.field-meta.xml
<CustomField>
    <fullName>Number_Ref_Value__c</fullName>
    <description>This variable is used if the reference variable is a number value</description>
    <label>Number Ref Value</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Ops_Order__c/Ops_Order__c.object-meta.xml
<CustomObject>
    <description>Order object for the GNO Team. Used for purposes of tracking orders and jobs.</description>
    <label>Ops Order</label>
    <nameField>
        <label>Ops Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ops Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Ops_Order__c/fields/ERPStatus__c.field-meta.xml
<CustomField>
    <fullName>ERPStatus__c</fullName>
    <label>ERP Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Ops_Order__c/fields/Order_Close_to_Ship__c.field-meta.xml
<CustomField>
    <fullName>Order_Close_to_Ship__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Order Close to Ship</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Ops_Order__c/fields/Order_OverDue_Flag__c.field-meta.xml
<CustomField>
    <fullName>Order_OverDue_Flag__c</fullName>
    <label>Order OverDue Flag</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/OrderOverdueBatch.cls
global class OrderOverdueBatch implements Database.Batchable<sObject>, Database.Stateful, schedulable {
    Integer orderShipTminus = 0;

    global Database.QueryLocator start(Database.BatchableContext bc) {
        for (Admin_Ref_Variable__mdt orderShipTminusRecord : [
            SELECT Number_Ref_Value__c
            FROM Admin_Ref_Variable__mdt
            WHERE Label = 'orderShipTminus'
        ]) {
            orderShipTminus = Integer.valueOf(orderShipTminusRecord.Number_Ref_Value__c) * -1;
        }

        return Database.getQueryLocator(
            [
                SELECT OrderDueDate__c, Order_Close_to_Ship__c, Order_OverDue_Flag__c
                FROM Ops_Order__c
                WHERE ERPStatus__c NOT IN :AppConstants.OPS_ORDER_COMPLETED_STATUSES AND OrderDueDate__c != NULL
            ]
        );
    }

    global void execute(Database.BatchableContext BC, list<Ops_Order__c> scope) {
        Date dToday = System.today();

        for (Ops_Order__c order : scope) {
            if (order.OrderDueDate__c != null) {
                order.Order_OverDue_Flag__c = order.OrderDueDate__c.daysBetween(dToday);
                if (!order.Order_Close_to_Ship__c && (order.Order_OverDue_Flag__c >= orderShipTminus)) {
                    order.Order_Close_to_Ship__c = true;
                }
            }
        }

        DatabaseUtilities.saveToDatabase(scope, 'OrderOverdueBatch.execute', 'Order Overdue Flag update');
    }

    global void finish(Database.BatchableContext BC) {
    }

    global void execute(SchedulableContext sc) {
        Database.executebatch(new OrderOverdueBatch());
    }
}