unpackaged/main/default/objects/Admin_Ref_Variable__mdt/Admin_Ref_Variable__mdt.object-meta.xml
<CustomObject>
    <description>This custom metadata is used to allow admins to adjust variables that are used in Apex flows</description>
    <label>Admin Ref Variable</label>
    <pluralLabel>Admin Ref Variables</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Admin_Ref_Variable__mdt/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>The name of the variable to be referenced in apex metadata queries</description>
    <label>Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Admin_Ref_Variable__mdt/fields/Text_Ref_Var__c.field-meta.xml
<CustomField>
    <fullName>Text_Ref_Var__c</fullName>
    <description>If the variable to be referenced by apex or elsewhere is a text variable</description>
    <label>Text Ref Var</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Quick Reference to the Primary Contact on an Opportunity</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities(PC)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Container for Opportunities that are part of the same project</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project__c/fields/Closed_Lost_Reason__c.field-meta.xml
<CustomField>
    <fullName>Closed_Lost_Reason__c</fullName>
    <inlineHelpText>Some Closed Lost details require additional information. For example: if selecting Competition please enter the competitor's name or 'Unknown'.</inlineHelpText>
    <label>Closed Lost Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Last_Opp_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Opp_Created_Date__c</fullName>
    <inlineHelpText>Looking at the Opps on this project, this is the most recent Opp Created Date</inlineHelpText>
    <label>Last Opp Created Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Last_Quote_Mod_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Quote_Mod_Date__c</fullName>
    <inlineHelpText>Of the Quotes on this Project (by way of Opps), this is the most recent Last Quote Modification Date in the ERP.</inlineHelpText>
    <label>Last Quote Mod Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Primary_Contact_LAD__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_LAD__c</fullName>
    <description>Non-AM LAD for sandbox testing</description>
    <formula>Primary_Contact__r.LastActivityDate</formula>
    <inlineHelpText>Non-AM LAD for sandbox testing</inlineHelpText>
    <label>Primary Contact LAD</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <inlineHelpText>A short description of this Project</inlineHelpText>
    <label>Project</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Initial Engagement</fullName>
            </value>
            <value>
                <fullName>Negotiation / Revision</fullName>
            </value>
            <value>
                <fullName>Pending Payment</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Sub_Stage__c.field-meta.xml
<CustomField>
    <fullName>Sub_Stage__c</fullName>
    <label>Sub Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Stage__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Sub_Stage</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Sub_Stage.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>No Response</fullName>
    </customValue>
    <customValue>
        <fullName>No Bid</fullName>
    </customValue>
    <customValue>
        <fullName>Price</fullName>
    </customValue>
    <customValue>
        <fullName>Lead Time</fullName>
    </customValue>
    <customValue>
        <fullName>Service Concerns</fullName>
    </customValue>
    <customValue>
        <fullName>Project Canceled</fullName>
    </customValue>
    <customValue>
        <fullName>Purchasing from Different Opportunity</fullName>
    </customValue>
    <customValue>
        <fullName>On-Demand Competition</fullName>
    </customValue>
    <customValue>
        <fullName>Local Competition</fullName>
    </customValue>
    <customValue>
        <fullName>Budgetary</fullName>
    </customValue>
    <customValue>
        <fullName>Late Quote</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Made In-House</fullName>
    </customValue>
    <customValue>
        <fullName>Auto-Closed</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Project on Hold</fullName>
    </customValue>
    <customValue>
        <fullName>Purchase Order</fullName>
    </customValue>
    <customValue>
        <fullName>Credit Card</fullName>
    </customValue>
    <masterLabel>Sub Stage</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/ProjectAutoCloseNoFutureTaskBatch.cls
/**
 *   @description Close the Project when:
 *     All Opps on the Project are closed (CW OR CL)
 *     && Project Created Date > 5 days ago
 *     Project was created by Automation (by created by user)
 *      OR
 *     ALL of the following are true:
 *     The Primary Contact on the Project has no open future tasks
 *     The Primary Contact on the Project has not been contacted in more than X days
 *     All of the Opportunities on the Project are older than X days
 *     None of the Opportunities have been updated from the ERP in more than X days
 **/

global class ProjectAutoCloseNoFutureTaskBatch implements Database.Batchable<sObject>, Database.Stateful {
    static final String BATCH_METHOD_NAME = 'ProjectAutoCloseNoFutureTaskBatch.execute';

    Date dateSinceLastActivity;
    Date dateSinceLastQuote;
    Date dateSinceLastOpp;
    Date dateSinceCreatedProject = Date.newInstance(1, 1, 1);

    Date dateSinceLastActivityNew = Date.newInstance(1, 1, 1);
    Date dateSinceLastQuoteNew = Date.newInstance(1, 1, 1);
    Date dateSinceLastOppNew = Date.newInstance(1, 1, 1);

    Date dateSinceLastActivityRevision = Date.newInstance(1, 1, 1);
    Date dateSinceLastQuoteRevision = Date.newInstance(1, 1, 1);
    Date dateSinceLastOppRevision = Date.newInstance(1, 1, 1);

    String batchQuery = ' SELECT Id, Stage__c, CreatedDate, CreatedById, Last_Opp_Created_Date__c, Last_Quote_Mod_Date__c, Primary_Contact_LAD__c, Primary_Contact__r.Outreach_Actively_Being_Sequenced__c FROM Project__c ';

    public ProjectAutoCloseNoFutureTaskBatch() {
        //storing metadata and date calculations in local vars
        for (Admin_Ref_Variable__mdt adminRefVarValue : [
            SELECT Text_Ref_Var__c, Name__c
            FROM Admin_Ref_Variable__mdt
            WHERE Name__c LIKE 'ProjectAutoCloseNoFutureTaskBatch%'
        ]) {
            Integer rangeInDays = Integer.valueOf(adminRefVarValue.Text_Ref_Var__c) * -1;
            Date dateSince = System.today().addDays(rangeInDays);

            if (adminRefVarValue.Name__c.contains('ProjectAutoCloseNoFutureTaskBatchLastAct') ) {
                if(dateSinceLastActivity == null || dateSince > dateSinceLastActivity){
                    dateSinceLastActivity = dateSince;
                }
                if(adminRefVarValue.Name__c.endsWith('New')){
                    dateSinceLastActivityNew = dateSince;
                }
                if(adminRefVarValue.Name__c.endsWith('Revision')){
                    dateSinceLastActivityRevision = dateSince;
                }
            }
            if (adminRefVarValue.Name__c.contains('ProjectAutoCloseNoFutureTaskBatchLastQuote') ) {
                if(dateSinceLastQuote == null || dateSince > dateSinceLastQuote){
                    dateSinceLastQuote = dateSince;
                }
                if(adminRefVarValue.Name__c.endsWith('New')){
                    dateSinceLastQuoteNew = dateSince;
                }
                if(adminRefVarValue.Name__c.endsWith('Revision')){
                    dateSinceLastQuoteRevision = dateSince;
                }
            }
            if (adminRefVarValue.Name__c.contains('ProjectAutoCloseNoFutureTaskBatchLastOpp') ) {
                if(dateSinceLastOpp == null || dateSince > dateSinceLastOpp){
                    dateSinceLastOpp = dateSince;
                }
                if(adminRefVarValue.Name__c.endsWith('New')){
                    dateSinceLastOppNew = dateSince;
                }
                if(adminRefVarValue.Name__c.endsWith('Revision')){
                    dateSinceLastOppRevision = dateSince;
                }
            }

            if (adminRefVarValue.Name__c == 'ProjectAutoCloseNoFutureTaskBatchLastProject') {
                dateSinceCreatedProject = dateSince;
            }

        }

    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        /**
         * Filling where clauses using metadata admin variables
         */

        //base conditions for all criterias
        String stageConditions = 'Stage__c = \'New\' OR Stage__c = \'System Reopened\' OR Stage__c = \'Initial Engagement\'';
        stageConditions += 'OR Stage__c = \'Negotiation / Revision\' OR Stage__c = \'Pending Payment\'';

        batchQuery += ' WHERE ( (' + stageConditions + ') AND CreatedById = \'' + AppConstants.API_USER + '\')';

        //#Criteria 1
        batchQuery += ' AND ( CreatedDate < :dateSinceCreatedProject ';

        // Criteria #2
        batchQuery += ' OR (';
        batchQuery += '   Primary_Contact__r.Outreach_Actively_Being_Sequenced__c = FALSE ';
        batchQuery += '   AND Primary_Contact_LAD__c < :dateSinceLastActivity ';
        batchQuery += '   AND Last_Opp_Created_Date__c < :dateSinceLastQuote ';
        batchQuery += '   AND Last_Quote_Mod_Date__c < :dateSinceLastOpp ';
        batchQuery += ' ) )';

        return Database.getQueryLocator(batchQuery);
    }

    global void execute(Database.BatchableContext BC, List<Project__c> projectList) {
        Set<Id> projectsOpen = new Set<Id>();
        Set<Id> projectsWithCW = new Set<Id>();
        Set<Id> projectsWithOpps = new Set<Id>();
        Map<Id, Project__c> closeProjectsMap = new Map<Id, Project__c>();

        Map<Id, Project__c> projectsMap = new Map<Id, Project__c>(projectList);

        //checking opportunity status and maping Project Details
        for (Opportunity opp : [
            SELECT StageName, Project__c
            FROM Opportunity
            WHERE Project__c IN :projectsMap.keySet()
        ]) {
            projectsWithOpps.add(opp.Project__c);

            if (opp.StageName == 'Closed Won') {
                projectsWithCW.add(opp.Project__c);
            }

            // Criteria #1
            if (projectsMap.get(opp.Project__c).CreatedDate < dateSinceCreatedProject) {
                //for Projects created before dateSinceCreatedProject check if all Opps are closed.
                if (opp.StageName != 'Closed Lost' && opp.StageName != 'Closed Won') {
                    projectsOpen.add(opp.Project__c);
                    closeProjectsMap.remove(opp.Project__c);
                }

                if (!projectsOpen.contains(opp.Project__c)) {
                    closeProjectsMap.put(opp.Project__c, projectsMap.get(opp.Project__c));
                }
            }
        }

        for (Project__c project : projectList) {
            projectsMap.put(project.Id, project);

            // Criteria #2 
            //Stage of ‘New’, ‘System Reopened’, or “Initial Engagement’,
            if ( 
                (
                    project.Stage__c == 'New' ||
                    project.Stage__c == 'System Reopened' ||
                    project.Stage__c == 'Initial Engagement'
                ) &&
                project.Primary_Contact_LAD__c < dateSinceLastActivityNew &&
                project.Last_Opp_Created_Date__c < dateSinceLastQuoteNew &&
                project.Last_Quote_Mod_Date__c < dateSinceLastOppNew &&
                project.Primary_Contact__r.Outreach_Actively_Being_Sequenced__c == FALSE
            ) {
                closeProjectsMap.put(project.Id, project);
            }

            // Criteria #2
            // Stage of ‘Negotiation/Revision or ‘Pending Payment’
            if (
                (
                    project.Stage__c == 'Negotiation / Revision' ||
                    project.Stage__c == 'Pending Payment'
                ) && 
                project.Primary_Contact_LAD__c < dateSinceLastActivityRevision && 
                project.Last_Opp_Created_Date__c < dateSinceLastQuoteRevision && 
                project.Last_Quote_Mod_Date__c < dateSinceLastOppRevision &&
                project.Primary_Contact__r.Outreach_Actively_Being_Sequenced__c == FALSE
            ) {
                closeProjectsMap.put(project.Id, project);
            }

            // Criteria #3 Empty Projects
            if (!projectsWithOpps.contains(project.Id)) {
                closeProjectsMap.put(project.Id, project);
            }
        }

        List<Project__c> projectsToClose = new List<Project__c>();
        for (Project__c project : closeProjectsMap.values()) {
            project.Stage__c = 'Closed Won';
            if (!projectsWithCW.contains(project.Id)) {
                project.Stage__c = 'Closed Lost';
                project.Sub_Stage__c = 'Auto-Closed';
                project.Closed_Lost_Reason__c = 'Auto-closed due to inactivity';
            }
            projectsToClose.add(project);
        }

        DatabaseUtilities.saveToDatabase(projectsToClose, BATCH_METHOD_NAME, 'Project Close No Future Batch update');
    }

    global void finish(Database.BatchableContext BC) {
    }
}