unpackaged/main/default/objects/Admin_Ref_Variable__mdt/Admin_Ref_Variable__mdt.object-meta.xml
<CustomObject>
    <description>This custom metadata is used to allow admins to adjust variables that are used in Apex flows</description>
    <label>Admin Ref Variable</label>
    <pluralLabel>Admin Ref Variables</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Admin_Ref_Variable__mdt/fields/Number_Ref_Value__c.field-meta.xml
<CustomField>
    <fullName>Number_Ref_Value__c</fullName>
    <description>This variable is used if the reference variable is a number value</description>
    <label>Number Ref Value</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>GNO Jobs</description>
    <label>Job</label>
    <nameField>
        <label>Job ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/OrderDueDate__c.field-meta.xml
<CustomField>
    <fullName>OrderDueDate__c</fullName>
    <label>Order Due Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/OrderID__c.field-meta.xml
<CustomField>
    <fullName>OrderID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Order associated with this job</description>
    <label>Order ID</label>
    <referenceTo>Ops_Order__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/ShippingService__c.field-meta.xml
<CustomField>
    <fullName>ShippingService__c</fullName>
    <label>Shipping Service</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Rescinded</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Vendor Completed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Auction Failed to Award</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Technical_Review_Status__c.field-meta.xml
<CustomField>
    <fullName>Technical_Review_Status__c</fullName>
    <label>Technical Review Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Technical Review Required</fullName>
                <default>true</default>
                <label>No Technical Review Required</label>
            </value>
            <value>
                <fullName>Pending Technical Review</fullName>
            </value>
            <value>
                <fullName>Technical Review Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/XometryJobID__c.field-meta.xml
<CustomField>
    <fullName>XometryJobID__c</fullName>
    <externalId>true</externalId>
    <label>Xometry Job ID</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/XometryOpsOrderID__c.field-meta.xml
<CustomField>
    <fullName>XometryOpsOrderID__c</fullName>
    <label>Xometry Ops Order ID</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Job_Order__c/Job_Order__c.object-meta.xml
<CustomObject>
    <label>Job Order</label>
    <nameField>
        <label>Job Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job_Order__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Job Orders</relationshipLabel>
    <relationshipName>Job_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Job_Order__c/fields/Ops_Order__c.field-meta.xml
<CustomField>
    <fullName>Ops_Order__c</fullName>
    <label>Ops Order</label>
    <referenceTo>Ops_Order__c</referenceTo>
    <relationshipLabel>Job Orders</relationshipLabel>
    <relationshipName>Job_Orders</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Job_Order__c/fields/XometryJobID__c.field-meta.xml
<CustomField>
    <fullName>XometryJobID__c</fullName>
    <label>Xometry Job ID</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Job_Order__c/fields/XometryOpsOrderID__c.field-meta.xml
<CustomField>
    <fullName>XometryOpsOrderID__c</fullName>
    <label>Xometry Ops Order ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Ops_Order__c/Ops_Order__c.object-meta.xml
<CustomObject>
    <description>Order object for the GNO Team. Used for purposes of tracking orders and jobs.</description>
    <label>Ops Order</label>
    <nameField>
        <label>Ops Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ops Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Ops_Order__c/fields/AllOrdersTotal__c.field-meta.xml
<CustomField>
    <fullName>AllOrdersTotal__c</fullName>
    <description>The total of all non-cancelled child orders and parent order.</description>
    <label>All Orders Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Ops_Order__c/fields/Cases_Completed__c.field-meta.xml
<CustomField>
    <fullName>Cases_Completed__c</fullName>
    <label>Cases Completed</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Ops_Order__c/fields/Cases_In_Progress__c.field-meta.xml
<CustomField>
    <fullName>Cases_In_Progress__c</fullName>
    <label>Cases In Progress</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Ops_Order__c/fields/Jobs_Completed__c.field-meta.xml
<CustomField>
    <fullName>Jobs_Completed__c</fullName>
    <label>Jobs Reviewed</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Ops_Order__c/fields/Jobs_In_Progress__c.field-meta.xml
<CustomField>
    <fullName>Jobs_In_Progress__c</fullName>
    <label>Jobs In Progress</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Ops_Order__c/fields/Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Date__c</fullName>
    <label>Order Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Ops_Order__c/fields/OrderTotal__c.field-meta.xml
<CustomField>
    <fullName>OrderTotal__c</fullName>
    <label>Order Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Ops_Order__c/fields/POD__c.field-meta.xml
<CustomField>
    <fullName>POD__c</fullName>
    <label>POD</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Albatrosses</fullName>
            </value>
            <value>
                <fullName>Atomic Rocks</fullName>
            </value>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>First Impressions</fullName>
            </value>
            <value>
                <fullName>Impodsters</fullName>
            </value>
            <value>
                <fullName>Rocket Power</fullName>
            </value>
            <value>
                <fullName>SpaceTechs</fullName>
            </value>
            <value>
                <fullName>Triple Threat</fullName>
            </value>
            <value>
                <fullName>Amazing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Ops_Order__c/fields/ShippingMethod__c.field-meta.xml
<CustomField>
    <fullName>ShippingMethod__c</fullName>
    <label>Shipping Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Ops_Order__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Partially Complete</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Reopened by Job</fullName>
            </value>
            <value>
                <fullName>Reopened by Updated Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Ops_Order__c/fields/XometryOpsOrderID__c.field-meta.xml
<CustomField>
    <fullName>XometryOpsOrderID__c</fullName>
    <externalId>true</externalId>
    <label>Xometry Ops Order ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/JobOrderHandlerTest.cls
@isTest
private class JobOrderHandlerTest {
    @isTest(seeAllData=false)
    static void renameOnCreateTest() {
        Ops_Order__c opsOrder = new Ops_Order__c();
        opsOrder.POD__c = 'First Impressions';
        opsOrder.XometryOpsOrderID__c = 'Ops-Order';
        opsOrder.OrderTotal__c = 1;
        insert opsOrder;

        // Job_Order__c jobOrder = new Job_Order__c();
        // jobOrder.XometryJobID__c = j.XometryJobID__c;
        // jobOrder.Job__c = j.Id;
        // jobOrder.Ops_Order__c = opsOrder.Id;
        // jobOrder.XometryOpsOrderID__c = opsOrder.XometryOpsOrderID__c;

        Test.startTest();
        Job__c j = new Job__c();
        j.Stage__c = 'Accepted';
        j.Name = 'Test-Job';
        j.XometryJobID__c = 'Test-Job';
        j.OrderDueDate__c = Date.today() + 7;
        j.ShippingService__C = 'Fedex';
        j.ShippingMethod__c = 'Two Day Air';
        j.XometryOpsOrderID__c = opsOrder.XometryOpsOrderID__c;
        insert j;
        Test.stopTest();

        System.debug('How many record are on the Job Order');
        List<Job_Order__c> myJOrderList = [SELECT Name, XometryOpsOrderID__c, XometryJobID__c FROM Job_Order__c];

        System.assertEquals(
            opsOrder.XometryOpsOrderID__c +
            '-' +
            j.XometryJobID__c,
            [SELECT Name FROM Job_Order__c LIMIT 1]
            .Name,
            'Junction should be renamed'
        );
    }

    @isTest(seeAllData=false)
    public static void updateStatusRollUpOnOrderTest() {
        admin_ref_variable__mdt largeOrderAmountRecord = [
            SELECT number_ref_Value__c
            FROM admin_ref_variable__mdt
            WHERE label = 'LargeOrderAmount'
        ][0];
        Double largeOrderAmount = largeOrderAmountRecord.number_ref_Value__c;
        Date OrderPlacedDate = Date.today();
        Ops_Order__c opsOrder = new Ops_Order__c();
        opsOrder.Cases_In_Progress__c = 99;
        opsOrder.Jobs_In_Progress__c = 99;
        opsOrder.Cases_Completed__c = 99;
        opsOrder.Jobs_Completed__c = 99;
        opsOrder.XometryOpsOrderID__c = 'BBBBB-20100';
        opsOrder.AllOrdersTotal__c = largeOrderAmount + 1;
        opsOrder.OrderTotal__c = largeOrderAmount + 1;
        opsOrder.Order_Date__c = OrderPlacedDate;

        Ops_Order__c opsOrder2 = new Ops_Order__c();
        opsOrder2.Cases_In_Progress__c = 99;
        opsOrder2.Jobs_In_Progress__c = 99;
        opsOrder2.Cases_Completed__c = 99;
        opsOrder2.Jobs_Completed__c = 99;
        opsOrder2.XometryOpsOrderID__c = 'BBBBB-20200';
        opsOrder2.AllOrdersTotal__c = largeOrderAmount + 1;
        opsOrder2.OrderTotal__c = largeOrderAmount + 1;
        opsOrder2.Order_Date__c = OrderPlacedDate;

        insert new List<Ops_Order__c>{ opsOrder, opsOrder2 };

        Job__c testJob = new Job__c(
            Technical_Review_Status__c = 'Pending Technical Review',
            Name = 'Test-Job1',
            XometryJobID__c = 'TestJob1',
            XometryOpsOrderID__c = opsOrder.XometryOpsOrderID__c
        );
        Job__c testJob2 = new Job__c(
            Technical_Review_Status__c = 'Pending Technical Review',
            Name = 'Test-Job2',
            XometryJobID__c = 'TestJob2',
            XometryOpsOrderID__c = opsOrder2.XometryOpsOrderID__c
        );

        Test.startTest();

        insert new List<Job__c>{ testJob, testJob2 };

        delete [SELECT Id FROM Job_Order__c WHERE Job__c = :testJob2.Id];

        Test.stopTest();

        Map<Id, Ops_Order__c> opsOrderResult = new Map<Id, Ops_Order__c>(
            [SELECT Jobs_In_Progress__c, Jobs_Completed__c FROM Ops_Order__c]
        );

        System.assertEquals(1, opsOrderResult.get(opsOrder.Id).Jobs_In_Progress__c, 'Rollup should be updated');
        System.assertEquals(0, opsOrderResult.get(opsOrder.Id).Jobs_Completed__c, 'Rollup should be updated');

        System.assertEquals(0, opsOrderResult.get(opsOrder2.Id).Jobs_In_Progress__c, 'Rollup should be updated');
        System.assertEquals(0, opsOrderResult.get(opsOrder2.Id).Jobs_Completed__c, 'Rollup should be updated');

        System.assertEquals(
            1,
            [SELECT Id FROM Job__c WHERE OrderID__c = :opsOrder2.Id].size(),
            'Job still relates to order'
        );
    }
}