unpackaged/main/default/objects/Admin_Ref_Variable__mdt/Admin_Ref_Variable__mdt.object-meta.xml
<CustomObject>
    <description>This custom metadata is used to allow admins to adjust variables that are used in Apex flows</description>
    <label>Admin Ref Variable</label>
    <pluralLabel>Admin Ref Variables</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Admin_Ref_Variable__mdt/fields/Number_Ref_Value__c.field-meta.xml
<CustomField>
    <fullName>Number_Ref_Value__c</fullName>
    <description>This variable is used if the reference variable is a number value</description>
    <label>Number Ref Value</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/GNOOrder__c.field-meta.xml
<CustomField>
    <fullName>GNOOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Ops_Order__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Job ID Associated with the Case</description>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>GNO Jobs</description>
    <label>Job</label>
    <nameField>
        <label>Job ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/OrderDueDate__c.field-meta.xml
<CustomField>
    <fullName>OrderDueDate__c</fullName>
    <label>Order Due Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/XometryJobID__c.field-meta.xml
<CustomField>
    <fullName>XometryJobID__c</fullName>
    <externalId>true</externalId>
    <label>Xometry Job ID</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/XometryOpsOrderID__c.field-meta.xml
<CustomField>
    <fullName>XometryOpsOrderID__c</fullName>
    <label>Xometry Ops Order ID</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Ops_Order__c/Ops_Order__c.object-meta.xml
<CustomObject>
    <description>Order object for the GNO Team. Used for purposes of tracking orders and jobs.</description>
    <label>Ops Order</label>
    <nameField>
        <label>Ops Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ops Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Ops_Order__c/fields/AllOrdersTotal__c.field-meta.xml
<CustomField>
    <fullName>AllOrdersTotal__c</fullName>
    <description>The total of all non-cancelled child orders and parent order.</description>
    <label>All Orders Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Ops_Order__c/fields/Is_Large_Order__c.field-meta.xml
<CustomField>
    <fullName>Is_Large_Order__c</fullName>
    <formula>AND(AllOrdersTotal__c  &gt;  $CustomMetadata.Admin_Ref_Variable__mdt.LargeOrderAmount.Number_Ref_Value__c,
 Order_Date__c  &gt;=  $CustomMetadata.Admin_Ref_Variable__mdt.LargeOrderAmount.Date_Ref_Value__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Large Order</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Ops_Order__c/fields/Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Date__c</fullName>
    <label>Order Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Ops_Order__c/fields/XometryOpsOrderID__c.field-meta.xml
<CustomField>
    <fullName>XometryOpsOrderID__c</fullName>
    <externalId>true</externalId>
    <label>Xometry Ops Order ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/OpsOrderPopulateBusinessHoursBatchTest.cls
@isTest
private class OpsOrderPopulateBusinessHoursBatchTest {
    
    @isTest(seeAllData=false)
    static void executeTest() {

        admin_ref_variable__mdt largeOrderAmountRecord = [
            SELECT number_ref_Value__c
            FROM admin_ref_variable__mdt
            WHERE label = 'LargeOrderAmount'
        ][0];

        Map<String, BusinessHours> hoursMap = new Map<String, BusinessHours>();
        for (BusinessHours bHours : [SELECT Id, Name FROM BusinessHours]) {
            hoursMap.put(bHours.Name, bHours);
        }

        Ops_Order__c testOpsOrder = new Ops_Order__c();
        testOpsOrder.XometryOpsOrderID__c = 'AAAAA-00001';
        testOpsOrder.Order_Date__c = Date.today();
        testOpsOrder.AllOrdersTotal__c = largeOrderAmountRecord.number_ref_Value__c + 1;
        insert testOpsOrder;

        System.assertEquals(
            true,
            [SELECT Is_Large_Order__c FROM Ops_Order__c WHERE Id = :testOpsOrder.Id]
            .Is_Large_Order__c,
            'Record is Large Order'
        );

        Job__c testJob = new Job__c();
        testJob.Name = 'Test-Job';
        testJob.XometryJobID__c = 'Test-Job';
        testJob.XometryOpsOrderID__c = 'AAAAA-00001';
        testJob.OrderDueDate__c = Date.today() + 7;
        insert testJob;

        Case testCase = new Case(Job__c = testJob.Id, GNOOrder__c = testOpsOrder.Id, Type = 'Technical Review');
        Case testCase2 = new Case(Job__c = testJob.Id, GNOOrder__c = testOpsOrder.Id, Type = 'Large Order Approval');
        Case testCase3 = new Case(Job__c = testJob.Id, GNOOrder__c = testOpsOrder.Id, Type = 'Technical Questions');
        insert new List<Case>{testCase,testCase2,testCase3};

        System.assertNotEquals(
            hoursMap.get('POD Business Hours - EST').Id,
            [SELECT BusinessHoursId FROM Case WHERE Id = :testCase.Id]
            .BusinessHoursId,
            'BusinessHoursId should not be default'
        );

        Test.startTest();

        Database.executeBatch( new OpsOrderPopulateBusinessHoursBatch() );

        Test.stopTest();

        Map<Id,Case> testResultMap = new Map<Id,Case>([SELECT BusinessHoursId FROM Case]);

        System.assertEquals(
            hoursMap.get('POD Business Hours - EST').Id,
            testResultMap.get(testCase.Id).BusinessHoursId,
            'BusinessHoursId should be updated'
        );

        System.assertEquals(
            hoursMap.get('POD Business Hours - EST').Id,
            testResultMap.get(testCase2.Id).BusinessHoursId,
            'BusinessHoursId should be updated'
        );

        System.assertNotEquals(
            hoursMap.get('POD Business Hours - EST').Id,
            testResultMap.get(testCase3.Id).BusinessHoursId,
            'BusinessHoursId should not be updated'
        );

    }
}