unpackaged/main/default/objects/Contact/fields/Primary_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>The Primary Email of the Contact.</description>
    <externalId>true</externalId>
    <inlineHelpText>Adjust the email above to change the value. The Primary Email Address is a unique email in the system.</inlineHelpText>
    <label>Primary Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Primary_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Primary Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/Order_Erp__c.object-meta.xml
<CustomObject>
    <description>This object cotains the orders from Xometry ERP. An order is created in Salesforce when the Order date is populated. 

Technical Note: Quote and Orders are the same object in the source system but seperated in Salesforce as Orders represent the end of the opportunity process.</description>
    <label>Order ERP</label>
    <nameField>
        <displayFormat>Order-{000000}</displayFormat>
        <label>Order Erp Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders ERP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order_Erp__c/fields/AccountID__c.field-meta.xml
<CustomField>
    <fullName>AccountID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Account that the order is placed for.</description>
    <label>AccountID</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Orders_Erp</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/ContactID__c.field-meta.xml
<CustomField>
    <fullName>ContactID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ContactID</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Orders_Erp</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/LeadID__c.field-meta.xml
<CustomField>
    <fullName>LeadID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LeadID</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>Orders_Erp</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/OpportunityID__c.field-meta.xml
<CustomField>
    <fullName>OpportunityID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OpportunityID</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Orders_Erp</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/Order_Email__c.field-meta.xml
<CustomField>
    <fullName>Order_Email__c</fullName>
    <description>The email address that was used to place the order.</description>
    <label>Order Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/Xometry_ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>Xometry_ERP_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>This value is the unique order.id created in erp. The quote ID and Order ID are the same.</description>
    <externalId>true</externalId>
    <inlineHelpText>Value to use to look up an order in the ERP.</inlineHelpText>
    <label>Order ID</label>
    <length>12</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/Quote_ERP__c.object-meta.xml
<CustomObject>
    <description>A quote that is sent over from ERP</description>
    <label>Quote ERP</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote_ERP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes ERP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Quote_ERP__c/fields/AccountID__c.field-meta.xml
<CustomField>
    <fullName>AccountID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Account that the quote belongs to</description>
    <label>AccountID</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Quotes_ERP</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/ContactID__c.field-meta.xml
<CustomField>
    <fullName>ContactID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Contact</description>
    <label>ContactID</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Quotes_ERP</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/LeadID__c.field-meta.xml
<CustomField>
    <fullName>LeadID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the lead a quote is associated with</description>
    <label>LeadID</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>Quotes_ERP</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/OpportunityID__c.field-meta.xml
<CustomField>
    <fullName>OpportunityID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the related opportunity</description>
    <label>OpportunityID</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Quotes_ERP</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Quote_Email__c.field-meta.xml
<CustomField>
    <fullName>Quote_Email__c</fullName>
    <description>The email that is associated with the quote.</description>
    <label>Quote Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Xometry_ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>Xometry_ERP_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Unique Qoute ID created in Xometry ERP</description>
    <externalId>true</externalId>
    <label>Quote ID</label>
    <length>13</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Supplies_Order__c/Supplies_Order__c.object-meta.xml
<CustomObject>
    <label>Supplies Order</label>
    <nameField>
        <label>Supplies Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplies Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Supplies_Order__c/fields/AccountID__c.field-meta.xml
<CustomField>
    <fullName>AccountID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AccountID</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supplies Orders</relationshipLabel>
    <relationshipName>Supplies_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Order__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ContactId</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Supplies Orders</relationshipLabel>
    <relationshipName>Supplies_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Order__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OpportunityId</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Supplies Orders</relationshipLabel>
    <relationshipName>Supplies_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Order__c/fields/Order_Email__c.field-meta.xml
<CustomField>
    <fullName>Order_Email__c</fullName>
    <label>Order Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Quote__c/Supplies_Quote__c.object-meta.xml
<CustomObject>
    <description>This stores the P21 Quotes as records in Salesforce before transformation.</description>
    <label>Supplies Quote</label>
    <nameField>
        <label>Supplies Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplies Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Supplies_Quote__c/fields/AccountID__c.field-meta.xml
<CustomField>
    <fullName>AccountID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AccountID</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supplies Quotes</relationshipLabel>
    <relationshipName>Supplies_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Quote__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ContactId</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Supplies Quotes</relationshipLabel>
    <relationshipName>Supplies_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Quote__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OpportunityId</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Supplies Quotes</relationshipLabel>
    <relationshipName>Supplies_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Quote__c/fields/Quote_Email__c.field-meta.xml
<CustomField>
    <fullName>Quote_Email__c</fullName>
    <label>Quote Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/classes/HandlerUtil.cls
public with sharing class HandlerUtil {
    /**
     * @description Convert the Lead to Opportunity Account from Quotes and Orders
     * @param convertList list of objects with leads associated for convertion
     *  convertList must not be a Lead for this function to work and Contact list must be after insert
     * @return srLeadConvertResult List of convert result
     */
    public static List<Database.LeadConvertResult> leadConverter(List<sObject> convertList) {
        List<Database.LeadConvert> leadConvertList = new List<Database.LeadConvert>();
        List<Database.LeadConvertResult> srLeadConvertResult = new List<Database.LeadConvertResult>();

        LeadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted = TRUE LIMIT 1];

        Map<String, Id> leadEmailCheckSet = new Map<String, Id>();
        Map<String, Id> leadERPCheckSet = new Map<String, Id>();
        for (sObject convertObj : convertList) {
            //quote path
            if (convertObj instanceof Quote_ERP__c) {
                Quote_ERP__c q = (Quote_ERP__c) convertObj;
                if (q.Quote_Email__c != null) {
                    leadEmailCheckSet.put(q.Quote_Email__c.toLowercase(), q.Id);
                }
            }
            //contact path
            if (convertObj instanceof Contact) {
                Contact c = (Contact) convertObj;
                if (c.Primary_Email__c != null) {
                    leadEmailCheckSet.put(c.Primary_Email__c.toLowercase(), c.Id);
                }
            }
            //order path
            if (convertObj instanceof Order_Erp__c) {
                Order_Erp__c o = (Order_Erp__c) convertObj;
                if (o.LeadID__c != null && o.Xometry_ERP_ID__c != null) {
                    leadERPCheckSet.put(o.Xometry_ERP_ID__c, o.Id);
                }
            }

            //SuppliesQuote path
            if (convertObj instanceof Supplies_Quote__C) {
                Supplies_Quote__C supQuote = (Supplies_Quote__C) convertObj;
                if (supQuote.Quote_Email__c != null) {
                    leadEmailCheckSet.put(supQuote.Quote_Email__c.toLowercase(), supQuote.Id);
                }
            }

            //SuppliesQuote path
            if (convertObj instanceof Supplies_Order__C) {
                Supplies_Order__C supOrder = (Supplies_Order__C) convertObj;
                if (supOrder.Order_Email__c != null) {
                    leadEmailCheckSet.put(supOrder.Order_Email__C.toLowercase(), supOrder.Id);
                }
            }
        }

        Map<Id, Id> leadConversionMap = new Map<Id, Id>();

        //quote+contact path
        if (!leadEmailCheckSet.isEmpty()) {
            //Fetch Leads to be converted
            //Create the DB converter for Leads
            for (Lead l : [
                SELECT ID, Primary_Email__c
                FROM Lead
                WHERE isConverted = FALSE AND Primary_Email__c IN :leadEmailCheckSet.keySet()
            ]) {
                if (leadEmailCheckSet.containskey(l.Primary_Email__c)) {
                    leadConversionMap.put(leadEmailCheckSet.get(l.Primary_Email__c), l.Id);
                }
            }
        }

        //order path
        if (!leadERPCheckSet.isEmpty()) {
            for (Quote_ERP__C existingQuote : [
                SELECT Xometry_ERP_ID__C, LeadID__C
                FROM Quote_ERP__C
                WHERE Xometry_ERP_ID__C IN :leadERPCheckSet.keySet() AND LeadID__R.IsConverted = FALSE
            ]) {
                leadConversionMap.put(leadERPCheckSet.get(existingQuote.Xometry_ERP_ID__C), existingQuote.LeadID__c);
            }
        }

        Set<Id> finalLeadIdSet = new Set<Id>();
        for (sObject convertObj : convertList) {
            if (
                leadConversionMap.containsKey((Id) convertObj.get('Id')) &&
                !finalLeadIdSet.contains(leadConversionMap.get((Id) convertObj.get('Id')))
            ) {
                //database Converter
                Database.LeadConvert l_dbLeadConvert = new Database.LeadConvert();
                l_dbLeadConvert.setConvertedStatus(convertStatus.MasterLabel);
                l_dbLeadConvert.setLeadID(leadConversionMap.get((Id) convertObj.get('Id')));
                finalLeadIdSet.add(leadConversionMap.get((Id) convertObj.get('Id')));
                l_dbLeadConvert.setOwnerID((Id) convertObj.get('OwnerID'));

                if (convertObj instanceof Contact) {
                    l_dbLeadConvert.setAccountID((Id) convertObj.get('AccountId'));
                    l_dbLeadConvert.setContactID((Id) convertObj.get('Id'));
                } else {
                    l_dbLeadConvert.setAccountID((Id) convertObj.get('AccountID__c'));
                    l_dbLeadConvert.setContactID((Id) convertObj.get('ContactID__c'));
                    l_dbLeadConvert.setOpportunityId((Id) convertObj.get('OpportunityID__c'));
                }
                //One Converter Class Per Lead
                leadConvertList.add(l_dbLeadConvert);
            }
        }

        if (leadConvertList.size() > 0) {
            srLeadConvertResult = Database.convertLead(leadConvertList, false);
        }

        return srLeadConvertResult;
    }
}