unpackaged/main/default/objects/Job_Order__c/Job_Order__c.object-meta.xml
<CustomObject>
    <label>Job Order</label>
    <nameField>
        <label>Job Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job_Order__c/fields/Ops_Order__c.field-meta.xml
<CustomField>
    <fullName>Ops_Order__c</fullName>
    <label>Ops Order</label>
    <referenceTo>Ops_Order__c</referenceTo>
    <relationshipLabel>Job Orders</relationshipLabel>
    <relationshipName>Job_Orders</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Job_Order__c/fields/XometryJobID__c.field-meta.xml
<CustomField>
    <fullName>XometryJobID__c</fullName>
    <label>Xometry Job ID</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Job_Order__c/fields/XometryOpsOrderID__c.field-meta.xml
<CustomField>
    <fullName>XometryOpsOrderID__c</fullName>
    <label>Xometry Ops Order ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Ops_Order__c/Ops_Order__c.object-meta.xml
<CustomObject>
    <description>Order object for the GNO Team. Used for purposes of tracking orders and jobs.</description>
    <label>Ops Order</label>
    <nameField>
        <label>Ops Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ops Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Ops_Order__c/fields/XometryOpsOrderID__c.field-meta.xml
<CustomField>
    <fullName>XometryOpsOrderID__c</fullName>
    <externalId>true</externalId>
    <label>Xometry Ops Order ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/JobOrderHandler.cls
public with sharing class JobOrderHandler {
    public static void renameOnCreate(List<Job_Order__c> newJoOrderList) {
        /**
         * @description changes the Name in the junction record to a more readeable identifier
         */
        Map<Id, List<Job_Order__c>> jobOrderMap = new Map<Id, List<Job_Order__c>>();
        for (Job_Order__c jobOrder : newJoOrderList) {
            jobOrder.Name = jobOrder.XometryOpsOrderID__c + '-' + jobOrder.XometryJobID__c;
        }
    }

    /**
     * @description Listens for status updates and send changes to Parent Orders
     * @param jobOrderList list of JobsOrder being created/updated/deleted
     * @param oldJobOrderMap - map of old JobOrders values
     */
    public static void updateStatusRollUpOnOrder(
        List<Job_Order__c> jobOrderList,
        Map<ID, Job_Order__c> oldJobOrderMap
    ) {
        Set<Id> orderIds = new Set<Id>();
        //Checking JobsOrders with updated Relations
        //and collecting Ids Orders to reset
        for (Job_Order__c oneJobOrder : jobOrderList) {
            Boolean cond = Trigger.isDelete;

            if (Trigger.isUpdate && ((oldJobOrderMap.get(oneJobOrder.Id).Ops_Order__c != oneJobOrder.Ops_Order__c))) {
                cond = true;

                if (oldJobOrderMap.get(oneJobOrder.Id).Ops_Order__c != null) {
                    //reset old order too
                    orderIds.add(oldJobOrderMap.get(oneJobOrder.Id).Ops_Order__c);
                }
            }

            if (cond && oneJobOrder.Ops_Order__c != null) {
                orderIds.add(oneJobOrder.Ops_Order__c);
            }
            //Get all OrderIds affected by looking at the junction Object
        }

        if (!orderIds.isEmpty()) {
            OpsOrderHandler.updateLargeOrderSummary(orderIds);
        }
    }
}