unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>GNO Jobs</description>
    <label>Job</label>
    <nameField>
        <label>Job ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/RiskFactor__c.field-meta.xml
<CustomField>
    <fullName>RiskFactor__c</fullName>
    <label>Risk Factor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Rescinded</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Vendor Completed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Auction Failed to Award</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Technical_Review_Status__c.field-meta.xml
<CustomField>
    <fullName>Technical_Review_Status__c</fullName>
    <label>Technical Review Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Technical Review Required</fullName>
                <default>true</default>
                <label>No Technical Review Required</label>
            </value>
            <value>
                <fullName>Pending Technical Review</fullName>
            </value>
            <value>
                <fullName>Technical Review Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Job_Order__c/Job_Order__c.object-meta.xml
<CustomObject>
    <label>Job Order</label>
    <nameField>
        <label>Job Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job_Order__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Job Orders</relationshipLabel>
    <relationshipName>Job_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Job_Order__c/fields/Ops_Order__c.field-meta.xml
<CustomField>
    <fullName>Ops_Order__c</fullName>
    <label>Ops Order</label>
    <referenceTo>Ops_Order__c</referenceTo>
    <relationshipLabel>Job Orders</relationshipLabel>
    <relationshipName>Job_Orders</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Ops_Order__c/Ops_Order__c.object-meta.xml
<CustomObject>
    <description>Order object for the GNO Team. Used for purposes of tracking orders and jobs.</description>
    <label>Ops Order</label>
    <nameField>
        <label>Ops Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ops Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Ops_Order__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Partially Complete</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Reopened by Job</fullName>
            </value>
            <value>
                <fullName>Reopened by Updated Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/UpdateJobReviewStatus.cls
public with sharing class UpdateJobReviewStatus implements Queueable {
    Map<Id, Ops_Order__c> newLargeOrdersMap = new Map<Id, Ops_Order__c>();
    public UpdateJobReviewStatus(Map<Id, Ops_Order__c> inNewLargeOrdersMap) {
        newLargeOrdersMap = inNewLargeOrdersMap;
    }
    public void execute(QueueableContext context) {
        System.debug('In Queuable execute');
        if (!newLargeOrdersMap.isEmpty()) {
            List<Job__c> jobsToUpdate = new List<Job__c>();
            for (Job_Order__c jobOrd : [
                SELECT Id, Job__c, Job__r.Technical_Review_Status__c
                FROM Job_Order__c
                WHERE
                    Ops_Order__c IN :newLargeOrdersMap.keySet()
                    AND Job__r.RiskFactor__c = 'High'
                    AND Job__r.Technical_Review_Status__c = 'No Technical Review Required'
                    AND Job__r.Stage__c NOT IN :AppConstants.jobClosedStringSet
            ]) {
                Job__c thisJob = new Job__c(
                    Id = jobOrd.Job__c,
                    Technical_Review_Status__c = 'Pending Technical Review'
                );
                jobsToUpdate.add(thisJob);
            }
            if (!jobsToUpdate.isEmpty()) {
                DatabaseUtilities.saveToDatabase(
                    jobsToUpdate,
                    'OpsOrderHandler.updateJobTechReviewStatus',
                    'Updating Job Tech Review Status'
                );
            }
        }
    }
}