unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>GNO Jobs</description>
    <label>Job</label>
    <nameField>
        <label>Job ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/OrderDueDate__c.field-meta.xml
<CustomField>
    <fullName>OrderDueDate__c</fullName>
    <label>Order Due Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/OrderID__c.field-meta.xml
<CustomField>
    <fullName>OrderID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Order associated with this job</description>
    <label>Order ID</label>
    <referenceTo>Ops_Order__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/ShippingService__c.field-meta.xml
<CustomField>
    <fullName>ShippingService__c</fullName>
    <label>Shipping Service</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Rescinded</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Vendor Completed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Auction Failed to Award</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/XometryJobID__c.field-meta.xml
<CustomField>
    <fullName>XometryJobID__c</fullName>
    <externalId>true</externalId>
    <label>Xometry Job ID</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/XometryOpsOrderID__c.field-meta.xml
<CustomField>
    <fullName>XometryOpsOrderID__c</fullName>
    <label>Xometry Ops Order ID</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Job_Event__c/Job_Event__c.object-meta.xml
<CustomObject>
    <label>Job Event</label>
    <nameField>
        <label>Job Event</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job_Event__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Job Events</relationshipLabel>
    <relationshipName>Job_Events</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/Job_Event__c/fields/JobID__c.field-meta.xml
<CustomField>
    <fullName>JobID__c</fullName>
    <label>Job ID</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Job_Event__c/fields/Qualifying_Object__c.field-meta.xml
<CustomField>
    <fullName>Qualifying_Object__c</fullName>
    <label>Qualifying Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Order</fullName>
            </value>
            <value>
                <fullName>Job</fullName>
            </value>
            <value>
                <fullName>Part</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Ops_Order__c/Ops_Order__c.object-meta.xml
<CustomObject>
    <description>Order object for the GNO Team. Used for purposes of tracking orders and jobs.</description>
    <label>Ops Order</label>
    <nameField>
        <label>Ops Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ops Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Ops_Order__c/fields/OrderTotal__c.field-meta.xml
<CustomField>
    <fullName>OrderTotal__c</fullName>
    <label>Order Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Ops_Order__c/fields/POD__c.field-meta.xml
<CustomField>
    <fullName>POD__c</fullName>
    <label>POD</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Albatrosses</fullName>
            </value>
            <value>
                <fullName>Atomic Rocks</fullName>
            </value>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>First Impressions</fullName>
            </value>
            <value>
                <fullName>Impodsters</fullName>
            </value>
            <value>
                <fullName>Rocket Power</fullName>
            </value>
            <value>
                <fullName>SpaceTechs</fullName>
            </value>
            <value>
                <fullName>Triple Threat</fullName>
            </value>
            <value>
                <fullName>Amazing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Ops_Order__c/fields/ShippingMethod__c.field-meta.xml
<CustomField>
    <fullName>ShippingMethod__c</fullName>
    <label>Shipping Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Ops_Order__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Partially Complete</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Reopened by Job</fullName>
            </value>
            <value>
                <fullName>Reopened by Updated Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Ops_Order__c/fields/XometryOpsOrderID__c.field-meta.xml
<CustomField>
    <fullName>XometryOpsOrderID__c</fullName>
    <externalId>true</externalId>
    <label>Xometry Ops Order ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Order_Event__c/Order_Event__c.object-meta.xml
<CustomObject>
    <label>Order Event</label>
    <nameField>
        <label>Order Event</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order_Event__c/fields/Job_Event__c.field-meta.xml
<CustomField>
    <fullName>Job_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Event</label>
    <referenceTo>Job_Event__c</referenceTo>
    <relationshipLabel>Job Triggered Events</relationshipLabel>
    <relationshipName>Job_Triggered_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Event__c/fields/Ops_Order__c.field-meta.xml
<CustomField>
    <fullName>Ops_Order__c</fullName>
    <label>Ops Order</label>
    <referenceTo>Ops_Order__c</referenceTo>
    <relationshipLabel>Order Events</relationshipLabel>
    <relationshipName>Order_Events</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/Order_Event__c/fields/OrderID__c.field-meta.xml
<CustomField>
    <fullName>OrderID__c</fullName>
    <label>Order ID</label>
    <length>11</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ProcessException/fields/Ops_Order__c.field-meta.xml
<CustomField>
    <fullName>Ops_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ops Order</label>
    <referenceTo>Ops_Order__c</referenceTo>
    <relationshipLabel>Process Exceptions</relationshipLabel>
    <relationshipName>Process_Exceptions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProcessException/fields/Qualifying_Object__c.field-meta.xml
<CustomField>
    <fullName>Qualifying_Object__c</fullName>
    <label>Qualifying Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Order</fullName>
            </value>
            <value>
                <fullName>Job</fullName>
            </value>
            <value>
                <fullName>Part</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ProcessException/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ProcessExceptionViewControllerTest.cls
@isTest
private class ProcessExceptionViewControllerTest {
    @isTest
    static void getProExcRelOrder_Test() {
        Ops_Order__c opsOrder = new Ops_Order__c();
        opsOrder.POD__c = 'First Impressions';
        opsOrder.XometryOpsOrderID__c = 'Ops-Order';
        opsOrder.OrderTotal__c = 1;
        insert opsOrder;

        Job__c j = new Job__c();
        j.Stage__c = 'Accepted';
        j.Name = 'Test-Job';
        j.XometryJobID__c = 'Test-Job';
        j.OrderDueDate__c = Date.today() + 7;
        j.ShippingService__C = 'Fedex';
        j.ShippingMethod__c = 'Two Day Air';
        j.XometryOpsOrderID__c = opsOrder.XometryOpsOrderID__c;
        insert j;

        Order_Event__c orderEvent = new Order_Event__c();
        orderEvent.Name = 'Test order Event 01';
        orderEvent.OrderID__c = opsOrder.XometryOpsOrderID__c;
        orderEvent.Ops_Order__c = opsOrder.Id;
        insert orderEvent;

        Job_Event__c jobEvent = new Job_Event__c();
        jobEvent.Name = 'Test job Event 01';
        jobEvent.JobID__c = j.XometryJobID__c;
        jobEvent.Job__c = j.Id;
        insert jobEvent;

        ProcessException objProc1 = new ProcessException();
        objProc1.AttachedToId = orderEvent.Id;
        objProc1.Message = 'Test 01';
        insert objProc1;

        ProcessException objProc3 = new ProcessException();
        objProc3.AttachedToId = jobEvent.Id;
        objProc3.Message = 'Test 03';
        insert objProc3;

        ProcessException objProc2 = new ProcessException();
        objProc2.AttachedToId = orderEvent.Id;
        objProc2.Message = 'Test 02';
        insert objProc2;

        Test.startTest();
            List<ProcessException> processExceptionsList = ProcessExceptionViewController.getAllProcessExceptions(opsOrder.Id);
        Test.stopTest();

        System.assertEquals(3, processExceptionsList.size(), 'Not all process Exceptions related to the order have been found');
        System.assertEquals(objProc2.Message, processExceptionsList[0].Message, 'Record is not the expected');
        System.assertEquals(objProc1.Message, processExceptionsList[1].Message, 'Record is not the expected');
        System.assertEquals(objProc3.Message, processExceptionsList[2].Message, 'Record is not the expected');
    }

    @isTest
    static void getProExcRelOrderMass_Test() {
        Ops_Order__c opsOrder = new Ops_Order__c();
        opsOrder.POD__c = 'First Impressions';
        opsOrder.XometryOpsOrderID__c = 'Ops-Order';
        opsOrder.OrderTotal__c = 1;
        opsOrder.pod__c = 'Automotive';
        insert opsOrder;

        Job__c j = new Job__c();
        j.Stage__c = 'Accepted';
        j.Name = 'Test-Job';
        j.XometryJobID__c = 'Test-Job';
        j.OrderDueDate__c = Date.today() + 7;
        j.ShippingService__C = 'Fedex';
        j.ShippingMethod__c = 'Two Day Air';
        j.XometryOpsOrderID__c = opsOrder.XometryOpsOrderID__c;
        insert j;

        List<Order_Event__c> lstOrderEvents = new List<Order_Event__c>();
        List<Job_Event__c> lstJobEvents = new List<Job_Event__c>();
        for(Integer i = 0; i < 50 ; i++)
        {
            Order_Event__c orderEvent = new Order_Event__c();
            orderEvent.Name = 'Test order Event '+i;
            orderEvent.OrderID__c = opsOrder.XometryOpsOrderID__c;
            orderEvent.Ops_Order__c = opsOrder.Id;
            orderEvent.Qualifying_Object__c = 'Part';
            orderEvent.Type__c = 'Late Bad Outcome';
            lstOrderEvents.add(orderEvent);
            
            Job_Event__c jobEvent = new Job_Event__c();
            jobEvent.Name = 'Test job Event '+i;
            jobEvent.JobID__c = j.XometryJobID__c;
            jobEvent.Job__c = j.Id;
            jobEvent.Qualifying_Object__c = 'Part';
            jobEvent.Type__c = 'Late Bad Outcome';
            lstJobEvents.add(jobEvent);
        }

        insert lstOrderEvents;
        insert lstJobEvents;

        Test.startTest();
            List<ProcessException> processExceptionsList = ProcessExceptionViewController.getAllProcessExceptions(opsOrder.Id);
        Test.stopTest();

        System.assertEquals(100, processExceptionsList.size(), 'Not all process Exceptions related to the order have been found');
    }

    @isTest    
    static void getProExcRelJob_Test() {
        Ops_Order__c opsOrder = new Ops_Order__c();
        opsOrder.POD__c = 'First Impressions';
        opsOrder.XometryOpsOrderID__c = 'Ops-Order';
        opsOrder.OrderTotal__c = 1;
        insert opsOrder;

        Job__c j = new Job__c();
        j.Stage__c = 'Accepted';
        j.Name = 'Test-Job';
        j.XometryJobID__c = 'Test-Job';
        j.OrderDueDate__c = Date.today() + 7;
        j.ShippingService__C = 'Fedex';
        j.ShippingMethod__c = 'Two Day Air';
        j.XometryOpsOrderID__c = opsOrder.XometryOpsOrderID__c;
        insert j;

        Order_Event__c orderEvent = new Order_Event__c();
        orderEvent.Name = 'Test order Event 01';
        orderEvent.OrderID__c = opsOrder.XometryOpsOrderID__c;
        orderEvent.Ops_Order__c = opsOrder.Id;
        insert orderEvent;

        Job_Event__c jobEvent = new Job_Event__c();
        jobEvent.Name = 'Test job Event 01';
        jobEvent.JobID__c = j.XometryJobID__c;
        jobEvent.Job__c = j.Id;
        insert jobEvent;

        ProcessException objProc1 = new ProcessException();
        objProc1.AttachedToId = orderEvent.Id;
        objProc1.Message = 'Test 01';
        insert objProc1;

        ProcessException objProc2 = new ProcessException();
        objProc2.AttachedToId = orderEvent.Id;
        objProc2.Message = 'Test 02';
        insert objProc2;

        ProcessException objProc3 = new ProcessException();
        objProc3.AttachedToId = jobEvent.Id;
        objProc3.Message = 'Test 03';
        insert objProc3;

        Test.startTest();
            List<ProcessException> processExceptionsList = ProcessExceptionViewController.getAllProcessExceptions(j.Id);
        Test.stopTest();

        System.assertEquals(1, processExceptionsList.size(), 'Not all process Exceptions related to the Job have been found');
        System.assertEquals(objProc3.Message, processExceptionsList[0].Message, 'Record is not the expected');
    }

    @isTest
    static void getOrderInfo_Test() {
        Ops_Order__c opsOrder = new Ops_Order__c();
        opsOrder.POD__c = 'First Impressions';
        opsOrder.XometryOpsOrderID__c = 'Ops-Order';
        opsOrder.OrderTotal__c = 1;
        insert opsOrder;

        Test.startTest();
            Ops_Order__c orderReturn = ProcessExceptionViewController.getOpsOrderInfo(opsOrder.Id);
        Test.stopTest();

        System.assertEquals(opsOrder.POD__c, orderReturn.POD__c, 'Not match the pod of the ops order');
    }

    @isTest
    static void getOrderInfoFromJob_Test() {
        Ops_Order__c opsOrder = new Ops_Order__c();
        opsOrder.POD__c = 'First Impressions';
        opsOrder.XometryOpsOrderID__c = 'Ops-Order';
        opsOrder.OrderTotal__c = 1;
        insert opsOrder;

        Job__c j = new Job__c();
        j.Stage__c = 'Accepted';
        j.Name = 'Test-Job';
        j.XometryJobID__c = 'Test-Job';
        j.OrderDueDate__c = Date.today() + 7;
        j.ShippingService__C = 'Fedex';
        j.ShippingMethod__c = 'Two Day Air';
        j.XometryOpsOrderID__c = opsOrder.XometryOpsOrderID__c;
        insert j;

        Test.startTest();
            Ops_Order__c orderReturn = ProcessExceptionViewController.getOpsOrderInfo(j.Id);
        Test.stopTest();

        System.assertEquals(opsOrder.POD__c, orderReturn.POD__c, 'Not match the pod of the ops order');
    }
}