unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>GNO Jobs</description>
    <label>Job</label>
    <nameField>
        <label>Job ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Job_Overdue_Flag__c.field-meta.xml
<CustomField>
    <fullName>Job_Overdue_Flag__c</fullName>
    <label>T- Days to Due Date</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Rescinded</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Vendor Completed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Auction Failed to Award</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/JobOverdueBatch.cls
global class JobOverdueBatch implements Database.Batchable<sObject>, schedulable {
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            [
                SELECT DueDate__c
                FROM Job__c
                WHERE Stage__c NOT IN ('Completed', 'Vendor Completed') AND DueDate__c != NULL
            ]
        );
    }

    global void execute(Database.BatchableContext BC, list<Job__c> scope) {
        Date dToday = System.today();

        for (Job__c job : scope) {
            if (job.DueDate__c != null) {
                job.Job_OverDue_Flag__c = job.DueDate__c.daysBetween(dToday);
            }
        }

        DatabaseUtilities.saveToDatabase(scope, 'JobOverdueBatch.execute', 'Job Overdue Flag update');
    }

    global void finish(Database.BatchableContext BC) {
    }

    global void execute(SchedulableContext sc) {
        Database.executebatch(new JobOverdueBatch());
    }
}