unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>GNO Jobs</description>
    <label>Job</label>
    <nameField>
        <label>Job ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/AcceptedPartnerID__c.field-meta.xml
<CustomField>
    <fullName>AcceptedPartnerID__c</fullName>
    <label>Accepted Partner ID</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/JobOrderedPart__c/JobOrderedPart__c.object-meta.xml
<CustomObject>
    <description>Jobs and their related ordered parts. Jobs hold the responsibility</description>
    <label>Job Ordered Part</label>
    <nameField>
        <label>Job Ordered Parts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Ordered Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/JobOrderedPart__c/fields/JobId__c.field-meta.xml
<CustomField>
    <fullName>JobId__c</fullName>
    <label>Job Id</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Job Ordered Parts</relationshipLabel>
    <relationshipName>Job_Ordered_Parts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/JobOrderedPart__c/fields/JobOrderedPartKey__c.field-meta.xml
<CustomField>
    <fullName>JobOrderedPartKey__c</fullName>
    <description>Job Id : Ordered Part Id</description>
    <label>Job Ordered Part Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/JobOrderedPart__c/fields/OrderedPartId__c.field-meta.xml
<CustomField>
    <fullName>OrderedPartId__c</fullName>
    <label>Ordered Part Id</label>
    <referenceTo>Ordered_Part__c</referenceTo>
    <relationshipLabel>Job Ordered Parts</relationshipLabel>
    <relationshipName>Job_Ordered_Parts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Ops_Order__c/Ops_Order__c.object-meta.xml
<CustomObject>
    <description>Order object for the GNO Team. Used for purposes of tracking orders and jobs.</description>
    <label>Ops Order</label>
    <nameField>
        <label>Ops Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ops Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Ops_Order__c/fields/Is_Large_Order__c.field-meta.xml
<CustomField>
    <fullName>Is_Large_Order__c</fullName>
    <formula>AND(AllOrdersTotal__c  &gt;  $CustomMetadata.Admin_Ref_Variable__mdt.LargeOrderAmount.Number_Ref_Value__c,
 Order_Date__c  &gt;=  $CustomMetadata.Admin_Ref_Variable__mdt.LargeOrderAmount.Date_Ref_Value__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Large Order</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Ordered_Part__c/Ordered_Part__c.object-meta.xml
<CustomObject>
    <label>Ordered Part</label>
    <nameField>
        <label>Xometry Ordered Part ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ordered Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Ordered_Part__c/fields/Ops_Order__c.field-meta.xml
<CustomField>
    <fullName>Ops_Order__c</fullName>
    <label>Ops Order</label>
    <referenceTo>Ops_Order__c</referenceTo>
    <relationshipLabel>Ordered Parts</relationshipLabel>
    <relationshipName>Ordered_Parts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/JobOrderedPartHandler.cls
public with sharing class JobOrderedPartHandler {
    /**
     * @description changes the Name in the junction record to a more readable identifier
     * @param newJobOrderedPartList list of newly created Job Ordered Part
     */
    public static void renameOnCreate(List<JobOrderedPart__c> newJobOrderedPartList) {
        Map<Id, List<JobOrderedPart__c>> jobJOPMap = new Map<Id, List<JobOrderedPart__c>>();
        for (JobOrderedPart__c jop : newJobOrderedPartList) {
            if (!String.isBlank(jop.JobOrderedPartKey__c)) {
                jop.Name = jop.JobOrderedPartKey__c;
            }
        }
    }

    /**
     * @description determines if the Job Ordered Part has being inserted belongs to a large Order if yes then prepare new summary information
     *
     * @param newJobOrderedPartList list of the insert Job Ordered Part information
     */
    public static void checkJobOrderedPartsForLargeOrderSummary(List<JobOrderedPart__c> newJobOrderedPartList) {
        if (!EventBusBypass.isByPassed(largeOrderHelper.ordPartByPass)) {
            Set<ID> orderedPartIDSet = new Set<ID>();
            for (JobOrderedPart__c jOrdPart : newJobOrderedPartList) {
                if (jOrdPart.JobId__c != null && jOrdPart.OrderedPartId__c != null) {
                    orderedPartIDSet.add(jOrdPart.OrderedPartId__c);
                }
            }
            Set<Id> opsOrderToSumIdSet = JobOrderedPartHandler.orderedPartPartofLargeOrderandOnJob(orderedPartIDSet);
            //If we are coming from the JobHandler then the bypass should be on and we can skip this as the jobhandler will handle the summary update
            OpsOrderHandler.updateLargeOrderSummary(opsOrderToSumIdSet);
        }
    }

    /*
    Determine if an Ordered Part is part of a Large Order and return a Set of OpsOrderIds
    */
    public static Set<ID> orderedPartPartofLargeOrder(Set<Id> OrderedPartIDSet) {
        //Map<ID, ID> orderedPartToLargeOrderMap = new Map<ID, ID>();
        Set<ID> orderIDSet = new Set<ID>();
        for (Ordered_Part__c ordPart : [
            SELECT Id, Ops_Order__c
            FROM Ordered_Part__c
            WHERE ID IN :OrderedPartIDSet AND Ops_Order__r.Is_Large_Order__c = TRUE
        ]) {
            //orderedPartToLargeOrderMap.put(ordPart.Id, ordPart.Ops_Order__C);
            orderIDSet.add(ordPart.Ops_Order__C);
        }
        return orderIDSet;
    }

    /*
     * @description Determines for an Ordered Part if the Ordered Part belongs to a Large Order and is Part of a Job that exists in Salesforce
     */
    public static Set<ID> orderedPartPartofLargeOrderandOnJob(Set<Id> OrderedPartIDSet) {
        Set<Id> OpsLarderOrderIDSet = new Set<ID>();
        for (Ordered_Part__c ordPart : [
            SELECT Id, Ops_Order__c, (SELECT Id, JobId__c, JobId__r.AcceptedPartnerID__c FROM Job_Ordered_Parts__r)
            FROM Ordered_Part__c
            WHERE ID IN :OrderedPartIDSet AND Ops_Order__r.Is_Large_Order__c = TRUE
        ]) {
            for (JobOrderedPart__c jOrdPart : ordPart.Job_Ordered_Parts__r) {
                if (jOrdPart.JobId__c != null && jOrdPart.JobId__r.AcceptedPartnerID__c != null) {
                    OpsLarderOrderIDSet.add(ordPart.Ops_Order__c);
                    break;
                }
            }
        }
        return OpsLarderOrderIDSet;
    }
}