unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>GNO Jobs</description>
    <label>Job</label>
    <nameField>
        <label>Job ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/Ordered_Part_Ids_String__c.field-meta.xml
<CustomField>
    <fullName>Ordered_Part_Ids_String__c</fullName>
    <label>Ordered Part Ids String</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Rescinded</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Vendor Completed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Auction Failed to Award</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/XometryJobID__c.field-meta.xml
<CustomField>
    <fullName>XometryJobID__c</fullName>
    <externalId>true</externalId>
    <label>Xometry Job ID</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/JobOrderedPart__c/JobOrderedPart__c.object-meta.xml
<CustomObject>
    <description>Jobs and their related ordered parts. Jobs hold the responsibility</description>
    <label>Job Ordered Part</label>
    <nameField>
        <label>Job Ordered Parts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Ordered Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/classes/JobOrderedPart_Test.cls
@isTest
public with sharing class JobOrderedPart_Test {
    @isTest
    static void renameOnCreateTest() {
        Job__c j = new Job__c();
        j.Name = 'J321034';
        j.XometryJobID__c = 'J321034';
        j.Stage__c = 'Accepted';
        j.ORDERED_PART_Ids_String__c = 'AAABBBCCaeidhgt';

        Test.startTest();
        insert j;
        Test.stopTest();

        JobOrderedPart__c jopRes = [SELECT Id, Name FROM JobOrderedPart__c][0];
        String uKey = j.XometryJobId__c + ' : AAABBBCCaeidhgt';
        System.assertEquals(uKey, jopRes.Name, 'name should be the unique key');
    }
}