unpackaged/main/default/objects/Box_Integration_Service__e/Box_Integration_Service__e.object-meta.xml
<CustomObject>
    <label>Box Integration Service</label>
    <pluralLabel>Box Integration Services</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Box_Integration_Service__e/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Box_Integration_Service__e/fields/Actor__c.field-meta.xml
<CustomField>
    <fullName>Actor__c</fullName>
    <label>Actor</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Box_Integration_Service__e/fields/CaseId__c.field-meta.xml
<CustomField>
    <fullName>CaseId__c</fullName>
    <label>CaseId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Box_Integration_Service__e/fields/CaseNumber__c.field-meta.xml
<CustomField>
    <fullName>CaseNumber__c</fullName>
    <label>CaseNumber</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Box_Integration_Service__e/fields/Filename__c.field-meta.xml
<CustomField>
    <fullName>Filename__c</fullName>
    <label>Filename</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Box_Integration_Service__e/fields/Filepath__c.field-meta.xml
<CustomField>
    <fullName>Filepath__c</fullName>
    <label>Filepath</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Box_Integration_Service__e/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <label>Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Primary_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>The Primary Email of the Contact.</description>
    <externalId>true</externalId>
    <inlineHelpText>Adjust the email above to change the value. The Primary Email Address is a unique email in the system.</inlineHelpText>
    <label>Primary Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Xometry_ERP_Contact_ID__c.field-meta.xml
<CustomField>
    <fullName>Xometry_ERP_Contact_ID__c</fullName>
    <description>The unique Contact Id that is created by the Xometry ERP</description>
    <externalId>true</externalId>
    <label>ERP Contact ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/BoxIntegrationService_Test.cls
@isTest
public class BoxIntegrationService_Test {

	@isTest(seeAllData=false)
    static void caseToPendingTest() {

    	Contact contactTest = new Contact();
        contactTest.FirstName = 'TestMan';
        contactTest.LastName = 'LastNamington';
        contactTest.Primary_Email__c = 'TestMan@domain.com';
        contactTest.Xometry_ERP_Contact_ID__c = '230AE';
        insert contactTest;

    	Case caseTest = new Case();
    	insert caseTest;

    	List<Box_Integration_Service__e> boxEventList = new List<Box_Integration_Service__e>();

    	Box_Integration_Service__e boxEvent = new Box_Integration_Service__e();
		boxEvent.Action__c = 'fileUploaded';
		boxEvent.Actor__c = '230AE';
		boxEvent.CaseId__c = caseTest.Id;
		boxEvent.Filename__c = 'Test.file';
		boxEvent.Filepath__c = 'Test/path';
		boxEvent.Time__c = System.now();

		boxEventList.add(boxEvent);

		Test.startTest();

		EventBus.publish(boxEventList);

		Test.stopTest();

		System.assertEquals('Response Received', [SELECT Status FROM Case WHERE Id = :caseTest.Id].Status );
		System.assertEquals(1, [SELECT Id FROM FeedItem WHERE ParentId = :caseTest.Id].size() );

    }
    
	@isTest(seeAllData=false)
    static void caseNumberToPendingTest() {

    	Contact contactTest = new Contact();
        contactTest.FirstName = 'TestMan';
        contactTest.LastName = 'LastNamington';
        contactTest.Primary_Email__c = 'TestMan@domain.com';
        contactTest.Xometry_ERP_Contact_ID__c = '230AE';
        insert contactTest;

    	Case caseTest = new Case();
    	insert caseTest;

    	caseTest = [SELECT CaseNumber FROM Case WHERE Id = :caseTest.Id];

    	List<Box_Integration_Service__e> boxEventList = new List<Box_Integration_Service__e>();

    	Box_Integration_Service__e boxEvent = new Box_Integration_Service__e();
		boxEvent.Action__c = 'fileUploaded';
		boxEvent.Actor__c = '230AE';
		boxEvent.CaseNumber__c = caseTest.CaseNumber;
		boxEvent.Filename__c = 'Test.file';
		boxEvent.Filepath__c = 'Test/path';
		boxEvent.Time__c = System.now();

		boxEventList.add(boxEvent);

		Test.startTest();

		EventBus.publish(boxEventList);

		Test.stopTest();

		System.assertEquals('Response Received', [SELECT Status FROM Case WHERE Id = :caseTest.Id].Status );
		System.assertEquals(1, [SELECT Id FROM FeedItem WHERE ParentId = :caseTest.Id].size() );

    }

}