unpackaged/main/default/objects/Order_Erp__c/Order_Erp__c.object-meta.xml
<CustomObject>
    <description>This object cotains the orders from Xometry ERP. An order is created in Salesforce when the Order date is populated. 

Technical Note: Quote and Orders are the same object in the source system but seperated in Salesforce as Orders represent the end of the opportunity process.</description>
    <label>Order ERP</label>
    <nameField>
        <displayFormat>Order-{000000}</displayFormat>
        <label>Order Erp Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders ERP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order_Erp__c/fields/LeadID__c.field-meta.xml
<CustomField>
    <fullName>LeadID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LeadID</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>Orders_Erp</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/Order_Canceled_Flag__c.field-meta.xml
<CustomField>
    <fullName>Order_Canceled_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>A flag that shows that an order has been canceled.</description>
    <label>Order Canceled Flag</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/Order_Subtotal__c.field-meta.xml
<CustomField>
    <fullName>Order_Subtotal__c</fullName>
    <label>Order Subtotal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/Order_Total__c.field-meta.xml
<CustomField>
    <fullName>Order_Total__c</fullName>
    <description>The total on the order</description>
    <label>Order Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>credit_card</fullName>
                <label>Credit Card</label>
            </value>
            <value>
                <fullName>purchase_order</fullName>
                <label>Purchase Order</label>
            </value>
            <value>
                <fullName>buy_now_pay_later</fullName>
                <label>Buy Now Pay Later</label>
            </value>
            <value>
                <fullName>no_payment</fullName>
                <label>No Payment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/process_isDMLS__c.field-meta.xml
<CustomField>
    <fullName>process_isDMLS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>process_isDMLS</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/Quote_ERP__c.object-meta.xml
<CustomObject>
    <description>A quote that is sent over from ERP</description>
    <label>Quote ERP</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote_ERP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes ERP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Quote_ERP__c/fields/LeadID__c.field-meta.xml
<CustomField>
    <fullName>LeadID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the lead a quote is associated with</description>
    <label>LeadID</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>Quotes_ERP</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/LeadConverterTest.cls
@isTest
public class LeadConverterTest {
    @isTest
    static void leadConvertTest1() {
        //Test Two Quotes. Convert the Lead and Confirm Opportunity has Primary Contact
        //Confirm both Quotes have account/Contact assigned
        List<Quote_ERP__C> newQuotes = TestDataFactory.createTestQuotesToLeads(1, 2);
        Set<ID> newQuoteIDSet = new Set<ID>();
        for (Quote_ERP__C q : newQuotes) {
            newQuoteIDSet.add(q.ID);
        }
        List<Quote_ERP__C> quoteLeadInfo = [SELECT ID, LeadID__C FROM Quote_ERP__C WHERE ID IN :newQuoteIDSet];
        Set<ID> leadIDSet = new Set<ID>();

        Quote_ERP__C convertQuoteEx = newQuotes[0];
        //Create an Order
        Order_ERP__C ord = TestDataFactory.createOrderERPFromQuote(false, convertQuoteEx);

        ord.Order_Canceled_Flag__c = false;
        ord.Order_Subtotal__c = 4500.00;
        ord.Order_Total__c = 5000.50;
        ord.Payment_Type__c = 'credit_card';
        ord.process_isDMLS__c = true;
        Test.startTest();
        insert ord;
        Test.stopTest();
    }
}