unpackaged/main/default/objects/Supplier__c/Supplier__c.object-meta.xml
<CustomObject>
    <label>Supplier</label>
    <nameField>
        <label>﻿Partner ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Supplier__c/fields/EmailAddress__c.field-meta.xml
<CustomField>
    <fullName>EmailAddress__c</fullName>
    <label>Email Address</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Supplier__c/fields/PartnerID__c.field-meta.xml
<CustomField>
    <fullName>PartnerID__c</fullName>
    <externalId>true</externalId>
    <label>Partner ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Supplier_Machine__c/Supplier_Machine__c.object-meta.xml
<CustomObject>
    <label>Supplier Machine</label>
    <nameField>
        <label>Supplier Machine Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Machines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Supplier_Machine__c/fields/MachineID__c.field-meta.xml
<CustomField>
    <fullName>MachineID__c</fullName>
    <externalId>true</externalId>
    <label>Machine ID</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Supplier_Machine__c/fields/MachineType__c.field-meta.xml
<CustomField>
    <fullName>MachineType__c</fullName>
    <label>Machine Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Binder Jetting</fullName>
            </value>
            <value>
                <fullName>Carbon DLS</fullName>
            </value>
            <value>
                <fullName>CNC Horizontal Mill</fullName>
            </value>
            <value>
                <fullName>CNC Lathe</fullName>
            </value>
            <value>
                <fullName>CNC Vertical Mill</fullName>
            </value>
            <value>
                <fullName>Die Casting</fullName>
            </value>
            <value>
                <fullName>Direct Metal Laser Sintering</fullName>
            </value>
            <value>
                <fullName>Extrusion</fullName>
            </value>
            <value>
                <fullName>Fused Deposition Modeling</fullName>
            </value>
            <value>
                <fullName>Hole Popper EDM</fullName>
            </value>
            <value>
                <fullName>HP Multi-Jet Fusion</fullName>
            </value>
            <value>
                <fullName>Injection Molding</fullName>
            </value>
            <value>
                <fullName>Laser Cutter</fullName>
            </value>
            <value>
                <fullName>MultiJet</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Plasma Cutter</fullName>
            </value>
            <value>
                <fullName>PolyJet 3D Printing</fullName>
            </value>
            <value>
                <fullName>Ram EDM</fullName>
            </value>
            <value>
                <fullName>Selective Laser Sintering</fullName>
            </value>
            <value>
                <fullName>Sheet Metal</fullName>
            </value>
            <value>
                <fullName>Sheet Metal Brake</fullName>
            </value>
            <value>
                <fullName>Sheet Metal Punch</fullName>
            </value>
            <value>
                <fullName>Sheet Metal Shear</fullName>
            </value>
            <value>
                <fullName>Stamping</fullName>
            </value>
            <value>
                <fullName>Stereolithography</fullName>
            </value>
            <value>
                <fullName>Swiss Lathe</fullName>
            </value>
            <value>
                <fullName>Urethane Molding</fullName>
            </value>
            <value>
                <fullName>Water Jet Cutter</fullName>
            </value>
            <value>
                <fullName>Wire Electrical Discharge Machining</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Supplier_Machine__c/fields/PartnerID__c.field-meta.xml
<CustomField>
    <fullName>PartnerID__c</fullName>
    <label>Partner ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Supplier_Machine__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Supplier__c</referenceTo>
    <relationshipLabel>Supplier Machines</relationshipLabel>
    <relationshipName>Supplier_Machines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Supplier_Machine__c/fields/XAxis__c.field-meta.xml
<CustomField>
    <fullName>XAxis__c</fullName>
    <label>X-Axis</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Supplier_Machine__c/fields/YAxis__c.field-meta.xml
<CustomField>
    <fullName>YAxis__c</fullName>
    <label>Y-Axis</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Supplier_Machine__c/fields/ZAxis__c.field-meta.xml
<CustomField>
    <fullName>ZAxis__c</fullName>
    <label>Z-Axis</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/SupplierMachineTest.cls
@isTest
public with sharing class SupplierMachineTest {
    @isTest
    public static void newSupplierMachine() {
        Supplier__c s = new Supplier__c();
        s.PartnerID__c = 'P0000';
        s.EmailAddress__c = 'supplier@gmail.com';
        insert s;

        Supplier_Machine__c mach = new Supplier_Machine__c();
        mach.machineID__c = '6116f568f8d105000951e08e-23374';
        mach.PartnerID__c = 'P0000';
        mach.MachineType__c = 'CNC Vertical Mill';
        mach.Quantity__c = 1;
        mach.Xaxis__c = 100;
        mach.Yaxis__c = 200;
        mach.Zaxis__c = 300;

        Test.startTest();
        insert mach;
        Test.stopTest();

        Supplier_Machine__c machineResult = [SELECT Id, Supplier__c FROM Supplier_Machine__c WHERE Id = :mach.Id][0];

        Supplier__c supplierResult = [SELECT Id, PartnerID__c FROM Supplier__c WHERE PartnerID__c = :s.PartnerID__c][0];

        System.assertEquals(
            supplierResult.Id,
            machineResult.Supplier__c,
            'The machine was associated to the wrong supplier'
        );
    }

    @isTest
    public static void newSupplierMachines_SameSupplier() {
        Supplier__c s = new Supplier__c();
        s.PartnerID__c = 'P0000';
        s.EmailAddress__c = 'supplier@gmail.com';
        insert s;

        List<Supplier_Machine__c> machineList = new List<Supplier_Machine__c>();

        Supplier_Machine__c mach1 = new Supplier_Machine__c();
        mach1.machineID__c = '6116f568f8d105000951e08e-23374';
        mach1.PartnerID__c = 'P0000';
        mach1.MachineType__c = 'CNC Vertical Mill';
        mach1.Quantity__c = 1;
        mach1.Xaxis__c = 100;
        mach1.Yaxis__c = 200;
        mach1.Zaxis__c = 300;
        machineList.add(mach1);

        Supplier_Machine__c mach2 = new Supplier_Machine__c();
        mach2.machineID__c = '6116f568f8d105000951e08e-23375';
        mach2.PartnerID__c = 'P0000';
        mach2.MachineType__c = 'Sheet Metal Brake';
        mach2.Quantity__c = 10;
        mach2.Xaxis__c = 100;
        mach2.Yaxis__c = 200;
        mach2.Zaxis__c = 300;
        machineList.add(mach2);

        Test.startTest();
        insert machineList;
        Test.stopTest();

        Supplier_Machine__c machine1Result = [SELECT Id, Supplier__c FROM Supplier_Machine__c WHERE Id = :mach1.Id][0];

        Supplier_Machine__c machine2Result = [SELECT Id, Supplier__c FROM Supplier_Machine__c WHERE Id = :mach2.Id][0];

        Supplier__c supplierResult = [SELECT Id, PartnerID__c FROM Supplier__c WHERE PartnerID__c = :s.PartnerID__c][0];

        System.assertEquals(
            supplierResult.Id,
            machine1Result.Supplier__c,
            'The first machine was associated to the wrong supplier'
        );
        System.assertEquals(
            supplierResult.Id,
            machine2Result.Supplier__c,
            'The second machine was associated to the wrong supplier'
        );
    }

    @isTest
    public static void newSupplierMachines_DifferentSuppliers() {
        Supplier__c s1 = new Supplier__c();
        s1.PartnerID__c = 'P0000';
        s1.EmailAddress__c = 'supplier1@gmail.com';
        insert s1;

        Supplier__c s2 = new Supplier__c();
        s2.PartnerID__c = 'P00001';
        s2.EmailAddress__c = 'supplier2@gmail.com';
        insert s2;

        List<Supplier_Machine__c> machineList = new List<Supplier_Machine__c>();

        Supplier_Machine__c mach1 = new Supplier_Machine__c();
        mach1.machineID__c = '6116f568f8d105000951e08e-23374';
        mach1.PartnerID__c = 'P0000';
        mach1.MachineType__c = 'CNC Vertical Mill';
        mach1.Quantity__c = 1;
        mach1.Xaxis__c = 100;
        mach1.Yaxis__c = 200;
        mach1.Zaxis__c = 300;
        machineList.add(mach1);

        Supplier_Machine__c mach2 = new Supplier_Machine__c();
        mach2.machineID__c = '6116f568f8d105000951e08e-23375';
        mach2.PartnerID__c = 'P00001';
        mach2.MachineType__c = 'Sheet Metal Brake';
        mach2.Quantity__c = 10;
        mach2.Xaxis__c = 100;
        mach2.Yaxis__c = 200;
        mach2.Zaxis__c = 300;
        machineList.add(mach2);

        Test.startTest();
        insert machineList;
        Test.stopTest();

        Supplier_Machine__c machine1Result = [SELECT Id, Supplier__c FROM Supplier_Machine__c WHERE Id = :mach1.Id][0];

        Supplier_Machine__c machine2Result = [SELECT Id, Supplier__c FROM Supplier_Machine__c WHERE Id = :mach2.Id][0];

        Supplier__c supplier1Result = [
            SELECT Id, PartnerID__c
            FROM Supplier__c
            WHERE PartnerID__c = :s1.PartnerID__c
        ][0];

        Supplier__c supplier2Result = [
            SELECT Id, PartnerID__c
            FROM Supplier__c
            WHERE PartnerID__c = :s2.PartnerID__c
        ][0];

        System.assertEquals(
            supplier1Result.Id,
            machine1Result.Supplier__c,
            'The machine was associated to the wrong supplier'
        );
        System.assertEquals(
            supplier2Result.Id,
            machine2Result.Supplier__c,
            'The machine was associated to the wrong supplier'
        );
    }
}