unpackaged/main/default/objects/Supplier__c/Supplier__c.object-meta.xml
<CustomObject>
    <label>Supplier</label>
    <nameField>
        <label>﻿Partner ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Supplier__c/fields/PartnerID__c.field-meta.xml
<CustomField>
    <fullName>PartnerID__c</fullName>
    <externalId>true</externalId>
    <label>Partner ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Supplier_Machine__c/Supplier_Machine__c.object-meta.xml
<CustomObject>
    <label>Supplier Machine</label>
    <nameField>
        <label>Supplier Machine Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Machines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Supplier_Machine__c/fields/PartnerID__c.field-meta.xml
<CustomField>
    <fullName>PartnerID__c</fullName>
    <label>Partner ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Supplier_Machine__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Supplier__c</referenceTo>
    <relationshipLabel>Supplier Machines</relationshipLabel>
    <relationshipName>Supplier_Machines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/SupplierMachineHandler.cls
public with sharing class SupplierMachineHandler {
    /**
     * @description associates Supplier Machines to Suppliers
     * @param newSupplierMachinesList
     */
    public static void associateSupplier(List<Supplier_Machine__c> newSupplierMachinesList) {
        Set<String> supplierIdSet = new Set<String>();
        for (Supplier_Machine__c mach : newSupplierMachinesList) {
            if (!String.isBlank(mach.PartnerID__c))
                supplierIdSet.add(mach.PartnerID__c);
        }

        if (!supplierIdSet.isEmpty()) {
            Map<String, Id> supplierIdToMachineMap = new Map<String, Id>();
            for (Supplier__c sup : [SELECT Id, PartnerID__c FROM Supplier__c WHERE PartnerID__c IN :supplierIdSet]) {
                supplierIdToMachineMap.put(sup.PartnerID__c, sup.Id);
            }

            for (Supplier_Machine__C mach : newSupplierMachinesList) {
                if (supplierIdToMachineMap.keySet().contains(mach.PartnerID__c)) {
                    mach.Supplier__c = supplierIdToMachineMap.get(mach.PartnerID__c);
                }
            }
        }
    }
}