unpackaged/main/default/objects/Opportunity/fields/Last_Quote_Xometry_Create_Time__c.field-meta.xml
<CustomField>
    <fullName>Last_Quote_Xometry_Create_Time__c</fullName>
    <description>Hidden field for Automated Processing to compare last time an Opps quote occured.</description>
    <label>Last Quote Modification Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Opportunity_Create_Date__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Create_Date__c</fullName>
    <formula>CreatedDate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Created Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Primary__c.field-meta.xml
<CustomField>
    <fullName>Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates that this Opp is one of the primary Opps for the Project in which it resides</inlineHelpText>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Container for Opportunities that are part of the same project</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Project Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Last_Opp_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Opp_Created_Date__c</fullName>
    <inlineHelpText>Looking at the Opps on this project, this is the most recent Opp Created Date</inlineHelpText>
    <label>Last Opp Created Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Last_Quote_Mod_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Quote_Mod_Date__c</fullName>
    <inlineHelpText>Of the Quotes on this Project (by way of Opps), this is the most recent Last Quote Modification Date in the ERP.</inlineHelpText>
    <label>Last Quote Mod Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <inlineHelpText>A short description of this Project</inlineHelpText>
    <label>Project</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/projectInfoUpdateBatch.cls
global class projectInfoUpdateBatch implements Database.Batchable<sObject>{
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([SELECT Id FROM Project__c]);
    }

    global void execute(Database.BatchableContext bc, List<Project__c> projectList) {
        Map<Id, Datetime> projectOppCreatedDateMap = new Map<Id, Date>();
        Map<Id, Datetime> projectLastQuoteModDateMap = new Map<Id, Datetime>();
        Map<Id, Decimal> projectAmountMap = new Map<Id, Decimal>();

        Set<String> lstProjectsIds = new Map<String, Project__c>(projectList).keySet();

        List<Opportunity> opps = [
                SELECT Project__c, Opportunity_Create_Date__c, Last_Quote_Xometry_Create_Time__c, Primary__c, Amount
                FROM Opportunity
                WHERE Project__c IN: lstProjectsIds
            ];

        for (Opportunity o : opps) {
            if (!projectOppCreatedDateMap.containsKey(o.Project__c)) {
                projectOppCreatedDateMap.put(o.Project__c, o.Opportunity_Create_Date__c);
            } else if (projectOppCreatedDateMap.get(o.Project__c) < o.Opportunity_Create_Date__c) {
                projectOppCreatedDateMap.put(o.Project__c, o.Opportunity_Create_Date__c);
            }

            if (!projectLastQuoteModDateMap.containsKey(o.Project__c)) {
                projectLastQuoteModDateMap.put(o.Project__c, o.Last_Quote_Xometry_Create_Time__c);
            } else if (projectLastQuoteModDateMap.get(o.Project__c) < o.Last_Quote_Xometry_Create_Time__c) {
                projectLastQuoteModDateMap.put(o.Project__c, o.Last_Quote_Xometry_Create_Time__c);
            }

            if(o.Primary__c && o.Amount != null)
            {
                Decimal decAmount = projectAmountMap.containsKey(o.Project__c) ? projectAmountMap.get(o.Project__c) : 0;
                decAmount += o.Amount;
                projectAmountMap.put(o.Project__c, decAmount);
            }
        }

        for (Project__c proj : projectList) {
            if (projectOppCreatedDateMap.containsKey(proj.Id)) {
                proj.Last_Opp_Created_Date__c = projectOppCreatedDateMap.get(proj.Id);
            } else {
                proj.Last_Opp_Created_Date__c = null;
            }

            if (projectLastQuoteModDateMap.containsKey(proj.Id)) {
                proj.Last_Quote_Mod_Date__c = projectLastQuoteModDateMap.get(proj.Id);
            } else {
                proj.Last_Quote_Mod_Date__c = null;
            }

            if (projectAmountMap.containsKey(proj.Id)) {
                proj.Amount__c = projectAmountMap.get(proj.Id);
            } else {
                proj.Amount__c = null;
            }
        }

        DatabaseUtilities.saveToDatabase(projectList, 'projectInfoUpdate_Batch.execute', 'Update the Last_Opp_Created_Date__c, Last_Quote_Mod_Date__c and Amount of the Projects');
    }

    global void finish(Database.BatchableContext bc) {
    }
}