unpackaged/main/default/objects/Opportunity/fields/Last_Quote_Xometry_Create_Time__c.field-meta.xml
<CustomField>
    <fullName>Last_Quote_Xometry_Create_Time__c</fullName>
    <description>Hidden field for Automated Processing to compare last time an Opps quote occured.</description>
    <label>Last Quote Modification Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Opportunity_Create_Date__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Create_Date__c</fullName>
    <formula>CreatedDate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Created Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Primary__c.field-meta.xml
<CustomField>
    <fullName>Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates that this Opp is one of the primary Opps for the Project in which it resides</inlineHelpText>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Container for Opportunities that are part of the same project</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Project Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Last_Opp_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Opp_Created_Date__c</fullName>
    <inlineHelpText>Looking at the Opps on this project, this is the most recent Opp Created Date</inlineHelpText>
    <label>Last Opp Created Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Last_Quote_Mod_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Quote_Mod_Date__c</fullName>
    <inlineHelpText>Of the Quotes on this Project (by way of Opps), this is the most recent Last Quote Modification Date in the ERP.</inlineHelpText>
    <label>Last Quote Mod Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <inlineHelpText>A short description of this Project</inlineHelpText>
    <label>Project</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/projectInfoUpdateBatch_Test.cls
@isTest
private class projectInfoUpdateBatch_Test {
    @TestSetup
    private static void setup() {
        Account a = TestDataFactory.createTestAccountNonGenerics(5, 'AM', 1)[0];
        Contact c = [SELECT ID FROM Contact][0];

        Project__c project = TestDataFactory.createProject(false, c.ID, a.Id, null, 'Project', 'Open');
        project.Last_Opp_Created_Date__c = Datetime.newInstance(1999, 1, 1);
        project.Last_Quote_Mod_Date__c = Datetime.newInstance(1999, 1, 1);
        insert project;

        Opportunity opp1 = TestDataFactory.createOpportunity(false, c.Id, a.Id, null, Date.newInstance(2019, 6, 14));
        opp1.Name = 'TestOpp1';
        opp1.Amount = 500;
        opp1.Primary__c = true;
        opp1.Project__c = project.Id;
        opp1.Last_Quote_Xometry_Create_Time__c = Datetime.newInstance(1999, 1, 1);
        insert opp1;

        Opportunity opp2 = TestDataFactory.createOpportunity(false, c.Id, a.Id, null, Date.newInstance(2019, 6, 14));
        opp2.Name = 'TestOpp2';
        opp2.Amount = 300;
        opp2.Project__c = project.Id;
        opp2.Last_Quote_Xometry_Create_Time__c = Datetime.newInstance(2019, 3, 3);
        insert opp2;

        Project__c project2 = TestDataFactory.createProject(false, c.ID, a.Id, null, 'Project', 'Open');
        project2.Last_Opp_Created_Date__c = Datetime.newInstance(1999, 1, 1);
        project2.Last_Quote_Mod_Date__c = Datetime.newInstance(1999, 1, 1);
        insert project2;

        Opportunity opp3 = TestDataFactory.createOpportunity(false, c.Id, a.Id, null, Date.newInstance(2019, 6, 14));
        opp3.Name = 'TestOpp3';
        opp3.Amount = 500;
        opp3.Primary__c = true;
        opp3.Project__c = project2.Id;        
        opp3.Last_Quote_Xometry_Create_Time__c = Datetime.newInstance(2019, 3, 3);
        insert opp3;

        Opportunity opp4 = TestDataFactory.createOpportunity(false, c.Id, a.Id, null, Date.newInstance(2019, 6, 14));
        opp4.Name = 'TestOpp4';
        opp4.Amount = 300;
        opp4.Primary__c = true;
        opp4.Project__c = project2.Id;
        opp4.Last_Quote_Xometry_Create_Time__c = Datetime.newInstance(1999, 1, 1);
        insert opp4;

        Project__c project3 = TestDataFactory.createProject(false, c.ID, a.Id, null, 'Project', 'Open');
        project3.Last_Opp_Created_Date__c = Datetime.newInstance(1999, 1, 1);
        project3.Last_Quote_Mod_Date__c = Datetime.newInstance(1999, 1, 1);
        insert project3;
        
        List<Opportunity> lstOpportunity = [SELECT Primary__c, Amount FROM Opportunity];
        System.debug(lstOpportunity);
    }

    @isTest
    private static void executeBatch() {
        Test.startTest();
            Database.executeBatch(new projectInfoUpdateBatch());
        Test.stopTest();

        List<Project__c> lstProjects = [SELECT Id, Last_Opp_Created_Date__c, Last_Quote_Mod_Date__c, Amount__c FROM Project__c];
        List<Opportunity> lstOpportunity = [SELECT Id, Last_Quote_Xometry_Create_Time__c, Opportunity_Create_Date__c, Primary__c FROM Opportunity];

        System.assertEquals(lstProjects[0].Last_Opp_Created_Date__c, lstOpportunity[1].Opportunity_Create_Date__c, 'The Last_Opp_Created_Date__c is wrong in the first project record');
        System.assertEquals(lstProjects[1].Last_Opp_Created_Date__c, lstOpportunity[3].Opportunity_Create_Date__c, 'The Last_Opp_Created_Date__c is wrong in the second project record');

        System.assertEquals(lstProjects[0].Last_Quote_Mod_Date__c, lstOpportunity[1].Last_Quote_Xometry_Create_Time__c, 'The Last_Quote_Mod_Date__c is wrong in the first project record');
        System.assertEquals(lstProjects[1].Last_Quote_Mod_Date__c, lstOpportunity[2].Last_Quote_Xometry_Create_Time__c, 'The Last_Quote_Mod_Date__c is wrong in the second project record');

        System.assertEquals(lstProjects[0].Amount__c, 500, 'The Amount__c is wrong in the first project record');
        System.assertEquals(lstProjects[1].Amount__c, 800, 'The Amount__c is wrong in the second project record');
    }
}