unpackaged/main/default/objects/Opportunity/fields/Last_Quote_Xometry_Create_Time__c.field-meta.xml
<CustomField>
    <fullName>Last_Quote_Xometry_Create_Time__c</fullName>
    <description>Hidden field for Automated Processing to compare last time an Opps quote occured.</description>
    <label>Last Quote Modification Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Opportunity_Create_Date__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Create_Date__c</fullName>
    <formula>CreatedDate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Created Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Quick Reference to the Primary Contact on an Opportunity</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities(PC)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Container for Opportunities that are part of the same project</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Last_Opp_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Opp_Created_Date__c</fullName>
    <inlineHelpText>Looking at the Opps on this project, this is the most recent Opp Created Date</inlineHelpText>
    <label>Last Opp Created Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Last_Quote_Mod_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Quote_Mod_Date__c</fullName>
    <inlineHelpText>Of the Quotes on this Project (by way of Opps), this is the most recent Last Quote Modification Date in the ERP.</inlineHelpText>
    <label>Last Quote Mod Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <inlineHelpText>A short description of this Project</inlineHelpText>
    <label>Project</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Initial Engagement</fullName>
            </value>
            <value>
                <fullName>Negotiation / Revision</fullName>
            </value>
            <value>
                <fullName>Pending Payment</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/projectUpdateBatchTest.cls
@isTest
public class projectUpdateBatchTest {
    @TestSetup
    static void makeProjects() {
        Account a = TestDataFactory.createTestAccountNonGenerics(5, 'AM', 1)[0];
        Contact c = [SELECT ID FROM Contact][0];

        Project__c project = new Project__c();
        project.Primary_Contact__c = c.Id;
        project.accountId__c = a.Id;
        project.Project__c = 'Project';
        project.Stage__c = 'Open';
        project.Last_Opp_Created_Date__c = Datetime.newInstance(1999, 1, 1);
        project.Last_Quote_Mod_Date__c = Datetime.newInstance(1999, 1, 1);
        insert project;

        Opportunity opp1 = new Opportunity();
        opp1.StageName = 'New';
        opp1.AccountId = a.Id;
        opp1.Primary_Contact__C = c.Id;
        opp1.CloseDate = Date.newInstance(2019, 6, 14);
        opp1.Name = 'TestOpp1';
        opp1.Project__c = project.Id;
        opp1.Last_Quote_Xometry_Create_Time__c = Datetime.newInstance(1999, 1, 1);
        insert opp1;

        Opportunity opp2 = new Opportunity();
        opp2.StageName = 'New';
        opp2.AccountId = a.Id;
        opp2.Primary_Contact__C = c.Id;
        opp2.CloseDate = Date.newInstance(2019, 6, 14);
        opp2.Name = 'TestOpp2';
        opp2.Project__c = project.Id;
        opp2.Last_Quote_Xometry_Create_Time__c = Datetime.newInstance(2019, 3, 3);
        insert opp2;
    }

    @isTest
    static void projectUpdateBatchTest_replaceDates() {
        Datetime lastQuoteCreateTime = Datetime.newInstance(1800, 5, 5);

        List<Opportunity> testOpps = [
            SELECT Id, Opportunity_Create_Date__c, Last_Quote_Xometry_Create_Time__c
            FROM Opportunity
            LIMIT 2
        ];
        Project__c project = [SELECT Id FROM Project__c LIMIT 1];

        Set<Id> oppIds = new Set<Id>();
        for (Opportunity o : testOpps) {
            oppIds.add(o.Id);
            if (o.Last_Quote_Xometry_Create_Time__c > lastQuoteCreateTime) {
                lastQuoteCreateTime = o.Last_Quote_Xometry_Create_Time__c;
            }
        }

        Test.startTest();
        System.enqueueJob(new projectUpdateBatch(oppIds));
        Test.stopTest();

        Project__c modifiedProject = [
            SELECT Id, Last_Opp_Created_Date__c, Last_Quote_Mod_Date__c
            FROM Project__c
            WHERE Id = :project.Id
        ];

        System.assertEquals(Date.today(), modifiedProject.Last_Opp_Created_Date__c.date(), 'Last Opp Created Date not set');
        System.assertEquals(lastQuoteCreateTime, modifiedProject.Last_Quote_Mod_Date__c, 'Last Quote Mod Date not set');
    }


    @isTest
    static void projectUpdateBatchTest_saveToDatabaseNullMethod() {
        boolean exceptionEncountered = false;

        Test.startTest();
        try {
            projectUpdateBatch.saveToDatabase(new List<SObject>(), '', 'Sample note');
        } catch (IllegalArgumentException caughtException) {
            exceptionEncountered = true;
        }
        Test.stopTest();

        System.assert(exceptionEncountered, 'Exception not encountered.');
    }

    @isTest
    private static void projectUpdateBatchTest_saveToDatabaseNullDevNote() {
        boolean exceptionEncountered = false;

        Test.startTest();
        try {
            projectUpdateBatch.saveToDatabase(new List<SObject>(), 'Sample Method', '');
        } catch (IllegalArgumentException caughtException) {
            exceptionEncountered = true;
        }
        Test.stopTest();

        System.assert(exceptionEncountered, 'Exception not encountered.');
    }
}