unpackaged/main/default/objects/Opportunity/fields/Last_Quote_Xometry_Create_Time__c.field-meta.xml
<CustomField>
    <fullName>Last_Quote_Xometry_Create_Time__c</fullName>
    <description>Hidden field for Automated Processing to compare last time an Opps quote occured.</description>
    <label>Last Quote Modification Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Opportunity_Create_Date__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Create_Date__c</fullName>
    <formula>CreatedDate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Created Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Container for Opportunities that are part of the same project</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project__c/fields/Last_Opp_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Opp_Created_Date__c</fullName>
    <inlineHelpText>Looking at the Opps on this project, this is the most recent Opp Created Date</inlineHelpText>
    <label>Last Opp Created Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Last_Quote_Mod_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Quote_Mod_Date__c</fullName>
    <inlineHelpText>Of the Quotes on this Project (by way of Opps), this is the most recent Last Quote Modification Date in the ERP.</inlineHelpText>
    <label>Last Quote Mod Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <inlineHelpText>A short description of this Project</inlineHelpText>
    <label>Project</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/projectDateUpdateFuture.cls
public inherited sharing class projectDateUpdateFuture {
    static final String PROJECT_UPDATE_METHOD_NOTE = 'projectDateUpdateFuture.updateProjectDates';
    static final String PROJECT_UPDATE_DEV_NOTE = 'Failed to update Project Objects';

    public static void updateProjectDatesNow(Set<Id> projectIdSet) {
        projectIdSet.remove(null);

        if (projectIdSet.size() > 0) {
            Map<Id, Datetime> projectOppCreatedDateMap = new Map<Id, Date>();
            Map<Id, Datetime> projectLastQuoteModDateMap = new Map<Id, Datetime>();

            // TODO: replace Last_Quote_Xometry_Create_Time__c with field indicating
            List<Opportunity> opps = [
                SELECT Project__c, Opportunity_Create_Date__c, Last_Quote_Xometry_Create_Time__c
                FROM Opportunity
                WHERE Project__c IN :projectIdSet
            ];

            for (Opportunity o : opps) {
                if (!projectOppCreatedDateMap.containsKey(o.Project__c)) {
                    projectOppCreatedDateMap.put(o.Project__c, o.Opportunity_Create_Date__c);
                } else if (projectOppCreatedDateMap.get(o.Project__c) < o.Opportunity_Create_Date__c) {
                    projectOppCreatedDateMap.put(o.Project__c, o.Opportunity_Create_Date__c);
                }

                if (!projectLastQuoteModDateMap.containsKey(o.Project__c)) {
                    projectLastQuoteModDateMap.put(o.Project__c, o.Last_Quote_Xometry_Create_Time__c);
                } else if (projectLastQuoteModDateMap.get(o.Project__c) < o.Last_Quote_Xometry_Create_Time__c) {
                    projectLastQuoteModDateMap.put(o.Project__c, o.Last_Quote_Xometry_Create_Time__c);
                }
            }

            List<Project__c> projectToUpdateList = new List<Project__c>();

            for (Id projId : projectIdSet) {
                Project__c proj = new Project__c(Id = projId);
                if (projectOppCreatedDateMap.containsKey(projId)) {
                    proj.Last_Opp_Created_Date__c = projectOppCreatedDateMap.get(projId);
                } else {
                    proj.Last_Opp_Created_Date__c = null;
                }
                if (projectLastQuoteModDateMap.containsKey(projId)) {
                    proj.Last_Quote_Mod_Date__c = projectLastQuoteModDateMap.get(projId);
                } else {
                    proj.Last_Quote_Mod_Date__c = null;
                }
                projectToUpdateList.add(proj);
            }

            DatabaseUtilities.saveToDatabase(projectToUpdateList, PROJECT_UPDATE_METHOD_NOTE, PROJECT_UPDATE_DEV_NOTE);
        }
    }

    @future
    public static void updateProjectDatesFuture(Set<Id> projectIdSet) {
        updateProjectDatesNow(projectIdSet);
    }

    public static void updateProjectDates(Set<Id> projectIdSet) {
        if (!System.isFuture() && !System.isBatch() && !System.isQueueable()) {
            updateProjectDatesFuture(projectIdSet);
        } else {
            updateProjectDatesNow(projectIdSet);
        }
    }
}