unpackaged/main/default/objects/Opportunity/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <label>Line of Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Line_of_Business</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Quick Reference to the Primary Contact on an Opportunity</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities(PC)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Container for Opportunities that are part of the same project</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <label>Line of Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Line_of_Business</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <inlineHelpText>A short description of this Project</inlineHelpText>
    <label>Project</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Initial Engagement</fullName>
            </value>
            <value>
                <fullName>Negotiation / Revision</fullName>
            </value>
            <value>
                <fullName>Pending Payment</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Project_Account__c/Project_Account__c.object-meta.xml
<CustomObject>
    <description>Accounts associated to a Project</description>
    <label>Project Account</label>
    <nameField>
        <displayFormat>PA-{0000000000}</displayFormat>
        <label>Project Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project_Account__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Accounts</relationshipLabel>
    <relationshipName>Project_Accounts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Project_Contact__c/Project_Contact__c.object-meta.xml
<CustomObject>
    <label>Project Contact</label>
    <nameField>
        <displayFormat>PC-{0000000000}</displayFormat>
        <label>Project Contacts Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project_Contact__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Contacts</relationshipLabel>
    <relationshipName>Project_Contacts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/globalValueSets/Line_of_Business.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Instant Quote</fullName>
    </customValue>
    <customValue>
        <fullName>Marketplace</fullName>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <masterLabel>Line of Business</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/SplitProjectController.cls
public with sharing class SplitProjectController {
    static final String ERROR_LOG = 'The following error occurred: ';
    static final String ERROR_FIELDS = 'Fields affected by that error: ';
    static final String UPDATE_OPP_DEV_NOTE = 'Opportunity Updates reassigning Projects';
    static final String UPDATE_OPP_METHOD_NAME = 'SplitProjectController.reassignOpps';
    static final String UPDATE_TASK_DEV_NOTE = 'Tasks updates to merged project';
    static final String UPDATE_TASK_METHOD_NAME = 'SplitProjectController.reassignTasks';
    static final String DELETE_JUNCTION_DEV_NOTE = 'Project Junctions failed to be removed';
    static final String DELETE_JUNCTION_METHOD_NAME = 'SplitProjectController.mergeProject';
    static final String DELETE_PROJECT_DEV_NOTE = 'Project failed to be removed';
    static final String DELETE_PROJECT_METHOD_NAME = 'SplitProjectController.mergeProject';

    /**
     * @description method to fetch projects
     * @param contactId id of contact to search for projects
     * @param projectId id of project to exclude
     * @return List of Project objects for a given contact excluding parameter project
     */
    @AuraEnabled
    public static List<Project__c> getProjectList(Id contactId, Id projectId) {
        return [SELECT Id, Name FROM Project__c WHERE Primary_Contact__c = :contactId AND Id != :projectId];
    }

    /**
     * @description method to fetch all open opportunities
     * @param projectId id of project to get the opportunities for
     * @return List of non-Closed opportunity objects
     */
    @AuraEnabled
    public static List<Opportunity> getOppList(Id projectId) {
        return [
            SELECT Id, Name, Project__c
            FROM Opportunity
            WHERE Project__c = :projectId AND StageName NOT IN ('Closed Won', 'Closed Lost')
        ];
    }

    /**
     * @description method to return fields from a project
     * @param projectId id of project to get the details of
     * @return single project with details
     */
    @AuraEnabled
    public static Project__c getProjectDetails(Id projectId) {
        return [
            SELECT Id, Name, Line_of_Business__c, Primary_Contact__c, AccountId__c, Stage__c, AccountId__r.Name
            FROM Project__c
            WHERE Id = :projectId
        ][0];
    }

    /**
     * @description method to reassign opportunities
     * @param projectId id of project
     * @param oppIds List of Opportunity ids
     * @return String indicating status of new project
     */
    @AuraEnabled
    public static string reassignOpps(Id projectId, List<Id> oppIds) {
        try {
            Set<Opportunity> updatedOppSet = new Set<Opportunity>();
            List<Opportunity> updatedOppsList = new List<Opportunity>();

            for (Id opp : oppIds) {
                Opportunity newOpp = new Opportunity();
                newOpp.Id = opp;
                newOpp.Project__c = projectId;
                updatedOppSet.add(newOpp);
            }
            updatedOppsList.addAll(updatedOppSet);

            DatabaseUtilities.upsertToDatabase(updatedOppsList, UPDATE_OPP_METHOD_NAME, UPDATE_OPP_DEV_NOTE);
            return 'success';
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
     * @description method to merge projects
     * @param projectId id of project
     * @param mergeProjectId id of project to merge into
     * @return String indicating success of project merge
     */
    @AuraEnabled
    public static string mergeProject(Id projectId, Id mergeProjectId) {
        try {
            List<Opportunity> oppFetchList = [
                SELECT Id, Name, Project__c
                FROM Opportunity
                WHERE Project__c = :projectId
            ];

            // move all opps
            Set<Opportunity> updatedOppSet = new Set<Opportunity>();
            List<Opportunity> updatedOppsList = new List<Opportunity>();

            for (Opportunity opp : oppFetchList) {
                opp.Project__c = mergeProjectId;
                updatedOppSet.add(opp);
            }
            updatedOppsList.addAll(updatedOppSet);

            DatabaseUtilities.upsertToDatabase(updatedOppsList, UPDATE_OPP_METHOD_NAME, UPDATE_OPP_DEV_NOTE);

            // update tasks relations to merged project
            Set<Task> updatedTaskSet = new Set<Task>();
            List<Task> updatedTaskList = new List<Task>();

            List<Task> taskFetchList = [SELECT WhatId, Subject FROM Task WHERE WhatId = :projectId];

            for (Task t : taskFetchList) {
                t.WhatId = mergeProjectId;
                updatedTaskSet.add(t);
            }
            updatedTaskList.addAll(updatedTaskSet);

            DatabaseUtilities.upsertToDatabase(updatedTaskList, UPDATE_TASK_METHOD_NAME, UPDATE_TASK_DEV_NOTE);

            // delete all junctions
            List<Project_Contact__c> originalProjectContactJunctions = [
                SELECT Id
                FROM Project_Contact__c
                WHERE Project__c = :projectId
            ];
            List<Project_Account__c> originalProjectAccountJunction = [
                SELECT Id
                FROM Project_Account__c
                WHERE Project__c = :projectId
            ];
            DatabaseUtilities.deleteFromDatabase(
                originalProjectContactJunctions,
                DELETE_JUNCTION_METHOD_NAME,
                DELETE_JUNCTION_DEV_NOTE
            );
            DatabaseUtilities.deleteFromDatabase(
                originalProjectAccountJunction,
                DELETE_JUNCTION_METHOD_NAME,
                DELETE_JUNCTION_DEV_NOTE
            );

            // delete original project
            //List<Project__c> originalProject = [SELECT Id FROM Project__c WHERE Id = :projectId];
            // deleteFromDatabase(originalProject, DELETE_PROJECT_METHOD_NAME, DELETE_PROJECT_DEV_NOTE);

            return 'success';
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}