unpackaged/main/default/objects/Opportunity/fields/Order_ERP_Xom_ID__c.field-meta.xml
<CustomField>
    <fullName>Order_ERP_Xom_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>The ERP ID for this Order</inlineHelpText>
    <label>Order ID</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Container for Opportunities that are part of the same project</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <inlineHelpText>A short description of this Project</inlineHelpText>
    <label>Project</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Initial Engagement</fullName>
            </value>
            <value>
                <fullName>Negotiation / Revision</fullName>
            </value>
            <value>
                <fullName>Pending Payment</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ValidationLostClosedProjectsBatch.cls
global class ValidationLostClosedProjectsBatch implements Database.Batchable<sObject> {
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            [
                SELECT ID, CloseDate, Order_ERP_Xom_ID__c, Project__c 
                FROM Opportunity 
                WHERE Project__c != null AND Project__r.Stage__c = 'Closed Lost' AND Stagename ='Closed Won' 
                ORDER BY Project__c, CloseDate desc
            ]
        );
    }

    global void execute(Database.BatchableContext bc, List<Opportunity> opportunityList) {

        Map<Id, Project__c> mapProject = new Map<Id, Project__c>();
        for(Opportunity opportunityWon : opportunityList)
        {
            if(!mapProject.containsKey(opportunityWon.Project__c))
            {
                mapProject.put(opportunityWon.Project__c, new Project__c(Id = opportunityWon.Project__c, Stage__c = 'Pending Payment'));
            }
        }
        
        DatabaseUtilities.saveToDatabase(mapProject.values(), 'ValidationLostClosedProjectsBatch', 'ValidationLostClosedProjectsBatch update Failed');
    }

    global void finish(Database.BatchableContext bc) {
    }
}