unpackaged/main/default/objects/Opportunity/fields/P21_Account_Details__c.field-meta.xml
<CustomField>
    <fullName>P21_Account_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>P21 Account Details</label>
    <referenceTo>P21_Account_Details__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/Supplies.recordType-meta.xml
<RecordType>
    <fullName>Supplies</fullName>
    <active>true</active>
    <businessProcess>Supplies Sales Process</businessProcess>
    <description>Supplies Record Type</description>
    <label>Supplies</label>
</RecordType>

unpackaged/main/default/objects/P21_Account_Details__c/P21_Account_Details__c.object-meta.xml
<CustomObject>
    <description>Contains information about P21 Customer mapped to an extension of an account</description>
    <label>P21 Account Details</label>
    <nameField>
        <label>P21 Account Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>P21 Account Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/P21_Account_Details__c/fields/Sup_FirstDateSuppliesOrder__c.field-meta.xml
<CustomField>
    <fullName>Sup_FirstDateSuppliesOrder__c</fullName>
    <label>First Date of Supplies Order</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/P21_Account_Details__c/fields/Sup_LastDateSuppliesOrder__c.field-meta.xml
<CustomField>
    <fullName>Sup_LastDateSuppliesOrder__c</fullName>
    <label>Last Date of Supplies Order</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/P21_Account_Details__c/fields/Sup_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Sup_Revenue__c</fullName>
    <label>Supplies Revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/P21_Account_Details__c/fields/Sup_TotalPotentialRevenue__c.field-meta.xml
<CustomField>
    <fullName>Sup_TotalPotentialRevenue__c</fullName>
    <label>Potential Supplies Revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/P21_Account_Details__c/fields/Sup_TotalQuotedRevenue__c.field-meta.xml
<CustomField>
    <fullName>Sup_TotalQuotedRevenue__c</fullName>
    <label>Total Quoted Supplies Revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/P21_Account_Details__c/fields/Sup_TotalRevenueLY__c.field-meta.xml
<CustomField>
    <fullName>Sup_TotalRevenueLY__c</fullName>
    <label>Last Year Job Revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/P21_Account_Details__c/fields/Sup_TotalRevenueTY__c.field-meta.xml
<CustomField>
    <fullName>Sup_TotalRevenueTY__c</fullName>
    <label>This Year Job Revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Order__c/Supplies_Order__c.object-meta.xml
<CustomObject>
    <label>Supplies Order</label>
    <nameField>
        <label>Supplies Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplies Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Supplies_Order__c/fields/P21_Account_DetailsID__c.field-meta.xml
<CustomField>
    <fullName>P21_Account_DetailsID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>P21 Account Details ID</label>
    <referenceTo>P21_Account_Details__c</referenceTo>
    <relationshipLabel>Supplies Orders</relationshipLabel>
    <relationshipName>Supplies_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/SuppliesP21AccDetailsAggBatch.cls
global class SuppliesP21AccDetailsAggBatch implements Database.Batchable<sObject> {
    static final ID oppSuppliesRecordTypeID = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName()
        .get('Supplies')
        .getRecordTypeID();

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            [
                SELECT
                    Id,
                    Sup_Revenue__c,
                    Sup_TotalQuotedRevenue__c,
                    Sup_TotalPotentialRevenue__c,
                    Sup_TotalRevenueLY__c,
                    Sup_TotalRevenueTY__c
                FROM P21_Account_Details__c
            ]
        );
    }

    global void execute(Database.BatchableContext bc, List<P21_Account_Details__c> p21AccDetailsList) {
        Map<Id, P21_Account_Details__c> mapRecordsP21AccDetails = new Map<Id, P21_Account_Details__c>(
            p21AccDetailsList
        );

        AggregateResult[] oppTotalQuotedAggRes = [
            SELECT P21_Account_Details__c P21Id, SUM(Amount) TotalQuoted
            FROM Opportunity
            WHERE
                P21_Account_Details__c IN :mapRecordsP21AccDetails.keySet()
                AND RecordTypeId = :oppSuppliesRecordTypeID
                AND Amount != NULL
            GROUP BY P21_Account_Details__c
        ];
        for (AggregateResult oppQuoteAgg : oppTotalQuotedAggRes) {
            ID P21Id = ID.valueOf(String.valueOf(oppQuoteAgg.get('P21Id')));
            Decimal totalQuoteAgg = Decimal.valueOf(String.valueOf(oppQuoteAgg.get('TotalQuoted')));
            if (mapRecordsP21AccDetails.containsKey(P21Id)) {
                P21_Account_Details__c supplier = mapRecordsP21AccDetails.get(P21Id);
                supplier.Sup_TotalQuotedRevenue__c = totalQuoteAgg;
                mapRecordsP21AccDetails.put(supplier.ID, supplier);
            }
        }

        AggregateResult[] oppRevenueAggRes = [
            SELECT P21_Account_Details__c P21Id, SUM(Amount) TotalRevenue
            FROM Opportunity
            WHERE
                P21_Account_Details__c IN :mapRecordsP21AccDetails.keySet()
                AND RecordTypeId = :oppSuppliesRecordTypeID
                AND StageName = 'Closed Won'
                AND Amount != NULL
            GROUP BY P21_Account_Details__c
        ];

        for (AggregateResult oppRevenueAgg : oppRevenueAggRes) {
            ID P21Id = ID.valueOf(String.valueOf(oppRevenueAgg.get('P21Id')));
            Decimal totalRevenueAgg = Decimal.valueOf(String.valueOf(oppRevenueAgg.get('TotalRevenue')));
            if (mapRecordsP21AccDetails.containsKey(P21Id)) {
                P21_Account_Details__c supplier = mapRecordsP21AccDetails.get(P21Id);
                supplier.Sup_Revenue__c = totalRevenueAgg;
                mapRecordsP21AccDetails.put(supplier.ID, supplier);
            }
        }

        AggregateResult[] oppPotentialRevAggRes = [
            SELECT P21_Account_Details__c P21Id, SUM(Amount) TotalPotentialRev
            FROM Opportunity
            WHERE
                P21_Account_Details__c IN :mapRecordsP21AccDetails.keySet()
                AND RecordTypeId = :oppSuppliesRecordTypeID
                AND StageName NOT IN ('Closed Won', 'Closed Lost')
                AND Amount != NULL
            GROUP BY P21_Account_Details__c
        ];

        for (AggregateResult oppPotentialRevAgg : oppPotentialRevAggRes) {
            ID P21Id = ID.valueOf(String.valueOf(oppPotentialRevAgg.get('P21Id')));
            Decimal totalPotentialRevAgg = Decimal.valueOf(String.valueOf(oppPotentialRevAgg.get('TotalPotentialRev')));
            if (mapRecordsP21AccDetails.containsKey(P21Id)) {
                P21_Account_Details__c p21AccDetail = mapRecordsP21AccDetails.get(P21Id);
                p21AccDetail.Sup_TotalPotentialRevenue__c = totalPotentialRevAgg;
                mapRecordsP21AccDetails.put(p21AccDetail.ID, p21AccDetail);
            }
        }

        List<Opportunity> closedWonOpps = [
            SELECT P21_Account_Details__c, Amount, CloseDate
            FROM Opportunity
            WHERE RecordTypeId = :oppSuppliesRecordTypeID AND StageName = 'Closed Won' AND Amount != NULL
        ];

        Map<Id, Decimal> supplierLYRevenue = new Map<Id, Decimal>();
        Map<Id, Decimal> supplierTYRevenue = new Map<Id, Decimal>();

        for (Opportunity opp : closedWonOpps) {
            if (mapRecordsP21AccDetails.containsKey(opp.P21_Account_Details__c)) {
                P21_Account_Details__c p21AccDetail = mapRecordsP21AccDetails.get(opp.P21_Account_Details__c);
                if (opp.CloseDate.year() == Date.today().year() - 1) {
                    if (supplierLYRevenue.containsKey(p21AccDetail.Id)) {
                        supplierLYRevenue.put(p21AccDetail.Id, supplierLYRevenue.get(p21AccDetail.id) + opp.Amount);
                    } else {
                        supplierLYRevenue.put(p21AccDetail.Id, opp.Amount);
                    }
                }
                if (opp.CloseDate.year() == Date.today().year()) {
                    if (supplierTYRevenue.containsKey(p21AccDetail.Id)) {
                        supplierTYRevenue.put(p21AccDetail.Id, supplierTYRevenue.get(p21AccDetail.id) + opp.Amount);
                    } else {
                        supplierTYRevenue.put(p21AccDetail.Id, opp.Amount);
                    }
                }
            }
        }

        for (P21_Account_Details__c p21AccDetail : mapRecordsP21AccDetails.values()) {
            if (supplierLYRevenue.containsKey(p21AccDetail.Id)) {
                p21AccDetail.Sup_TotalRevenueLY__c = supplierLYRevenue.get(p21AccDetail.Id);
            } else {
                p21AccDetail.Sup_TotalRevenueLY__c = 0;
            }

            if (supplierTYRevenue.containsKey(p21AccDetail.Id)) {
                p21AccDetail.Sup_TotalRevenueTY__c = supplierTYRevenue.get(p21AccDetail.Id);
            } else {
                p21AccDetail.Sup_TotalRevenueTY__c = 0;
            }
        }

        List<AggregateResult> lstSuppliesOrders = [
            SELECT P21_Account_DetailsID__c P21Id, MIN(Order_Date__c) minData, MAX(Order_Date__c) maxData
            FROM Supplies_Order__c
            WHERE P21_Account_DetailsID__c IN :mapRecordsP21AccDetails.keySet()
            GROUP BY P21_Account_DetailsID__c
        ];
        for (AggregateResult supOrderAgg : lstSuppliesOrders) {
            ID P21Id = ID.valueOf(String.valueOf(supOrderAgg.get('P21Id')));
            Date dtFirstSupOrder = Date.valueOf(String.valueOf(supOrderAgg.get('minData')));
            Date dtLastSupOrder = Date.valueOf(String.valueOf(supOrderAgg.get('maxData')));
            if (mapRecordsP21AccDetails.containsKey(P21Id)) {
                P21_Account_Details__c supplier = mapRecordsP21AccDetails.get(P21Id);
                supplier.Sup_FirstDateSuppliesOrder__c = dtFirstSupOrder;
                supplier.Sup_LastDateSuppliesOrder__c = dtLastSupOrder;
                mapRecordsP21AccDetails.put(supplier.ID, supplier);
            }
        }

        DatabaseUtilities.saveToDatabase(
            mapRecordsP21AccDetails.values(),
            'SuppliesP21AccDetailsAggBatch',
            'Suppliers P21AccountsDetails Agg Failed'
        );
    }

    global void finish(Database.BatchableContext bc) {
    }
}