unpackaged/main/default/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Quick Reference to the Primary Contact on an Opportunity</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities(PC)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Container for Opportunities that are part of the same project</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <inlineHelpText>A short description of this Project</inlineHelpText>
    <label>Project</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Project_Account__c/Project_Account__c.object-meta.xml
<CustomObject>
    <description>Accounts associated to a Project</description>
    <label>Project Account</label>
    <nameField>
        <displayFormat>PA-{0000000000}</displayFormat>
        <label>Project Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Project Accounts</relationshipLabel>
    <relationshipName>Project_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Project_Account__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Accounts</relationshipLabel>
    <relationshipName>Project_Accounts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Project_Contact__c/Project_Contact__c.object-meta.xml
<CustomObject>
    <label>Project Contact</label>
    <nameField>
        <displayFormat>PC-{0000000000}</displayFormat>
        <label>Project Contacts Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project_Contact__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Contacts</relationshipLabel>
    <relationshipName>Project_Contacts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/SplitProjectControllerTest.cls
@isTest
public with sharing class SplitProjectControllerTest {
    @isTest
    private static void getProjectList_returnProjectList() {
        Account a = TestDataFactory.createTestAccountNonGenerics(5, 'AM', 1)[0];
        Contact c = [SELECT ID FROM Contact][0];

        Project__c p = new Project__c();
        p.accountId__c = a.Id;
        p.Primary_Contact__c = c.Id;
        p.Project__c = 'test';

        insert p;

        Project__c p2 = new Project__c();
        p2.accountId__c = a.Id;
        p2.Primary_Contact__c = c.Id;
        p2.Project__c = 'test two';

        insert p2;

        Test.startTest();
        List<Project__c> returnedProjects = SplitProjectController.getProjectList(c.Id, p.Id);
        Test.stopTest();

        System.assert(returnedProjects.size() != 0, 'nothing returned');
    }

    @isTest
    private static void getOppList_returnOppList() {
        Account a = TestDataFactory.createTestAccountNonGenerics(5, 'AM', 1)[0];
        Contact c = [SELECT ID FROM Contact][0];

        Project__c p = new Project__c();
        p.accountId__c = a.Id;
        p.Primary_Contact__c = c.Id;
        p.Project__c = 'test';

        insert p;

        Opportunity o = new Opportunity();
        o.Name = 'Opp Test Name';
        o.StageName = 'Open';
        o.CloseDate = Date.newInstance(1999, 1, 1);
        o.Project__c = p.Id;

        insert o;

        Test.startTest();
        List<Opportunity> returnedOpps = SplitProjectController.getOppList(p.Id);
        Test.stopTest();

        System.assert(returnedOpps.size() != 0, 'nothing returned');
    }

    @isTest
    private static void getProjectDetails_returnProject() {
        Account a = TestDataFactory.createTestAccountNonGenerics(5, 'AM', 1)[0];
        Contact c = [SELECT ID FROM Contact][0];

        Project__c p = new Project__c();
        p.accountId__c = a.Id;
        p.Primary_Contact__c = c.Id;
        p.Project__c = 'test';

        insert p;

        Test.startTest();
        Project__c returnedProject = SplitProjectController.getProjectDetails(p.Id);
        Test.stopTest();

        System.assertNotEquals(returnedProject, null, 'nothing returned');
    }

    @isTest
    private static void reassignOpps_returnString() {
        Account a = TestDataFactory.createTestAccountNonGenerics(5, 'AM', 1)[0];
        Contact c = [SELECT ID FROM Contact][0];

        Project__c p = new Project__c();
        p.accountId__c = a.Id;
        p.Primary_Contact__c = c.Id;
        p.Project__c = 'test';

        insert p;

        Opportunity o = new Opportunity();
        o.Name = 'Opp Test Name';
        o.StageName = 'Open';
        o.CloseDate = Date.newInstance(1999, 1, 1);
        o.Project__c = p.Id;

        Opportunity o2 = new Opportunity();
        o2.Name = 'Opp Test Name';
        o2.StageName = 'Open';
        o2.CloseDate = Date.newInstance(1999, 1, 1);
        o2.Project__c = p.Id;

        insert o;
        insert o2;

        List<Id> oppList = new List<Id>();
        oppList.add(o.Id);
        oppList.add(o2.Id);

        Test.startTest();
        String returnString = SplitProjectController.reassignOpps(p.Id, oppList);
        Test.stopTest();

        System.assertEquals(returnString, 'success', 'nothing returned');
    }

    @isTest
    private static void mergeProject_returnString() {
        Account a = TestDataFactory.createTestAccountNonGenerics(5, 'AM', 1)[0];
        Contact c = [SELECT ID FROM Contact][0];

        Project__c p = new Project__c();
        p.accountId__c = a.Id;
        p.Primary_Contact__c = c.Id;
        p.Project__c = 'test';

        insert p;

        Opportunity o = new Opportunity();
        o.Name = 'Opp Test Name';
        o.StageName = 'Open';
        o.CloseDate = Date.newInstance(1999, 1, 1);
        o.Project__c = p.Id;

        Opportunity o2 = new Opportunity();
        o2.Name = 'Opp Test Name';
        o2.StageName = 'Open';
        o2.CloseDate = Date.newInstance(1999, 1, 1);
        o2.Project__c = p.Id;

        insert o;
        insert o2;

        Project__c p2 = new Project__c();
        p2.accountId__c = a.Id;
        p2.Primary_Contact__c = c.Id;
        p2.Project__c = 'test';

        insert p2;

        Test.startTest();
        String returnString = SplitProjectController.mergeProject(p.Id, p2.Id);
        Test.stopTest();

        List<Project__c> returnedProjects = [SELECT Id, Project__c FROM Project__c WHERE Id = :p.Id OR Id = :p2.Id];

        List<Project_Contact__c> projectContactList = [SELECT Id FROM Project_Contact__c];
        List<Project_Account__c> projectAccountList = [SELECT Id FROM Project_Account__c];

        System.assertEquals(returnString, 'success', 'nothing returned');
    }

    @isTest
    private static void mergeProject_removeJunctions() {
        Account a = TestDataFactory.createTestAccountNonGenerics(5, 'AM', 1)[0];
        Contact c = [SELECT ID FROM Contact][0];

        Project__c p = new Project__c();
        p.accountId__c = a.Id;
        p.Primary_Contact__c = c.Id;
        p.Project__c = 'test';

        insert p;

        Opportunity o = new Opportunity();
        o.Name = 'Opp Test Name';
        o.StageName = 'Open';
        o.CloseDate = Date.newInstance(1999, 1, 1);
        o.Project__c = p.Id;

        Opportunity o2 = new Opportunity();
        o2.Name = 'Opp Test Name';
        o2.StageName = 'Open';
        o2.CloseDate = Date.newInstance(1999, 1, 1);
        o2.Project__c = p.Id;

        insert o;
        insert o2;

        Project__c p2 = new Project__c();
        p2.accountId__c = a.Id;
        p2.Primary_Contact__c = c.Id;
        p2.Project__c = 'test';

        insert p2;

        Project_Account__c deletedProjectAccountJunction = new Project_Account__c();
        deletedProjectAccountJunction.Project__c = p.Id;
        deletedProjectAccountJunction.account__c = a.Id;
        insert deletedProjectAccountJunction;

        Test.startTest();
        String returnString = SplitProjectController.mergeProject(p.Id, p2.Id);
        Test.stopTest();

        List<Project__c> returnedProjects = [SELECT Id, Project__c FROM Project__c WHERE Id = :p.Id OR Id = :p2.Id];

        List<Project_Contact__c> projectContactList = [SELECT Id FROM Project_Contact__c];
        List<Project_Account__c> projectAccountList = [SELECT Id FROM Project_Account__c];

        System.assertEquals(returnString, 'success', 'nothing returned');
        System.assertEquals(projectContactList.size(), 1, 'Only One Junction should be removed');
        System.assertEquals(projectAccountList.size(), 0, 'Junction should be removed');
    }

    @isTest
    private static void mergeProject_keepJunctions() {
        Account a = TestDataFactory.createTestAccountNonGenerics(5, 'AM', 1)[0];
        Contact c = [SELECT ID FROM Contact][0];

        Project__c p = new Project__c();
        p.accountId__c = a.Id;
        p.Primary_Contact__c = c.Id;
        p.Project__c = 'test';

        insert p;

        Opportunity o = new Opportunity();
        o.Name = 'Opp Test Name';
        o.StageName = 'Open';
        o.CloseDate = Date.newInstance(1999, 1, 1);
        o.Project__c = p.Id;

        Opportunity o2 = new Opportunity();
        o2.Name = 'Opp Test Name';
        o2.StageName = 'Open';
        o2.CloseDate = Date.newInstance(1999, 1, 1);
        o2.Project__c = p.Id;

        insert o;
        insert o2;

        Project__c p2 = new Project__c();
        p2.accountId__c = a.Id;
        p2.Primary_Contact__c = c.Id;
        p2.Project__c = 'test';

        insert p2;

        Project_Account__c deletedProjectAccountJunction = new Project_Account__c();
        deletedProjectAccountJunction.Project__c = p2.Id;
        deletedProjectAccountJunction.account__c = a.Id;
        insert deletedProjectAccountJunction;

        Test.startTest();
        String returnString = SplitProjectController.mergeProject(p.Id, p2.Id);
        Test.stopTest();

        List<Project__c> returnedProjects = [SELECT Id, Project__c FROM Project__c WHERE Id = :p.Id OR Id = :p2.Id];

        List<Project_Contact__c> projectContactList = [SELECT Id FROM Project_Contact__c];
        List<Project_Account__c> projectAccountList = [SELECT Id FROM Project_Account__c];

        System.assertEquals('success', returnString, 'nothing returned');
        System.assertEquals(1, projectContactList.size(), 'Junction should not be removed');
        System.assertEquals(1, projectAccountList.size(), 'Junction should not be removed');
    }

    @isTest
    private static void mergeProject_keepTasks() {
        Account a = TestDataFactory.createTestAccountNonGenerics(5, 'AM', 1)[0];
        Contact c = [SELECT ID FROM Contact][0];

        Project__c p = new Project__c();
        p.accountId__c = a.Id;
        p.Primary_Contact__c = c.Id;
        p.Project__c = 'test';

        insert p;

        Project__c p2 = new Project__c();
        p2.accountId__c = a.Id;
        p2.Primary_Contact__c = c.Id;
        p2.Project__c = 'test two';

        insert p2;

        Task t = new Task();
        t.Status = 'Open';
        t.Priority = 'Normal';
        t.WhatId = p.Id;
        insert t;

        Test.startTest();
        SplitProjectController.mergeProject(p.Id, p2.Id);
        Test.stopTest();

        Task taskResRelated = [SELECT Id, WhatId FROM Task WHERE WhatId = :p2.Id][0];

        System.assertEquals(p2.Id, taskResRelated.WhatId, 'Expect task to be related to merged project.');
    }

    @isTest
    private static void mergeProject_keepAllTasks() {
        Account a = TestDataFactory.createTestAccountNonGenerics(5, 'AM', 1)[0];
        Contact c = [SELECT ID FROM Contact][0];

        Project__c p = new Project__c();
        p.accountId__c = a.Id;
        p.Primary_Contact__c = c.Id;
        p.Project__c = 'test';

        insert p;

        Project__c p2 = new Project__c();
        p2.accountId__c = a.Id;
        p2.Primary_Contact__c = c.Id;
        p2.Project__c = 'test two';

        insert p2;

        Task t = new Task();
        t.Status = 'Open';
        t.Priority = 'Normal';
        t.WhatId = p.Id;
        insert t;

        Task t2 = new Task();
        t2.Status = 'Open';
        t2.Priority = 'Normal';
        t2.WhatId = p.Id;
        insert t2;

        Test.startTest();
        SplitProjectController.mergeProject(p.Id, p2.Id);
        Test.stopTest();

        List<Task> taskResRelated = [SELECT Id, WhatId FROM Task WHERE WhatId = :p2.Id];

        System.assertEquals(p2.Id, taskResRelated[0].WhatId, 'Expect task to be related to merged project.');
        System.assertEquals(p2.Id, taskResRelated[1].WhatId, 'Expect task to be related to merged project.');
    }
}