unpackaged/main/default/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Quick Reference to the Primary Contact on an Opportunity</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities(PC)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Container for Opportunities that are part of the same project</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <inlineHelpText>A short description of this Project</inlineHelpText>
    <label>Project</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Initial Engagement</fullName>
            </value>
            <value>
                <fullName>Negotiation / Revision</fullName>
            </value>
            <value>
                <fullName>Pending Payment</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/westCoastContactFlip.cls
/**
 * Async Queueable class to flip a given Account's Contacts to the West Coast BDR
 */
public class westCoastContactFlip implements Queueable {
    static final String WEST_COAST_CONTACT_FLIP_METHOD_NOTE = 'westCoastContactFlip.execute';
    static final String WEST_COAST_CONTACT_FLIP_CONTACT_DEV_NOTE = 'West Coast Contact Flip has failed';
    static final String WEST_COAST_CONTACT_FLIP_OPP_DEV_NOTE = 'West Coast Opportunity Flip has failed';

    ID WestCoastOwnerID;
    Set<ID> contactIDSet = new Set<ID>();

    /**
     * @description enqueued job for changing all BDR owned contacts for a given Account
     * @param reassignedAccountIDSet list of IDs for Accounts which are now owned by the West Coast BDR
     */
    public westCoastContactFlip(Set<ID> reassignedAccountIDSet, ID westCoastBDR) {
        // select all BDR owned contacts for a given account
        List<Contact> BDRContacts = [
            SELECT ID
            FROM Contact
            WHERE AccountId IN :reassignedAccountIDSet AND Owner.UserRole.Name = :AppConstants.BDR_NAME
        ];

        // put West Coast ID and Contact ID in map
        for (Contact c : BDRContacts) {
            WestCoastOwnerID = westCoastBDR;
            contactIDSet.add(c.ID);
        }
    }

    public void execute(QueueableContext context) {
        List<Contact> updatedContactList = [SELECT ID, OwnerID FROM Contact WHERE ID IN :contactIDSet];

        for (Contact c : updatedContactList) {
            c.OwnerID = WestCoastOwnerID;
        }

        List<Opportunity> opportunityList = [
            SELECT ID, OwnerId
            FROM Opportunity
            WHERE
                StageName NOT IN ('Closed Won', 'Closed Lost')
                AND PRIMARY_CONTACT__C IN :contactIDSet
                AND Owner.UserRole.Name = :AppConstants.BDR_NAME
        ];

        for (Opportunity opp : opportunityList) {
            opp.OwnerId = WestCoastOwnerID;
        }

        List<Project__c> projectList = [
            SELECT ID, OwnerId, Primary_Contact__c
            FROM Project__c
            WHERE
                Stage__c NOT IN ('Closed Won', 'Closed Lost')
                AND Primary_Contact__c IN :contactIDSet
                AND Owner.UserRole.Name = :AppConstants.BDR_NAME
        ];

        for (Project__c p : projectList) {
            p.OwnerId = WestCoastOwnerID;
        }

        DatabaseUtilities.saveToDatabase(
            updatedContactList,
            WEST_COAST_CONTACT_FLIP_METHOD_NOTE,
            WEST_COAST_CONTACT_FLIP_CONTACT_DEV_NOTE
        );
        DatabaseUtilities.saveToDatabase(
            opportunityList,
            WEST_COAST_CONTACT_FLIP_METHOD_NOTE,
            WEST_COAST_CONTACT_FLIP_OPP_DEV_NOTE
        );
        DatabaseUtilities.saveToDatabase(
            projectList,
            WEST_COAST_CONTACT_FLIP_METHOD_NOTE,
            WEST_COAST_CONTACT_FLIP_CONTACT_DEV_NOTE
        );
    }
}