unpackaged/main/default/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Quick Reference to the Primary Contact on an Opportunity</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities(PC)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Container for Opportunities that are part of the same project</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Closed_Lost_Reason__c.field-meta.xml
<CustomField>
    <fullName>Closed_Lost_Reason__c</fullName>
    <inlineHelpText>Some Closed Lost details require additional information. For example: if selecting Competition please enter the competitor's name or 'Unknown'.</inlineHelpText>
    <label>Closed Lost Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <inlineHelpText>A short description of this Project</inlineHelpText>
    <label>Project</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Initial Engagement</fullName>
            </value>
            <value>
                <fullName>Negotiation / Revision</fullName>
            </value>
            <value>
                <fullName>Pending Payment</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ProjectBatchTest.cls
@isTest
public with sharing class ProjectBatchTest {
    @TestSetup
    private static void setup() {
        Account a = TestDataFactory.createTestAccountNonGenerics(5, 'AM', 1)[0];
        Contact c = [SELECT ID FROM Contact][0];

        Project__c project1 = new Project__c();
        project1.Primary_Contact__c = c.Id;
        project1.accountId__c = a.Id;
        project1.Project__c = 'PreInserted Project 1';
        project1.Stage__c = 'New';

        Project__c project2 = new Project__c();
        project2.Primary_Contact__c = c.Id;
        project2.accountId__c = a.Id;
        project2.Project__c = 'PreInserted Project 2';
        project2.Stage__c = 'New';

        Project__c project3 = new Project__c();
        project3.Primary_Contact__c = c.Id;
        project3.accountId__c = a.Id;
        project3.Project__c = 'PreInserted Project 3';
        project3.Stage__c = 'Closed Won';

        insert project1;
        insert project2;
        insert project3;

        Opportunity opp = new Opportunity();
        opp.StageName = 'Open';
        opp.AccountId = a.Id;
        opp.Primary_Contact__C = c.Id;
        opp.CloseDate = Date.newInstance(2019, 6, 14);
        opp.Name = 'TestOppOne';
        opp.Project__c = project1.Id;

        insert opp;
    }

    @isTest
    private static void projectBatchTest() {
        Test.startTest();
        ProjectBatch batch = new ProjectBatch();
        Database.executeBatch(batch);
        Test.stopTest();

        List<Project__c> projectList = [SELECT id, Stage__c, Closed_Lost_Reason__c FROM Project__c ORDER BY Project__c];

        System.assertEquals('New', projectList[0].Stage__c, 'First Project should be Open');
        System.assertEquals('Closed Lost', projectList[1].Stage__c, 'Second Project should be Closed Lost');
        System.assertEquals(
            'No Opportunities associated -- Closed automatically weekly',
            projectList[1].Closed_Lost_Reason__c,
            'Second Project should be Closed Lost'
        );
        System.assertEquals('Closed Won', projectList[2].Stage__c, 'Third Project should be Closed Won');
    }
}