unpackaged/main/default/objects/Opportunity/fields/Primary__c.field-meta.xml
<CustomField>
    <fullName>Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates that this Opp is one of the primary Opps for the Project in which it resides</inlineHelpText>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Container for Opportunities that are part of the same project</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <inlineHelpText>A short description of this Project</inlineHelpText>
    <label>Project</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/updateProjectOppsController.cls
public with sharing class updateProjectOppsController {
    static final String DELETION_LOG = 'The delete id was: ';
    static final String ERROR_LOG = 'The following error occurred: ';
    static final String ERROR_FIELDS = 'Fields affected by that error: ';
    static final String UPDATE_OPP_DEV_NOTE = 'Opportunity Updates reassigning Projects';
    static final String UPDATE_OPP_METHOD_NAME = 'UpdateProjectOppsController.updateOpps';

    /**
     * @description method to fetch all open opportunities
     * @param projectId id of project to get the opportunities for
     * @return List of non-Closed opportunity objects
     */
    @AuraEnabled
    public static List<Opportunity> getOppList(Id projectId) {
        return [
            SELECT Id, Name, Project__c, Primary__c, StageName, RecordTypeId
            FROM Opportunity
            WHERE Project__c = :projectId AND StageName NOT IN ('Closed Won', 'Closed Lost')
        ];
    }

    /**
     * @description method to change opportunity field values
     * @param projectId id of project
     * @param oppIds List of Opportunity ids
     * @return String indicating status of changed opps
     */
    @AuraEnabled
    public static string updateOpps(List<Id> oppIds) {
        try {
            // Set<Opportunity> updatedOppSet = new Set<Opportunity>();

            List<Opportunity> updatedOppsList = [SELECT Id, Primary__c FROM Opportunity WHERE Id IN :oppIds];

            for (Opportunity opp : updatedOppsList) {
                if (opp.Primary__c == true) {
                    opp.Primary__c = false;
                } else {
                    opp.Primary__c = true;
                }
            }

            DatabaseUtilities.saveToDatabase(updatedOppsList, UPDATE_OPP_METHOD_NAME, UPDATE_OPP_DEV_NOTE);
            return 'success';
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}