unpackaged/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Container for Opportunities that are part of the same project</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project__c/fields/Closed_Lost_Reason__c.field-meta.xml
<CustomField>
    <fullName>Closed_Lost_Reason__c</fullName>
    <inlineHelpText>Some Closed Lost details require additional information. For example: if selecting Competition please enter the competitor's name or 'Unknown'.</inlineHelpText>
    <label>Closed Lost Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <inlineHelpText>A short description of this Project</inlineHelpText>
    <label>Project</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Initial Engagement</fullName>
            </value>
            <value>
                <fullName>Negotiation / Revision</fullName>
            </value>
            <value>
                <fullName>Pending Payment</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Project__c/recordTypes/Enterprise_Offering.recordType-meta.xml
<RecordType>
    <fullName>Enterprise_Offering</fullName>
    <active>true</active>
    <description>Project record type for Enterprise offerings such as Punchout, MSA, SOW etc</description>
    <label>Enterprise Offering</label>
</RecordType>

unpackaged/main/default/classes/ProjectBatch.cls
global class ProjectBatch implements Database.Batchable<sObject>, Database.Stateful {
    static final String PROJECT_BATCH_METHOD_NAME = 'ProjectBatch.execute';
    static final String PROJECT_BATCH_DEV_NOTE = 'Project Batch update';
    static final Id enterpriseOfferingId = Schema.SObjectType.Project__c.getRecordTypeInfosByDeveloperName()
        .get('Enterprise_Offering')
        .getRecordTypeID();

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            [
                SELECT Id, Stage__c, Closed_Lost_Reason__c
                FROM Project__c
                WHERE
                    Id NOT IN (SELECT Project__c FROM Opportunity)
                    AND Stage__c = 'New'
                    AND RecordTypeId != :enterpriseOfferingId
            ]
        );
    }

    global void execute(Database.BatchableContext bc, List<Project__c> projectList) {
        List<Project__c> projectsToClose = new List<Project__c>();
        for (Project__c proj : projectList) {
            proj.Stage__c = 'Closed Lost';
            proj.Closed_Lost_Reason__c = 'No Opportunities associated -- Closed automatically weekly';
            projectsToClose.add(proj);
        }

        DatabaseUtilities.saveToDatabase(projectsToClose, PROJECT_BATCH_METHOD_NAME, PROJECT_BATCH_DEV_NOTE);
    }

    global void finish(Database.BatchableContext bc) {
    }
}