unpackaged/main/default/objects/P21_Account_Details__c/P21_Account_Details__c.object-meta.xml
<CustomObject>
    <description>Contains information about P21 Customer mapped to an extension of an account</description>
    <label>P21 Account Details</label>
    <nameField>
        <label>P21 Account Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>P21 Account Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/P21_Account_Details__c/fields/Override_Zipcode_Routing__c.field-meta.xml
<CustomField>
    <fullName>Override_Zipcode_Routing__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This will stop the P21 Account Owner from being Changed by automation.</inlineHelpText>
    <label>Override Zipcode Routing</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/P21_Account_Details__c/fields/P21_CustomerID__c.field-meta.xml
<CustomField>
    <fullName>P21_CustomerID__c</fullName>
    <externalId>true</externalId>
    <label>P21 CustomerID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/P21_Account_Details__c/fields/Primary_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Primary_Zip_Code__c</fullName>
    <label>Primary Zip Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/SuppliesTerritoryRoutingBatch.cls
global class SuppliesTerritoryRoutingBatch implements Database.Batchable<sObject>, Database.Stateful {
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            [
                SELECT Id, Primary_Zip_Code__c, P21_CustomerID__C
                FROM P21_Account_Details__C
                WHERE Override_Zipcode_Routing__c = FALSE
            ]
        );
    }

    global void execute(Database.BatchableContext bc, List<P21_Account_Details__C> p21AccountsToUpdate) {
        Map<String, P21_Account_Details__c> p21AccountsToUpdateMap = new Map<String, P21_Account_Details__c>();
        List<routingAddress> p21AccountsToRoute = new List<routingAddress>();
        for (P21_Account_Details__C p21Acct : p21AccountsToUpdate) {
            p21AccountsToUpdateMap.put(p21Acct.P21_CustomerID__C, p21Acct);
            routingAddress myRoutingAddress = new routingAddress(
                p21Acct.Primary_Zip_Code__c,
                null,
                null,
                null,
                p21Acct.P21_CustomerID__C
            );
            p21AccountsToRoute.add(myRoutingAddress);
        }
        p21AccountsToRoute = routingHelper.suppliesTerritoryRouting(p21AccountsToRoute, 'Supplies');

        for (routingAddress rAddr : p21AccountsToRoute) {
            if (p21AccountsToUpdateMap.containsKey(rAddr.sourceID)) {
                p21AccountsToUpdateMap.get(rAddr.sourceID).OwnerID = rAddr.routedOwnerID;
            }
        }

        if (!p21AccountsToUpdateMap.values().isEmpty()) {
            DatabaseUtilities.saveToDatabase(
                p21AccountsToUpdateMap.values(),
                'SuppliesTerritoryRountingBatch',
                'Updating P21 Account Owners'
            );
        }
    }

    global void finish(Database.BatchableContext bc) {
    }
}