unpackaged/main/default/objects/PSE_Form__c/PSE_Form__c.object-meta.xml
<CustomObject>
    <description>Manual Quote Forms that gather additional information when a customer needs a Manual Quote created.
Currently, only applies to IM, CNC, Additive, and Die Casting (2021-04-29)
Currently, the forms exist in Hubspot and are being connected to Salesforce via Hubspot -&gt; Snowflake -&gt; Workato -&gt; Salesforce (2021-04-29)</description>
    <label>PSE Form</label>
    <nameField>
        <displayFormat>PSE Form # {00000000}</displayFormat>
        <label>PSE Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSE Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/PSE_Form__c/fields/Active_Project__c.field-meta.xml
<CustomField>
    <fullName>Active_Project__c</fullName>
    <label>Active Project or Cost Check</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/PSE_Form__c/fields/Additional_Info__c.field-meta.xml
<CustomField>
    <fullName>Additional_Info__c</fullName>
    <inlineHelpText>Is there anything else you would like us to know about your project as we begin quoting your design?</inlineHelpText>
    <label>Is there anything else we should know?</label>
    <length>65536</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/PSE_Form__c/fields/cosmetic_or_structural_parts__c.field-meta.xml
<CustomField>
    <fullName>cosmetic_or_structural_parts__c</fullName>
    <description>Are your parts cosmetic, structural or both? Are your parts cosmetic, structural or both?</description>
    <label>cosmetic,structuralorboth?</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/PSE_Form__c/fields/Design_Feedback__c.field-meta.xml
<CustomField>
    <fullName>Design_Feedback__c</fullName>
    <inlineHelpText>Are you open to receiving design feedback that may reduce your cost/lead time?</inlineHelpText>
    <label>AreYouOpenToRecevingDesignFeedback?</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/PSE_Form__c/fields/Estimated_Future_Volume__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Future_Volume__c</fullName>
    <inlineHelpText>After your initial order, what is your estimated future demand and over what time period?</inlineHelpText>
    <label>What is your estimated future demand?</label>
    <length>65536</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/PSE_Form__c/fields/How_Many_Additional_Trial_Parts_Needed__c.field-meta.xml
<CustomField>
    <fullName>How_Many_Additional_Trial_Parts_Needed__c</fullName>
    <label>How Many Additional Trial Parts Needed</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/PSE_Form__c/fields/Important_Aspect__c.field-meta.xml
<CustomField>
    <fullName>Important_Aspect__c</fullName>
    <inlineHelpText>What is the most important aspect of your project? We want to optimize our quote to your priorities.</inlineHelpText>
    <label>WhatIsTheMostImportantAspectofYourProj?</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/PSE_Form__c/fields/Is_a_formal_production_approval_process__c.field-meta.xml
<CustomField>
    <fullName>Is_a_formal_production_approval_process__c</fullName>
    <description>Is a formal production approval process required (PPAP)?</description>
    <label>Is a formal production approval process</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/PSE_Form__c/fields/Needs_Additional_Trial_Parts__c.field-meta.xml
<CustomField>
    <fullName>Needs_Additional_Trial_Parts__c</fullName>
    <label>Needs Additional Trial Parts?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/PSE_Form__c/fields/Ordered_From_Xometry_Before__c.field-meta.xml
<CustomField>
    <fullName>Ordered_From_Xometry_Before__c</fullName>
    <label>Ordered These Parts From Xometry Before</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/PSE_Form__c/fields/ordering_additional_volume_picklist__c.field-meta.xml
<CustomField>
    <fullName>ordering_additional_volume_picklist__c</fullName>
    <description>User plans to order additional volume of these parts. This data is represented as a picklist rather than a checkbox because the PSE Form dashboard can only display nullable fields.</description>
    <label>Plans To Order Additional Volume?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/PSE_Form__c/fields/Price_For_Parts__c.field-meta.xml
<CustomField>
    <fullName>Price_For_Parts__c</fullName>
    <description>Question: What price for these parts would make you want to work with us? on CNC Form</description>
    <inlineHelpText>What price for these parts would make you want to work with us?</inlineHelpText>
    <label>What price for these parts to use Xom?</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/PSE_Form__c/fields/Quote_ERP__c.field-meta.xml
<CustomField>
    <fullName>Quote_ERP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote ERP</label>
    <referenceTo>Quote_ERP__c</referenceTo>
    <relationshipLabel>PSE Forms</relationshipLabel>
    <relationshipName>PSE_Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/PSE_Form__c/fields/Quote_ID__c.field-meta.xml
<CustomField>
    <fullName>Quote_ID__c</fullName>
    <externalId>true</externalId>
    <label>Quote ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/PSE_Form__c/fields/usa_production_required__c.field-meta.xml
<CustomField>
    <fullName>usa_production_required__c</fullName>
    <label>manufacturedinUSA?</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/PSE_Form__c/fields/WhenDoYouNeedYourOrderDelivered__c.field-meta.xml
<CustomField>
    <fullName>WhenDoYouNeedYourOrderDelivered__c</fullName>
    <description>when_do_you_need_your_order_delivered_ in Hubspot</description>
    <label>When Do You Need Your Order Delivered?</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/PSE_Form__c/fields/WhenLikelyToPlaceOrder__c.field-meta.xml
<CustomField>
    <fullName>WhenLikelyToPlaceOrder__c</fullName>
    <description>when_likely_to_place_order in Hubspot</description>
    <label>When Likely To Place Order?</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/PSE_Form__c/recordTypes/Dynamic_Form.recordType-meta.xml
<RecordType>
    <fullName>Dynamic_Form</fullName>
    <active>true</active>
    <description>Semi-Structured PSE Form Data</description>
    <label>Dynamic Form</label>
</RecordType>

unpackaged/main/default/objects/Quote_ERP__c/Quote_ERP__c.object-meta.xml
<CustomObject>
    <description>A quote that is sent over from ERP</description>
    <label>Quote ERP</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote_ERP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes ERP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Quote_ERP__c/fields/Xometry_ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>Xometry_ERP_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Unique Qoute ID created in Xometry ERP</description>
    <externalId>true</externalId>
    <label>Quote ID</label>
    <length>13</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/XomEndpoint_MQRequestResourceTest.cls
@isTest
public class XomEndpoint_MQRequestResourceTest {
    
    @isTest
    static void testPseCasesCanBeCreated() {        
        Quote_ERP__C quote = TestDataFactory.createQuote(false);
        quote.Xometry_ERP_ID__C = 'AAAAA-00001';
        insert quote;

        List<XomEndpoint_MQRequestResource.MQPseDataItem> boundaryQuestionObjects = new List<XomEndpoint_MQRequestResource.MQPseDataItem> {
            new XomEndpoint_MQRequestResource.MQPseDataItem(
                'Test Label 1',
                'Test Key 1',
                'Test Value 1'
            ),
            new XomEndpoint_MQRequestResource.MQPseDataItem(
                'Test Label 2',
                'Test Key 2',
                'Test Value 2'
            )
        };
        
        Test.startTest();
        XomEndpoint_MQRequestResource.MQRequestResponseShape response = XomEndpoint_MQRequestResource.createMQRequest('AAAAA-00001', 'pse_form_cnc', boundaryQuestionObjects);
        Test.stopTest();

        PSE_Form__c pseForm = [SELECT Id, Quote_ID__c, RecordTypeId  FROM PSE_Form__c WHERE Quote_ID__c = 'AAAAA-00001'];

        System.assertEquals(pseForm.id, response.PSEFormObjectId, 'REST response did not return PSEForm ID');
    }

    @isTest
    static void testSlugsMapToPSEFields() {        
        Quote_ERP__C quote = TestDataFactory.createQuote(false);
        quote.Xometry_ERP_ID__C = 'AAAAA-00001';
        insert quote;


        List<XomEndpoint_MQRequestResource.MQPseDataItem> boundaryQuestionObjects = new List<XomEndpoint_MQRequestResource.MQPseDataItem> {
            new XomEndpoint_MQRequestResource.MQPseDataItem(
                'Are you open to receiving design feedback that may reduce your cost or lead time?',
                'open_to_design_feedback',
                'No'
            ),
            new XomEndpoint_MQRequestResource.MQPseDataItem(
                'Is there anything else you would like us to know about your project?',
                'anything_else_we_should_know',
                'Nothing comes to mind.'
            ),
            new XomEndpoint_MQRequestResource.MQPseDataItem(
                'When do you need your parts to be delivered?',
                'when_need_order_delivered',
                '2023-01-29'
            ),
            new XomEndpoint_MQRequestResource.MQPseDataItem(
                'When will you place the order?',
                'when_likely_to_place_order',
                '2023-01-20'
            ),
            new XomEndpoint_MQRequestResource.MQPseDataItem(
                'Do your parts need to be manufactured in the U.S.?',
                'parts_must_be_made_in_usa',
                'Yes'
            ),
            new XomEndpoint_MQRequestResource.MQPseDataItem(
                'Do you have a price target?',
                'what_price_for_parts',
                '$1000'
            ),
            new XomEndpoint_MQRequestResource.MQPseDataItem(
                'Select the option that better matches the priorities of your project.',
                'important_aspect',
                'Shortest Possible Leadtime'
            ),
            new XomEndpoint_MQRequestResource.MQPseDataItem(
                'Have you ordered this part from Xometry before?',
                'ordered_from_xometry_before',
                'Yes'
            ),
            new XomEndpoint_MQRequestResource.MQPseDataItem(
                'Do you plan on ordering additional quantities of this design in the future?',
                'plan_on_ordering_more',
                'Yes'
            ),
            new XomEndpoint_MQRequestResource.MQPseDataItem(
                'Are your parts cosmetic, structural or both?',
                'cosmetic_or_structural_parts',
                'Cosmetic'
            ),
            new XomEndpoint_MQRequestResource.MQPseDataItem(
                'Is a formal Production Part Approval Process (PAPP) required on this project?',
                'is_papp_required',
                'Yes'
            ),
            new XomEndpoint_MQRequestResource.MQPseDataItem(
                'Is this an order for an active project or are you inquiring for budgetary reasons?',
                'active_or_checking_cost',
                'I am checking the cost.'
            ),
            new XomEndpoint_MQRequestResource.MQPseDataItem(
                'The tooling cost includes 10 trial parts. Will you need more trial parts before your order is complete?',
                'additional_trial_parts_quantity',
                '10 Trial Parts'
            ),
            new XomEndpoint_MQRequestResource.MQPseDataItem(
                'After this order, when are you likely to order again and in what quantity?',
                'estimated_future_volume',
                'Next week, 1000 units.'
            ),
            new XomEndpoint_MQRequestResource.MQPseDataItem(
                'Will you need more trial parts before your order is complete?',
                'needs_additional_trial_parts',
                'yEs'
            )
        };
        
        Test.startTest();
        XomEndpoint_MQRequestResource.MQRequestResponseShape response = XomEndpoint_MQRequestResource.createMQRequest('AAAAA-00001', 'pse_form_cnc', boundaryQuestionObjects);
        Test.stopTest();

        Map<String, String> fieldNameToExpectedValue = new Map<String, String>{
            'Design_Feedback__c' => 'No',
            'Additional_Info__c' => 'Nothing comes to mind.',
            'WhenDoYouNeedYourOrderDelivered__c' => '2023-01-29',
            'WhenLikelyToPlaceOrder__c' => '2023-01-20',
            'usa_production_required__c' => 'Yes',
            'Price_For_Parts__c' => '$1000',
            'Important_Aspect__c' => 'Shortest Possible Leadtime',
            'Ordered_From_Xometry_Before__c' => 'Yes',
            'ordering_additional_volume_picklist__c' => 'Yes',
            'cosmetic_or_structural_parts__c' => 'Cosmetic',
            'Is_a_formal_production_approval_process__c' => 'Yes',
            'Active_Project__c' => 'I am checking the cost.',
            'How_Many_Additional_Trial_Parts_Needed__c' => '10 Trial Parts',
            'Estimated_Future_Volume__c' => 'Next week, 1000 units.',
            'Needs_Additional_Trial_Parts__c' => 'Yes'
        };
        List<String> fieldNameList = new List<String>();
        for (String fieldName : fieldNameToExpectedValue.keySet()) {
            fieldNameList.add(fieldName);
        }

        PSE_Form__c pseForm = Database.query(
            'SELECT Id, Quote_ID__c, RecordTypeId, ' +
            String.join(fieldNameList, ', ') +
            ' FROM PSE_Form__c where Quote_ID__c = \'AAAAA-00001\' LIMIT 1'
        );

        System.assertEquals(
            pseForm.RecordTypeId,
            Schema.SObjectType.PSE_Form__c.getRecordTypeInfosByDeveloperName().get('Dynamic_Form').getRecordTypeId(),
            'Expected Record Type ID to correspond to the "Dynamic_Form" Record Type Developer Name.'
        );

        for (String fieldName: fieldNameToExpectedValue.keySet()) {
            System.assertEquals(
                pseForm.get(fieldName),
                fieldNameToExpectedValue.get(fieldName),
                'Field: ' + fieldName + ' was not copied correctly.'
            );
        }

        System.assertEquals(pseForm.id, response.PSEFormObjectId, 'REST response did not return PSEForm ID');
    }
}