unpackaged/main/default/objects/PSE_Form__c/PSE_Form__c.object-meta.xml
<CustomObject>
    <description>Manual Quote Forms that gather additional information when a customer needs a Manual Quote created.
Currently, only applies to IM, CNC, Additive, and Die Casting (2021-04-29)
Currently, the forms exist in Hubspot and are being connected to Salesforce via Hubspot -&gt; Snowflake -&gt; Workato -&gt; Salesforce (2021-04-29)</description>
    <label>PSE Form</label>
    <nameField>
        <displayFormat>PSE Form # {00000000}</displayFormat>
        <label>PSE Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSE Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/PSE_Form__c/fields/Quote_ID__c.field-meta.xml
<CustomField>
    <fullName>Quote_ID__c</fullName>
    <externalId>true</externalId>
    <label>Quote ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/PSE_Form__c/recordTypes/Dynamic_Form.recordType-meta.xml
<RecordType>
    <fullName>Dynamic_Form</fullName>
    <active>true</active>
    <description>Semi-Structured PSE Form Data</description>
    <label>Dynamic Form</label>
</RecordType>

unpackaged/main/default/classes/XomEndpoint_MQRequestResource.cls
@RestResource(urlMapping='/CreateMQRequest/v1/*')
global class XomEndpoint_MQRequestResource {
    global class MQPseDataItem {
        String label;
        String key;
        String value;

        // Exclusively consumed by the Test Class 
        public MqPseDataItem(String label, String key, String value) {
            this.label = label;
            this.key = key;
            this.value = value;
        }
    }

    global class MQRequestResponseShape {
        public String PSEFormObjectId;

        public MQRequestResponseShape(String PSEFormObjectId) {
            this.PSEFormObjectId = PSEFormObjectId;
        }
    }


    public static void updatePSEFormFromQuestions(
        List<MQPseDataItem> questions,
        PSE_Form__c pseForm
    ) {
        for (MQPseDataItem q : questions) {
            String mappedPSEFormFieldName = PSEFormFieldMapper.getPSEFormFieldName(q.key);

            if (String.isBlank(mappedPSEFormFieldName)) {
                continue;
            }

            // These are Yes/No picklists. They have a little bit of extra
            // processing to make piping data into the fields less brittle.
            String mappedPSEFormFieldValue = q.value;
            if (q.key == 'plan_on_ordering_more' || q.key == 'needs_additional_trial_parts') {
                // This key maps to a picklist, so we add some special treatment
                // to make it not so prone to failure
                mappedPseFormFieldValue = mappedPSEFormFieldValue.toLowerCase() == 'yes' ? 'Yes' : 'No';
            }

            pseForm.put(mappedPSEFormFieldName, mappedPSEFormFieldValue);
        }
    }

    @HttpPost
    global static MQRequestResponseShape createMQRequest(
        String quoteId,
        String questionnaireSlug,
        List<MQPseDataItem> questions
    ) {

        PSE_Form__c pseForm = new PSE_Form__c(
            Quote_ID__c = quoteId,
            RecordTypeId = Schema.SObjectType.PSE_Form__c.getRecordTypeInfosByDeveloperName()
            .get('Dynamic_Form')
            .getRecordTypeId()
        );
        
        updatePSEFormFromQuestions(questions, pseForm);

        DatabaseUtilities.insertToDatabase(
            new List<PSE_Form__c>{ pseForm },
            'XomEndpoint_MQRequestResource.createMQRequest',
            'Insert PSE Form object before Linking Question objects'
        );

        return new MQRequestResponseShape(pseForm.id);
    }
}