unpackaged/main/default/objects/PSE_Form__c/PSE_Form__c.object-meta.xml
<CustomObject>
    <description>Manual Quote Forms that gather additional information when a customer needs a Manual Quote created.
Currently, only applies to IM, CNC, Additive, and Die Casting (2021-04-29)
Currently, the forms exist in Hubspot and are being connected to Salesforce via Hubspot -&gt; Snowflake -&gt; Workato -&gt; Salesforce (2021-04-29)</description>
    <label>PSE Form</label>
    <nameField>
        <displayFormat>PSE Form # {00000000}</displayFormat>
        <label>PSE Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSE Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/PSE_Form__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>ORIGINAL Case that the Quote is/was associated with.</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>PSE Forms</relationshipLabel>
    <relationshipName>PSE_Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/pseFormDisplayController.cls
public with sharing class pseFormDisplayController {
    public class PSEFormFoundResult {
        @AuraEnabled
        public List<String> pseFormFieldNames { get;set; }
        
        @AuraEnabled
        public Id pseFormId { get;set; }

        public PSEFormFoundResult(List<String> pseFormFieldNames, Id pseFormId) {
            this.pseFormFieldNames = pseFormFieldNames;
            this.pseFormId = pseFormId;
        }
    }
    
    @AuraEnabled
    public static PSEFormFoundResult getPSEQuestionsForCaseId(Id caseId) {
        
        List<String> pseFormDashboardFieldNames = PSEFormFieldMapper.getAllPSEFormDashboardFieldNames();
        
        List<PSE_Form__c> pseFormCheck = Database.query(
            'SELECT Id, ' +
            String.join(pseFormDashboardFieldNames, ', ') +
            ' FROM PSE_Form__c where Case__c=:caseId LIMIT 1'
        );

        if (pseFormCheck.isEmpty()) {
            return null;
        }

        PSE_Form__c pseForm = pseFormCheck[0];

        List<String> populatedPseFormFieldNames = new List<String>{};
        
        for (String fieldName : pseFormDashboardFieldNames) {
            Object value = pseForm.get(fieldName);

            if (value != null) {
                populatedPseFormFieldNames.add(fieldName);
            }
        }

        return new PSEFormFoundResult(
            populatedPseFormFieldNames, pseForm.Id
        );
    }
}