unpackaged/main/default/objects/Audit_Trail_Error__c/Audit_Trail_Error__c.object-meta.xml
<CustomObject>
    <label>Audit Trail Error</label>
    <nameField>
        <displayFormat>AER-{0}</displayFormat>
        <label>Audit Trail Error Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit Trail Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Audit_Trail_Error__c/fields/Dev_Audit_Notes__c.field-meta.xml
<CustomField>
    <fullName>Dev_Audit_Notes__c</fullName>
    <description>Additional Notes Captured by Developer at time of error/Exception as needed.</description>
    <label>Dev Audit Notes</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Audit_Trail_Error__c/fields/errorMessage__c.field-meta.xml
<CustomField>
    <fullName>errorMessage__c</fullName>
    <description>ErrorMessage that is returned from Apex/Lightning</description>
    <label>errorMessage</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Audit_Trail_Error__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <description>Developer Name for where error Occurred. Should match Apex/Lightning component.</description>
    <label>Module</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/EmailMessageHelper.cls
public with sharing class EmailMessageHelper {
    /**
     * @description Helper class for EmailMessages
     * Reduces queries in AppConstants since all these of these are used to send an email, but nowhere else
     */
    public static final Boolean inSandbox = [
        SELECT IsSandbox
        FROM Organization
        WHERE Id = :UserInfo.getOrganizationId()
    ]
    .IsSandbox;

    public static final String supportRoutingAddress{
        get{
            if(supportRoutingAddress == null){
                if(inSandbox){
                    String emailDomainName = [SELECT EmailDomainName FROM EmailServicesAddress WHERE DeveloperName = 'support' LIMIT 1]?.EmailDomainName;
                    supportRoutingAddress = 'support@' + ( emailDomainName != null ? emailDomainName : 'testxometry.com' );
                }else{
                    supportRoutingAddress = 'support@xometry.com';
                }
            }


            return supportRoutingAddress;

        }
        set;
    }

    public static List<Messaging.SendEmailResult> sendEmail(List<Messaging.SingleEmailMessage> sendEmails, Boolean allOrNothing){
        
        List<Messaging.SendEmailResult> results = new List<Messaging.SendEmailResult>();

        if(!EmailMessageHelper.InSandbox){

            results = Messaging.sendEmail(sendEmails, allOrNothing);

        }else{

            List<EmailMessage> testEmailMessageList = new List<EmailMessage>();
            for(Messaging.SingleEmailMessage mail:sendEmails){
                EmailMessage testEmailMessage = new EmailMessage();
                testEmailMessage.ParentId = mail.getWhatId();
                testEmailMessage.Subject = mail.getSubject();
                testEmailMessage.HtmlBody = mail.getHtmlBody();
                testEmailMessageList.add(testEmailMessage);
            }

            insert testEmailMessageList;

        }

        return results;

    }

    public static final EmailTemplate missingEUDEmailTemplate = [
        SELECT Id, Name, Subject, Body
        FROM EmailTemplate
        WHERE Name = 'Missing EUD Text Template'
    ];

    public static final ID supportOrgWideEmailID = [
        SELECT ID
        FROM OrgWideEmailAddress
        WHERE Address = 'support@xometry.com'
        LIMIT 1
    ][0]
    .Id;

    /**
     * @description logs a general exception to audit trail error
     * @param e general exception error
     */
    public static void handleEmailError(Exception e, String module, String dev_audit_notes) {
        Audit_Trail_Error__c auditError = new Audit_Trail_Error__c();
        auditError.Module__c = module;
        auditError.Dev_Audit_Notes__c = dev_audit_notes;
        auditError.errorMessage__c = e.getMessage().abbreviate(250);
        insert auditError;
    }
}