unpackaged/main/default/objects/Audit_Trail_Error__c/Audit_Trail_Error__c.object-meta.xml
<CustomObject>
    <label>Audit Trail Error</label>
    <nameField>
        <displayFormat>AER-{0}</displayFormat>
        <label>Audit Trail Error Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit Trail Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Audit_Trail_Error__c/fields/Dev_Audit_Notes__c.field-meta.xml
<CustomField>
    <fullName>Dev_Audit_Notes__c</fullName>
    <description>Additional Notes Captured by Developer at time of error/Exception as needed.</description>
    <label>Dev Audit Notes</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Audit_Trail_Error__c/fields/errorFields__c.field-meta.xml
<CustomField>
    <fullName>errorFields__c</fullName>
    <description>Column that contains specific fields when an error occurs.</description>
    <label>errorFields</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Audit_Trail_Error__c/fields/errorMessage__c.field-meta.xml
<CustomField>
    <fullName>errorMessage__c</fullName>
    <description>ErrorMessage that is returned from Apex/Lightning</description>
    <label>errorMessage</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Audit_Trail_Error__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <description>Developer Name for where error Occurred. Should match Apex/Lightning component.</description>
    <label>Module</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Audit_Trail_Error__c/fields/StatusCode__c.field-meta.xml
<CustomField>
    <fullName>StatusCode__c</fullName>
    <description>Any Apex/Lightning Status Code that is returned.</description>
    <label>StatusCode</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>GNO Jobs</description>
    <label>Job</label>
    <nameField>
        <label>Job ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Job_is_Past_Due__c.field-meta.xml
<CustomField>
    <fullName>Job_is_Past_Due__c</fullName>
    <formula>IF( OR(ISPICKVAL(Stage__c, 'Completed'), ISPICKVAL(Stage__c, 'Vendor Completed')), 'Fully Shipped',
IF( DueDate__c &lt; TODAY(), TEXT(Job_Overdue_Flag__c) &amp; ' ' &amp; Days_Syntax__c &amp; ' Late',
IF( DueDate__c = TODAY(), 'Due Today', 
'Due in ' &amp; TEXT(ABS(Job_Overdue_Flag__c)) &amp; ' ' &amp; Days_Syntax__c)
) 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Job OTS Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Job_Overdue_Flag__c.field-meta.xml
<CustomField>
    <fullName>Job_Overdue_Flag__c</fullName>
    <label>T- Days to Due Date</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Rescinded</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Vendor Completed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Auction Failed to Award</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/XometryJobID__c.field-meta.xml
<CustomField>
    <fullName>XometryJobID__c</fullName>
    <externalId>true</externalId>
    <label>Xometry Job ID</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/XometryOpsOrderID__c.field-meta.xml
<CustomField>
    <fullName>XometryOpsOrderID__c</fullName>
    <label>Xometry Ops Order ID</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/JobOverdueBatchTest.cls
@isTest
private class JobOverdueBatchTest {
    @isTest(seeAllData=false)
    static void executeOverdueTest() {
        Job__c testJob = new Job__c();
        testJob.Name = 'Test-Job';
        testJob.XometryJobID__c = 'Test-Job';
        testJob.XometryOpsOrderID__c = '1234';
        testJob.DueDate__c = Date.today() - 7;
        insert testJob;

        Test.startTest();
        Database.executeBatch(new JobOverdueBatch());
        Test.stopTest();

        List<Job__c> jobList = [SELECT Job_OverDue_Flag__c, Job_is_Past_Due__c FROM Job__c];

        System.assertEquals(7, jobList[0].Job_OverDue_Flag__c, 'Job OverDue should be updated');
    }

    @isTest(seeAllData=false)
    static void executeNotOverdueTest() {
        Job__c testJob = new Job__c();
        testJob.Name = 'Test-Job';
        testJob.XometryJobID__c = 'Test-Job';
        testJob.XometryOpsOrderID__c = '1234';
        testJob.DueDate__c = Date.today() + 7;
        insert testJob;

        Test.startTest();
        Database.executeBatch(new JobOverdueBatch());
        Test.stopTest();

        List<Job__c> jobList = [SELECT Job_OverDue_Flag__c, Job_is_Past_Due__c FROM Job__c];

        System.assertEquals(-7, jobList[0].Job_OverDue_Flag__c, 'Job OverDue should be updated');
    }

    @isTest(seeAllData=false)
    static void executeShippedOnCreateDayTest() {
        Job__c testJob = new Job__c();
        testJob.Name = 'Test-Job';
        testJob.XometryJobID__c = 'Test-Job';
        testJob.XometryOpsOrderID__c = '1234';
        testJob.DueDate__c = Date.today() - 7;
        testJob.Stage__c = 'Completed';
        insert testJob;

        Test.startTest();
        Database.executeBatch(new JobOverdueBatch());
        Test.stopTest();

        List<Job__c> jobList = [SELECT Job_OverDue_Flag__c, Job_is_Past_Due__c FROM Job__c];

        System.assertEquals(7, jobList[0].Job_OverDue_Flag__c, 'Job OverDue shouldnt be updated');
    }

    @isTest(seeAllData=false)
    static void executeShippedTest() {
        Job__c testJob = new Job__c();
        testJob.Name = 'Test-Job';
        testJob.XometryJobID__c = 'Test-Job';
        testJob.XometryOpsOrderID__c = '1234';
        testJob.DueDate__c = Date.today().addDays(7);
        insert testJob;

        Database.executeBatch(new JobOverdueBatch());

        testJob.Stage__c = 'Vendor Completed';
        update testJob;

        Test.startTest();
        Database.executeBatch(new JobOverdueBatch());
        Test.stopTest();

        List<Job__c> jobList = [SELECT Job_OverDue_Flag__c, Job_is_Past_Due__c FROM Job__c];

        System.assertEquals(-7, jobList[0].Job_OverDue_Flag__c, 'Job OverDue shouldnt be updated');
    }

    @isTest(seeAllData=false)
    static void executeDateNull() {
        Job__c testJob = new Job__c();
        testJob.Name = 'Test-Job';
        testJob.XometryJobID__c = 'Test-Job';
        testJob.XometryOpsOrderID__c = '1234';
        testJob.DueDate__c = null;
        insert testJob;

        Test.startTest();
        Database.executeBatch(new JobOverdueBatch());
        Test.stopTest();

        List<Audit_Trail_Error__c> auditTrail = [
            SELECT ID, name, module__C, dev_audit_notes__c, statusCode__c, errorFields__c, errorMessage__c, CreatedDate
            FROM Audit_Trail_Error__c
        ];
        System.assertEquals(0, auditTrail.size(), 'There should not be any errors');
    }

    @isTest
    static void scheduleTest() {
        String CRON_EXP = '0 0 0 1 1 ? *';

        Test.startTest();
        String jobID = System.schedule('scheduleTest', CRON_EXP, new JobOverdueBatch());
        Test.stopTest();

        System.assertNotEquals(null, jobID, 'Job id is not null');
    }
}