unpackaged/main/default/objects/Audit_Trail_Error__c/Audit_Trail_Error__c.object-meta.xml
<CustomObject>
    <label>Audit Trail Error</label>
    <nameField>
        <displayFormat>AER-{0}</displayFormat>
        <label>Audit Trail Error Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit Trail Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Audit_Trail_Error__c/fields/Dev_Audit_Notes__c.field-meta.xml
<CustomField>
    <fullName>Dev_Audit_Notes__c</fullName>
    <description>Additional Notes Captured by Developer at time of error/Exception as needed.</description>
    <label>Dev Audit Notes</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Audit_Trail_Error__c/fields/errorFields__c.field-meta.xml
<CustomField>
    <fullName>errorFields__c</fullName>
    <description>Column that contains specific fields when an error occurs.</description>
    <label>errorFields</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Audit_Trail_Error__c/fields/errorMessage__c.field-meta.xml
<CustomField>
    <fullName>errorMessage__c</fullName>
    <description>ErrorMessage that is returned from Apex/Lightning</description>
    <label>errorMessage</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Audit_Trail_Error__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <description>Developer Name for where error Occurred. Should match Apex/Lightning component.</description>
    <label>Module</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/BoxAuthenticationSettings__c/BoxAuthenticationSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Box Authentication Settings</label>
</CustomObject>

unpackaged/main/default/objects/BoxAuthenticationSettings__c/fields/Classification_ITAR__c.field-meta.xml
<CustomField>
    <fullName>Classification_ITAR__c</fullName>
    <label>Classification ITAR</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/BoxAuthenticationSettings__c/fields/Classification_NonITAR__c.field-meta.xml
<CustomField>
    <fullName>Classification_NonITAR__c</fullName>
    <label>Classification NonITAR</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/BoxAuthenticationSettings__c/fields/Collaboration_Group__c.field-meta.xml
<CustomField>
    <fullName>Collaboration_Group__c</fullName>
    <description>The Salesforce_Box_User box group ID</description>
    <label>Collaboration Group</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Box_Folder__c.field-meta.xml
<CustomField>
    <fullName>Box_Folder__c</fullName>
    <label>Box Folder</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/BoxITARConsumerFolderId__c.field-meta.xml
<CustomField>
    <fullName>BoxITARConsumerFolderId__c</fullName>
    <label>Box ITAR Consumer Folder Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/BoxNonITARConsumerFolderId__c.field-meta.xml
<CustomField>
    <fullName>BoxNonITARConsumerFolderId__c</fullName>
    <label>Box Non-ITAR Consumer Folder Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Xometry_ERP_Contact_ID__c.field-meta.xml
<CustomField>
    <fullName>Xometry_ERP_Contact_ID__c</fullName>
    <description>The unique Contact Id that is created by the Xometry ERP</description>
    <externalId>true</externalId>
    <label>ERP Contact ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/BoxUserViewController.cls
public class BoxUserViewController {
    @AuraEnabled
    static public List<Contact> getBoxUserContact(String inputEmail) {
        return [SELECT Id, Name, Email, Xometry_ERP_Contact_ID__c FROM Contact WHERE Email = :inputEmail LIMIT 1];
    }

    @AuraEnabled
    static public boolean searchFolder(String caseId) {
        ResultSearchBox.Root result = BoxUtils.search('query=' + caseId + '&type=folder&fields=name');
        if (result.total_count > 0) {
            return true;
        } else {
            return false;
        }
    }

    @AuraEnabled
    static public CreateFolderResponse createFolder(String caseId) {
        CreateFolderResponse resp;

        try {
            Case objCase = [SELECT CaseNumber, CreatedDate FROM Case WHERE Id = :caseId];
            String strRootFolderName = objCase.CreatedDate.format('yyyy MMMM');
            String strIdRootFolder;

            ResultSearchBox.Root result = BoxUtils.search(
                'query=%22%0A' +
                strRootFolderName.replace(' ', '+') +
                '%22%0A&type=folder&fields=name'
            );
            if (result.total_count == 0) {
                // String strCasesRootFolderId = '207368767577';

                String strCasesFolderName = 'Cases';
                ResultSearchBox.Root resultCases = BoxUtils.search(
                    'query=' +
                    strCasesFolderName +
                    '&type=folder&fields=name'
                );
                String strCasesRootFolderId = resultCases.entries[0].id;

                strIdRootFolder = BoxUtils.createFolder(strCasesRootFolderId, strRootFolderName);
            } else {
                strIdRootFolder = result.entries[0].id;
            }

            String caseFolderId = BoxUtils.createFolderForRecordId(caseId, objCase.caseNumber);
            BoxUtils.moveFolder(strIdRootFolder, caseFolderId);

            //Create SubFolders
            String itarInternalFolderId = BoxUtils.createFolder(
                caseFolderId,
                objCase.caseNumber + '-Sensitive-Internal'
            );
            String itarConsumerFolderId = BoxUtils.createFolder(
                itarInternalFolderId,
                'Sensitive-' +
                objCase.caseNumber +
                '-Consumer'
            );

            String nonItarinternalFolderId = BoxUtils.createFolder(
                caseFolderId,
                objCase.caseNumber + '-Not Export-Controlled-Internal'
            );
            String nonItarConsumerFolderId = BoxUtils.createFolder(
                nonItarinternalFolderId,
                'Not Export-Controlled-' +
                objCase.caseNumber +
                '-Consumer'
            );

            if (!System.isBatch()) {
                createFolderPostProcessingFuture(
                    objCase.Id,
                    caseFolderId,
                    nonItarinternalFolderId,
                    itarInternalFolderId,
                    nonItarConsumerFolderId,
                    itarConsumerFolderId
                );

                BoxUtils.commitChanges();
            } else {
                createFolderPostProcessing(
                    objCase.Id,
                    caseFolderId,
                    nonItarinternalFolderId,
                    itarInternalFolderId,
                    nonItarConsumerFolderId,
                    itarConsumerFolderId
                );
            }

            resp = new CreateFolderResponse('Success', caseFolderId, itarConsumerFolderId, nonItarConsumerFolderId);
        } catch (Exception e) {
            resp = new CreateFolderResponse(e.getMessage(), '', '', '');
        }

        return resp;
    }

    @future(callout=true)
    static public void createFolderPostProcessingFuture(
        Id caseId,
        String caseFolderId,
        String nonItarinternalFolderId,
        String itarInternalFolderId,
        String nonItarConsumerFolderId,
        String itarConsumerFolderId
    ) {
        createFolderPostProcessing(
            caseId,
            caseFolderId,
            nonItarinternalFolderId,
            itarInternalFolderId,
            nonItarConsumerFolderId,
            itarConsumerFolderId
        );

        List<Case> case2up = new List<Case>();
        case2up.add(
            new Case(
                Id = caseId,
                Box_Folder__c = caseFolderId,
                BoxITARConsumerFolderId__c = itarConsumerFolderId,
                BoxNonITARConsumerFolderId__c = nonItarConsumerFolderId
            )
        );
        DatabaseUtilities.saveToDatabase(case2up, 'addDefaultCollaborator', 'Update Case box folder Id');
    }

    static public void createFolderPostProcessing(
        Id caseId,
        String caseFolderId,
        String nonItarinternalFolderId,
        String itarInternalFolderId,
        String nonItarConsumerFolderId,
        String itarConsumerFolderId
    ) {
        addDefaultCollaborator(caseFolderId, nonItarinternalFolderId);

        addDefaultClassification(nonItarinternalFolderId, itarInternalFolderId);
    }

    static public String addDefaultCollaborator(String caseFolderId, String nonItarinternalFolderId) {
        String resp = 'Success';
        try {
            BoxAuthenticationSettings__c bas = BoxAuthenticationSettings__c.getInstance();

            String groupId = bas.Collaboration_Group__c;
            BoxUtils.BoxResponse boxResp = BoxUtils.addCollaborator(
                nonItarinternalFolderId,
                'folder',
                groupId,
                'group',
                'editor'
            );
        } catch (Exception e) {
            resp = e.getMessage();
        }

        return resp;
    }

    static public String addDefaultClassification(String nonItarinternalFolderId, String itarInternalFolderId) {
        String resp;

        try {
            BoxAuthenticationSettings__c bas = BoxAuthenticationSettings__c.getInstance();

            BoxUtils.BoxResponse boxResp = BoxUtils.addLabelClassificationToFolder(
                nonItarinternalFolderId,
                bas.Classification_NonITAR__c
            );

            BoxUtils.BoxResponse boxResp2 = BoxUtils.addLabelClassificationToFolder(
                itarInternalFolderId,
                bas.Classification_ITAR__c
            );

            BoxUtils.BoxResponse boxResp3 = BoxUtils.addCascadePolicyToFolder(nonItarinternalFolderId);

            Map<String, Object> respMap = (Map<String, Object>) JSON.deserializeUntyped(boxResp3.data);
            System.debug(LoggingLevel.ERROR, '*** respMap: ' + respMap);
            if (respMap.containsKey('id')) {
                BoxUtils.forceCascadePolicy(String.valueOf(respMap.get('id')));
            }

            BoxUtils.BoxResponse boxResp4 = BoxUtils.addCascadePolicyToFolder(itarInternalFolderId);

            Map<String, Object> respMap2 = (Map<String, Object>) JSON.deserializeUntyped(boxResp4.data);
            System.debug(LoggingLevel.ERROR, '*** respMap2: ' + respMap2);
            if (respMap2.containsKey('id')) {
                BoxUtils.forceCascadePolicy(String.valueOf(respMap2.get('id')));
            }

            resp = 'success';
        } catch (Exception e) {
            resp = e.getMessage();
        }

        return resp;
    }

    @AuraEnabled
    static public String createUser(string name, string login, string external_app_user_id, string job_title) {
        try {
            BoxUser.CreateUserRequest objUser = new BoxUser.CreateUserRequest();
            objUser.name = name;
            objUser.login = login;
            objUser.external_app_user_id = external_app_user_id;
            objUser.job_title = null;
            BoxUtils.createUser(objUser);
            return 'Success';
        } catch (Exception e) {
            return e.getMessage();
        }
    }

    @AuraEnabled
    static public void addAuditError(string email, string errorMessage) {
        try {
            Audit_Trail_Error__c auditError = new Audit_Trail_Error__c();
            auditError.Module__c = 'boxUserView';
            auditError.Dev_Audit_Notes__c = 'Contact search from box';
            auditError.errorMessage__c = 'LWC BoxUser: ' + errorMessage;
            auditError.errorFields__c = email;
            insert auditError;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}