unpackaged/main/default/objects/Audit_Trail_Error__c/Audit_Trail_Error__c.object-meta.xml
<CustomObject>
    <label>Audit Trail Error</label>
    <nameField>
        <displayFormat>AER-{0}</displayFormat>
        <label>Audit Trail Error Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit Trail Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Audit_Trail_Error__c/fields/Dev_Audit_Notes__c.field-meta.xml
<CustomField>
    <fullName>Dev_Audit_Notes__c</fullName>
    <description>Additional Notes Captured by Developer at time of error/Exception as needed.</description>
    <label>Dev Audit Notes</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Audit_Trail_Error__c/fields/errorFields__c.field-meta.xml
<CustomField>
    <fullName>errorFields__c</fullName>
    <description>Column that contains specific fields when an error occurs.</description>
    <label>errorFields</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Audit_Trail_Error__c/fields/errorMessage__c.field-meta.xml
<CustomField>
    <fullName>errorMessage__c</fullName>
    <description>ErrorMessage that is returned from Apex/Lightning</description>
    <label>errorMessage</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Audit_Trail_Error__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <description>Developer Name for where error Occurred. Should match Apex/Lightning component.</description>
    <label>Module</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Audit_Trail_Error__c/fields/StatusCode__c.field-meta.xml
<CustomField>
    <fullName>StatusCode__c</fullName>
    <description>Any Apex/Lightning Status Code that is returned.</description>
    <label>StatusCode</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Ops_Order__c/Ops_Order__c.object-meta.xml
<CustomObject>
    <description>Order object for the GNO Team. Used for purposes of tracking orders and jobs.</description>
    <label>Ops Order</label>
    <nameField>
        <label>Ops Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ops Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Ops_Order__c/fields/ERPStatus__c.field-meta.xml
<CustomField>
    <fullName>ERPStatus__c</fullName>
    <label>ERP Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Ops_Order__c/fields/Order_is_Past_Due__c.field-meta.xml
<CustomField>
    <fullName>Order_is_Past_Due__c</fullName>
    <formula>IF( OR(  ISPICKVAL(Stage__c, 'Completed'),ISPICKVAL(Stage__c, 'Vendor Completed') ),

'Order is Shipped',

IF( OrderDueDate__c &lt; TODAY() ,

'Order is Overdue by ' &amp; TEXT(Order_OverDue_Flag__c) &amp; ' days',

IF( OrderDueDate__c = TODAY(), 'Order is not due yet', 'Order is not due yet - Due in ' &amp; TEXT(ABS(Order_OverDue_Flag__c)) &amp; ' days')

)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order is Past Due</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Ops_Order__c/fields/Order_OverDue_Flag__c.field-meta.xml
<CustomField>
    <fullName>Order_OverDue_Flag__c</fullName>
    <label>Order OverDue Flag</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Ops_Order__c/fields/XometryOpsOrderID__c.field-meta.xml
<CustomField>
    <fullName>XometryOpsOrderID__c</fullName>
    <externalId>true</externalId>
    <label>Xometry Ops Order ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/OrderOverdueBatchTest.cls
@isTest
private class OrderOverdueBatchTest {
    @isTest(seeAllData=false)
    static void executeOverdueTest() {
        Ops_Order__c testOrder = new Ops_Order__c(XometryOpsOrderID__c = 'AAAAA-00001');
        testOrder.OrderDueDate__c = Date.today() - 7;
        insert testOrder;

        Test.startTest();
        Database.executeBatch(new OrderOverdueBatch());
        Test.stopTest();

        List<Ops_Order__c> orderList = [SELECT Order_OverDue_Flag__c, Order_is_Past_Due__c FROM Ops_Order__c];

        System.assertEquals(7, orderList[0].Order_OverDue_Flag__c, 'Order OverDue should be updated');
    }

    @isTest(seeAllData=false)
    static void executeNotOverdueTest() {
        Ops_Order__c testOrder = new Ops_Order__c(XometryOpsOrderID__c = 'AAAAA-00001');
        testOrder.OrderDueDate__c = Date.today() + 7;
        insert testOrder;

        Test.startTest();
        Database.executeBatch(new OrderOverdueBatch());
        Test.stopTest();

        List<Ops_Order__c> orderList = [SELECT Order_OverDue_Flag__c, Order_is_Past_Due__c FROM Ops_Order__c];

        System.assertEquals(-7, orderList[0].Order_OverDue_Flag__c, 'Order OverDue should be updated');
    }

    @isTest(seeAllData=false)
    static void executeShippedTest() {
        Ops_Order__c testOrder = new Ops_Order__c(XometryOpsOrderID__c = 'AAAAA-00001');
        testOrder.ERPStatus__c = 'Shipped';
        testOrder.OrderDueDate__c = Date.today() + 7;
        insert testOrder;

        Test.startTest();
        Database.executeBatch(new OrderOverdueBatch());
        Test.stopTest();

        List<Ops_Order__c> orderList = [SELECT Order_OverDue_Flag__c, Order_is_Past_Due__c FROM Ops_Order__c];

        System.assertEquals(null, orderList[0].Order_OverDue_Flag__c, 'Order OverDue should be updated');
    }

    @isTest(seeAllData=false)
    static void executeDateNull() {
        Ops_Order__c testOrder = new Ops_Order__c(XometryOpsOrderID__c = 'AAAAA-00001');
        testOrder.OrderDueDate__c = null;
        insert testOrder;

        Test.startTest();
        Database.executeBatch(new OrderOverdueBatch());
        Test.stopTest();

        List<Audit_Trail_Error__c> auditTrail = [
            SELECT ID, name, module__C, dev_audit_notes__c, statusCode__c, errorFields__c, errorMessage__c, CreatedDate
            FROM Audit_Trail_Error__c
        ];
        System.assertEquals(0, auditTrail.size(), 'There should not be any errors');
    }

    @isTest
    static void scheduleTest() {
        String CRON_EXP = '0 0 0 1 1 ? *';

        Test.startTest();
        String jobID = System.schedule('scheduleTest', CRON_EXP, new OrderOverdueBatch());
        Test.stopTest();

        System.assertNotEquals(null, jobID, 'Job id is not null');
    }
}