unpackaged/main/default/objects/Audit_Trail_Error__c/Audit_Trail_Error__c.object-meta.xml
<CustomObject>
    <label>Audit Trail Error</label>
    <nameField>
        <displayFormat>AER-{0}</displayFormat>
        <label>Audit Trail Error Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit Trail Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Audit_Trail_Error__c/fields/Dev_Audit_Notes__c.field-meta.xml
<CustomField>
    <fullName>Dev_Audit_Notes__c</fullName>
    <description>Additional Notes Captured by Developer at time of error/Exception as needed.</description>
    <label>Dev Audit Notes</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Audit_Trail_Error__c/fields/errorMessage__c.field-meta.xml
<CustomField>
    <fullName>errorMessage__c</fullName>
    <description>ErrorMessage that is returned from Apex/Lightning</description>
    <label>errorMessage</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Audit_Trail_Error__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <description>Developer Name for where error Occurred. Should match Apex/Lightning component.</description>
    <label>Module</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Audit_Trail_Error__c/fields/SourceId__c.field-meta.xml
<CustomField>
    <fullName>SourceId__c</fullName>
    <label>SourceId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/Order_Erp__c.object-meta.xml
<CustomObject>
    <description>This object cotains the orders from Xometry ERP. An order is created in Salesforce when the Order date is populated. 

Technical Note: Quote and Orders are the same object in the source system but seperated in Salesforce as Orders represent the end of the opportunity process.</description>
    <label>Order ERP</label>
    <nameField>
        <displayFormat>Order-{000000}</displayFormat>
        <label>Order Erp Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders ERP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/classes/emailLauncher.cls
public with sharing class emailLauncher implements Queueable {
    private set<ID> caseIDToEmailSet;
    private Map<ID, String> eudCaseToOrderMap;
    private List<Order_ERP__C> inOrdersList;
    private Integer retryCount;
    private final Integer retryMaxCount = 2;

    public emailLauncher(set<ID> caseIDToEmailSet, Map<ID, String> eudCaseToOrderMap, List<Order_ERP__C> inOrdersList, Integer retryCount) {
        this.CaseIDToEmailSet = caseIDToEmailSet;
        this.eudCaseToOrderMap = eudCaseToOrderMap;
        this.inOrdersList = inOrdersList;
        this.retryCount = retryCount;
    }

    public void execute(QueueableContext context) {
        Integer emailChunkSize = 20;
        System.debug('Email launcher has fired');
        //Main Logic
        Set<ID> eudCaseIdNow = new Set<ID>();
        Set<ID> eudCaseIdLater = new Set<ID>();
        Map<ID, String> eudCaseToOrderMapLater = new Map<ID, String>();

        //Break apart the email chunks into emailChunkSize Limit and chunk the next set into a Later future call
        for (ID caseId : eudCaseToOrderMap.keySet()) {
            if (eudCaseIdNow.size() < emailChunkSize) {
                eudCaseIdNow.add(caseId);
            } else {
                eudCaseIdLater.add(caseId);
                eudCaseToOrderMapLater.put(caseId, eudCaseToOrderMap.get(caseId));
            }
        }

        //process some cases now
        if ( !eudCaseIdNow.isEmpty() ) {
            List<Id> caseProcessFailedResult = OrderERPHandler.sendEUDEmail(eudCaseIdNow);
            if(!caseProcessFailedResult.isEmpty()){
                retryCount++;
                for(Id caseId : caseProcessFailedResult){
                    eudCaseIdLater.add(caseId);
                    eudCaseToOrderMapLater.put(caseId, eudCaseToOrderMap.get(caseId));
                }
            }
        }

        if ( !eudCaseIdLater.isEmpty() && retryCount <= retryMaxCount ) {

            //chunk the next set into another future call
            if (!Test.isRunningTest()) {
                ID jobID = System.enqueueJob(new emailLauncher(eudCaseIdLater, eudCaseToOrderMapLater, inOrdersList, retryCount));
            }

        }else{

            if( !eudCaseIdLater.isEmpty() ){

                List<Audit_Trail_Error__c> auditErrorList = new List<Audit_Trail_Error__c>();
                for(Id caseId : eudCaseIdLater){
                    Audit_Trail_Error__c auditError = new Audit_Trail_Error__c();
                    auditError.Module__c = 'emailLauncher.execute';
                    auditError.Dev_Audit_Notes__c = 'Pending EUD Email';
                    auditError.SourceId__c = caseId;
                    auditError.errorMessage__c = 'RetryCount exceeded our limit.';
                    auditErrorList.add(auditError);
                }

                insert auditErrorList;

            }

            // pass empty set and map
            if (!Test.isRunningTest()) {
                orderQLauncherHelper.queLauncherFirer(
                    inOrdersList,
                    'emailComplete',
                    new Map<ID, String>(),
                    new List<Case>()
                );
            }

        }

    }
}