unpackaged/main/default/objects/Audit_Trail_Error__c/Audit_Trail_Error__c.object-meta.xml
<CustomObject>
    <label>Audit Trail Error</label>
    <nameField>
        <displayFormat>AER-{0}</displayFormat>
        <label>Audit Trail Error Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit Trail Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Audit_Trail_Error__c/fields/Dev_Audit_Notes__c.field-meta.xml
<CustomField>
    <fullName>Dev_Audit_Notes__c</fullName>
    <description>Additional Notes Captured by Developer at time of error/Exception as needed.</description>
    <label>Dev Audit Notes</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Audit_Trail_Error__c/fields/errorMessage__c.field-meta.xml
<CustomField>
    <fullName>errorMessage__c</fullName>
    <description>ErrorMessage that is returned from Apex/Lightning</description>
    <label>errorMessage</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Audit_Trail_Error__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <description>Developer Name for where error Occurred. Should match Apex/Lightning component.</description>
    <label>Module</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Audit_Trail_Error__c/fields/StatusCode__c.field-meta.xml
<CustomField>
    <fullName>StatusCode__c</fullName>
    <description>Any Apex/Lightning Status Code that is returned.</description>
    <label>StatusCode</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Contact_s_Date_of_First_Order__c.field-meta.xml
<CustomField>
    <fullName>Contact_s_Date_of_First_Order__c</fullName>
    <description>First date that the contact placed an order</description>
    <label>Date of First Order</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Date_of_Last_Order__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Last_Order__c</fullName>
    <label>Date of Last Order</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Number_Quotes__c.field-meta.xml
<CustomField>
    <fullName>Number_Quotes__c</fullName>
    <label># of Quotes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Sup_DateOfFirstOrder__c.field-meta.xml
<CustomField>
    <fullName>Sup_DateOfFirstOrder__c</fullName>
    <label>Supplies Date of First Order</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Sup_DateOfFirstQuote__c.field-meta.xml
<CustomField>
    <fullName>Sup_DateOfFirstQuote__c</fullName>
    <label>Supplies Date of First Quote</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Sup_DateOfLastQuote__c.field-meta.xml
<CustomField>
    <fullName>Sup_DateOfLastQuote__c</fullName>
    <label>Supplies Date of Last Quote</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Sup_NumberQuotes__c.field-meta.xml
<CustomField>
    <fullName>Sup_NumberQuotes__c</fullName>
    <label>Supplies Number of Quotes</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/Order_Erp__c.object-meta.xml
<CustomObject>
    <description>This object cotains the orders from Xometry ERP. An order is created in Salesforce when the Order date is populated. 

Technical Note: Quote and Orders are the same object in the source system but seperated in Salesforce as Orders represent the end of the opportunity process.</description>
    <label>Order ERP</label>
    <nameField>
        <displayFormat>Order-{000000}</displayFormat>
        <label>Order Erp Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders ERP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order_Erp__c/fields/ContactID__c.field-meta.xml
<CustomField>
    <fullName>ContactID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ContactID</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Orders_Erp</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/Order_ERP_CreatedDate__c.field-meta.xml
<CustomField>
    <fullName>Order_ERP_CreatedDate__c</fullName>
    <description>Date that an order was placed.</description>
    <label>Order Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Order_Erp__c/fields/Xometry_ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>Xometry_ERP_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>This value is the unique order.id created in erp. The quote ID and Order ID are the same.</description>
    <externalId>true</externalId>
    <inlineHelpText>Value to use to look up an order in the ERP.</inlineHelpText>
    <label>Order ID</label>
    <length>12</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/Quote_ERP__c.object-meta.xml
<CustomObject>
    <description>A quote that is sent over from ERP</description>
    <label>Quote ERP</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote_ERP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes ERP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Quote_ERP__c/fields/ContactID__c.field-meta.xml
<CustomField>
    <fullName>ContactID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Contact</description>
    <label>ContactID</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Quotes_ERP</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Quote_ERP_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Quote_ERP_Created_Date__c</fullName>
    <description>The date the quote was created in the ERP system</description>
    <label>Quote Created Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Quote_ERP__c/fields/Xometry_ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>Xometry_ERP_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Unique Qoute ID created in Xometry ERP</description>
    <externalId>true</externalId>
    <label>Quote ID</label>
    <length>13</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Supplies_Order__c/Supplies_Order__c.object-meta.xml
<CustomObject>
    <label>Supplies Order</label>
    <nameField>
        <label>Supplies Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplies Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Supplies_Order__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ContactId</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Supplies Orders</relationshipLabel>
    <relationshipName>Supplies_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Quote__c/Supplies_Quote__c.object-meta.xml
<CustomObject>
    <description>This stores the P21 Quotes as records in Salesforce before transformation.</description>
    <label>Supplies Quote</label>
    <nameField>
        <label>Supplies Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplies Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Supplies_Quote__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ContactId</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Supplies Quotes</relationshipLabel>
    <relationshipName>Supplies_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Supplies_Quote__c/fields/P21_ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>P21_ERP_ID__c</fullName>
    <description>The unique Order ID which can be a Quote from P21 Order Entry.</description>
    <externalId>true</externalId>
    <label>P21 ERP ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Supplies_Quote__c/fields/Quote_P21_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Quote_P21_Created_Date__c</fullName>
    <label>Quote Created Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/updateContactQuoteDates.cls
global class updateContactQuoteDates implements Database.Batchable<sObject>, Database.Stateful {
    // instance member to retain state across transactions
    global Integer UCQDrecordsProcessed = 0;
    global Integer batchTracker = 0;
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT ID, Name, Contact_s_Date_of_First_Order__c, First_Quote_Date__c, Date_of_Last_Order__c, Date_of_Last_Quote__c, Sup_DateOfFirstQuote__c, Sup_DateOfLastQuote__c, Sup_NumberQuotes__c, Sup_DateOfFirstOrder__c, Sup_DateOfLastOrder__c from Contact order by AccountID'
        );
    }
    global void execute(Database.BatchableContext bc, List<Contact> scope) {
        batchTracker = batchTracker + 1;
        SET<ID> lContactIDSET = new Set<ID>();
        Map<ID, Contact> lContactIDMap = new Map<ID, Contact>();
        for (Contact c : scope) {
            lContactIDSET.add(c.ID);
            lContactIDMap.put(c.ID, c);
        }
        // Fetch the Quote Dates
        AggregateResult[] quoteAggRes = [
            SELECT
                ContactID__C ContactID,
                Max(Quote_ERP_Created_Date__C) Last_Quote_Date,
                Min(Quote_ERP_Created_Date__C) First_Quote_Date,
                Count_Distinct(Xometry_ERP_ID__C) NumQuotes
            FROM Quote_ERP__C
            WHERE ContactID__C IN :lContactIDSET
            GROUP BY ContactID__C
        ];
        for (AggregateResult laggRes : quoteAggRes) {
            ID lID = ID.valueOf(String.valueOf(laggRes.get('ContactID')));
            Date lLastQuoteDate = Date.valueOf(String.valueOf(laggRes.get('Last_Quote_Date')));
            Date lFirstQuoteDate = Date.valueOf(String.valueOf(laggRes.get('First_Quote_Date')));
            Integer lNumQuotes = Integer.valueOf(String.valueOf(laggRes.get('NumQuotes')));
            if (lContactIDMap.containsKey(lID)) {
                contact lContact = lContactIDMap.get(lID);
                lContact.First_Quote_Date__c = lFirstQuoteDate;
                lContact.Date_of_Last_Quote__c = lLastQuoteDate;
                lContact.Number_Quotes__c = lNumQuotes;
                lContactIDMap.put(lContact.ID, lContact);
            }
        }
        // Fetch the Orders Data
        AggregateResult[] orderAggRes = [
            SELECT
                ContactID__C ContactID,
                Max(Order_ERP_CreatedDate__c) Last_Order_Date,
                Min(Order_ERP_CreatedDate__c) First_Order_Date
            FROM Order_ERP__C
            WHERE ContactID__C IN :lContactIDSET
            GROUP BY ContactID__C
        ];
        for (AggregateResult laggRes : orderAggRes) {
            ID lID = ID.valueOf(String.valueOf(laggRes.get('ContactID')));
            Date lLastOrderDate = Date.valueOf(String.valueOf(laggRes.get('Last_Order_Date')));
            Date lFirstOrderDate = Date.valueOf(String.valueOf(laggRes.get('First_Order_Date')));
            if (lContactIDMap.containsKey(lID)) {
                contact lContact = lContactIDMap.get(lID);
                lContact.Contact_s_Date_of_First_Order__c = lFirstOrderDate;
                lContact.Date_of_Last_Order__c = lLastOrderDate;
                lContactIDMap.put(lContact.ID, lContact);
            }
        }

        // Fetch the Supplies Quote Dates
        AggregateResult[] suppliesQuoteAggRes = [
            SELECT
                ContactID__C ContactID,
                Max(Quote_P21_Created_Date__c) Sup_LastQuoteDate,
                Min(Quote_P21_Created_Date__c) Sup_FirstQuoteDate,
                COUNT_DISTINCT(P21_ERP_ID__C) Sup_NumQuotes
            FROM Supplies_Quote__C
            WHERE ContactID__C IN :lContactIDSET
            GROUP BY ContactID__C
        ];
        for (AggregateResult laggRes : suppliesQuoteAggRes) {
            ID lID = ID.valueOf(String.valueOf(laggRes.get('ContactID')));
            Date lSupLastQuoteDate = Date.valueOf(String.valueOf(laggRes.get('Sup_LastQuoteDate')));
            Date lSupFirstQuoteDate = Date.valueOf(String.valueOf(laggRes.get('Sup_FirstQuoteDate')));
            Integer lSupNumQuotes = Integer.valueOf(String.valueOf(laggRes.get('Sup_NumQuotes')));
            if (lContactIDMap.containsKey(lID)) {
                contact lContact = lContactIDMap.get(lID);
                lContact.Sup_DateOfFirstQuote__c = lSupFirstQuoteDate;
                lContact.Sup_DateOfLastQuote__c = lSupLastQuoteDate;
                lContact.Sup_NumberQuotes__c = lSupNumQuotes;
                lContactIDMap.put(lContact.ID, lContact);
            }
        }
        // Fetch the Supplies Order Dates
        AggregateResult[] suppliesOrderAggRes = [
            SELECT ContactID__C ContactID, Max(Order_Date__c) Sup_LastOrderDate, Min(Order_Date__c) Sup_FirstOrderDate
            FROM Supplies_Order__c
            WHERE ContactID__C IN :lContactIDSET
            GROUP BY ContactID__C
        ];
        for (AggregateResult laggRes : suppliesOrderAggRes) {
            ID lID = ID.valueOf(String.valueOf(laggRes.get('ContactID')));
            Date lSupLastOrderDate = Date.valueOf(String.valueOf(laggRes.get('Sup_LastOrderDate')));
            Date lSupFirstOrderDate = Date.valueOf(String.valueOf(laggRes.get('Sup_FirstOrderDate')));
            if (lContactIDMap.containsKey(lID)) {
                contact lContact = lContactIDMap.get(lID);
                lContact.Sup_DateOfFirstOrder__c = lSupFirstOrderDate;
                lContact.Sup_DateOfLastOrder__c = lSupLastOrderDate;
                lContactIDMap.put(lContact.ID, lContact);
            }
        }

        //Update the Contacts

        System.debug('About to start the Contact Updates');
        List<Contact> contactUpdateList = new List<Contact>();
        contactUpdateList = lContactIDMap.values();
        System.debug('Contacts to Update List is');
        System.debug('The size of the Contact Update List is : ' + contactUpdateList.size());
        System.debug(contactUpdateList);
        Integer updateTracker = DatabaseUtilities.saveToDatabaseTracking(
            contactUpdateList,
            'updateContactQuoteDates.execute',
            'Contact Updates in Execution Queu'
        );
        UCQDrecordsProcessed = UCQDrecordsProcessed + contactUpdateList.size();

        // To be uncommented when investigating record locking
        // Temporary Custom

        // List<Audit_Trail_Error__c> myAuditErrorList = new List<Audit_Trail_Error__c>();
        // integer localRecord1 = 0;
        // Audit_Trail_Error__c myAuditError = new Audit_Trail_Error__c();
        // myAuditError.Module__c = 'updateContactQuoteDates.Manualexecute';
        // myAuditError.Dev_Audit_Notes__c = 'The size of the Contact Update List is : ' + contactUpdateList.size();
        // myAuditError.StatusCode__c = 'BatchJobUpdate';
        // myAuditError.errorMessage__c =
        //     'The size of successes is : ' +
        //     updatetracker +
        //     ' The numof errors is : ' +
        //     localRecord1;
        // myAuditErrorList.add(myAuditError);

        // if (!myAuditErrorList.isEmpty()) {
        //     insert myAuditErrorList;
        // }

        System.debug('Current Records Processed' + UCQDrecordsProcessed);
        System.debug('The update tracker records for this batch are ' + updateTracker);
    }

    global void finish(Database.BatchableContext bc) {
        System.debug(UCQDrecordsProcessed + ' records processed. Shazam!');
    }
}