unpackaged/main/default/objects/Audit_Trail_Error__c/Audit_Trail_Error__c.object-meta.xml
<CustomObject>
    <label>Audit Trail Error</label>
    <nameField>
        <displayFormat>AER-{0}</displayFormat>
        <label>Audit Trail Error Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit Trail Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Audit_Trail_Error__c/fields/Dev_Audit_Notes__c.field-meta.xml
<CustomField>
    <fullName>Dev_Audit_Notes__c</fullName>
    <description>Additional Notes Captured by Developer at time of error/Exception as needed.</description>
    <label>Dev Audit Notes</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Audit_Trail_Error__c/fields/errorFields__c.field-meta.xml
<CustomField>
    <fullName>errorFields__c</fullName>
    <description>Column that contains specific fields when an error occurs.</description>
    <label>errorFields</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Audit_Trail_Error__c/fields/errorMessage__c.field-meta.xml
<CustomField>
    <fullName>errorMessage__c</fullName>
    <description>ErrorMessage that is returned from Apex/Lightning</description>
    <label>errorMessage</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Audit_Trail_Error__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <description>Developer Name for where error Occurred. Should match Apex/Lightning component.</description>
    <label>Module</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Audit_Trail_Error__c/fields/StatusCode__c.field-meta.xml
<CustomField>
    <fullName>StatusCode__c</fullName>
    <description>Any Apex/Lightning Status Code that is returned.</description>
    <label>StatusCode</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Last_Quote_Xometry_Create_Time__c.field-meta.xml
<CustomField>
    <fullName>Last_Quote_Xometry_Create_Time__c</fullName>
    <description>Hidden field for Automated Processing to compare last time an Opps quote occured.</description>
    <label>Last Quote Modification Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Opportunity_Create_Date__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Create_Date__c</fullName>
    <formula>CreatedDate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Created Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Container for Opportunities that are part of the same project</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project__c/fields/Last_Opp_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Opp_Created_Date__c</fullName>
    <inlineHelpText>Looking at the Opps on this project, this is the most recent Opp Created Date</inlineHelpText>
    <label>Last Opp Created Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Last_Quote_Mod_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Quote_Mod_Date__c</fullName>
    <inlineHelpText>Of the Quotes on this Project (by way of Opps), this is the most recent Last Quote Modification Date in the ERP.</inlineHelpText>
    <label>Last Quote Mod Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <inlineHelpText>A short description of this Project</inlineHelpText>
    <label>Project</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/projectUpdateBatch.cls
/**
 * Async Queueable class update projects on opp change
 */
public class projectUpdateBatch implements Queueable {
    static final String ERROR_FIELDS = 'Fields affected by that error: ';
    static final String ERROR_LOG = 'The following error occurred: ';
    static final String NULL_PARAM_ERROR = 'Method Called or Dev Audit Note is null.';
    static final String SUCCESS_LOG = 'The succesful update id was: ';

    static final String PROJECT_UPDATE_METHOD_NOTE = 'Updating Project Opp Created Date and Last Quote Mod Date';
    static final String PROJECT_UPDATE_DEV_NOTE = 'Failed to update Project Objects';

    Set<Id> projectIdSet = new Set<Id>();
    Map<Id, Datetime> projectOppCreatedDateMap = new Map<Id, Date>();
    Map<Id, Datetime> projectLastQuoteModDateMap = new Map<Id, Datetime>();

    public projectUpdateBatch(Set<Id> opportunityIdSet) {
        // TODO: replace Last_Quote_Xometry_Create_Time__c
        List<Opportunity> opps = [
            SELECT Project__c, Opportunity_Create_Date__c, Last_Quote_Xometry_Create_Time__c
            FROM Opportunity
            WHERE Id IN :opportunityIdSet
        ];

        for (Opportunity o : opps) {
            projectIdSet.add(o.Project__c);

            if (!projectOppCreatedDateMap.containsKey(o.Project__c)) {
                projectOppCreatedDateMap.put(o.Project__c, o.Opportunity_Create_Date__c);
            } else if (projectOppCreatedDateMap.get(o.Project__c) < o.Opportunity_Create_Date__c) {
                projectOppCreatedDateMap.remove(o.Project__c);
                projectOppCreatedDateMap.put(o.Project__c, o.Opportunity_Create_Date__c);
            }

            if (!projectLastQuoteModDateMap.containsKey(o.Project__c)) {
                projectLastQuoteModDateMap.put(o.Project__c, o.Last_Quote_Xometry_Create_Time__c);
            } else if (projectLastQuoteModDateMap.get(o.Project__c) < o.Last_Quote_Xometry_Create_Time__c) {
                projectLastQuoteModDateMap.remove(o.Project__c);
                projectLastQuoteModDateMap.put(o.Project__c, o.Last_Quote_Xometry_Create_Time__c);
            }
        }
    }

    public void execute(QueueableContext context) {
        List<Project__c> projectToUpdateList = [
            SELECT Id, Last_Opp_Created_Date__c, Last_Quote_Mod_Date__c
            FROM Project__c
            WHERE Id IN :projectIdSet
        ];

        for (Project__c proj : projectToUpdateList) {
            // Optional Chaining can't come soon enough
            // We can replace these with projectOppCreatedDateMap.get(proj.Id)?.Last_Opp_Created_Date__c
            if (projectOppCreatedDateMap.containsKey(proj.Id)) {
                proj.Last_Opp_Created_Date__c = projectOppCreatedDateMap.get(proj.Id);
            }
            if (projectLastQuoteModDateMap.containsKey(proj.Id)) {
                proj.Last_Quote_Mod_Date__c = projectLastQuoteModDateMap.get(proj.Id);
            }
        }

        saveToDatabase(projectToUpdateList, PROJECT_UPDATE_METHOD_NOTE, PROJECT_UPDATE_DEV_NOTE);
    }

    /**
     * @description generic function to save a list of custom objects to the database
     * @param updateList List of SObjects to be saved to the database
     * @param methodCalled String representation of the associated method for logging purposes
     * @param devAuditNote Useful message for developers to debug errors for log audits
     */
    public static void saveToDatabase(List<SObject> updateList, String methodCalled, String devAuditNote) {
        List<Audit_Trail_Error__c> auditErrorList = new List<Audit_Trail_Error__c>();

        // This has limited functionality as part of this handler class, as it is called by constants.
        // But this would be useful if abstracted to a standalone Database helper class.
        if (String.isBlank(methodCalled) || String.isBlank(devAuditNote)) {
            throw new IllegalArgumentException();
        }

        if (!updateList.isEmpty()) {
            Database.SaveResult[] srList = Database.update(updateList, false);
            for (Database.SaveResult sr : srList) {
                if (sr.isSuccess()) {
                    System.debug(SUCCESS_LOG + sr.getID());
                } else {
                    // Log errors
                    for (Database.Error err : sr.getErrors()) {
                        System.debug(ERROR_LOG);
                        System.debug(err.getStatusCode() + ' : ' + err.getMessage());
                        System.debug(ERROR_FIELDS + err.getFields());
                        Audit_Trail_Error__c auditError = new Audit_Trail_Error__c();
                        auditError.Module__c = methodCalled;
                        auditError.Dev_Audit_Notes__c = devAuditNote;
                        auditError.StatusCode__c = err.getStatusCode().name();
                        auditError.errorMessage__c = err.getMessage().abbreviate(250);
                        auditError.errorFields__c = String.join(err.getFields(), ' ').abbreviate(250);
                        auditErrorList.add(auditError);
                    }
                }
            }
        }

        insert auditErrorList;
    }
}